-- Generated by kanon from bool.kn, word.kn. Do not edit.
import L4.Ops
import L4.Model.Word.left_lit
import L4.Model.Word.plain

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L4

open Classical Kanon

def Word.add.r_lits (O : Ops) (f : CfgMod.Flags) (n : Int) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Wd x _) _), (Term.mk (Kind.Wd y _) _) =>
    (whenSome true ((Term.mk (Kind.Wd (O.orc.wsum x y) n) (Ty.TWord n))))
    | _, _ => none)

def Word.add.r_plain (O : Ops) (f : CfgMod.Flags) (n : Int) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | a, b =>
    (whenSome ((decide ((Word.left_lit a) = (0 : Int))) && (! f.strict))
    ((Term.mk (Kind.Op2 (Op2.WAdd Word.plain n) a b) (Ty.TWord n)))))

def Word.add.r_default (O : Ops) (f : CfgMod.Flags) (n : Int) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | _, _ =>
    (whenSome true ((Term.mk (Kind.Op2 (Op2.WAdd f n) v1 v2) (Ty.TWord n)))))

def Word.add.step (O : Ops) (f : CfgMod.Flags) (n : Int) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [Word.add.r_lits O f n v1 v2, Word.add.r_plain O f n v1 v2, Word.add.r_default O f n v1 v2]).getD (Word.add.spec f n v1 v2)

end L4
