-- Generated by kanon from bool.kn, word.kn. Do not edit.
import L4.Ops
import L4.Model.Word.plain

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L4

open Classical Kanon

def Word.double_closed.r_main (O : Ops) (n : Int) (v : Term) : Option Term :=
  (whenSome true
  ((Term.mk (Kind.Op2 (Op2.WAdd Word.plain n) v v) (Ty.TWord n))))

def Word.double_closed.step (O : Ops) (n : Int) (v : Term) : Term :=
  (firstSome [Word.double_closed.r_main O n v]).getD (Word.double_closed.spec n v)

end L4
