-- Generated by kanon from bool.kn, word.kn. Do not edit.
import L4.Signatures

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L4

open Classical Kanon

def Word.first (a : Int) (_ : Int) : Int :=
  a

end L4
