-- Generated by kanon from bool.kn, word.kn. Do not edit.
import L4.Ops
import L4.Model.Word.is_down
import L4.Model.Word.is_word

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L4

open Classical Kanon

def Word.round.r_keep (O : Ops) (m : CfgMod.Rounding) (n : Int) (v : Term) : Option Term :=
  (match v with
    | x =>
    (whenSome (((Word.is_down m) || (decide (m = CfgMod.Rounding.Up))) && (Word.is_word (ty x)))
    (x)))

def Word.round.r_default (O : Ops) (m : CfgMod.Rounding) (n : Int) (v : Term) : Option Term :=
  (match v with
    | _ =>
    (whenSome true ((Term.mk (Kind.Op1 (Op1.WRound m n) v) (Ty.TWord n)))))

def Word.round.step (O : Ops) (m : CfgMod.Rounding) (n : Int) (v : Term) : Term :=
  (firstSome [Word.round.r_keep O m n v, Word.round.r_default O m n v]).getD (Word.round.spec m n v)

end L4
