-- Generated by kanon from bool.kn, word.kn. Do not edit.
import L4.Signatures
import L4.Model.Word.plain

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L4

open Classical Kanon

def Word.twice (n : Int) (v : Term) : Term :=
  (Term.mk (Kind.Op2 (Op2.WAdd Word.plain n) v v) (Ty.TWord n))

end L4
