-- Generated by kanon from vec.kn. Do not edit.

import ArraysExample.Prims

namespace ArraysExample

/-! The primitives of the rules, with the types they are declared with. -/

noncomputable section


end

end ArraysExample
