-- Generated by kanon from vec.kn. Do not edit.
import KanonCore.Attr
import ArraysExample.Semantics

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace ArraysExample

open Classical Kanon

attribute [kanon_spec]
  Vec.len.spec
  Vec.get.spec
  Vec.set.spec

/-- Every rule function refines its spec. -/
structure Ops.Sound (O : Ops) : Prop where
  orc : O.orc.Compat
  vec_len : ∀ (v : Term), Refines (Vec.len.spec v) (O.vec_len v)
  vec_get : ∀ (v : Term) (i : Term), Refines (Vec.get.spec v i) (O.vec_get v i)
  vec_set : ∀ (v : Term) (i : Term) (x : Term), Refines (Vec.set.spec v i x) (O.vec_set v i x)

end ArraysExample
