-- Generated by kanon from lang.knl, vec.knl. Do not edit.

import ArraysExample.Abstract

namespace ArraysExample

mutual
inductive Kind where
  | Int : Int → Kind
  | Vec : (Array Int) → Kind
  | Op1 : Op1 → Term → Kind
  | Op2 : Op2 → Term → Term → Kind
  | Op3 : Op3 → Term → Term → Term → Kind
inductive Term where
  | mk (kind : Kind) (ty : Ty)
end

def Term.kind : Term → Kind
  | .mk k _ => k

def Term.ty : Term → Ty
  | .mk _ t => t

@[simp] theorem Term.kind_mk (k : Kind) (t : Ty) : (Term.mk k t).kind = k := rfl
@[simp] theorem Term.ty_mk (k : Kind) (t : Ty) : (Term.mk k t).ty = t := rfl

instance : Inhabited Kind := ⟨.Int default⟩
instance : Inhabited Term := ⟨.mk default default⟩

end ArraysExample
