-- Generated by kanon from lang.knl, bool.knl, vec.knl. Do not edit.

namespace ArraysExample

inductive Op1 where
  | Not
  /-- The number of elements of an array. -/
  | Len
  deriving DecidableEq, Repr, Inhabited

inductive Op2 where
  | And
  | Or
  | Eq
  /-- The element at an index, which must be in bounds. -/
  | Get
  deriving DecidableEq, Repr, Inhabited

/-- The operators whose operands commute (`[@comm]`). -/
def Op2.Comm : Op2 → Prop
  | .And | .Or | .Eq => True
  | _ => False

inductive Op3 where
  | Ite
  /-- The array with the element at an index replaced: a copy. -/
  | Set
  deriving DecidableEq, Repr, Inhabited

inductive OpN where
  | Distinct
  deriving DecidableEq, Repr, Inhabited

inductive Ty where
  | TBool
  | TInt
  | TVec
  deriving DecidableEq, Repr, Inhabited

end ArraysExample
