-- Generated by kanon from bool.kn, word.kn. Do not edit.
import KanonCore.Tactics
import L4.Statements.Word.double
import L4.Instance.Word
import L4.Lang.Bool
import L4.Lang.Cfg
import L4.Lang.Word
import WordMod.Soundness.Word.double

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L4

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Word.double.r_main.main.ok : Word.double.r_main.main.Stmt :=
  fun O hO => WordMod.Word.double.r_main.main.ok (S := sem) wordSyntax
  (Ops.toWord O) (Ops.Sound.toWord hO)

theorem Word.double.r_main.proof : Word.double.r_main.Stmt := by
  intro O hO n v res h
  simp only [Word.double.r_main] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Word.double.r_main.main.ok O hO)

theorem Word.double.step_sound (O : Ops) (hO : O.Sound) (n : Int) (v : Term) :
  Refines (Word.double.spec n v) (Word.double.step O n v) := by
  unfold Word.double.step
  refine Refinement.firstSome_cons (fun res h => Word.double.r_main.proof O hO n v res h) ?_
  exact Refinement.firstSome_nil

end L4
