-- Generated by kanon from bool.kn, word.kn. Do not edit.
import KanonCore.Tactics
import L4.Statements.Word.round
import L4.Instance.Word
import L4.Lang.Bool
import L4.Lang.Cfg
import L4.Lang.Word
import WordMod.Soundness.Word.round

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L4

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Word.round.r_keep.main.ok : Word.round.r_keep.main.Stmt :=
  fun O hO => WordMod.Word.round.r_keep.main.ok (S := sem) wordSyntax
  (Ops.toWord O) (Ops.Sound.toWord hO)

theorem Word.round.r_keep.proof : Word.round.r_keep.Stmt := by
  intro O hO m n v res h
  simp only [Word.round.r_keep] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Word.round.r_keep.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Word.round.r_default.main.ok : Word.round.r_default.main.Stmt :=
  fun O hO => WordMod.Word.round.r_default.main.ok (S := sem) wordSyntax
  (Ops.toWord O) (Ops.Sound.toWord hO)

theorem Word.round.r_default.proof : Word.round.r_default.Stmt := by
  intro O hO m n v res h
  simp only [Word.round.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Word.round.r_default.main.ok O hO)

theorem Word.round.step_sound (O : Ops) (hO : O.Sound) (m : CfgMod.Rounding) (n : Int) (v : Term) :
  Refines (Word.round.spec m n v) (Word.round.step O m n v) := by
  unfold Word.round.step
  refine Refinement.firstSome_cons (fun res h => Word.round.r_keep.proof O hO m n v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Word.round.r_default.proof O hO m n v res h) ?_
  exact Refinement.firstSome_nil

end L4
