kanon lean-all DIR writes the Lean files of a language under DIR. Each module
has its own, in Generated/R for its root R: those of its nodes (Node.lean,
Lang.lean) and of its rules (Model.lean, Lift.lean, Soundness.lean, and a file
per function, under Statements/ and Soundness/, and for the commutativity). The
language has its terms, their semantics and its rule functions (Syntax.lean,
Semantics.lean, Rules.lean) in Generated/Ex (its root is Ex, by
[@@@lean_root "Ex"]), which is also that of its own module; the int module is
under Generated/Ex/Int. See lean_generated.t for the Generated directory.

  $ kanon lean-all out lang.knl
  $ find out -name '*.lean' | sort
  out/Generated/Ex/Int/Lang.lean
  out/Generated/Ex/Int/Lift.lean
  out/Generated/Ex/Int/Model.lean
  out/Generated/Ex/Int/Node.lean
  out/Generated/Ex/Int/Soundness.lean
  out/Generated/Ex/Int/Soundness/Comm.lean
  out/Generated/Ex/Int/Soundness/Int/neg.lean
  out/Generated/Ex/Int/Soundness/Int/plus.lean
  out/Generated/Ex/Int/Statements/Comm.lean
  out/Generated/Ex/Int/Statements/Int/neg.lean
  out/Generated/Ex/Int/Statements/Int/plus.lean
  out/Generated/Ex/Lang.lean
  out/Generated/Ex/Lift.lean
  out/Generated/Ex/Model.lean
  out/Generated/Ex/Node.lean
  out/Generated/Ex/Rules.lean
  out/Generated/Ex/Semantics.lean
  out/Generated/Ex/Soundness.lean
  out/Generated/Ex/Syntax.lean

Each generated proof of an arm has its own bound on heartbeats: that of its
rule function ([@lean_heartbeats 800000] on neg), else that of the language
([@@@lean_heartbeats "300000"]).

  $ cat out/Generated/Ex/Int/Soundness/*/*.lean | grep 'maxHeartbeats [0-9]* in' | sort | uniq -c
        4 set_option maxHeartbeats 300000 in
        3 set_option maxHeartbeats 800000 in

Lang.lean states the typing of each node, at the sorts of a language.

  $ sed -n '/^def Node.wt/,/^$/p' out/Generated/Ex/Int/Lang.lean
  def Node.wt {T Ty : Type} (sInt : Ex.Int.Srt → Ty) (ty : T → Ty) : Node T → Ty → Prop
    | (.Int x1), t => (t = (sInt .TInt))
    | (.Plus a1 a2), t => (ty a1 = (sInt .TInt) ∧ ty a2 = (sInt .TInt) ∧ t = (sInt .TInt))
    | (.Neg a1), t => (ty a1 = (sInt .TInt) ∧ t = (sInt .TInt))
  

With --check, kanon lean-all only checks that the files are up to date.

  $ kanon lean-all --check out lang.knl

The hand-written proofs of a module, Proofs.lean, are imported by its generated
proofs, under Soundness/, when they exist.

  $ mkdir -p out/Ex/Int
  $ echo 'import Generated.Ex.Int.Statements.Int.neg' > out/Ex/Int/Proofs.lean
  $ kanon lean-all --check out lang.knl
  kanon: out/Generated/Ex/Int/Soundness/Comm.lean is not up to date (run kanon lean-all)
  kanon: out/Generated/Ex/Int/Soundness/Int/plus.lean is not up to date (run kanon lean-all)
  kanon: out/Generated/Ex/Int/Soundness/Int/neg.lean is not up to date (run kanon lean-all)
  [1]
  $ kanon lean-all out lang.knl
  $ grep '^import' out/Generated/Ex/Int/Soundness/Int/neg.lean
  import Generated.Ex.Int.Statements.Int.neg
  import Ex.Int.Proofs
  import Generated.Ex.Int.Soundness.Comm

The files of Generated/Ex that kanon no longer generates are removed, and the
files of Ex are kept.

  $ echo '-- Generated by kanon from int.kn. Do not edit.' > out/Generated/Ex/Int/Old.lean
  $ echo '-- A file of mine.' > out/Ex/Int/Mine.lean
  $ kanon lean-all --check out lang.knl
  kanon: out/Generated/Ex/Int/Old.lean is no longer generated (run kanon lean-all)
  [1]
  $ kanon lean-all out lang.knl
  $ ls out/Ex/Int out/Generated/Ex/Int
  out/Ex/Int:
  Mine.lean
  Proofs.lean
  
  out/Generated/Ex/Int:
  Lang.lean
  Lift.lean
  Model.lean
  Node.lean
  Soundness
  Soundness.lean
  Statements

The bound on heartbeats is a positive number.

  $ mkdir bad && cp lang.knl int.knl bad && sed 's/800000/0/' int.kn > bad/int.kn
  $ kanon lean-all out bad/lang.knl
  bad/int.kn:7:17: [@lean_heartbeats n]: n must be a positive integer
  [1]

With [@lean_proofs "F"], the generated proofs of a function import
Proofs/F.lean instead of Proofs.lean, so that editing another proof file does
not rebuild them.

  $ mkdir split && cp lang.knl int.knl split
  $ sed 's/\[@lean_heartbeats 800000\]/[@lean_heartbeats 800000] [@lean_proofs "Neg"]/' int.kn > split/int.kn
  $ kanon lean-all out split/lang.knl
  $ grep '^import' out/Generated/Ex/Int/Soundness/Int/neg.lean out/Generated/Ex/Int/Soundness/Int/plus.lean
  out/Generated/Ex/Int/Soundness/Int/neg.lean:import Generated.Ex.Int.Statements.Int.neg
  out/Generated/Ex/Int/Soundness/Int/neg.lean:import Ex.Int.Proofs.Neg
  out/Generated/Ex/Int/Soundness/Int/neg.lean:import Generated.Ex.Int.Soundness.Comm
  out/Generated/Ex/Int/Soundness/Int/plus.lean:import Generated.Ex.Int.Statements.Int.plus
  out/Generated/Ex/Int/Soundness/Int/plus.lean:import Ex.Int.Proofs
  out/Generated/Ex/Int/Soundness/Int/plus.lean:import Generated.Ex.Int.Soundness.Comm

The proofs of the cases that an extend adds to the function of another module
import its file, and the commutativity proofs those of the [@comm] nodes. A
generated file imports the file of each item that it proves, or Proofs.lean.

  $ mkdir ext && cp int.kn ext && cat lang.knl > ext/lang.knl && echo 'use "zero"' >> ext/lang.knl
  $ printf 'use "int"\n\nextend rule Int.neg before lit [@lean_proofs "Zero"] =\n  | zero: Neg (Int 0) -> Int 0\n' > ext/zero.kn
  $ sed 's/\[@comm\]/[@comm] [@lean_proofs "Comm"]/' int.knl > ext/int.knl
  $ kanon lean-all out ext/lang.knl
  $ grep '^import' out/Generated/Ex/Zero/Soundness/Int/neg.lean out/Generated/Ex/Int/Soundness/Comm.lean
  out/Generated/Ex/Zero/Soundness/Int/neg.lean:import Generated.Ex.Zero.Statements.Int.neg
  out/Generated/Ex/Zero/Soundness/Int/neg.lean:import Ex.Zero.Proofs.Zero
  out/Generated/Ex/Zero/Soundness/Int/neg.lean:import Generated.Ex.Int.Soundness.Comm
  out/Generated/Ex/Int/Soundness/Comm.lean:import Generated.Ex.Int.Statements.Comm
  out/Generated/Ex/Int/Soundness/Comm.lean:import Ex.Int.Proofs.Comm

It is only for a rule, an extensible helper, an extend or a [@comm] node.

  $ sed 's/^fn negate (x : int) : int/fn negate (x : int) : int [@lean_proofs "Neg"]/' int.kn > bad/int.kn
  $ kanon lean-all out bad/lang.knl
  bad/int.kn:3:28: [@lean_proofs] is only for a rule or an extensible helper
  [1]
  $ sed 's/^node Neg : TInt -> TInt/& [@lean_proofs "Neg"]/' int.knl > ext/int.knl
  $ kanon lean-all out ext/lang.knl
  ext/int.knl:3:26: [@lean_proofs] on a node is only for a [@comm] one
  [1]
