kanon lean-all DIR writes the Lean files of a language under DIR. Each module
has its own, under the directory of its root: those of its nodes (Node.lean,
Lang.lean) and of its rules (Model.lean, Lift.lean, Soundness.lean, and a file
per function, under Statements/ and Soundness/, and for the commutativity). The
language has its terms, their semantics and its rule functions (Syntax.lean,
Semantics.lean, Rules.lean) under its root (Ex, by [@@@lean_root "Ex"]), which
is also that of its own module; the int module is under Ex/Int.

  $ kanon lean-all out lang.knl
  $ find out -name '*.lean' | sort
  out/Ex/Int/Lang.lean
  out/Ex/Int/Lift.lean
  out/Ex/Int/Model.lean
  out/Ex/Int/Node.lean
  out/Ex/Int/Soundness.lean
  out/Ex/Int/Soundness/Comm.lean
  out/Ex/Int/Soundness/Int/neg.lean
  out/Ex/Int/Soundness/Int/plus.lean
  out/Ex/Int/Statements/Comm.lean
  out/Ex/Int/Statements/Int/neg.lean
  out/Ex/Int/Statements/Int/plus.lean
  out/Ex/Lang.lean
  out/Ex/Lift.lean
  out/Ex/Model.lean
  out/Ex/Node.lean
  out/Ex/Rules.lean
  out/Ex/Semantics.lean
  out/Ex/Soundness.lean
  out/Ex/Syntax.lean

Each generated proof of an arm has its own bound on heartbeats: that of its
rule function ([@lean_heartbeats 800000] on neg), else that of the language
([@@@lean_heartbeats "300000"]).

  $ cat out/Ex/Int/Soundness/*/*.lean | grep 'maxHeartbeats [0-9]* in' | sort | uniq -c
        4 set_option maxHeartbeats 300000 in
        3 set_option maxHeartbeats 800000 in

Lang.lean states the typing of each node, at the sorts of a language.

  $ sed -n '/^def Node.wt/,/^$/p' out/Ex/Int/Lang.lean
  def Node.wt {T Ty : Type} (sInt : Ex.Int.Srt → Ty) (ty : T → Ty) : Node T → Ty → Prop
    | (.Int x1), t => (t = (sInt .TInt))
    | (.Plus a1 a2), t => (ty a1 = (sInt .TInt) ∧ ty a2 = (sInt .TInt) ∧ t = (sInt .TInt))
    | (.Neg a1), t => (ty a1 = (sInt .TInt) ∧ t = (sInt .TInt))
  

With --check, kanon lean-all only checks that the files are up to date.

  $ kanon lean-all --check out lang.knl

The hand-written proofs of a module, Proofs.lean, are imported by its generated
proofs, under Soundness/, when they exist.

  $ echo 'import Ex.Int.Statements.Int.neg' > out/Ex/Int/Proofs.lean
  $ kanon lean-all --check out lang.knl
  kanon: out/Ex/Int/Soundness/Comm.lean is not up to date (run kanon lean-all)
  kanon: out/Ex/Int/Soundness/Int/plus.lean is not up to date (run kanon lean-all)
  kanon: out/Ex/Int/Soundness/Int/neg.lean is not up to date (run kanon lean-all)
  [1]
  $ kanon lean-all out lang.knl
  $ grep '^import' out/Ex/Int/Soundness/Int/neg.lean
  import Ex.Int.Statements.Int.neg
  import Ex.Int.Proofs
  import Ex.Int.Soundness.Comm

The files that kanon generated and no longer does are removed; the others are
kept.

  $ echo '-- Generated by kanon from int.kn. Do not edit.' > out/Ex/Int/Old.lean
  $ echo '-- A file of mine.' > out/Ex/Int/Mine.lean
  $ kanon lean-all --check out lang.knl
  kanon: out/Ex/Int/Old.lean is no longer generated (run kanon lean-all)
  [1]
  $ kanon lean-all out lang.knl
  $ ls out/Ex/Int
  Lang.lean
  Lift.lean
  Mine.lean
  Model.lean
  Node.lean
  Proofs.lean
  Soundness
  Soundness.lean
  Statements

The bound on heartbeats is a positive number.

  $ mkdir bad && cp lang.knl int.knl bad && sed 's/800000/0/' int.kn > bad/int.kn
  $ kanon lean-all out bad/lang.knl
  bad/int.kn:7:17: [@lean_heartbeats n]: n must be a positive integer
  [1]

With [@lean_proofs "F"], the generated proofs of a function import
Proofs/F.lean instead of Proofs.lean, so that editing another proof file does
not rebuild them.

  $ sed 's/\[@lean_heartbeats 800000\]/[@lean_heartbeats 800000] [@lean_proofs "Neg"]/' int.kn > int2.kn && mv int2.kn int.kn
  $ kanon lean-all out lang.knl
  $ grep '^import' out/Ex/Int/Soundness/Int/neg.lean out/Ex/Int/Soundness/Int/plus.lean
  out/Ex/Int/Soundness/Int/neg.lean:import Ex.Int.Statements.Int.neg
  out/Ex/Int/Soundness/Int/neg.lean:import Ex.Int.Proofs.Neg
  out/Ex/Int/Soundness/Int/neg.lean:import Ex.Int.Soundness.Comm
  out/Ex/Int/Soundness/Int/plus.lean:import Ex.Int.Statements.Int.plus
  out/Ex/Int/Soundness/Int/plus.lean:import Ex.Int.Proofs
  out/Ex/Int/Soundness/Int/plus.lean:import Ex.Int.Soundness.Comm

[@@@lean_proofs "F"] in the declarations of a module does so for its other
proofs, the commutativity included.

  $ echo '[@@@lean_proofs "Base"]' >> int.knl
  $ kanon lean-all out lang.knl
  $ grep -h '^import Ex.Int.Proofs' out/Ex/Int/Soundness/Comm.lean out/Ex/Int/Soundness/Int/*.lean
  import Ex.Int.Proofs.Base
  import Ex.Int.Proofs.Neg
  import Ex.Int.Proofs.Base

It is only for a rule or an extensible helper.

  $ sed 's/^fn negate (x : int) : int/fn negate (x : int) : int [@lean_proofs "Neg"]/' int.kn > bad/int.kn
  $ kanon lean-all out bad/lang.knl
  bad/int.kn:3:28: [@lean_proofs] is only for a rule or an extensible helper
  [1]
