kanon lean-all DIR writes the Lean files of a language under DIR, in the
directory of its root (Ex, by [@@@lean_root "Ex"]): one file per rule function
and per helper (or group of mutually recursive helpers), in the directory of its
module, for its model, its statements and its proofs.

  $ kanon lean-all out lang.knl
  $ find out -name '*.lean' | sort
  out/Ex/Lifts.lean
  out/Ex/Model.lean
  out/Ex/Model/Int/add.lean
  out/Ex/Model/Int/neg.lean
  out/Ex/Model/Int/negate.lean
  out/Ex/Model/Int/plus.lean
  out/Ex/Model/mk_commut_binop.lean
  out/Ex/Nodes.lean
  out/Ex/Ops.lean
  out/Ex/Signatures.lean
  out/Ex/Soundness.lean
  out/Ex/Soundness/Int/neg.lean
  out/Ex/Soundness/Int/plus.lean
  out/Ex/Soundness/Laws.lean
  out/Ex/Statements.lean
  out/Ex/Statements/Int/neg.lean
  out/Ex/Statements/Int/plus.lean
  out/Ex/Syntax.lean
  out/Ex/Types.lean
  out/Ex/Typing.lean

Each file imports what it needs: the model of a rule function, the record of
the rule functions and the helpers that its rules call.

  $ grep '^import' out/Ex/Model/Int/neg.lean
  import Ex.Ops
  import Ex.Model.Int.negate

Each generated proof of an arm has its own bound on heartbeats: that of its
rule function ([@lean_heartbeats 800000] on neg), else that of the language
([@@@lean_heartbeats "300000"]).

  $ grep -B1 'kanon_proof%' out/Ex/Soundness/Int/neg.lean out/Ex/Soundness/Int/plus.lean
  out/Ex/Soundness/Int/neg.lean-set_option maxHeartbeats 800000 in
  out/Ex/Soundness/Int/neg.lean:theorem Int.neg.r_lit.main.ok : Int.neg.r_lit.main.Stmt := kanon_proof% Int.neg.r_lit.main
  --
  out/Ex/Soundness/Int/neg.lean-set_option maxHeartbeats 800000 in
  out/Ex/Soundness/Int/neg.lean:theorem Int.neg.r_twice.main.ok : Int.neg.r_twice.main.Stmt := kanon_proof% Int.neg.r_twice.main
  --
  out/Ex/Soundness/Int/neg.lean-set_option maxHeartbeats 800000 in
  out/Ex/Soundness/Int/neg.lean:theorem Int.neg.r_default.main.ok : Int.neg.r_default.main.Stmt := kanon_proof% Int.neg.r_default.main
  --
  out/Ex/Soundness/Int/plus.lean-set_option maxHeartbeats 300000 in
  out/Ex/Soundness/Int/plus.lean:theorem Int.plus.r_lits.main.ok : Int.plus.r_lits.main.Stmt := kanon_proof% Int.plus.r_lits.main
  --
  out/Ex/Soundness/Int/plus.lean-set_option maxHeartbeats 300000 in
  out/Ex/Soundness/Int/plus.lean:theorem Int.plus.r_unit_zero.main.ok : Int.plus.r_unit_zero.main.Stmt := kanon_proof% Int.plus.r_unit_zero.main
  --
  out/Ex/Soundness/Int/plus.lean-set_option maxHeartbeats 300000 in
  out/Ex/Soundness/Int/plus.lean:theorem Int.plus.r_default.main.ok : Int.plus.r_default.main.Stmt := kanon_proof% Int.plus.r_default.main

Nodes.lean states the typing and the evaluation of each node, as the simp sets
kanon_wt and kanon_ev of the language unfold them.

  $ sed -n '/Nodes.Op2.Plus.wt/,/^$/p' out/Ex/Nodes.lean
  @[kanon_node_wt] theorem Nodes.Op2.Plus.wt (a1 : Term) (a2 : Term) (t : Ty) :
    kanon_unfold_eq% kanon_wt (sem.WT (Term.mk (Kind.Op2 Op2.Plus a1 a2) t)) := by
    simp only [kanon_wt]
  

With --check, kanon lean-all only checks that the files are up to date.

  $ kanon lean-all --check out lang.knl

The hand-written proofs of a rule function, under Proofs, are imported by its
generated proofs, under Soundness, when they exist (Proofs/Laws.lean for
Soundness/Laws.lean):

  $ mkdir -p out/Ex/Proofs/Int
  $ echo 'import Ex.Statements.Int.neg' > out/Ex/Proofs/Int/neg.lean
  $ kanon lean-all --check out lang.knl
  kanon: out/Ex/Soundness/Int/neg.lean is not up to date (run kanon lean-all)
  [1]
  $ kanon lean-all out lang.knl
  $ grep '^import' out/Ex/Soundness/Int/neg.lean
  import Ex.Statements.Int.neg
  import Ex.Soundness.Laws
  import Ex.Proofs.Int.neg

The files that kanon generated and no longer does are removed; the others are
kept.

  $ echo '-- Generated by kanon from int.kn. Do not edit.' > out/Ex/Model/Int/old.lean
  $ echo '-- A file of mine.' > out/Ex/Model/Int/mine.lean
  $ kanon lean-all --check out lang.knl
  kanon: out/Ex/Model/Int/old.lean is no longer generated (run kanon lean-all)
  [1]
  $ kanon lean-all out lang.knl
  $ ls out/Ex/Model/Int
  add.lean
  mine.lean
  neg.lean
  negate.lean
  plus.lean

The bound on heartbeats is a positive number.

  $ mkdir bad && cp lang.knl int.knl bad && sed 's/800000/0/' int.kn > bad/int.kn
  $ kanon lean-all out bad/lang.knl
  bad/int.kn:7:17: [@lean_heartbeats n]: n must be a positive integer
  [1]
