-- Generated by kanon from num.knl, num.kn. Do not edit.
import KanonCore.Embed

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace NumMod

open Classical Kanon

/-- The sorts of the module. -/
inductive Srt where
  | TNum
  deriving DecidableEq, Repr, Inhabited

/-- The nodes of the module, over the terms `T` of a language. -/
inductive Node (T : Type) where
  | Num (x1 : Int)
  | Add (a1 : T) (a2 : T)
  | Lt (a1 : T) (a2 : T)
  /-- The maximum of two integers. -/
  | Max (a1 : T) (a2 : T)

namespace Node

variable {T U : Type}

/-- The node with its children mapped by `f`. -/
def map (f : T → U) : Node T → Node U
  | (.Num x1) => (.Num x1)
  | (.Add a1 a2) => (.Add (f a1) (f a2))
  | (.Lt a1 a2) => (.Lt (f a1) (f a2))
  | (.Max a1 a2) => (.Max (f a1) (f a2))

/-- Every child of the node satisfies `P`. -/
def All (P : T → Prop) : Node T → Prop
  | (.Num x1) => True
  | (.Add a1 a2) => P a1 ∧ P a2
  | (.Lt a1 a2) => P a1 ∧ P a2
  | (.Max a1 a2) => P a1 ∧ P a2

/-- The nodes have the same arguments, and their children are related by `R`. -/
def Rel (R : T → U → Prop) : Node T → Node U → Prop
  | (.Num x1), (.Num x1') => x1 = x1'
  | (.Add a1 a2), (.Add a1' a2') => R a1 a1' ∧ R a2 a2'
  | (.Lt a1 a2), (.Lt a1' a2') => R a1 a1' ∧ R a2 a2'
  | (.Max a1 a2), (.Max a1' a2') => R a1 a1' ∧ R a2 a2'
  | _, _ => False

end Node

end NumMod
