-- Generated by kanon from num.knl, num.kn. Do not edit.
import NumMod.Ops

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace NumMod

open Classical Kanon

/-- The operands of `Add` commute. -/
def Add.comm.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} (L : NumMod.Syntax B LBool) [KanonBool.Sem LBool] [Sem L] (a b : S.Term) (t : S.Ty),
  S.Refines (B.node (L.AddK a b) t)
  (B.node (L.AddK b a) t)

end NumMod
