-- Generated by kanon from num.knl, num.kn. Do not edit.
import KanonCore.Generic
import KanonBool.Syntax

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace NumMod

open Classical Kanon

/-- What the module `Num` needs of the terms `B` of a language of semantics `S`, whose
modules that it uses have the interfaces of the parameters: Kanon generates it, and each
language that uses the module gives it, by definition. -/
structure Syntax {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] (B : Kanon.Base S) (LBool : KanonBool.Syntax B) where
  TNum : S.Ty
  TNum_ne_TBool : TNum ≠ LBool.TBool
  NumK : Int → B.Kind
  AddK : S.Term → S.Term → B.Kind
  LtK : S.Term → S.Term → B.Kind
  /-- The maximum of two integers. -/
  MaxK : S.Term → S.Term → B.Kind
  NumK_name : ∀ (x1 : Int), B.kindName (NumK x1) = "Num"
  AddK_name : ∀ (a1 : S.Term) (a2 : S.Term), B.kindName (AddK a1 a2) = "Add"
  LtK_name : ∀ (a1 : S.Term) (a2 : S.Term), B.kindName (LtK a1 a2) = "Lt"
  MaxK_name : ∀ (a1 : S.Term) (a2 : S.Term), B.kindName (MaxK a1 a2) = "Max"
  num_is_pos : S.Term → Bool
  WT_Num : ∀ (x1 : Int) (t : S.Ty), S.WT (B.node (NumK x1) t) ↔ t = TNum
  WT_Add : ∀ (a1 : S.Term) (a2 : S.Term) (t : S.Ty), S.WT (B.node (AddK a1 a2) t) ↔ ((S.ty a1) = TNum ∧ (S.ty a2) = TNum ∧ t = TNum) ∧ S.WT a1 ∧ S.WT a2
  WT_Lt : ∀ (a1 : S.Term) (a2 : S.Term) (t : S.Ty), S.WT (B.node (LtK a1 a2) t) ↔ ((S.ty a1) = TNum ∧ (S.ty a2) = TNum ∧ t = LBool.TBool) ∧ S.WT a1 ∧ S.WT a2
  WT_Max : ∀ (a1 : S.Term) (a2 : S.Term) (t : S.Ty), S.WT (B.node (MaxK a1 a2) t) ↔ ((S.ty a1) = TNum ∧ (S.ty a2) = TNum ∧ t = TNum) ∧ S.WT a1 ∧ S.WT a2
  /-- The arguments of a `Num` node. -/
  asNum : S.Term → Option Int
  asNum_node : ∀ (x1 : Int) (t : S.Ty), asNum (B.node (NumK x1) t) = some x1
  asNum_sound : ∀ (v : S.Term) (x1 : Int), asNum v = some x1 → v = (B.node (NumK x1) (S.ty v))
  asNum_other : ∀ (k : B.Kind) (t : S.Ty), B.kindName k ≠ "Num" → asNum (B.node k t) = none
  /-- The arguments of a `Add` node. -/
  asAdd : S.Term → Option (S.Term × S.Term)
  asAdd_node : ∀ (a1 : S.Term) (a2 : S.Term) (t : S.Ty), asAdd (B.node (AddK a1 a2) t) = some (a1, a2)
  asAdd_sound : ∀ (v : S.Term) (a1 : S.Term) (a2 : S.Term), asAdd v = some (a1, a2) → v = (B.node (AddK a1 a2) (S.ty v))
  asAdd_other : ∀ (k : B.Kind) (t : S.Ty), B.kindName k ≠ "Add" → asAdd (B.node k t) = none
  /-- The arguments of a `Lt` node. -/
  asLt : S.Term → Option (S.Term × S.Term)
  asLt_node : ∀ (a1 : S.Term) (a2 : S.Term) (t : S.Ty), asLt (B.node (LtK a1 a2) t) = some (a1, a2)
  asLt_sound : ∀ (v : S.Term) (a1 : S.Term) (a2 : S.Term), asLt v = some (a1, a2) → v = (B.node (LtK a1 a2) (S.ty v))
  asLt_other : ∀ (k : B.Kind) (t : S.Ty), B.kindName k ≠ "Lt" → asLt (B.node k t) = none
  /-- The arguments of a `Max` node. -/
  asMax : S.Term → Option (S.Term × S.Term)
  asMax_node : ∀ (a1 : S.Term) (a2 : S.Term) (t : S.Ty), asMax (B.node (MaxK a1 a2) t) = some (a1, a2)
  asMax_sound : ∀ (v : S.Term) (a1 : S.Term) (a2 : S.Term), asMax v = some (a1, a2) → v = (B.node (MaxK a1 a2) (S.ty v))
  asMax_other : ∀ (k : B.Kind) (t : S.Ty), B.kindName k ≠ "Max" → asMax (B.node k t) = none
  /-- The arguments of the sort `TNum`. -/
  asTNum : S.Ty → Option Unit
  asTNum_sort : asTNum TNum = some ()
  asTNum_sound : ∀ (s : S.Ty), asTNum s = some () → s = TNum
  num_is_pos_eq : ∀ (v : S.Term), (num_is_pos v) =
      ((firstSome [(match (asNum v) with
                     | some z =>
                     some ((decide ((0 : Int) < z)))
                     | _ => none)]).getD
        (match v with | _ => false))

attribute [kanon_law]
  Syntax.NumK_name
  Syntax.asNum_other
  Syntax.AddK_name
  Syntax.asAdd_other
  Syntax.LtK_name
  Syntax.asLt_other
  Syntax.MaxK_name
  Syntax.asMax_other

end NumMod
