-- Generated by kanon from vec.knl, vec.kn. Do not edit.
import ArraysExample.Vec.Lift
import ArraysExample.Vec.Soundness.Vec.len
import ArraysExample.Vec.Soundness.Vec.get
import ArraysExample.Vec.Soundness.Vec.set

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace ArraysExample.Vec

open Classical Kanon

end ArraysExample.Vec
