Parametrised abstract types: `type 'a box [@ocaml "Box.t"]` declares a host type
constructor, applied to types where types are written (`t box`, `(t, int) pair`).
The generated OCaml passes the equality and the hash of the arguments to the
host's.

  $ cat > lang.knl <<'KN'
  > [@@@ocaml_prims "Prims"]
  > use "rules"
  > type 'a box [@ocaml "Box.t"] [@equal "Box.equal"] [@hash "Box.hash"]
  > type ('a, 'b) pair [@ocaml "Pair.t"] [@equal "Pair.equal"] [@hash "Pair.hash"]
  > sort TInt
  > node Int of int : TInt
  > node Arr of t box : TInt
  > node Pairs of (t, int) pair * (t box) option : TInt
  > KN
  $ cat > rules.kn <<'KN'
  > prim box_get : t box -> int -> t
  > fn first (b : t box) : t = box_get b 0
  > fn same (a b : t box) : bool = a = b
  > KN
  $ kanon ocaml-types lang.knl | sed -n '/^type/,/^and ty/p;/^and equal_kind/,/^and equal_ty/p'
  type 'a box = 'a Box.t
  
  and ('a0, 'a1) pair = ('a0, 'a1) Pair.t
  
  and kind =
    | Int of Z.t
    | Arr of (t box)
    | Pairs of ((t, Z.t) pair) * ((t box) option)
  
  and ty =
  and equal_kind (a : kind) (b : kind) =
    match (a, b) with
    | Int a1, Int b1 -> Z.equal a1 b1
    | Arr a1, Arr b1 -> (Box.equal equal_t) a1 b1
    | Pairs (a1, a2), Pairs (b1, b2) ->
        (Pair.equal equal_t Z.equal) a1 b1 &&
        (Option.equal (Box.equal equal_t)) a2 b2
    | _ -> false
  
  and hash_kind (a : kind) =
    match a with
    | Int a1 -> hash_combine (0) (Z.hash a1)
    | Arr a1 -> hash_combine (1) ((Box.hash hash_t) a1)
    | Pairs (a1, a2) ->
        hash_combine (hash_combine (2) ((Pair.hash hash_t Z.hash) a1))
          ((function None -> 0 | Some x -> hash_combine 1 ((Box.hash hash_t) x)) a2)
  
  and equal_ty (a : ty) (b : ty) =
  $ kanon ocaml lang.knl | sed -n '/^let/,$p'
  let[@inline] first (b : (t box)) : t = (Prims.box_get b Z.zero)
  
  let[@inline] same (a : (t box)) (b : (t box)) : bool =
      (((Box.equal equal_t) a b))
  
  let as_int (t : t) =
    match[@warning "-11"] t with { kind = Int (p1); _ } -> Some p1 | _ -> None
  
  let is_int (t : t) =
    match[@warning "-11"] t with { kind = Int (_); _ } -> true | _ -> false
  
  let as_arr (t : t) =
    match[@warning "-11"] t with { kind = Arr (p1); _ } -> Some p1 | _ -> None
  
  let is_arr (t : t) =
    match[@warning "-11"] t with { kind = Arr (_); _ } -> true | _ -> false
  
  let as_pairs (t : t) =
    match[@warning "-11"] t with { kind = Pairs (p1, p2); _ } -> Some (p1, p2) | _ -> None
  
  let is_pairs (t : t) =
    match[@warning "-11"] t with { kind = Pairs (_, _); _ } -> true | _ -> false
  
  let as_tint (t : ty) =
    match[@warning "-11"] t with TInt -> Some () | _ -> None
  
  let is_tint (t : ty) = match[@warning "-11"] t with TInt -> true | _ -> false
  
  
  $ kanon ocaml-tests lang.knl | sed -n '/^let untested/p'
  let untested = [  ]

Lean has no parametrised abstract types.

  $ kanon lean-syntax lang.knl > /dev/null
  lang.knl:3:8: type box is parametrised: parametrised abstract types are not supported in Lean
  [1]

Errors: the arity, unknown constructors, a parametrised type without arguments.

  $ cat > lang.knl <<'KN'
  > [@@@ocaml_prims "Prims"]
  > type 'a box [@ocaml "Box.t"] [@equal "Box.equal"] [@hash "Box.hash"]
  > type ('a, 'b) pair [@ocaml "Pair.t"] [@equal "Pair.equal"] [@hash "Pair.hash"]
  > sort TInt
  > node Int of int : TInt
  > KN
  $ for ty in "box" "(t, int) box" "int pair" "t array" "(int, int) list" "int t" "int option box"; do
  >   echo "prim p : $ty -> int" > rules.kn
  >   kanon ocaml lang.knl rules.kn 2>&1
  > done
  rules.kn:1:9: type box is parametrised: it expects 1 argument
  rules.kn:1:18: type box expects 1 argument, given 2
  rules.kn:1:13: type pair expects 2 arguments, given 1
  rules.kn:1:11: unknown type constructor array
  rules.kn:1:20: type list expects 1 argument, given 2
  rules.kn:1:13: type t takes no argument
  (* Generated by kanon from rules.kn. Do not edit. *)
  
  [@@@warning "-a+11"]
  
  module _ : sig
    val p : ((Z.t option) box) -> Z.t
  end = Prims
  
  let as_int (t : t) =
    match[@warning "-11"] t with { kind = Int (p1); _ } -> Some p1 | _ -> None
  
  let is_int (t : t) =
    match[@warning "-11"] t with { kind = Int (_); _ } -> true | _ -> false
  
  let as_tint (t : ty) =
    match[@warning "-11"] t with TInt -> Some () | _ -> None
  
  let is_tint (t : ty) = match[@warning "-11"] t with TInt -> true | _ -> false
  
  

Declarations: only abstract types have parameters, and the host's equality and
hash are required, since they take those of the arguments. A container has no
constructors in patterns, and `[@noeq]` forbids `=`.

  $ for decl in "type 'a r = { x : int }" "type 'a e = A | B" "type ('a, 'a) p [@ocaml \"P.t\"] [@equal \"P.equal\"] [@hash \"P.hash\"]" "type 'a b [@ocaml \"B.t\"]" "type 'a b [@ocaml \"B.t\"] [@equal \"B.equal\"]"; do
  >   printf '%s\nsort TInt\nnode Int of int : TInt\n' "$decl" > lang.knl
  >   kanon ocaml-types lang.knl 2>&1 | head -3
  > done
  lang.knl:1:8: type r: only abstract types have type parameters
  lang.knl:1:8: type e: only abstract types have type parameters
  lang.knl:1:14: type p: type parameters must be distinct
  lang.knl:1:8: type b is parametrised: [@equal "M.equal"] is required, a function taking the equality of each argument first
  lang.knl:1:8: type b is parametrised: [@hash "M.hash"] is required, a function taking the hash of each argument first
  $ cat > lang.knl <<'KN'
  > [@@@ocaml_prims "Prims"]
  > type 'a box [@ocaml "Box.t"] [@noeq] [@equal "Box.equal"] [@hash "Box.hash"]
  > sort TInt
  > node Int of int : TInt
  > KN
  $ cat > rules.kn <<'KN'
  > fn same (a b : t box) : bool = a = b
  > KN
  $ kanon ocaml lang.knl rules.kn
  rules.kn:1:31: equality is not allowed at type t box
  [1]
  $ cat > rules.kn <<'KN'
  > fn size (b : t box) : int = match b with [] -> 0 | _ -> 1
  > KN
  $ kanon ocaml lang.knl rules.kn
  rules.kn:1:41: [] at type t box
  [1]
  $ cat > rules.kn <<'KN'
  > fn size (b : t box) : int = match b with _ -> 1
  > fn id (b : t box) : t box = let c = b in c
  > KN
  $ kanon ocaml lang.knl rules.kn | grep -c "let\[@inline\]"
  2
