-- Generated by kanon from bool.kn, num.kn, neg.kn, even.kn, mix.kn. Do not edit.
import KanonCore.Tactics
import L3.Statements.Num.add
import L3.Instance.Neg
import L3.Lang
import NegMod.Soundness.Num.add
import L3.Instance.Num
import L3.Lang
import NumMod.Soundness.Num.add

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L3

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Num.add.r_unit_zero.main.ok : Num.add.r_unit_zero.main.Stmt :=
  fun O hO => NumMod.Num.add.r_unit_zero.main.ok (S := sem) numSyntax
  (Ops.toNum O) (Ops.Sound.toNum hO)

set_option maxHeartbeats 400000 in
theorem Num.add.r_unit_zero.swap.ok : Num.add.r_unit_zero.swap.Stmt :=
  fun O hO => NumMod.Num.add.r_unit_zero.swap.ok (S := sem) numSyntax
  (Ops.toNum O) (Ops.Sound.toNum hO)

theorem Num.add.r_unit_zero.proof : Num.add.r_unit_zero.Stmt := by
  intro O hO v1 v2 res h
  simp only [Num.add.r_unit_zero] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Num.add.r_unit_zero.main.ok O hO)
  · kanon_arm h (Num.add.r_unit_zero.swap.ok O hO)

set_option maxHeartbeats 400000 in
theorem Num.add.r_lits.main.ok : Num.add.r_lits.main.Stmt :=
  fun O hO => NumMod.Num.add.r_lits.main.ok (S := sem) numSyntax
  (Ops.toNum O) (Ops.Sound.toNum hO)

theorem Num.add.r_lits.proof : Num.add.r_lits.Stmt := by
  intro O hO v1 v2 res h
  simp only [Num.add.r_lits] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Num.add.r_lits.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Num.add.r_negself.main.ok : Num.add.r_negself.main.Stmt :=
  fun O hO => NegMod.Num.add.r_negself.main.ok (S := sem) negSyntax
  (Ops.toNeg O) (Ops.Sound.toNeg hO)

set_option maxHeartbeats 400000 in
theorem Num.add.r_negself.swap.ok : Num.add.r_negself.swap.Stmt :=
  fun O hO => NegMod.Num.add.r_negself.swap.ok (S := sem) negSyntax
  (Ops.toNeg O) (Ops.Sound.toNeg hO)

theorem Num.add.r_negself.proof : Num.add.r_negself.Stmt := by
  intro O hO v1 v2 res h
  simp only [Num.add.r_negself] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Num.add.r_negself.main.ok O hO)
  · kanon_arm h (Num.add.r_negself.swap.ok O hO)

set_option maxHeartbeats 400000 in
theorem Num.add.r_default.main.ok : Num.add.r_default.main.Stmt :=
  fun O hO => NumMod.Num.add.r_default.main.ok (S := sem) numSyntax
  (Ops.toNum O) (Ops.Sound.toNum hO)

theorem Num.add.r_default.proof : Num.add.r_default.Stmt := by
  intro O hO v1 v2 res h
  simp only [Num.add.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Num.add.r_default.main.ok O hO)

theorem Num.add.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (Num.add.spec v1 v2) (Num.add.step O v1 v2) := by
  unfold Num.add.step
  refine Refinement.firstSome_cons (fun res h => Num.add.r_unit_zero.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Num.add.r_lits.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Num.add.r_negself.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Num.add.r_default.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

end L3
