-- Generated by kanon from int.kn. Do not edit.
import DivisionExample.Signatures

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace DivisionExample

open Classical Kanon

def Int.add (x : Int) (y : Int) : Int :=
  (x + y)

end DivisionExample
