-- Generated by kanon from lang.knl. Do not edit.
import IntsExample.Node
import IntsExample.Sem
import KanonCore.Proof
import KanonBool.Lang
import IntMod.Lang

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace IntsExample

open Classical Kanon

/-- The typing of the nodes of the module, at the sorts of a language (by the embeddings
of the sorts of the modules), given the types of their children (`ty`). -/
def Node.wt {T Ty : Type} (sBool : KanonBool.Srt → Ty) (sInt : IntMod.Srt → Ty) (ty : T → Ty) : Node T → Ty → Prop
  | (.Var x1), t => True

/-- What the module needs of a language `S`: its nodes and sorts embedded in the terms and types
of `S`, which types and evaluates them as the module says. -/
class Lang (S : Kanon.Sem) [KanonBool.Lang S] [IntMod.Lang S] extends Values S.toDom where
  node : Kanon.NodeEmbed Node S
  WT_inj : ∀ n t, S.WT (node.inj n t) ↔ Node.wt (KanonBool.Lang.srt (S := S)).inj (IntMod.Lang.srt (S := S)).inj S.ty n t ∧ n.All S.WT
  ev_inj : ∀ ρ n t, S.ev ρ (node.inj n t) = Node.eval ρ t (n.map (S.ev ρ))
  proj_Bool_inj_Lang : ∀ n t, (KanonBool.Lang.node (S := S)).proj (node.inj n t) = none
  proj_Int_inj_Lang : ∀ n t, (IntMod.Lang.node (S := S)).proj (node.inj n t) = none
  proj_Lang_inj_Bool : ∀ n t, node.proj ((KanonBool.Lang.node (S := S)).inj n t) = none
  proj_Lang_inj_Int : ∀ n t, node.proj ((IntMod.Lang.node (S := S)).inj n t) = none

section

variable {S : Kanon.Sem} [KanonBool.Lang S] [IntMod.Lang S] [L : Lang S]

/-- The term of a node of the module. -/
abbrev mk (n : Node S.Term) (t : S.Ty) : S.Term := L.node.inj n t

/-- The node of the module that a term is, if it is one. -/
abbrev proj (e : S.Term) : Option (Node S.Term) := L.node.proj e

@[simp, kanon_wt] theorem ty_mk (n : Node S.Term) (t : S.Ty) : S.ty (mk n t) = t :=
  L.node.ty_inj n t

@[kanon_wt] theorem WT_mk (n : Node S.Term) (t : S.Ty) :
  S.WT (mk n t) ↔ Node.wt KanonBool.Lang.srt.inj IntMod.Lang.srt.inj S.ty n t ∧ n.All S.WT :=
  L.WT_inj n t

@[kanon_ev] theorem ev_mk (ρ : S.Env) (n : Node S.Term) (t : S.Ty) :
  S.ev ρ (mk n t) = Node.eval ρ t (n.map (S.ev ρ)) :=
  L.ev_inj ρ n t

@[simp] theorem proj_mk (n : Node S.Term) (t : S.Ty) : proj (mk n t) = some n :=
  L.node.proj_inj n t

@[simp] theorem mk_inj_iff {n n' : Node S.Term} {t t' : S.Ty} :
  mk n t = mk n' t' ↔ n = n' ∧ t = t' :=
  L.node.inj_eq_iff

@[simp] theorem proj_Bool_mk_Lang (n : IntsExample.Node S.Term) (t : S.Ty) :
  KanonBool.proj (IntsExample.mk n t) = none :=
  L.proj_Bool_inj_Lang n t

@[simp] theorem proj_Int_mk_Lang (n : IntsExample.Node S.Term) (t : S.Ty) :
  IntMod.proj (IntsExample.mk n t) = none :=
  L.proj_Int_inj_Lang n t

@[simp] theorem proj_Lang_mk_Bool (n : KanonBool.Node S.Term) (t : S.Ty) :
  IntsExample.proj (KanonBool.mk n t) = none :=
  L.proj_Lang_inj_Bool n t

@[simp] theorem proj_Lang_mk_Int (n : IntMod.Node S.Term) (t : S.Ty) :
  IntsExample.proj (IntMod.mk n t) = none :=
  L.proj_Lang_inj_Int n t

/-- Refined children: the node is typed and evaluated as refined. -/
theorem Node.rel_refines {n n' : Node S.Term} (h : n.Rel S.Refines n') (w : n.All S.WT) :
  n'.All S.WT ∧ (∀ t, Node.wt KanonBool.Lang.srt.inj IntMod.Lang.srt.inj S.ty n t → Node.wt KanonBool.Lang.srt.inj IntMod.Lang.srt.inj S.ty n' t) ∧
    ∀ ρ, (n.map (S.ev ρ)).Rel Kanon.Sem.OLe (n'.map (S.ev ρ)) := by
  cases n <;> cases n' <;> simp only [Node.Rel, Node.All, Node.wt, Node.map] at h w ⊢ <;>
    kanon_rel_refines

/-- Refining the children of a node refines it, at the same sort (when it is well-typed). -/
@[kanon_congr_lemma] theorem mk_congr {n n' : Node S.Term} {t t' : S.Ty} (h : n.Rel S.Refines n')
    (ht : S.WT (mk n t) → t' = t) : S.Refines (mk n t) (mk n' t') := by
  refine Kanon.Sem.Refines.intro (fun w => ?_) (fun ρ v w _ e => ?_) <;> obtain rfl := (ht w).symm <;>
    rw [WT_mk] at w
  · obtain ⟨h1, h2, -⟩ := Node.rel_refines h w.2
    exact ⟨(WT_mk _ _).2 ⟨h2 t w.1, h1⟩, by simp only [ty_mk]⟩
  · rw [ev_mk] at e ⊢
    exact Node.eval_mono ρ t ((Node.rel_refines h w.2).2.2 ρ) v e

end

attribute [kanon_wt] Node.wt Node.All
attribute [kanon_ev] Node.map Node.eval
attribute [kanon_rel] Node.Rel

end IntsExample
