-- Generated by kanon from lang.knl, bool.knl, int.knl. Do not edit.
import IntsExample.Val
import KanonBool.Lang
import IntMod.Lang
import IntsExample.Lang

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace IntsExample

open Classical Kanon

mutual

/-- The typing of the terms. -/
def Term.WT : Term → Prop
  | .bool n t => KanonBool.Node.wt Ty.bool Term.ty n t ∧ allBool n
  | .int n t => IntMod.Node.wt Ty.bool Ty.int Term.ty n t ∧ allInt n
  | .lang n t => IntsExample.Node.wt Ty.bool Ty.int Term.ty n t ∧ allLang n

def allBool : KanonBool.Node Term → Prop
  | (.Bool x1) => True
  | (.Not a1) => a1.WT
  | (.And a1 a2) => a1.WT ∧ a2.WT
  | (.Or a1 a2) => a1.WT ∧ a2.WT
  | (.Eq a1 a2) => a1.WT ∧ a2.WT
  | (.Ite a1 a2 a3) => a1.WT ∧ a2.WT ∧ a3.WT
  | (.Distinct l1) => allList l1

def allInt : IntMod.Node Term → Prop
  | (.Int x1) => True
  | (.Plus a1 a2) => a1.WT ∧ a2.WT
  | (.Lt a1 a2) => a1.WT ∧ a2.WT

def allLang : IntsExample.Node Term → Prop
  | (.Var x1) => True

def allList : List Term → Prop
  | [] => True
  | x :: xs => x.WT ∧ allList xs

end

mutual

/-- The evaluation of the terms. -/
def ev (ρ : Env) : Term → Option Val
  | .bool n t => KanonBool.Node.eval (D := dom) ρ t (evBool ρ n)
  | .int n t => IntMod.Node.eval (D := dom) ρ t (evInt ρ n)
  | .lang n t => IntsExample.Node.eval (D := dom) ρ t (evLang ρ n)

def evBool (ρ : Env) : KanonBool.Node Term → KanonBool.Node (Option Val)
  | (.Bool x1) => (.Bool x1)
  | (.Not a1) => (.Not (ev ρ a1))
  | (.And a1 a2) => (.And (ev ρ a1) (ev ρ a2))
  | (.Or a1 a2) => (.Or (ev ρ a1) (ev ρ a2))
  | (.Eq a1 a2) => (.Eq (ev ρ a1) (ev ρ a2))
  | (.Ite a1 a2 a3) => (.Ite (ev ρ a1) (ev ρ a2) (ev ρ a3))
  | (.Distinct l1) => (.Distinct (evList ρ l1))

def evInt (ρ : Env) : IntMod.Node Term → IntMod.Node (Option Val)
  | (.Int x1) => (.Int x1)
  | (.Plus a1 a2) => (.Plus (ev ρ a1) (ev ρ a2))
  | (.Lt a1 a2) => (.Lt (ev ρ a1) (ev ρ a2))

def evLang (ρ : Env) : IntsExample.Node Term → IntsExample.Node (Option Val)
  | (.Var x1) => (.Var x1)

def evList (ρ : Env) : List Term → List (Option Val)
  | [] => []
  | x :: xs => ev ρ x :: evList ρ xs

end

theorem allList_iff : ∀ l, allList l ↔ ∀ x ∈ l, Term.WT x
  | [] => by simp [allList]
  | x :: xs => by simp [allList, allList_iff xs]

theorem evList_eq (ρ : Env) : ∀ l, evList ρ l = l.map (ev ρ)
  | [] => rfl
  | x :: xs => by rw [evList, evList_eq ρ xs]; rfl

theorem allBool_iff (n : KanonBool.Node Term) : allBool n ↔ n.All Term.WT := by
  cases n <;> simp [allBool, KanonBool.Node.All, allList_iff]

theorem evBool_eq (ρ : Env) (n : KanonBool.Node Term) : evBool ρ n = n.map (ev ρ) := by
  cases n <;> simp only [evBool, KanonBool.Node.map, evList_eq]

theorem allInt_iff (n : IntMod.Node Term) : allInt n ↔ n.All Term.WT := by
  cases n <;> simp [allInt, IntMod.Node.All, allList_iff]

theorem evInt_eq (ρ : Env) (n : IntMod.Node Term) : evInt ρ n = n.map (ev ρ) := by
  cases n <;> simp only [evInt, IntMod.Node.map, evList_eq]

theorem allLang_iff (n : IntsExample.Node Term) : allLang n ↔ n.All Term.WT := by
  cases n <;> simp [allLang, IntsExample.Node.All, allList_iff]

theorem evLang_eq (ρ : Env) (n : IntsExample.Node Term) : evLang ρ n = n.map (ev ρ) := by
  cases n <;> simp only [evLang, IntsExample.Node.map, evList_eq]

/-- The typing of a node of `Bool`. -/
theorem WT_bool (n : KanonBool.Node Term) (t : Ty) :
  Term.WT (.bool n t) ↔ KanonBool.Node.wt Ty.bool Term.ty n t ∧ n.All Term.WT := by
  show (_ ∧ allBool n) ↔ _; rw [allBool_iff]

/-- The evaluation of a node of `Bool`. -/
theorem ev_bool (ρ : Env) (n : KanonBool.Node Term) (t : Ty) :
  ev ρ (.bool n t) = KanonBool.Node.eval (D := dom) ρ t (n.map (ev ρ)) :=
  congrArg (KanonBool.Node.eval (D := dom) ρ t) (evBool_eq ρ n)

/-- The typing of a node of `Int`. -/
theorem WT_int (n : IntMod.Node Term) (t : Ty) :
  Term.WT (.int n t) ↔ IntMod.Node.wt Ty.bool Ty.int Term.ty n t ∧ n.All Term.WT := by
  show (_ ∧ allInt n) ↔ _; rw [allInt_iff]

/-- The evaluation of a node of `Int`. -/
theorem ev_int (ρ : Env) (n : IntMod.Node Term) (t : Ty) :
  ev ρ (.int n t) = IntMod.Node.eval (D := dom) ρ t (n.map (ev ρ)) :=
  congrArg (IntMod.Node.eval (D := dom) ρ t) (evInt_eq ρ n)

/-- The typing of a node of `Lang`. -/
theorem WT_lang (n : IntsExample.Node Term) (t : Ty) :
  Term.WT (.lang n t) ↔ IntsExample.Node.wt Ty.bool Ty.int Term.ty n t ∧ n.All Term.WT := by
  show (_ ∧ allLang n) ↔ _; rw [allLang_iff]

/-- The evaluation of a node of `Lang`. -/
theorem ev_lang (ρ : Env) (n : IntsExample.Node Term) (t : Ty) :
  ev ρ (.lang n t) = IntsExample.Node.eval (D := dom) ρ t (n.map (ev ρ)) :=
  congrArg (IntsExample.Node.eval (D := dom) ρ t) (evLang_eq ρ n)

/-- The semantics of the language. -/
@[reducible] def sem : Kanon.Sem where
  toDom := dom
  Term := Term
  ty := Term.ty
  WT := Term.WT
  ev := ev
  size := sizeOf

/-- The value of a term; `none` for poison. -/
abbrev eval : Env → Term → Option Val := sem.eval

/-- `r` refines `spec`: it has the same type, and the same value whenever `spec` is not poison. -/
abbrev Refines : Term → Term → Prop := sem.Refines

instance : Refinement Refines := Sem.refinement

instance instBoolLang : KanonBool.Lang sem where
  toValues := inferInstanceAs (KanonBool.Values dom)
  node := {
    inj := .bool
    proj := fun e => match e with | .bool n _ => some n | _ => none
    ty_inj := fun _ _ => rfl
    proj_inj := fun _ _ => rfl
    inj_proj := by intro e n h; cases e <;> cases h <;> rfl }
  WT_inj := WT_bool
  ev_inj := ev_bool
  size_proj := by kanon_size_proj
  srt := {
    inj := .bool
    proj := fun s => match s with | .bool s => some s | _ => none
    proj_inj := fun _ => rfl
    inj_proj := by intro b a h; cases b <;> cases h <;> rfl }

instance instIntLang : IntMod.Lang sem where
  toValues := inferInstanceAs (IntMod.Values dom)
  node := {
    inj := .int
    proj := fun e => match e with | .int n _ => some n | _ => none
    ty_inj := fun _ _ => rfl
    proj_inj := fun _ _ => rfl
    inj_proj := by intro e n h; cases e <;> cases h <;> rfl }
  WT_inj := WT_int
  ev_inj := ev_int
  size_proj := by kanon_size_proj
  srt := {
    inj := .int
    proj := fun s => match s with | .int s => some s | _ => none
    proj_inj := fun _ => rfl
    inj_proj := by intro b a h; cases b <;> cases h <;> rfl }
  proj_Bool_inj_Int _ _ := rfl
  proj_Int_inj_Bool _ _ := rfl
  sortProj_Bool_inj_Int _ := rfl
  sortProj_Int_inj_Bool _ := rfl

instance instLangLang : IntsExample.Lang sem where
  toValues := inferInstanceAs (IntsExample.Values dom)
  node := {
    inj := .lang
    proj := fun e => match e with | .lang n _ => some n | _ => none
    ty_inj := fun _ _ => rfl
    proj_inj := fun _ _ => rfl
    inj_proj := by intro e n h; cases e <;> cases h <;> rfl }
  WT_inj := WT_lang
  ev_inj := ev_lang
  size_proj := by kanon_size_proj
  proj_Bool_inj_Lang _ _ := rfl
  proj_Int_inj_Lang _ _ := rfl
  proj_Lang_inj_Bool _ _ := rfl
  proj_Lang_inj_Int _ _ := rfl

end IntsExample
