-- Generated by kanon from bool.kn, int.kn. Do not edit.

import IntsExample.Prims

namespace IntsExample

/-! The primitives of the rules, with the types they are declared with. -/

noncomputable section

example : Term := v_true
example : Term := v_false

end

end IntsExample
