-- Generated by kanon from bool.kn, int.kn. Do not edit.
import IntsExample.Semantics

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace IntsExample

open Classical Kanon

/-- Every rule function refines its spec. -/
structure Ops.Sound (O : Ops) : Prop where
  orc : O.orc.Compat
  bool_and_ : ∀ (v1 : Term) (v2 : Term), Refines (Bool.and_.spec v1 v2) (O.bool_and_ v1 v2)
  bool_or_ : ∀ (v1 : Term) (v2 : Term), Refines (Bool.or_.spec v1 v2) (O.bool_or_ v1 v2)
  bool_not_ : ∀ (sv : Term), Refines (Bool.not_.spec sv) (O.bool_not_ sv)
  bool_ite : ∀ (guard : Term) (if_ : Term) (else_ : Term), Refines (Bool.ite.spec guard if_ else_) (O.bool_ite guard if_ else_)
  bool_eq : ∀ (v1 : Term) (v2 : Term), Refines (Bool.eq.spec v1 v2) (O.bool_eq v1 v2)
  bool_eq_untyped : ∀ (v1 : Term) (v2 : Term), Refines (Bool.eq_untyped.spec v1 v2) (O.bool_eq_untyped v1 v2)
  bool_distinct : ∀ (l : (List Term)), Refines (Bool.distinct.spec l) (O.bool_distinct l)
  int_plus : ∀ (v1 : Term) (v2 : Term), Refines (Int.plus.spec v1 v2) (O.int_plus v1 v2)
  int_int_lt : ∀ (v1 : Term) (v2 : Term), Refines (Int.int_lt.spec v1 v2) (O.int_int_lt v1 v2)

/-- The operands of `Op2.And` commute. -/
def Op2.And.comm.Stmt : Prop :=
  ∀ (a b : Term) (t : Ty),
  Refines (Term.mk (Kind.Op2 Op2.And a b) t)
  (Term.mk (Kind.Op2 Op2.And b a) t)

/-- The operands of `Op2.Or` commute. -/
def Op2.Or.comm.Stmt : Prop :=
  ∀ (a b : Term) (t : Ty),
  Refines (Term.mk (Kind.Op2 Op2.Or a b) t)
  (Term.mk (Kind.Op2 Op2.Or b a) t)

/-- The operands of `Op2.Eq` commute. -/
def Op2.Eq.comm.Stmt : Prop :=
  ∀ (a b : Term) (t : Ty),
  Refines (Term.mk (Kind.Op2 Op2.Eq a b) t)
  (Term.mk (Kind.Op2 Op2.Eq b a) t)

/-- The operands of `Op2.Plus` commute. -/
def Op2.Plus.comm.Stmt : Prop :=
  ∀ (a b : Term) (t : Ty),
  Refines (Term.mk (Kind.Op2 Op2.Plus a b) t)
  (Term.mk (Kind.Op2 Op2.Plus b a) t)

def Bool.and_.r_same.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.and_.r_same O v1 v2 = some res →
  Refines (Bool.and_.spec v1 v2) res

def Bool.and_.r_false_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.and_.r_false_ O v1 v2 = some res →
  Refines (Bool.and_.spec v1 v2) res

def Bool.and_.r_true_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.and_.r_true_ O v1 v2 = some res →
  Refines (Bool.and_.spec v1 v2) res

def Bool.and_.r_not.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.and_.r_not O v1 v2 = some res →
  Refines (Bool.and_.spec v1 v2) res

def Bool.and_.r_and_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.and_.r_and_ O v1 v2 = some res →
  Refines (Bool.and_.spec v1 v2) res

def Bool.and_.r_or_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.and_.r_or_ O v1 v2 = some res →
  Refines (Bool.and_.spec v1 v2) res

def Bool.and_.r_eq_neq.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.and_.r_eq_neq O v1 v2 = some res →
  Refines (Bool.and_.spec v1 v2) res

def Bool.and_.r_default.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.and_.r_default O v1 v2 = some res →
  Refines (Bool.and_.spec v1 v2) res

def Bool.and_.r_same.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term),
  (decide (v1 = v2)) = true →
  Refines (Bool.and_.spec v1 v2)
  (v1)

def Bool.and_.r_false_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (t__2 : Ty),
  Refines (Bool.and_.spec (Term.mk (Kind.Bool false) t__2) v2)
  (v_false)

def Bool.and_.r_false_.swap.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (t__2 : Ty),
  Refines (Bool.and_.spec v1 (Term.mk (Kind.Bool false) t__2))
  (v_false)

def Bool.and_.r_true_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (t__2 : Ty),
  Refines (Bool.and_.spec (Term.mk (Kind.Bool true) t__2) v2)
  (v2)

def Bool.and_.r_true_.swap.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (t__2 : Ty),
  Refines (Bool.and_.spec v1 (Term.mk (Kind.Bool true) t__2))
  (v1)

def Bool.and_.r_not.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (kanon__3 : Term) (t__4 : Ty),
  (decide (v1 = kanon__3)) = true →
  Refines (Bool.and_.spec v1 (Term.mk (Kind.Op1 Op1.Not kanon__3) t__4))
  (v_false)

def Bool.and_.r_not.swap.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (kanon__3 : Term) (t__4 : Ty),
  (decide (v2 = kanon__3)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op1 Op1.Not kanon__3) t__4) v2)
  (v_false)

def Bool.and_.r_and_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (a : Term) (w__3 : Term) (t__4 : Ty),
  (decide (a = v2)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op2 Op2.And a w__3) t__4) v2)
  ((Term.mk (Kind.Op2 Op2.And a w__3) t__4))

def Bool.and_.r_and_.swap1.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (w__3 : Term) (a : Term) (t__4 : Ty),
  (decide (a = v2)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op2 Op2.And w__3 a) t__4) v2)
  ((Term.mk (Kind.Op2 Op2.And w__3 a) t__4))

def Bool.and_.r_and_.swap2.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (a : Term) (w__3 : Term) (t__4 : Ty),
  (decide (a = v1)) = true →
  Refines (Bool.and_.spec v1 (Term.mk (Kind.Op2 Op2.And a w__3) t__4))
  ((Term.mk (Kind.Op2 Op2.And a w__3) t__4))

def Bool.and_.r_and_.swap1_swap2.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (w__3 : Term) (a : Term) (t__4 : Ty),
  (decide (a = v1)) = true →
  Refines (Bool.and_.spec v1 (Term.mk (Kind.Op2 Op2.And w__3 a) t__4))
  ((Term.mk (Kind.Op2 Op2.And w__3 a) t__4))

def Bool.and_.r_or_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (a : Term) (w__3 : Term) (t__4 : Ty),
  (decide (a = v2)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op2 Op2.Or a w__3) t__4) v2)
  (a)

def Bool.and_.r_or_.swap1.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (w__3 : Term) (a : Term) (t__4 : Ty),
  (decide (a = v2)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op2 Op2.Or w__3 a) t__4) v2)
  (a)

def Bool.and_.r_or_.swap2.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (a : Term) (w__3 : Term) (t__4 : Ty),
  (decide (a = v1)) = true →
  Refines (Bool.and_.spec v1 (Term.mk (Kind.Op2 Op2.Or a w__3) t__4))
  (a)

def Bool.and_.r_or_.swap1_swap2.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (w__3 : Term) (a : Term) (t__4 : Ty),
  (decide (a = v1)) = true →
  Refines (Bool.and_.spec v1 (Term.mk (Kind.Op2 Op2.Or w__3 a) t__4))
  (a)

def Bool.and_.r_eq_neq.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (a : Term) (x : Term) (t__4 : Ty) (kanon__7 : Term) (y : Term) (t__9 : Ty),
  ((decide (a = kanon__7)) && (Bool.sure_neq x y)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op2 Op2.Eq a x) t__4) (Term.mk (Kind.Op2 Op2.Eq kanon__7 y) t__9))
  (v_false)

def Bool.and_.r_eq_neq.swap2.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (a : Term) (x : Term) (t__4 : Ty) (y : Term) (kanon__7 : Term) (t__9 : Ty),
  ((decide (a = kanon__7)) && (Bool.sure_neq x y)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op2 Op2.Eq a x) t__4) (Term.mk (Kind.Op2 Op2.Eq y kanon__7) t__9))
  (v_false)

def Bool.and_.r_eq_neq.swap1.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (x : Term) (a : Term) (t__4 : Ty) (kanon__7 : Term) (y : Term) (t__9 : Ty),
  ((decide (a = kanon__7)) && (Bool.sure_neq x y)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op2 Op2.Eq x a) t__4) (Term.mk (Kind.Op2 Op2.Eq kanon__7 y) t__9))
  (v_false)

def Bool.and_.r_eq_neq.swap1_swap2.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (x : Term) (a : Term) (t__4 : Ty) (y : Term) (kanon__7 : Term) (t__9 : Ty),
  ((decide (a = kanon__7)) && (Bool.sure_neq x y)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op2 Op2.Eq x a) t__4) (Term.mk (Kind.Op2 Op2.Eq y kanon__7) t__9))
  (v_false)

def Bool.and_.r_default.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term),
  Refines (Bool.and_.spec v1 v2)
  ((Term.mk (mk_commut_binop O Op2.And v1 v2) Ty.TBool))

def Bool.or_.r_same.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.or_.r_same O v1 v2 = some res →
  Refines (Bool.or_.spec v1 v2) res

def Bool.or_.r_true_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.or_.r_true_ O v1 v2 = some res →
  Refines (Bool.or_.spec v1 v2) res

def Bool.or_.r_false_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.or_.r_false_ O v1 v2 = some res →
  Refines (Bool.or_.spec v1 v2) res

def Bool.or_.r_not.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.or_.r_not O v1 v2 = some res →
  Refines (Bool.or_.spec v1 v2) res

def Bool.or_.r_or_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.or_.r_or_ O v1 v2 = some res →
  Refines (Bool.or_.spec v1 v2) res

def Bool.or_.r_and_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.or_.r_and_ O v1 v2 = some res →
  Refines (Bool.or_.spec v1 v2) res

def Bool.or_.r_default.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.or_.r_default O v1 v2 = some res →
  Refines (Bool.or_.spec v1 v2) res

def Bool.or_.r_same.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term),
  (decide (v1 = v2)) = true →
  Refines (Bool.or_.spec v1 v2)
  (v1)

def Bool.or_.r_true_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (t__2 : Ty),
  Refines (Bool.or_.spec (Term.mk (Kind.Bool true) t__2) v2)
  (v_true)

def Bool.or_.r_true_.swap.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (t__2 : Ty),
  Refines (Bool.or_.spec v1 (Term.mk (Kind.Bool true) t__2))
  (v_true)

def Bool.or_.r_false_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (t__2 : Ty),
  Refines (Bool.or_.spec (Term.mk (Kind.Bool false) t__2) v2)
  (v2)

def Bool.or_.r_false_.swap.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (t__2 : Ty),
  Refines (Bool.or_.spec v1 (Term.mk (Kind.Bool false) t__2))
  (v1)

def Bool.or_.r_not.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (kanon__3 : Term) (t__4 : Ty),
  (decide (v1 = kanon__3)) = true →
  Refines (Bool.or_.spec v1 (Term.mk (Kind.Op1 Op1.Not kanon__3) t__4))
  (v_true)

def Bool.or_.r_not.swap.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (kanon__3 : Term) (t__4 : Ty),
  (decide (v2 = kanon__3)) = true →
  Refines (Bool.or_.spec (Term.mk (Kind.Op1 Op1.Not kanon__3) t__4) v2)
  (v_true)

def Bool.or_.r_or_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (a : Term) (w__3 : Term) (t__4 : Ty),
  (decide (a = v2)) = true →
  Refines (Bool.or_.spec (Term.mk (Kind.Op2 Op2.Or a w__3) t__4) v2)
  ((Term.mk (Kind.Op2 Op2.Or a w__3) t__4))

def Bool.or_.r_or_.swap1.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (w__3 : Term) (a : Term) (t__4 : Ty),
  (decide (a = v2)) = true →
  Refines (Bool.or_.spec (Term.mk (Kind.Op2 Op2.Or w__3 a) t__4) v2)
  ((Term.mk (Kind.Op2 Op2.Or w__3 a) t__4))

def Bool.or_.r_or_.swap2.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (a : Term) (w__3 : Term) (t__4 : Ty),
  (decide (a = v1)) = true →
  Refines (Bool.or_.spec v1 (Term.mk (Kind.Op2 Op2.Or a w__3) t__4))
  ((Term.mk (Kind.Op2 Op2.Or a w__3) t__4))

def Bool.or_.r_or_.swap1_swap2.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (w__3 : Term) (a : Term) (t__4 : Ty),
  (decide (a = v1)) = true →
  Refines (Bool.or_.spec v1 (Term.mk (Kind.Op2 Op2.Or w__3 a) t__4))
  ((Term.mk (Kind.Op2 Op2.Or w__3 a) t__4))

def Bool.or_.r_and_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (a : Term) (w__3 : Term) (t__4 : Ty),
  (decide (a = v2)) = true →
  Refines (Bool.or_.spec (Term.mk (Kind.Op2 Op2.And a w__3) t__4) v2)
  (a)

def Bool.or_.r_and_.swap1.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (w__3 : Term) (a : Term) (t__4 : Ty),
  (decide (a = v2)) = true →
  Refines (Bool.or_.spec (Term.mk (Kind.Op2 Op2.And w__3 a) t__4) v2)
  (a)

def Bool.or_.r_and_.swap2.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (a : Term) (w__3 : Term) (t__4 : Ty),
  (decide (a = v1)) = true →
  Refines (Bool.or_.spec v1 (Term.mk (Kind.Op2 Op2.And a w__3) t__4))
  (a)

def Bool.or_.r_and_.swap1_swap2.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (w__3 : Term) (a : Term) (t__4 : Ty),
  (decide (a = v1)) = true →
  Refines (Bool.or_.spec v1 (Term.mk (Kind.Op2 Op2.And w__3 a) t__4))
  (a)

def Bool.or_.r_default.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term),
  Refines (Bool.or_.spec v1 v2)
  ((Term.mk (mk_commut_binop O Op2.Or v1 v2) Ty.TBool))

def Bool.not_.r_true_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (sv : Term) (res : Term), Bool.not_.r_true_ O sv = some res →
  Refines (Bool.not_.spec sv) res

def Bool.not_.r_false_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (sv : Term) (res : Term), Bool.not_.r_false_ O sv = some res →
  Refines (Bool.not_.spec sv) res

def Bool.not_.r_not.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (sv : Term) (res : Term), Bool.not_.r_not O sv = some res →
  Refines (Bool.not_.spec sv) res

def Bool.not_.r_or_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (sv : Term) (res : Term), Bool.not_.r_or_ O sv = some res →
  Refines (Bool.not_.spec sv) res

def Bool.not_.r_and_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (sv : Term) (res : Term), Bool.not_.r_and_ O sv = some res →
  Refines (Bool.not_.spec sv) res

def Bool.not_.r_ite.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (sv : Term) (res : Term), Bool.not_.r_ite O sv = some res →
  Refines (Bool.not_.spec sv) res

def Bool.not_.r_distinct.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (sv : Term) (res : Term), Bool.not_.r_distinct O sv = some res →
  Refines (Bool.not_.spec sv) res

def Bool.not_.r_default.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (sv : Term) (res : Term), Bool.not_.r_default O sv = some res →
  Refines (Bool.not_.spec sv) res

def Bool.not_.r_true_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (t__2 : Ty),
  Refines (Bool.not_.spec (Term.mk (Kind.Bool true) t__2))
  (v_false)

def Bool.not_.r_false_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (t__2 : Ty),
  Refines (Bool.not_.spec (Term.mk (Kind.Bool false) t__2))
  (v_true)

def Bool.not_.r_not.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (sv : Term) (t__3 : Ty),
  Refines (Bool.not_.spec (Term.mk (Kind.Op1 Op1.Not sv) t__3))
  (sv)

def Bool.not_.r_or_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (t__4 : Ty),
  Refines (Bool.not_.spec (Term.mk (Kind.Op2 Op2.Or v1 v2) t__4))
  ((O.bool_and_ (O.bool_not_ v1) (O.bool_not_ v2)))

def Bool.not_.r_and_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (t__4 : Ty),
  Refines (Bool.not_.spec (Term.mk (Kind.Op2 Op2.And v1 v2) t__4))
  ((O.bool_or_ (O.bool_not_ v1) (O.bool_not_ v2)))

def Bool.not_.r_ite.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (g : Term) (a : Term) (b : Term) (t__5 : Ty),
  Refines (Bool.not_.spec (Term.mk (Kind.Op3 Op3.Ite g a b) t__5))
  ((O.bool_ite g (O.bool_not_ a) (O.bool_not_ b)))

def Bool.not_.r_distinct.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (l : Term) (r : Term) (t__7 : Ty),
  Refines (Bool.not_.spec (Term.mk (Kind.OpN OpN.Distinct (l :: (r :: []))) t__7))
  ((O.bool_eq l r))

def Bool.not_.r_default.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (sv : Term),
  Refines (Bool.not_.spec sv)
  ((Term.mk (Kind.Op1 Op1.Not sv) Ty.TBool))

def Bool.ite.r_true_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_true_ O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_false_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_false_ O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_bool.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_bool O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_not_bool.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_not_bool O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_false_then.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_false_then O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_true_then.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_true_then O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_false_else.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_false_else O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_true_else.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_true_else O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_not_guard.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_not_guard O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_guard_then.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_guard_then O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_guard_else.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_guard_else O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_ite_then.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_ite_then O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_ite_else.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_ite_else O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_and_ite_then.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_and_ite_then O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_or_ite_else.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_or_ite_else O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_same.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_same O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_default.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term) (res : Term), Bool.ite.r_default O guard if_ else_ = some res →
  Refines (Bool.ite.spec guard if_ else_) res

def Bool.ite.r_true_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (if_ : Term) (else_ : Term) (t__2 : Ty),
  Refines (Bool.ite.spec (Term.mk (Kind.Bool true) t__2) if_ else_)
  (if_)

def Bool.ite.r_false_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (if_ : Term) (else_ : Term) (t__2 : Ty),
  Refines (Bool.ite.spec (Term.mk (Kind.Bool false) t__2) if_ else_)
  (else_)

def Bool.ite.r_bool.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (t__3 : Ty) (t__5 : Ty),
  Refines (Bool.ite.spec guard (Term.mk (Kind.Bool true) t__3) (Term.mk (Kind.Bool false) t__5))
  (guard)

def Bool.ite.r_not_bool.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (t__3 : Ty) (t__5 : Ty),
  Refines (Bool.ite.spec guard (Term.mk (Kind.Bool false) t__3) (Term.mk (Kind.Bool true) t__5))
  ((O.bool_not_ guard))

def Bool.ite.r_false_then.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (else_ : Term) (t__3 : Ty),
  Refines (Bool.ite.spec guard (Term.mk (Kind.Bool false) t__3) else_)
  ((O.bool_and_ (O.bool_not_ guard) else_))

def Bool.ite.r_true_then.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (else_ : Term) (t__3 : Ty),
  Refines (Bool.ite.spec guard (Term.mk (Kind.Bool true) t__3) else_)
  ((O.bool_or_ guard else_))

def Bool.ite.r_false_else.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (t__4 : Ty),
  Refines (Bool.ite.spec guard if_ (Term.mk (Kind.Bool false) t__4))
  ((O.bool_and_ guard if_))

def Bool.ite.r_true_else.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (t__4 : Ty),
  Refines (Bool.ite.spec guard if_ (Term.mk (Kind.Bool true) t__4))
  ((O.bool_or_ (O.bool_not_ guard) if_))

def Bool.ite.r_not_guard.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (if_ : Term) (else_ : Term) (g : Term) (t__3 : Ty),
  Refines (Bool.ite.spec (Term.mk (Kind.Op1 Op1.Not g) t__3) if_ else_)
  ((O.bool_ite g else_ if_))

def Bool.ite.r_guard_then.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term),
  (decide (guard = if_)) = true →
  Refines (Bool.ite.spec guard if_ else_)
  ((O.bool_or_ guard else_))

def Bool.ite.r_guard_else.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term),
  (decide (guard = else_)) = true →
  Refines (Bool.ite.spec guard if_ else_)
  ((O.bool_and_ guard if_))

def Bool.ite.r_ite_then.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (else_ : Term) (kanon__3 : Term) (x : Term) (w__5 : Term) (t__6 : Ty),
  (decide (guard = kanon__3)) = true →
  Refines (Bool.ite.spec guard (Term.mk (Kind.Op3 Op3.Ite kanon__3 x w__5) t__6) else_)
  ((O.bool_ite guard x else_))

def Bool.ite.r_ite_else.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (kanon__4 : Term) (w__5 : Term) (y : Term) (t__7 : Ty),
  (decide (guard = kanon__4)) = true →
  Refines (Bool.ite.spec guard if_ (Term.mk (Kind.Op3 Op3.Ite kanon__4 w__5 y) t__7))
  ((O.bool_ite guard if_ y))

def Bool.ite.r_and_ite_then.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (else_ : Term) (g : Term) (w__3 : Term) (t__4 : Ty) (kanon__7 : Term) (x : Term) (w__9 : Term) (t__10 : Ty),
  (decide (g = kanon__7)) = true →
  Refines (Bool.ite.spec (Term.mk (Kind.Op2 Op2.And g w__3) t__4) (Term.mk (Kind.Op3 Op3.Ite kanon__7 x w__9) t__10) else_)
  ((O.bool_ite (Term.mk (Kind.Op2 Op2.And g w__3) t__4) x else_))

def Bool.ite.r_and_ite_then.swap.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (else_ : Term) (w__3 : Term) (g : Term) (t__4 : Ty) (kanon__7 : Term) (x : Term) (w__9 : Term) (t__10 : Ty),
  (decide (g = kanon__7)) = true →
  Refines (Bool.ite.spec (Term.mk (Kind.Op2 Op2.And w__3 g) t__4) (Term.mk (Kind.Op3 Op3.Ite kanon__7 x w__9) t__10) else_)
  ((O.bool_ite (Term.mk (Kind.Op2 Op2.And w__3 g) t__4) x else_))

def Bool.ite.r_or_ite_else.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (if_ : Term) (g : Term) (w__3 : Term) (t__4 : Ty) (kanon__8 : Term) (w__9 : Term) (y : Term) (t__11 : Ty),
  (decide (g = kanon__8)) = true →
  Refines (Bool.ite.spec (Term.mk (Kind.Op2 Op2.Or g w__3) t__4) if_ (Term.mk (Kind.Op3 Op3.Ite kanon__8 w__9 y) t__11))
  ((O.bool_ite (Term.mk (Kind.Op2 Op2.Or g w__3) t__4) if_ y))

def Bool.ite.r_or_ite_else.swap.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (if_ : Term) (w__3 : Term) (g : Term) (t__4 : Ty) (kanon__8 : Term) (w__9 : Term) (y : Term) (t__11 : Ty),
  (decide (g = kanon__8)) = true →
  Refines (Bool.ite.spec (Term.mk (Kind.Op2 Op2.Or w__3 g) t__4) if_ (Term.mk (Kind.Op3 Op3.Ite kanon__8 w__9 y) t__11))
  ((O.bool_ite (Term.mk (Kind.Op2 Op2.Or w__3 g) t__4) if_ y))

def Bool.ite.r_same.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term),
  (decide (if_ = else_)) = true →
  Refines (Bool.ite.spec guard if_ else_)
  (if_)

def Bool.ite.r_default.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (guard : Term) (if_ : Term) (else_ : Term),
  Refines (Bool.ite.spec guard if_ else_)
  ((Term.mk (Kind.Op3 Op3.Ite guard if_ else_) (ty if_)))

def Bool.eq.r_ints.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.eq.r_ints O v1 v2 = some res →
  Refines (Bool.eq.spec v1 v2) res

def Bool.eq.r_same.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.eq.r_same O v1 v2 = some res →
  Refines (Bool.eq.spec v1 v2) res

def Bool.eq.r_bools.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.eq.r_bools O v1 v2 = some res →
  Refines (Bool.eq.spec v1 v2) res

def Bool.eq.r_ite_ite.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.eq.r_ite_ite O v1 v2 = some res →
  Refines (Bool.eq.spec v1 v2) res

def Bool.eq.r_false_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.eq.r_false_ O v1 v2 = some res →
  Refines (Bool.eq.spec v1 v2) res

def Bool.eq.r_true_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.eq.r_true_ O v1 v2 = some res →
  Refines (Bool.eq.spec v1 v2) res

def Bool.eq.r_nots.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.eq.r_nots O v1 v2 = some res →
  Refines (Bool.eq.spec v1 v2) res

def Bool.eq.r_default.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.eq.r_default O v1 v2 = some res →
  Refines (Bool.eq.spec v1 v2) res

def Bool.eq.r_ints.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (x : Int) (t__2 : Ty) (y : Int) (t__4 : Ty),
  Refines (Bool.eq.spec (Term.mk (Kind.Int x) t__2) (Term.mk (Kind.Int y) t__4))
  ((Bool.of_bool (decide (x = y))))

def Bool.eq.r_same.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term),
  (decide (v1 = v2)) = true →
  Refines (Bool.eq.spec v1 v2)
  (v_true)

def Bool.eq.r_bools.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (b1 : Bool) (t__2 : Ty) (b2 : Bool) (t__4 : Ty),
  Refines (Bool.eq.spec (Term.mk (Kind.Bool b1) t__2) (Term.mk (Kind.Bool b2) t__4))
  ((Bool.of_bool (decide (b1 = b2))))

def Bool.eq.r_ite_ite.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (b : Term) (l : Term) (r : Term) (t__5 : Ty) (kanon__7 : Term) (l' : Term) (r' : Term) (t__10 : Ty),
  (decide (b = kanon__7)) = true →
  Refines (Bool.eq.spec (Term.mk (Kind.Op3 Op3.Ite b l r) t__5) (Term.mk (Kind.Op3 Op3.Ite kanon__7 l' r') t__10))
  ((O.bool_ite b (O.bool_eq l l') (O.bool_eq r r')))

def Bool.eq.r_false_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (t__2 : Ty),
  Refines (Bool.eq.spec (Term.mk (Kind.Bool false) t__2) v2)
  ((O.bool_not_ v2))

def Bool.eq.r_false_.swap.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (t__2 : Ty),
  Refines (Bool.eq.spec v1 (Term.mk (Kind.Bool false) t__2))
  ((O.bool_not_ v1))

def Bool.eq.r_true_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (t__2 : Ty),
  Refines (Bool.eq.spec (Term.mk (Kind.Bool true) t__2) v2)
  (v2)

def Bool.eq.r_true_.swap.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (t__2 : Ty),
  Refines (Bool.eq.spec v1 (Term.mk (Kind.Bool true) t__2))
  (v1)

def Bool.eq.r_nots.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (b : Term) (t__3 : Ty) (c : Term) (t__6 : Ty),
  Refines (Bool.eq.spec (Term.mk (Kind.Op1 Op1.Not b) t__3) (Term.mk (Kind.Op1 Op1.Not c) t__6))
  ((O.bool_eq b c))

def Bool.eq.r_default.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term),
  Refines (Bool.eq.spec v1 v2)
  ((Term.mk (mk_commut_binop O Op2.Eq v1 v2) Ty.TBool))

def Bool.eq_untyped.r_ill_typed.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.eq_untyped.r_ill_typed O v1 v2 = some res →
  Refines (Bool.eq_untyped.spec v1 v2) res

def Bool.eq_untyped.r_typed.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.eq_untyped.r_typed O v1 v2 = some res →
  Refines (Bool.eq_untyped.spec v1 v2) res

def Bool.eq_untyped.r_ill_typed.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term),
  (! (decide ((ty v1) = (ty v2)))) = true →
  Refines (Bool.eq_untyped.spec v1 v2)
  (v_false)

def Bool.eq_untyped.r_typed.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term),
  Refines (Bool.eq_untyped.spec v1 v2)
  ((O.bool_eq v1 v2))

def Bool.distinct.r_small.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (l : (List Term)) (res : Term), Bool.distinct.r_small O l = some res →
  Refines (Bool.distinct.spec l) res

def Bool.distinct.r_distinct.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (l : (List Term)) (res : Term), Bool.distinct.r_distinct O l = some res →
  Refines (Bool.distinct.spec l) res

def Bool.distinct.r_not_distinct.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (l : (List Term)) (res : Term), Bool.distinct.r_not_distinct O l = some res →
  Refines (Bool.distinct.spec l) res

def Bool.distinct.r_default.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (l : (List Term)) (res : Term), Bool.distinct.r_default O l = some res →
  Refines (Bool.distinct.spec l) res

def Bool.distinct.r_small.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (l : (List Term)),
  (Bool.at_most_one l) = true →
  Refines (Bool.distinct.spec l)
  (v_true)

def Bool.distinct.r_distinct.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (l : (List Term)),
  (decide ((Bool.distinct_check l) = (some true))) = true →
  Refines (Bool.distinct.spec l)
  (v_true)

def Bool.distinct.r_not_distinct.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (l : (List Term)),
  (decide ((Bool.distinct_check l) = (some false))) = true →
  Refines (Bool.distinct.spec l)
  (v_false)

def Bool.distinct.r_default.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (l : (List Term)),
  Refines (Bool.distinct.spec l)
  ((Term.mk (Kind.OpN OpN.Distinct (O.orc.sort_by_tag l)) Ty.TBool))

def Int.plus.r_lits.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Int.plus.r_lits O v1 v2 = some res →
  Refines (Int.plus.spec v1 v2) res

def Int.plus.r_unit_zero.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Int.plus.r_unit_zero O v1 v2 = some res →
  Refines (Int.plus.spec v1 v2) res

def Int.plus.r_default.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Int.plus.r_default O v1 v2 = some res →
  Refines (Int.plus.spec v1 v2) res

def Int.plus.r_lits.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (i1 : Int) (t__2 : Ty) (i2 : Int) (t__4 : Ty),
  Refines (Int.plus.spec (Term.mk (Kind.Int i1) t__2) (Term.mk (Kind.Int i2) t__4))
  ((Term.mk (Kind.Int (Int.add i1 i2)) Ty.TInt))

def Int.plus.r_unit_zero.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (kanon__2 : Int) (t__3 : Ty),
  (decide (kanon__2 = (0 : Int))) = true →
  Refines (Int.plus.spec v1 (Term.mk (Kind.Int kanon__2) t__3))
  (v1)

def Int.plus.r_unit_zero.swap.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (kanon__2 : Int) (t__3 : Ty),
  (decide (kanon__2 = (0 : Int))) = true →
  Refines (Int.plus.spec (Term.mk (Kind.Int kanon__2) t__3) v2)
  (v2)

def Int.plus.r_default.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term),
  Refines (Int.plus.spec v1 v2)
  ((Term.mk (mk_commut_binop O Op2.Plus v1 v2) Ty.TInt))

def Int.int_lt.r_lits.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Int.int_lt.r_lits O v1 v2 = some res →
  Refines (Int.int_lt.spec v1 v2) res

def Int.int_lt.r_same.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Int.int_lt.r_same O v1 v2 = some res →
  Refines (Int.int_lt.spec v1 v2) res

def Int.int_lt.r_default.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Int.int_lt.r_default O v1 v2 = some res →
  Refines (Int.int_lt.spec v1 v2) res

def Int.int_lt.r_lits.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (x : Int) (t__2 : Ty) (y : Int) (t__4 : Ty),
  Refines (Int.int_lt.spec (Term.mk (Kind.Int x) t__2) (Term.mk (Kind.Int y) t__4))
  ((Bool.of_bool (decide (x < y))))

def Int.int_lt.r_same.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term),
  (decide (v1 = v2)) = true →
  Refines (Int.int_lt.spec v1 v2)
  (v_false)

def Int.int_lt.r_default.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term),
  Refines (Int.int_lt.spec v1 v2)
  ((Term.mk (Kind.Op2 Op2.Lt v1 v2) Ty.TBool))

end IntsExample
