-- Generated by kanon from bool.kn, int.kn. Do not edit.
import IntsExample.Prims

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace IntsExample

open Classical Kanon

def Op1.WT : Op1 → Ty → Ty → Prop
  | .Not, kanon__a, kanon__t =>
      kanon__a = Ty.TBool ∧ kanon__t = Ty.TBool

def Op2.WT : Op2 → Ty → Ty → Ty → Prop
  | .And, kanon__a, kanon__b, kanon__t
  | .Or, kanon__a, kanon__b, kanon__t =>
      kanon__a = Ty.TBool ∧ kanon__b = Ty.TBool ∧ kanon__t = Ty.TBool
  | .Eq, kanon__a, kanon__b, kanon__t =>
      kanon__b = kanon__a ∧ kanon__t = Ty.TBool
  | .Plus, kanon__a, kanon__b, kanon__t =>
      kanon__a = Ty.TInt ∧ kanon__b = Ty.TInt ∧ kanon__t = Ty.TInt
  | .Lt, kanon__a, kanon__b, kanon__t =>
      kanon__a = Ty.TInt ∧ kanon__b = Ty.TInt ∧ kanon__t = Ty.TBool

def Op3.WT : Op3 → Ty → Ty → Ty → Ty → Prop
  | .Ite, kanon__a, kanon__b, kanon__c, kanon__t =>
      kanon__a = Ty.TBool ∧ kanon__c = kanon__b ∧ kanon__t = kanon__b

def OpN.WT : OpN → Ty → Ty → Prop
  | .Distinct, kanon__a, kanon__t =>
      kanon__t = Ty.TBool

end IntsExample
