-- Generated by kanon from even.knl, even.kn. Do not edit.
import EvenMod.Statements.Even.rem2
import EvenMod.Soundness.Laws
import EvenMod.Proofs.Even.rem2

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace EvenMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Even.rem2.r_lit.main.ok : Even.rem2.r_lit.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Even.rem2.r_lit.main)

set_option maxHeartbeats 400000 in
theorem Even.rem2.r_default.main.ok : Even.rem2.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Even.rem2.r_default.main)

end EvenMod
