-- Generated by kanon from even.knl, even.kn. Do not edit.
import EvenMod.Statements
import EvenMod.Lifts
import EvenMod.Lib.Rule

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace EvenMod

open Classical Kanon

end EvenMod
