-- Generated by kanon from bool.kn. Do not edit.
import BoolExample.Ops
import BoolExample.Model.Bool.sure_neq
import BoolExample.Model.mk_commut_binop

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BoolExample

open Classical Kanon

def Bool.and_.r_same (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with | v, kanon__2 => (whenSome (decide (v = kanon__2)) (v)))

def Bool.and_.r_false_ (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Bool false) _), _ =>
    (whenSome true (v_false))
    | _, _ => none)
  <|> (match v1, v2 with
        | _, (Term.mk (Kind.Bool false) _) =>
        (whenSome true (v_false))
        | _, _ => none)

def Bool.and_.r_true_ (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Bool true) _), x =>
    (whenSome true (x))
    | _, _ => none)
  <|> (match v1, v2 with
        | x, (Term.mk (Kind.Bool true) _) =>
        (whenSome true (x))
        | _, _ => none)

def Bool.and_.r_not (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | p, (Term.mk (Kind.Op1 Op1.Not kanon__3) _) =>
    (whenSome (decide (p = kanon__3)) (v_false))
    | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Op1 Op1.Not kanon__3) _), p =>
        (whenSome (decide (p = kanon__3)) (v_false))
        | _, _ => none)

def Bool.and_.r_and_ (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | x@(Term.mk (Kind.Op2 Op2.And a _) _), kanon__7 =>
    (whenSome (decide (a = kanon__7)) (x))
    | _, _ => none)
  <|> (match v1, v2 with
        | x@(Term.mk (Kind.Op2 Op2.And _ a) _), kanon__7 =>
        (whenSome (decide (a = kanon__7)) (x))
        | _, _ => none)
  <|> (match v1, v2 with
        | kanon__7, x@(Term.mk (Kind.Op2 Op2.And a _) _) =>
        (whenSome (decide (a = kanon__7)) (x))
        | _, _ => none)
  <|> (match v1, v2 with
        | kanon__7, x@(Term.mk (Kind.Op2 Op2.And _ a) _) =>
        (whenSome (decide (a = kanon__7)) (x))
        | _, _ => none)

def Bool.and_.r_or_ (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Op2 Op2.Or a _) _), kanon__6 =>
    (whenSome (decide (a = kanon__6)) (a))
    | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Op2 Op2.Or _ a) _), kanon__6 =>
        (whenSome (decide (a = kanon__6)) (a))
        | _, _ => none)
  <|> (match v1, v2 with
        | kanon__6, (Term.mk (Kind.Op2 Op2.Or a _) _) =>
        (whenSome (decide (a = kanon__6)) (a))
        | _, _ => none)
  <|> (match v1, v2 with
        | kanon__6, (Term.mk (Kind.Op2 Op2.Or _ a) _) =>
        (whenSome (decide (a = kanon__6)) (a))
        | _, _ => none)

def Bool.and_.r_eq_neq (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Op2 Op2.Eq a x) _), (Term.mk (Kind.Op2 Op2.Eq kanon__7 y) _) =>
    (whenSome ((decide (a = kanon__7)) && (Bool.sure_neq x y)) (v_false))
    | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Op2 Op2.Eq a x) _), (Term.mk (Kind.Op2 Op2.Eq y kanon__7) _) =>
        (whenSome ((decide (a = kanon__7)) && (Bool.sure_neq x y)) (v_false))
        | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Op2 Op2.Eq x a) _), (Term.mk (Kind.Op2 Op2.Eq kanon__7 y) _) =>
        (whenSome ((decide (a = kanon__7)) && (Bool.sure_neq x y)) (v_false))
        | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Op2 Op2.Eq x a) _), (Term.mk (Kind.Op2 Op2.Eq y kanon__7) _) =>
        (whenSome ((decide (a = kanon__7)) && (Bool.sure_neq x y)) (v_false))
        | _, _ => none)

def Bool.and_.r_default (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | _, _ =>
    (whenSome true ((Term.mk (mk_commut_binop O Op2.And v1 v2) Ty.TBool))))

def Bool.and_.step (O : Ops) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [Bool.and_.r_same O v1 v2, Bool.and_.r_false_ O v1 v2, Bool.and_.r_true_ O v1 v2, Bool.and_.r_not O v1 v2, Bool.and_.r_and_ O v1 v2, Bool.and_.r_or_ O v1 v2, Bool.and_.r_eq_neq O v1 v2, Bool.and_.r_default O v1 v2]).getD (Bool.and_.spec v1 v2)

end BoolExample
