-- Generated by kanon from bool.kn. Do not edit.
import BoolExample.Signatures

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BoolExample

open Classical Kanon

def Bool.at_most_one (l : (List Term)) : Bool :=
  ((firstSome [(match l with | [] => some (true) | _ => none),
    (match l with | (_ :: []) => some (true) | _ => none)]).getD
    (match l with | _ => false))

end BoolExample
