-- Generated by kanon from l2.knl. Do not edit.
import L2.Lang
import L2.Sem
import NegMod.Model
import KanonCore.Model
import KanonCore.Attr
import KanonCore.Embed

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace L2

open Classical Kanon

/-- The rule functions, oracles and extensible helpers of the module, in the model of a
language. -/
structure Ops (S : Kanon.Sem) extends toNegOps : NegMod.Ops S

variable {S : Kanon.Sem} [KanonBool.Lang S] [NumMod.Lang S] [NegMod.Lang S] [L2.Lang S]

/-- What the proofs assume of the model: its rule functions refine their specs, its oracles
and extensible helpers do what they are assumed to do. -/
structure Ops.Sound (O : Ops S) : Prop extends toNegSound : NegMod.Ops.Sound O.toNegOps

end L2
