-- Generated by kanon from int.kn. Do not edit.
import DivisionExample.Statements
import DivisionExample.Model.Int.div

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace DivisionExample

open Classical Kanon

def Int.div.r_self.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Int.div.r_self O v1 v2 = some res →
  Refines (Int.div.spec v1 v2) res

def Int.div.r_default.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Int.div.r_default O v1 v2 = some res →
  Refines (Int.div.spec v1 v2) res

def Int.div.r_self.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term),
  Nonzero v2 →
  (decide (v1 = v2)) = true →
  Refines (Int.div.spec v1 v2)
  ((Term.mk (Kind.Int (1 : Int)) Ty.TInt))

def Int.div.r_default.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term),
  Nonzero v2 →
  Refines (Int.div.spec v1 v2)
  ((Term.mk (Kind.Op2 Op2.Div v1 v2) Ty.TInt))

end DivisionExample
