-- Generated by kanon from vec.kn. Do not edit.
import ArraysExample.Signatures

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace ArraysExample

open Classical Kanon

def Vec.in_bounds (a : (Array Int)) (i : Int) : Bool :=
  ((decide ((0 : Int) ≤ i)) && (decide (i < (arrayLength a))))

end ArraysExample
