-- Generated by kanon from vec.kn. Do not edit.
import ArraysExample.Ops

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace ArraysExample

open Classical Kanon

def Vec.len.r_lit (O : Ops) (v : Term) : Option Term :=
  (match v with
    | (Term.mk (Kind.Vec a) _) =>
    (whenSome true ((Term.mk (Kind.Int (arrayLength a)) Ty.TInt)))
    | _ => none)

def Vec.len.r_default (O : Ops) (v : Term) : Option Term :=
  (match v with
    | _ =>
    (whenSome true ((Term.mk (Kind.Op1 Op1.Len v) Ty.TInt))))

def Vec.len.step (O : Ops) (v : Term) : Term :=
  (firstSome [Vec.len.r_lit O v, Vec.len.r_default O v]).getD (Vec.len.spec v)

end ArraysExample
