-- Generated by kanon from vec.kn. Do not edit.
import ArraysExample.Signatures

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace ArraysExample

open Classical Kanon

def Vec.same (a : (Array Int)) (b : (Array Int)) : Bool :=
  (decide (a = b))

end ArraysExample
