-- Generated by kanon from bool.knl, bool.kn. Do not edit.
import KanonBool.Statements.Bool.and_
import KanonBool.Proofs
import KanonBool.Soundness.Comm

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace KanonBool

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_same.main.ok : Bool.and_.r_same.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.and_.r_same.main)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_false_.main.ok : Bool.and_.r_false_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.and_.r_false_.main)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_false_.swap.ok : Bool.and_.r_false_.swap.Stmt := by
  intro S _ _ O hO v1 t__2
  refine Kanon.Sem.Refines.trans ?_ (Bool.and_.r_false_.main.ok O hO v1 t__2)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.And.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_true_.main.ok : Bool.and_.r_true_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.and_.r_true_.main)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_true_.swap.ok : Bool.and_.r_true_.swap.Stmt := by
  intro S _ _ O hO v1 t__2
  refine Kanon.Sem.Refines.trans ?_ (Bool.and_.r_true_.main.ok O hO v1 t__2)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.And.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_not.main.ok : Bool.and_.r_not.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.and_.r_not.main)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_not.swap.ok : Bool.and_.r_not.swap.Stmt := by
  intro S _ _ O hO v2 kanon__3 t__4 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bool.and_.r_not.main.ok O hO v2 kanon__3 t__4 hg)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.And.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_and_.main.ok : Bool.and_.r_and_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.and_.r_and_.main)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_and_.swap1.ok : Bool.and_.r_and_.swap1.Stmt := by
  intro S _ _ O hO v2 w__3 a t__4 hg
  have : S.Refines (KanonBool.mk (.And w__3 a) t__4)
    (KanonBool.mk (.And a w__3) t__4) :=
    KanonBool.And.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Kanon.Sem.Refines.trans (Bool.and_.r_and_.main.ok O hO v2 a w__3 t__4 hg)
    (by (try dsimp only); (repeat' apply Kanon.Refinement.ite_congr) <;> first | exact Kanon.Sem.Refines.refl | kanon_comm))
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_and_.swap2.ok : Bool.and_.r_and_.swap2.Stmt := by
  intro S _ _ O hO v1 a w__3 t__4 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bool.and_.r_and_.main.ok O hO v1 a w__3 t__4 hg)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.And.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_and_.swap1_swap2.ok : Bool.and_.r_and_.swap1_swap2.Stmt := by
  intro S _ _ O hO v1 w__3 a t__4 hg
  have : S.Refines (KanonBool.mk (.And w__3 a) t__4)
    (KanonBool.mk (.And a w__3) t__4) :=
    KanonBool.And.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Kanon.Sem.Refines.trans (Bool.and_.r_and_.main.ok O hO v1 a w__3 t__4 hg)
    (by (try dsimp only); (repeat' apply Kanon.Refinement.ite_congr) <;> first | exact Kanon.Sem.Refines.refl | kanon_comm))
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.And.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_or_.main.ok : Bool.and_.r_or_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.and_.r_or_.main)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_or_.swap1.ok : Bool.and_.r_or_.swap1.Stmt := by
  intro S _ _ O hO v2 w__3 a t__4 hg
  have : S.Refines (KanonBool.mk (.Or w__3 a) t__4)
    (KanonBool.mk (.Or a w__3) t__4) :=
    KanonBool.Or.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.and_.r_or_.main.ok O hO v2 a w__3 t__4 hg)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_or_.swap2.ok : Bool.and_.r_or_.swap2.Stmt := by
  intro S _ _ O hO v1 a w__3 t__4 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bool.and_.r_or_.main.ok O hO v1 a w__3 t__4 hg)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.And.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_or_.swap1_swap2.ok : Bool.and_.r_or_.swap1_swap2.Stmt := by
  intro S _ _ O hO v1 w__3 a t__4 hg
  have : S.Refines (KanonBool.mk (.Or w__3 a) t__4)
    (KanonBool.mk (.Or a w__3) t__4) :=
    KanonBool.Or.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.and_.r_or_.main.ok O hO v1 a w__3 t__4 hg)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.And.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_eq_neq.main.ok : Bool.and_.r_eq_neq.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.and_.r_eq_neq.main)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_eq_neq.swap2.ok : Bool.and_.r_eq_neq.swap2.Stmt := by
  intro S _ _ O hO a x t__4 y kanon__7 t__9 hg
  have : S.Refines (KanonBool.mk (.Eq y kanon__7) t__9)
    (KanonBool.mk (.Eq kanon__7 y) t__9) :=
    KanonBool.Eq.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.and_.r_eq_neq.main.ok O hO a x t__4 kanon__7 y t__9 hg)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_eq_neq.swap1.ok : Bool.and_.r_eq_neq.swap1.Stmt := by
  intro S _ _ O hO x a t__4 kanon__7 y t__9 hg
  have : S.Refines (KanonBool.mk (.Eq x a) t__4)
    (KanonBool.mk (.Eq a x) t__4) :=
    KanonBool.Eq.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.and_.r_eq_neq.main.ok O hO a x t__4 kanon__7 y t__9 hg)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_eq_neq.swap1_swap2.ok : Bool.and_.r_eq_neq.swap1_swap2.Stmt := by
  intro S _ _ O hO x a t__4 y kanon__7 t__9 hg
  have : S.Refines (KanonBool.mk (.Eq x a) t__4)
    (KanonBool.mk (.Eq a x) t__4) :=
    KanonBool.Eq.comm.ok ..
  have : S.Refines (KanonBool.mk (.Eq y kanon__7) t__9)
    (KanonBool.mk (.Eq kanon__7 y) t__9) :=
    KanonBool.Eq.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.and_.r_eq_neq.main.ok O hO a x t__4 kanon__7 y t__9 hg)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_default.main.ok : Bool.and_.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.and_.r_default.main)

theorem Bool.and_.r_same.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.and_.r_same O v1 v2 = some res) : S.Refines (KanonBool.Bool.and_.spec v1 v2) res := by
  unfold Bool.and_.r_same at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.and_.r_same.main.ok O hO)

theorem Bool.and_.r_false_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.and_.r_false_ O v1 v2 = some res) : S.Refines (KanonBool.Bool.and_.spec v1 v2) res := by
  unfold Bool.and_.r_false_ at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.and_.r_false_.main.ok O hO)
  · kanon_arm h (Bool.and_.r_false_.swap.ok O hO)

theorem Bool.and_.r_true_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.and_.r_true_ O v1 v2 = some res) : S.Refines (KanonBool.Bool.and_.spec v1 v2) res := by
  unfold Bool.and_.r_true_ at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.and_.r_true_.main.ok O hO)
  · kanon_arm h (Bool.and_.r_true_.swap.ok O hO)

theorem Bool.and_.r_not.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.and_.r_not O v1 v2 = some res) : S.Refines (KanonBool.Bool.and_.spec v1 v2) res := by
  unfold Bool.and_.r_not at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.and_.r_not.main.ok O hO)
  · kanon_arm h (Bool.and_.r_not.swap.ok O hO)

theorem Bool.and_.r_and_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.and_.r_and_ O v1 v2 = some res) : S.Refines (KanonBool.Bool.and_.spec v1 v2) res := by
  unfold Bool.and_.r_and_ at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.and_.r_and_.main.ok O hO)
  · kanon_arm h (Bool.and_.r_and_.swap1.ok O hO)
  · kanon_arm h (Bool.and_.r_and_.swap2.ok O hO)
  · kanon_arm h (Bool.and_.r_and_.swap1_swap2.ok O hO)

theorem Bool.and_.r_or_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.and_.r_or_ O v1 v2 = some res) : S.Refines (KanonBool.Bool.and_.spec v1 v2) res := by
  unfold Bool.and_.r_or_ at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.and_.r_or_.main.ok O hO)
  · kanon_arm h (Bool.and_.r_or_.swap1.ok O hO)
  · kanon_arm h (Bool.and_.r_or_.swap2.ok O hO)
  · kanon_arm h (Bool.and_.r_or_.swap1_swap2.ok O hO)

theorem Bool.and_.r_eq_neq.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.and_.r_eq_neq O v1 v2 = some res) : S.Refines (KanonBool.Bool.and_.spec v1 v2) res := by
  unfold Bool.and_.r_eq_neq at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.and_.r_eq_neq.main.ok O hO)
  · kanon_arm h (Bool.and_.r_eq_neq.swap2.ok O hO)
  · kanon_arm h (Bool.and_.r_eq_neq.swap1.ok O hO)
  · kanon_arm h (Bool.and_.r_eq_neq.swap1_swap2.ok O hO)

theorem Bool.and_.r_default.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.and_.r_default O v1 v2 = some res) : S.Refines (KanonBool.Bool.and_.spec v1 v2) res := by
  unfold Bool.and_.r_default at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.and_.r_default.main.ok O hO)

end KanonBool
