-- Generated by kanon from bool.knl, bool.kn. Do not edit.
import KanonBool.Statements.Bool.eq
import KanonBool.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace KanonBool

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_same.main.ok : Bool.eq.r_same.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_same.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_bools.main.ok : Bool.eq.r_bools.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_bools.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_ite_ite.main.ok : Bool.eq.r_ite_ite.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_ite_ite.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_false_.main.ok : Bool.eq.r_false_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_false_.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_false_.swap.ok : Bool.eq.r_false_.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_false_.swap)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_true_.main.ok : Bool.eq.r_true_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_true_.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_true_.swap.ok : Bool.eq.r_true_.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_true_.swap)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_nots.main.ok : Bool.eq.r_nots.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_nots.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_default.main.ok : Bool.eq.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_default.main)

end KanonBool
