-- Generated by kanon from bool.knl, bool.kn. Do not edit.
import KanonBool.Statements.Bool.eq_untyped
import KanonBool.Proofs
import KanonBool.Soundness.Comm

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace KanonBool

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bool.eq_untyped.r_ill_typed.main.ok : Bool.eq_untyped.r_ill_typed.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq_untyped.r_ill_typed.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq_untyped.r_typed.main.ok : Bool.eq_untyped.r_typed.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq_untyped.r_typed.main)

theorem Bool.eq_untyped.r_ill_typed.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq_untyped.r_ill_typed O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq_untyped.spec v1 v2) res := by
  unfold Bool.eq_untyped.r_ill_typed at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq_untyped.r_ill_typed.main.ok O hO)

theorem Bool.eq_untyped.r_typed.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq_untyped.r_typed O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq_untyped.spec v1 v2) res := by
  unfold Bool.eq_untyped.r_typed at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq_untyped.r_typed.main.ok O hO)

end KanonBool
