-- Generated by kanon from bool.knl, bool.kn. Do not edit.
import KanonBool.Statements.Bool.eq_untyped
import KanonBool.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace KanonBool

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bool.eq_untyped.r_ill_typed.main.ok : Bool.eq_untyped.r_ill_typed.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq_untyped.r_ill_typed.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq_untyped.r_typed.main.ok : Bool.eq_untyped.r_typed.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq_untyped.r_typed.main)

end KanonBool
