-- Generated by kanon from bool.kn, int.kn. Do not edit.
import IntsExample.Statements
import IntsExample.Model.Int.plus

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace IntsExample

open Classical Kanon

def Int.plus.r_lits.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Int.plus.r_lits O v1 v2 = some res →
  Refines (Int.plus.spec v1 v2) res

def Int.plus.r_unit_zero.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Int.plus.r_unit_zero O v1 v2 = some res →
  Refines (Int.plus.spec v1 v2) res

def Int.plus.r_default.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Int.plus.r_default O v1 v2 = some res →
  Refines (Int.plus.spec v1 v2) res

def Int.plus.r_lits.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (i1 : Int) (t__2 : Ty) (i2 : Int) (t__4 : Ty),
  Refines (Int.plus.spec (Term.mk (Kind.Int i1) t__2) (Term.mk (Kind.Int i2) t__4))
  ((Term.mk (Kind.Int (Int.add i1 i2)) Ty.TInt))

def Int.plus.r_unit_zero.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (kanon__2 : Int) (t__3 : Ty),
  (decide (kanon__2 = (0 : Int))) = true →
  Refines (Int.plus.spec v1 (Term.mk (Kind.Int kanon__2) t__3))
  (v1)

def Int.plus.r_unit_zero.swap.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (kanon__2 : Int) (t__3 : Ty),
  (decide (kanon__2 = (0 : Int))) = true →
  Refines (Int.plus.spec (Term.mk (Kind.Int kanon__2) t__3) v2)
  (v2)

def Int.plus.r_default.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term),
  Refines (Int.plus.spec v1 v2)
  ((Term.mk (mk_commut_binop O Op2.Plus v1 v2) Ty.TInt))

end IntsExample
