-- Generated by kanon from num.knl, num.kn. Do not edit.
import NumMod.Statements.Num.add
import NumMod.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace NumMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Num.add.r_unit_zero.main.ok : Num.add.r_unit_zero.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Num.add.r_unit_zero.main)

set_option maxHeartbeats 400000 in
theorem Num.add.r_unit_zero.swap.ok : Num.add.r_unit_zero.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Num.add.r_unit_zero.swap)

set_option maxHeartbeats 400000 in
theorem Num.add.r_lits.main.ok : Num.add.r_lits.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Num.add.r_lits.main)

set_option maxHeartbeats 400000 in
theorem Num.add.r_default.main.ok : Num.add.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Num.add.r_default.main)

end NumMod
