-- Generated by kanon from num.knl, num.kn. Do not edit.
import NumMod.Statements.Num.less
import NumMod.Soundness.Laws
import NumMod.Proofs.Num.less

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace NumMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Num.less.r_lits.main.ok : Num.less.r_lits.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Num.less.r_lits.main)

set_option maxHeartbeats 400000 in
theorem Num.less.r_pos.main.ok : Num.less.r_pos.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Num.less.r_pos.main)

set_option maxHeartbeats 400000 in
theorem Num.less.r_same.main.ok : Num.less.r_same.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Num.less.r_same.main)

set_option maxHeartbeats 400000 in
theorem Num.less.r_default.main.ok : Num.less.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Num.less.r_default.main)

end NumMod
