-- Generated by kanon from bool.kn, int.kn. Do not edit.
import IntsExample.Ops
import IntsExample.Model.Bool.of_bool

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace IntsExample

open Classical Kanon

def Int.int_lt.r_lits (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Int x) _), (Term.mk (Kind.Int y) _) =>
    (whenSome true ((Bool.of_bool (decide (x < y)))))
    | _, _ => none)

def Int.int_lt.r_same (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | x, kanon__2 =>
    (whenSome (decide (x = kanon__2)) (v_false)))

def Int.int_lt.r_default (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | _, _ =>
    (whenSome true ((Term.mk (Kind.Op2 Op2.Lt v1 v2) Ty.TBool))))

def Int.int_lt.step (O : Ops) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [Int.int_lt.r_lits O v1 v2, Int.int_lt.r_same O v1 v2, Int.int_lt.r_default O v1 v2]).getD (Int.int_lt.spec v1 v2)

end IntsExample
