-- Generated by kanon from word.knl, word.kn. Do not edit.
import WordMod.Lift

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace WordMod

open Classical Kanon

def Word.round.r_check.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [WordMod.Lang S] [KanonBool.Typed S] [WordMod.Typed S] (O : Ops S), O.Sound →
  ∀ (m : CfgMod.Rounding) (n : Int) (z : Int) (w__2 : Int) (t__3 : S.Ty),
  S.Refines (WordMod.Word.round.spec m n (WordMod.mk (.Wd z w__2) t__3))
  (((firstSome [(match (O.word_wcheck z) with
                  | (some _) =>
                  some ((WordMod.mk (.WRound m n (WordMod.mk (.Wd z w__2) t__3)) (WordMod.sort (.TWord n))))
                  | _ => none),
     (match (O.word_wcheck z) with
       | none =>
       some ((WordMod.mk (.WRound m n (WordMod.mk (.Wd z w__2) t__3)) (WordMod.sort (.TWord n))))
       | _ => none)]).getD
     Inhabited.default))

def Word.round.r_keep.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [WordMod.Lang S] [KanonBool.Typed S] [WordMod.Typed S] (O : Ops S), O.Sound →
  ∀ (m : CfgMod.Rounding) (n : Int) (v : S.Term),
  (((WordMod.Word.is_down m) || (decide (m = CfgMod.Rounding.Up))) && (WordMod.Word.is_word (S.ty v))) = true →
  S.Refines (WordMod.Word.round.spec m n v)
  (v)

def Word.round.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [WordMod.Lang S] [KanonBool.Typed S] [WordMod.Typed S] (O : Ops S), O.Sound →
  ∀ (m : CfgMod.Rounding) (n : Int) (v : S.Term),
  S.Refines (WordMod.Word.round.spec m n v)
  ((WordMod.mk (.WRound m n v) (WordMod.sort (.TWord n))))

end WordMod
