// The tree of the Lean files of an example, for the guide's file widget: built from the files of
// the repository (so that it is the real layout), each file linked to the section of the guide
// that explains its kind, with the files of the functions collapsed to a few. The generated files
// of the roots are in `Generated/`, and the hand-written ones of each root in a directory beside it.

/** An entry of the tree. */
export type Entry =
  | { kind: "dir"; name: string; children: Entry[] }
  | {
      kind: "file";
      name: string;
      /** The id of the section of the guide that explains it. */
      section: string;
      generated: boolean;
      /** A file that the example does not have, which others may (`Proofs.lean`). */
      absent?: boolean;
    }
  /** Files left out: one per function. */
  | { kind: "more"; section: string; hidden: string[] };

/** The section of a file, by its path under the directory of its root in `Generated`, or the root. */
function sectionOf(path: string[]): string {
  const [first, ...rest] = path;
  if (rest.length === 0) return `file-${first.replace(/\.lean$/, "").toLowerCase()}`;
  const comm = rest.length === 1 && rest[0] === "Comm.lean";
  if (first === "Statements") return comm ? "file-statements-comm" : "file-statements";
  if (first === "Soundness") return comm ? "file-soundness-comm" : "file-soundness-fn";
  throw new Error(`files: no section for ${path.join("/")}`);
}

/** The order of the files of a directory: that in which they import each other. */
const ORDER = [
  "Types", "Abstract", "Node", "Sem", "Lang", "Prims", "Model", "Lift", "Statements", "Proofs",
  "Soundness", "Syntax", "Val", "Semantics", "Typing", "Rules",
];

function rank(e: Entry): number {
  if (e.kind === "more") return Infinity;
  const stem = e.name.replace(/\.lean$/, "").replace(/\/$/, "");
  const i = ORDER.indexOf(stem);
  // a directory of a root first, then its files; Soundness/ before Soundness.lean
  return i < 0 ? (e.kind === "dir" ? -1 : ORDER.length) : 2 * i + (e.kind === "dir" ? 0 : 1);
}

function sorted(entries: Entry[]): Entry[] {
  return [...entries].sort((a, b) => rank(a) - rank(b));
}

/**
 * The tree of the files `files` (their texts, by their paths relative to the example's
 * directory): the `Generated/` directory, with a directory per root (`Generated/IntMod/Node.lean`)
 * whose files of the functions (`Statements/M/f.lean`) are collapsed to those of `keep`
 * (`Int/plus.lean`) and an ellipsis, then a directory per root with its hand-written files
 * (`IntMod/Sem.lean`), and the hand-written files `absent` (`IntMod/Proofs.lean`) that the example
 * does not have.
 */
export function fileTree(
  files: Record<string, string>,
  options: { keep: string[]; absent: string[]; project: string[] },
): Entry[] {
  const handRoots = new Map<string, Entry[]>();
  const generatedRoots = new Map<string, Map<string, string>>();
  const top: Entry[] = [];
  for (const [path, text] of Object.entries(files)) {
    const [first, ...rest] = path.split("/");
    if (rest.length === 0) {
      if (!options.project.includes(first)) throw new Error(`files: ${first} is not expected`);
      top.push({ kind: "file", name: first, section: "project", generated: false });
      continue;
    }
    const generated = first === "Generated";
    if (generated !== text.startsWith("-- Generated by kanon"))
      throw new Error(`files: ${path} is ${generated ? "not " : ""}generated`);
    if (generated) {
      const [root, ...inner] = rest;
      if (inner.length === 0) throw new Error(`files: ${path} is not expected`);
      if (!generatedRoots.has(root)) generatedRoots.set(root, new Map());
      generatedRoots.get(root)!.set(inner.join("/"), text);
      continue;
    }
    if (rest.length !== 1) throw new Error(`files: ${path} is not expected`);
    if (!handRoots.has(first)) handRoots.set(first, []);
    handRoots.get(first)!.push({ kind: "file", name: rest[0], section: sectionOf(rest), generated: false });
  }
  for (const path of options.absent) {
    const [root, name] = path.split("/");
    if (handRoots.get(root)?.some((e) => e.kind === "file" && e.name === name))
      throw new Error(`files: ${path} exists`);
    if (!handRoots.has(root)) handRoots.set(root, []);
    handRoots
      .get(root)!
      .push({ kind: "file", name, section: sectionOf([name]), generated: false, absent: true });
  }
  const byName = ([a]: [string, unknown], [b]: [string, unknown]) => a.localeCompare(b);
  const generatedDirs: Entry[] = [...generatedRoots].sort(byName).map(([root, inner]) => {
    const children: Entry[] = [];
    const sub = new Map<string, string[]>();
    for (const path of inner.keys()) {
      const parts = path.split("/");
      if (parts.length === 1) {
        children.push({ kind: "file", name: parts[0], section: sectionOf(parts), generated: true });
        continue;
      }
      // Statements/ and Soundness/: Comm.lean, and a file per function, M/f.lean
      const [dir, ...name] = parts;
      if (!sub.has(dir)) sub.set(dir, []);
      sub.get(dir)!.push(name.join("/"));
    }
    for (const [dir, list] of sub) {
      const file = (name: string): Entry => {
        if (!list.includes(name)) throw new Error(`files: no Generated/${root}/${dir}/${name}`);
        return { kind: "file", name, section: sectionOf([dir, ...name.split("/")]), generated: true };
      };
      const shown = [...(list.includes("Comm.lean") ? ["Comm.lean"] : []), ...options.keep];
      const named = shown.map(file);
      const hidden = list.filter((n) => !shown.includes(n)).sort();
      if (hidden.length > 0) named.push({ kind: "more", section: sectionOf([dir, "f.lean"]), hidden });
      children.push({ kind: "dir", name: `${dir}/`, children: named });
    }
    return { kind: "dir", name: `${root}/`, children: sorted(children) };
  });
  const handDirs: Entry[] = [...handRoots]
    .sort(byName)
    .map(([root, hand]) => ({ kind: "dir", name: `${root}/`, children: sorted(hand) }));
  const project = (e: Entry) => (e.kind === "file" ? options.project.indexOf(e.name) : 0);
  return [
    { kind: "dir", name: "Generated/", children: generatedDirs },
    ...handDirs,
    ...top.sort((a, b) => project(a) - project(b)),
  ];
}
