// The tree of the Lean files of an example, for the guide's file widget: built from the files of
// the repository (so that it is the real layout), each file linked to the section of the guide
// that explains its kind, with the files of the functions collapsed to a few.

/** An entry of the tree. */
export type Entry =
  | { kind: "dir"; name: string; children: Entry[] }
  | {
      kind: "file";
      name: string;
      /** The id of the section of the guide that explains it. */
      section: string;
      generated: boolean;
      /** A file that the example does not have, which others may (`Proofs.lean`). */
      absent?: boolean;
    }
  /** Files left out: one per function. */
  | { kind: "more"; section: string; hidden: string[] };

/** The section of a file, by its path under the directory of its root. */
function sectionOf(path: string[]): string {
  const [first, ...rest] = path;
  if (rest.length === 0) return `file-${first.replace(/\.lean$/, "").toLowerCase()}`;
  const comm = rest.length === 1 && rest[0] === "Comm.lean";
  if (first === "Statements") return comm ? "file-statements-comm" : "file-statements";
  if (first === "Soundness") return comm ? "file-soundness-comm" : "file-soundness-fn";
  throw new Error(`files: no section for ${path.join("/")}`);
}

/** The order of the files of a directory: that in which they import each other. */
const ORDER = [
  "Types", "Abstract", "Node", "Sem", "Lang", "Prims", "Model", "Lift", "Statements", "Proofs",
  "Soundness", "Syntax", "Val", "Semantics", "Typing", "Rules",
];

function rank(e: Entry): number {
  if (e.kind === "more") return Infinity;
  const stem = e.name.replace(/\.lean$/, "").replace(/\/$/, "");
  const i = ORDER.indexOf(stem);
  // a directory of a root first, then its files; Soundness/ before Soundness.lean
  return i < 0 ? (e.kind === "dir" ? -1 : ORDER.length) : 2 * i + (e.kind === "dir" ? 0 : 1);
}

function sorted(entries: Entry[]): Entry[] {
  return [...entries].sort((a, b) => rank(a) - rank(b));
}

/**
 * The tree of the files `files` (their texts, by their paths relative to the example's
 * directory, `IntMod/Node.lean`): a directory per root, with the files of its functions
 * (`Statements/M/f.lean`) collapsed to those of `keep` (`Int/plus.lean`) and an ellipsis, and
 * the hand-written files `absent` (`IntMod/Proofs.lean`) that the example does not have.
 */
export function fileTree(
  files: Record<string, string>,
  options: { keep: string[]; absent: string[]; project: string[] },
): Entry[] {
  const roots = new Map<string, Map<string, string>>();
  const top: Entry[] = [];
  for (const [path, text] of Object.entries(files)) {
    const [root, ...rest] = path.split("/");
    if (rest.length === 0) {
      if (!options.project.includes(root)) throw new Error(`files: ${root} is not expected`);
      top.push({ kind: "file", name: root, section: "project", generated: false });
      continue;
    }
    if (!roots.has(root)) roots.set(root, new Map());
    roots.get(root)!.set(rest.join("/"), text);
  }
  for (const path of options.absent) {
    const [root, ...rest] = path.split("/");
    if (roots.get(root)?.has(rest.join("/"))) throw new Error(`files: ${path} exists`);
  }
  const dirs: Entry[] = [...roots].sort(([a], [b]) => a.localeCompare(b)).map(([root, inner]) => {
    const children: Entry[] = [];
    const sub = new Map<string, { name: string; generated: boolean }[]>();
    for (const [path, text] of inner) {
      const parts = path.split("/");
      const generated = text.startsWith("-- Generated by kanon");
      if (parts.length === 1) {
        children.push({ kind: "file", name: path, section: sectionOf(parts), generated });
        continue;
      }
      // Statements/ and Soundness/: Comm.lean, and a file per function, M/f.lean
      const [dir, ...name] = parts;
      if (!sub.has(dir)) sub.set(dir, []);
      sub.get(dir)!.push({ name: name.join("/"), generated });
    }
    for (const path of options.absent) {
      const [r, name] = path.split("/");
      if (r === root)
        children.push({ kind: "file", name, section: sectionOf([name]), generated: false, absent: true });
    }
    for (const [dir, list] of sub) {
      const file = (name: string): Entry => {
        const f = list.find((x) => x.name === name);
        if (!f) throw new Error(`files: no ${root}/${dir}/${name}`);
        return { kind: "file", name, section: sectionOf([dir, ...name.split("/")]), generated: f.generated };
      };
      const shown = [...(list.some((f) => f.name === "Comm.lean") ? ["Comm.lean"] : []), ...options.keep];
      const named = shown.map(file);
      const hidden = list.map((f) => f.name).filter((n) => !shown.includes(n)).sort();
      if (hidden.length > 0) named.push({ kind: "more", section: sectionOf([dir, "f.lean"]), hidden });
      children.push({ kind: "dir", name: `${dir}/`, children: named });
    }
    return { kind: "dir", name: `${root}/`, children: sorted(children) };
  });
  const project = (e: Entry) => (e.kind === "file" ? options.project.indexOf(e.name) : 0);
  return [...dirs, ...top.sort((a, b) => project(a) - project(b))];
}
