<script lang="ts">
  // The Lean files of an example as a tree, each linked to the section of the guide that explains
  // it: the hand-written ones in the theme colour, those the example does not have dashed, and the entries of
  // the section in view marked.
  import type { Entry } from "./files";

  interface Props {
    title: string;
    entries: Entry[];
    /** The id of the section in view. */
    current?: string;
  }

  const { title, entries, current }: Props = $props();
</script>

{#snippet list(items: Entry[])}
  <ul>
    {#each items as e, i (i)}
      <li>
        {#if e.kind === "dir"}
          <span class="dir">{e.name}</span>
          {@render list(e.children)}
        {:else if e.kind === "file"}
          <a
            href="#{e.section}"
            class={{ hand: !e.generated, absent: e.absent }}
            aria-current={current === e.section ? "location" : undefined}
            title={e.absent ? "Written by hand, if any (examples/ints has none)" : e.generated ? "Generated by Kanon" : "Written by hand"}
            >{e.name}</a
          >
        {:else}
          <a
            href="#{e.section}"
            class="more"
            aria-current={current === e.section ? "location" : undefined}
            title="One per function: {e.hidden.join(', ')}">…</a
          >
        {/if}
      </li>
    {/each}
  </ul>
{/snippet}

<nav class="tree" aria-label="The files of the example">
  <details open>
    <summary>{title}</summary>
    {@render list(entries)}
    <p class="legend">
      <span class="hand">by hand</span><span>generated</span><span class="absent">if any</span>
    </p>
  </details>
</nav>

<style>
  .tree {
    font-family: var(--mono);
    font-size: var(--fs-sm);
    line-height: 1.5;
    border: 1px solid var(--border);
    border-radius: var(--radius-lg);
    background: var(--bg2);
    padding: var(--sp-3) var(--sp-4);
  }
  /* A plain disclosure, in the frame of the tree. */
  details {
    margin: 0;
    padding: 0;
    border: none;
    background: none;
  }
  summary {
    cursor: pointer;
    color: var(--color2);
    overflow-wrap: anywhere;
  }
  ul {
    list-style: none;
    margin: 0;
    padding: 0;
  }
  ul ul {
    padding-left: 1.1em;
    border-left: 1px solid var(--border);
    margin-left: 0.3em;
  }
  li {
    margin: 0;
    overflow-wrap: anywhere;
  }
  .dir {
    padding: 0 var(--sp-1);
    color: var(--color2);
  }
  a {
    display: inline-block;
    padding: 0 var(--sp-1);
    border-radius: var(--radius-sm);
    color: var(--color2);
    text-decoration: none;
  }
  a:hover {
    color: var(--color);
    background: var(--bg3);
  }
  .hand {
    font-weight: 600;
    color: var(--theme);
  }
  .absent {
    font-weight: 400;
    font-style: italic;
    color: var(--faint);
    text-decoration: underline dashed;
    text-underline-offset: 0.2em;
  }
  a[aria-current] {
    color: var(--theme);
    background: var(--theme-soft);
  }
  .legend {
    display: flex;
    flex-wrap: wrap;
    gap: 0 var(--sp-3);
    margin: var(--sp-2) 0 0;
    color: var(--color2);
  }
  .legend span {
    white-space: nowrap;
  }
</style>
