-- Generated by kanon from bool.kn, int.kn. Do not edit.
import IntsExample.Ops

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace IntsExample

open Classical Kanon

def mk_commut_binop (O : Ops) (op : Op2) (l : Term) (r : Term) : Kind :=
  (if (O.orc.tag_le l r) then (Kind.Op2 op l r) else (Kind.Op2 op r l))

end IntsExample
