-- Generated by kanon from bool.kn, num.kn. Do not edit.
import L1.Interface
import L1.Interface.Bool
import L1.Model.Num.is_pos
import NumMod.Syntax

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L1

open Classical Kanon

/-- The interface of the module `Num`: every law holds by definition. -/
def numSyntax : NumMod.Syntax (S := sem) modBase boolSyntax where
  TNum := Ty.TNum
  TNum_ne_TBool := by intros; exact nofun
  asTNum := fun s => match s with | Ty.TNum => some () | _ => none
  asTNum_sort := by intros; rfl
  asTNum_sound := by intro s h; cases s <;> cases h <;> rfl
  NumK := fun x1 => (Kind.Num x1)
  WT_Num := by intros; first | exact Iff.rfl | kanon_law
  asNum := fun v => match v with | Term.mk (Kind.Num x1) _ => some x1 | _ => none
  asNum_node := by intros; rfl
  asNum_sound := by intro v x1 h; dsimp only at h; split at h <;> cases h <;> rfl
  AddK := fun a1 a2 => (Kind.Op2 Op2.Add a1 a2)
  WT_Add := by intros; first | exact Iff.rfl | kanon_law
  asAdd := fun v => match v with | Term.mk (Kind.Op2 Op2.Add a1 a2) _ => some (a1, a2) | _ => none
  asAdd_node := by intros; rfl
  asAdd_sound := by intro v a1 a2 h; dsimp only at h; split at h <;> cases h <;> rfl
  LtK := fun a1 a2 => (Kind.Op2 Op2.Lt a1 a2)
  WT_Lt := by intros; first | exact Iff.rfl | kanon_law
  asLt := fun v => match v with | Term.mk (Kind.Op2 Op2.Lt a1 a2) _ => some (a1, a2) | _ => none
  asLt_node := by intros; rfl
  asLt_sound := by intro v a1 a2 h; dsimp only at h; split at h <;> cases h <;> rfl
  MaxK := fun a1 a2 => (Kind.Op2 Op2.Max a1 a2)
  WT_Max := by intros; first | exact Iff.rfl | kanon_law
  asMax := fun v => match v with | Term.mk (Kind.Op2 Op2.Max a1 a2) _ => some (a1, a2) | _ => none
  asMax_node := by intros; rfl
  asMax_sound := by intro v a1 a2 h; dsimp only at h; split at h <;> cases h <;> rfl
  num_is_pos := Num.is_pos
  num_is_pos_eq := by kanon_bridge Num.is_pos

attribute [kanon_law] numSyntax

end L1
