-- Generated by kanon from bool.kn. Do not edit.
import BoolExample.Statements
import BoolExample.Lang
import KanonBool.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BoolExample

open Classical Kanon

@[kanon_comm_lemma] theorem Op2.And.comm.ok : Op2.And.comm.Stmt :=
  fun a b t => KanonBool.And.comm.ok (S := sem) boolSyntax a b t

end BoolExample
