-- Generated by kanon from int.kn. Do not edit.
import KanonCore.Node
import DivisionExample.Semantics

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace DivisionExample

open Classical Kanon

kanon_node_lemma kanon_node_wt Nodes.Kind.Var.wt (x1 : String) (t : Ty) :
  sem.WT (Term.mk (Kind.Var x1) t)

kanon_node_lemma kanon_node_ev Nodes.Kind.Var.ev (ρ : sem.Env) (x1 : String) (t : Ty) :
  sem.ev ρ (Term.mk (Kind.Var x1) t)

kanon_node_lemma kanon_node_wt Nodes.Kind.Int.wt (x1 : Int) (t : Ty) :
  sem.WT (Term.mk (Kind.Int x1) t)

kanon_node_lemma kanon_node_ev Nodes.Kind.Int.ev (ρ : sem.Env) (x1 : Int) (t : Ty) :
  sem.ev ρ (Term.mk (Kind.Int x1) t)

kanon_node_lemma kanon_node_wt Nodes.Op2.Plus.wt (a1 : Term) (a2 : Term) (t : Ty) :
  sem.WT (Term.mk (Kind.Op2 Op2.Plus a1 a2) t)

kanon_node_lemma kanon_node_ev Nodes.Op2.Plus.ev (ρ : sem.Env) (a1 : Term) (a2 : Term) (t : Ty) :
  sem.ev ρ (Term.mk (Kind.Op2 Op2.Plus a1 a2) t)

kanon_node_lemma kanon_node_wt Nodes.Op2.Div.wt (a1 : Term) (a2 : Term) (t : Ty) :
  sem.WT (Term.mk (Kind.Op2 Op2.Div a1 a2) t)

kanon_node_lemma kanon_node_ev Nodes.Op2.Div.ev (ρ : sem.Env) (a1 : Term) (a2 : Term) (t : Ty) :
  sem.ev ρ (Term.mk (Kind.Op2 Op2.Div a1 a2) t)

kanon_node_lemma kanon_node_wt Nodes.Op1.Sq1.wt (a1 : Term) (t : Ty) :
  sem.WT (Term.mk (Kind.Op1 Op1.Sq1 a1) t)

kanon_node_lemma kanon_node_ev Nodes.Op1.Sq1.ev (ρ : sem.Env) (a1 : Term) (t : Ty) :
  sem.ev ρ (Term.mk (Kind.Op1 Op1.Sq1 a1) t)

end DivisionExample
