-- Generated by kanon from int.kn. Do not edit.
import KanonCore.Node
import DivisionExample.Lib.Rule

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace DivisionExample

open Classical Kanon

@[kanon_node_wt] theorem Nodes.Kind.Var.wt (x1 : String) (t : Ty) :
  kanon_unfold_eq% kanon_wt (sem.WT (Term.mk (Kind.Var x1) t)) := by
  simp only [kanon_wt]

@[kanon_node_ev] theorem Nodes.Kind.Var.ev (ρ : sem.Env) (x1 : String) (t : Ty) :
  kanon_unfold_eq% kanon_ev (sem.ev ρ (Term.mk (Kind.Var x1) t)) := by
  simp only [kanon_ev]

@[kanon_node_wt] theorem Nodes.Kind.Int.wt (x1 : Int) (t : Ty) :
  kanon_unfold_eq% kanon_wt (sem.WT (Term.mk (Kind.Int x1) t)) := by
  simp only [kanon_wt]

@[kanon_node_ev] theorem Nodes.Kind.Int.ev (ρ : sem.Env) (x1 : Int) (t : Ty) :
  kanon_unfold_eq% kanon_ev (sem.ev ρ (Term.mk (Kind.Int x1) t)) := by
  simp only [kanon_ev]

@[kanon_node_wt] theorem Nodes.Op2.Plus.wt (a1 : Term) (a2 : Term) (t : Ty) :
  kanon_unfold_eq% kanon_wt (sem.WT (Term.mk (Kind.Op2 Op2.Plus a1 a2) t)) := by
  simp only [kanon_wt]

@[kanon_node_ev] theorem Nodes.Op2.Plus.ev (ρ : sem.Env) (a1 : Term) (a2 : Term) (t : Ty) :
  kanon_unfold_eq% kanon_ev (sem.ev ρ (Term.mk (Kind.Op2 Op2.Plus a1 a2) t)) := by
  simp only [kanon_ev]

@[kanon_node_wt] theorem Nodes.Op2.Div.wt (a1 : Term) (a2 : Term) (t : Ty) :
  kanon_unfold_eq% kanon_wt (sem.WT (Term.mk (Kind.Op2 Op2.Div a1 a2) t)) := by
  simp only [kanon_wt]

@[kanon_node_ev] theorem Nodes.Op2.Div.ev (ρ : sem.Env) (a1 : Term) (a2 : Term) (t : Ty) :
  kanon_unfold_eq% kanon_ev (sem.ev ρ (Term.mk (Kind.Op2 Op2.Div a1 a2) t)) := by
  simp only [kanon_ev]

@[kanon_node_wt] theorem Nodes.Op1.Sq1.wt (a1 : Term) (t : Ty) :
  kanon_unfold_eq% kanon_wt (sem.WT (Term.mk (Kind.Op1 Op1.Sq1 a1) t)) := by
  simp only [kanon_wt]

@[kanon_node_ev] theorem Nodes.Op1.Sq1.ev (ρ : sem.Env) (a1 : Term) (t : Ty) :
  kanon_unfold_eq% kanon_ev (sem.ev ρ (Term.mk (Kind.Op1 Op1.Sq1 a1) t)) := by
  simp only [kanon_ev]

end DivisionExample
