-- Generated by kanon from lang.knl, int.knl. Do not edit.
import DivisionExample.Val
import DivMod.Lang
import DivisionExample.Lang

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace DivisionExample

open Classical Kanon

mutual

/-- The typing of the terms. -/
def Term.WT : Term → Prop
  | .int n t => DivMod.Node.wt Ty.int Term.ty n t ∧ allInt n
  | .lang n t => DivisionExample.Node.wt Ty.int Term.ty n t ∧ allLang n

def allInt : DivMod.Node Term → Prop
  | (.Int x1) => True
  | (.Plus a1 a2) => a1.WT ∧ a2.WT
  | (.Div a1 a2) => a1.WT ∧ a2.WT
  | (.Sq1 a1) => a1.WT

def allLang : DivisionExample.Node Term → Prop
  | (.Var x1) => True

end

mutual

/-- The evaluation of the terms. -/
def ev (ρ : Env) : Term → Option Val
  | .int n t => DivMod.Node.eval (D := dom) ρ t (evInt ρ n)
  | .lang n t => DivisionExample.Node.eval (D := dom) ρ t (evLang ρ n)

def evInt (ρ : Env) : DivMod.Node Term → DivMod.Node (Option Val)
  | (.Int x1) => (.Int x1)
  | (.Plus a1 a2) => (.Plus (ev ρ a1) (ev ρ a2))
  | (.Div a1 a2) => (.Div (ev ρ a1) (ev ρ a2))
  | (.Sq1 a1) => (.Sq1 (ev ρ a1))

def evLang (ρ : Env) : DivisionExample.Node Term → DivisionExample.Node (Option Val)
  | (.Var x1) => (.Var x1)

end

theorem allInt_iff (n : DivMod.Node Term) : allInt n ↔ n.All Term.WT := by
  cases n <;> simp [allInt, DivMod.Node.All]

theorem evInt_eq (ρ : Env) (n : DivMod.Node Term) : evInt ρ n = n.map (ev ρ) := by
  cases n <;> simp only [evInt, DivMod.Node.map]

theorem allLang_iff (n : DivisionExample.Node Term) : allLang n ↔ n.All Term.WT := by
  cases n <;> simp [allLang, DivisionExample.Node.All]

theorem evLang_eq (ρ : Env) (n : DivisionExample.Node Term) : evLang ρ n = n.map (ev ρ) := by
  cases n <;> simp only [evLang, DivisionExample.Node.map]

/-- The typing of a node of `Int`. -/
theorem WT_int (n : DivMod.Node Term) (t : Ty) :
  Term.WT (.int n t) ↔ DivMod.Node.wt Ty.int Term.ty n t ∧ n.All Term.WT := by
  show (_ ∧ allInt n) ↔ _; rw [allInt_iff]

/-- The evaluation of a node of `Int`. -/
theorem ev_int (ρ : Env) (n : DivMod.Node Term) (t : Ty) :
  ev ρ (.int n t) = DivMod.Node.eval (D := dom) ρ t (n.map (ev ρ)) :=
  congrArg (DivMod.Node.eval (D := dom) ρ t) (evInt_eq ρ n)

/-- The typing of a node of `Lang`. -/
theorem WT_lang (n : DivisionExample.Node Term) (t : Ty) :
  Term.WT (.lang n t) ↔ DivisionExample.Node.wt Ty.int Term.ty n t ∧ n.All Term.WT := by
  show (_ ∧ allLang n) ↔ _; rw [allLang_iff]

/-- The evaluation of a node of `Lang`. -/
theorem ev_lang (ρ : Env) (n : DivisionExample.Node Term) (t : Ty) :
  ev ρ (.lang n t) = DivisionExample.Node.eval (D := dom) ρ t (n.map (ev ρ)) :=
  congrArg (DivisionExample.Node.eval (D := dom) ρ t) (evLang_eq ρ n)

/-- The semantics of the language. -/
@[reducible] def sem : Kanon.Sem where
  toDom := dom
  Term := Term
  ty := Term.ty
  WT := Term.WT
  ev := ev

/-- The value of a term; `none` for poison. -/
abbrev eval : Env → Term → Option Val := sem.eval

/-- `r` refines `spec`: it has the same type, and the same value whenever `spec` is not poison. -/
abbrev Refines : Term → Term → Prop := sem.Refines

instance : Refinement Refines := Sem.refinement

instance instIntLang : DivMod.Lang sem where
  toValues := inferInstanceAs (DivMod.Values dom)
  node := {
    inj := .int
    proj := fun e => match e with | .int n _ => some n | _ => none
    ty_inj := fun _ _ => rfl
    proj_inj := fun _ _ => rfl
    inj_proj := by intro e n h; cases e <;> cases h <;> rfl }
  WT_inj := WT_int
  ev_inj := ev_int
  srt := {
    inj := .int
    proj := fun s => match s with | .int s => some s
    proj_inj := fun _ => rfl
    inj_proj := by intro b a h; cases b <;> cases h <;> rfl }

instance instLangLang : DivisionExample.Lang sem where
  toValues := inferInstanceAs (DivisionExample.Values dom)
  node := {
    inj := .lang
    proj := fun e => match e with | .lang n _ => some n | _ => none
    ty_inj := fun _ _ => rfl
    proj_inj := fun _ _ => rfl
    inj_proj := by intro e n h; cases e <;> cases h <;> rfl }
  WT_inj := WT_lang
  ev_inj := ev_lang
  proj_Int_inj_Lang _ _ := rfl
  proj_Lang_inj_Int _ _ := rfl

end DivisionExample
