-- Generated by kanon from int.kn. Do not edit.
import DivisionExample.Statements
import DivisionExample.Lib.Rule
import DivisionExample.Proofs

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace DivisionExample

open Classical Kanon

@[kanon_comm_lemma] theorem Op2.Plus.comm.ok : Op2.Plus.comm.Stmt := kanon_proof% Op2.Plus.comm

theorem Int.plus.r_lits.main.ok : Int.plus.r_lits.main.Stmt := kanon_proof% Int.plus.r_lits.main

theorem Int.plus.r_lits.proof : Int.plus.r_lits.Stmt := by
  intro O hO v1 v2 res h
  simp only [Int.plus.r_lits] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Int.plus.r_lits.main.ok O hO)

theorem Int.plus.r_unit_zero.main.ok : Int.plus.r_unit_zero.main.Stmt := kanon_proof% Int.plus.r_unit_zero.main

theorem Int.plus.r_unit_zero.swap.ok : Int.plus.r_unit_zero.swap.Stmt := by
  intro O hO v2 kanon__2 t__3 hg
  refine Refinement.trans ?_
    (Int.plus.r_unit_zero.main.ok O hO v2 kanon__2 t__3 hg)
  simp only [Int.plus.spec]
  refine Refinement.trans (Op2.Plus.comm.ok ..) ?_
  kanon_congr

theorem Int.plus.r_unit_zero.proof : Int.plus.r_unit_zero.Stmt := by
  intro O hO v1 v2 res h
  simp only [Int.plus.r_unit_zero] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Int.plus.r_unit_zero.main.ok O hO)
  · kanon_arm h (Int.plus.r_unit_zero.swap.ok O hO)

theorem Int.plus.r_default.main.ok : Int.plus.r_default.main.Stmt := kanon_proof% Int.plus.r_default.main

theorem Int.plus.r_default.proof : Int.plus.r_default.Stmt := by
  intro O hO v1 v2 res h
  simp only [Int.plus.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Int.plus.r_default.main.ok O hO)

theorem Int.div.r_self.main.ok : Int.div.r_self.main.Stmt := kanon_proof% Int.div.r_self.main

theorem Int.div.r_self.proof : Int.div.r_self.Stmt := by
  intro O hO v1 v2 res hs_v2 h
  simp only [Int.div.r_self] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Int.div.r_self.main.ok O hO)

theorem Int.div.r_default.main.ok : Int.div.r_default.main.Stmt := kanon_proof% Int.div.r_default.main

theorem Int.div.r_default.proof : Int.div.r_default.Stmt := by
  intro O hO v1 v2 res hs_v2 h
  simp only [Int.div.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Int.div.r_default.main.ok O hO)

theorem Int.sq1.r_default.main.ok : Int.sq1.r_default.main.Stmt := kanon_proof% Int.sq1.r_default.main

theorem Int.sq1.r_default.proof : Int.sq1.r_default.Stmt := by
  intro O hO v res h
  simp only [Int.sq1.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Int.sq1.r_default.main.ok O hO)

theorem Int.sq1.post.main.ok : Int.sq1.post.main.Stmt := kanon_proof% Int.sq1.post.main

theorem Int.plus.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (Int.plus.spec v1 v2) (Int.plus.step O v1 v2) := by
  unfold Int.plus.step
  refine Refinement.firstSome_cons (fun res h => Int.plus.r_lits.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Int.plus.r_unit_zero.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Int.plus.r_default.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

theorem Int.div.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) (hs_v2 : Nonzero v2) :
  Refines (Int.div.spec v1 v2) (Int.div.step O v1 v2) := by
  unfold Int.div.step
  refine Refinement.firstSome_cons (fun res h => Int.div.r_self.proof O hO v1 v2 res hs_v2 h) ?_
  refine Refinement.firstSome_cons (fun res h => Int.div.r_default.proof O hO v1 v2 res hs_v2 h) ?_
  exact Refinement.firstSome_nil

theorem Int.sq1.step_sound (O : Ops) (hO : O.Sound) (v : Term) :
  Refines (Int.sq1.spec v) (Int.sq1.step O v) := by
  unfold Int.sq1.step
  refine Refinement.firstSome_cons (fun res h => Int.sq1.r_default.proof O hO v res h) ?_
  exact Refinement.firstSome_nil

/-- Every rule function refines its spec, for any amount of fuel. -/
theorem opsN_sound (orc : Oracle) (h : orc.Compat) :
  ∀ n, (opsN orc n).Sound
  | 0 =>
    { orc := h,
      int_plus := fun v1 v2 => Refinement.refl,
      int_div := fun v1 v2 hs_v2 => Refinement.refl,
      int_sq1 := fun v => Refinement.refl }
  | n + 1 =>
    have hO := opsN_sound orc h n
    { orc := hO.orc,
      int_plus := Int.plus.step_sound _ hO,
      int_div := Int.div.step_sound _ hO,
      int_sq1 := Int.sq1.step_sound _ hO }

end DivisionExample
