-- Generated by kanon from int.kn. Do not edit.
import DivisionExample.Model
import DivisionExample.Soundness.Laws.Op2.Plus
import DivisionExample.Soundness.Int.plus
import DivisionExample.Soundness.Int.div
import DivisionExample.Soundness.Int.sq1

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace DivisionExample

open Classical Kanon

/-- Every rule function refines its spec, for any amount of fuel. -/
theorem opsN_sound (orc : Oracle) (h : orc.Compat) :
  ∀ n, (opsN orc n).Sound
  | 0 =>
    { orc := h,
      int_plus := fun v1 v2 => Refinement.refl,
      int_div := fun v1 v2 hs_v2 => Refinement.refl,
      int_sq1 := fun v => Refinement.refl }
  | n + 1 =>
    have hO := opsN_sound orc h n
    { orc := hO.orc,
      int_plus := Int.plus.step_sound _ hO,
      int_div := Int.div.step_sound _ hO,
      int_sq1 := Int.sq1.step_sound _ hO }

end DivisionExample
