-- Generated by kanon from lang.knl, int.knl. Do not edit.

namespace DivisionExample

inductive Op1 where
  /-- The square of an integer plus one, which is not zero. -/
  | Sq1
  deriving DecidableEq, Repr, Inhabited

inductive Op2 where
  | Plus
  /-- The quotient: the divisor is not zero. -/
  | Div
  deriving DecidableEq, Repr, Inhabited

/-- The operators whose operands commute (`[@comm]`). -/
def Op2.Comm : Op2 → Prop
  | .Plus => True
  | _ => False

inductive Ty where
  | TInt
  deriving DecidableEq, Repr, Inhabited

end DivisionExample
