-- Generated by kanon from bool.knl, bool.kn. Do not edit.
import KanonBool.Lift

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace KanonBool

open Classical Kanon

def Bool.eq_untyped.r_ill_typed.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term),
  (! (decide ((S.ty v1) = (S.ty v2)))) = true →
  S.Refines (KanonBool.Bool.eq_untyped.spec v1 v2)
  (KanonBool.v_false)

def Bool.eq_untyped.r_typed.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term),
  S.Refines (KanonBool.Bool.eq_untyped.spec v1 v2)
  ((O.bool_eq v1 v2))

end KanonBool
