-- Generated by kanon from bool.knl, bool.kn. Do not edit.
import KanonBool.Statements

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace KanonBool

open Classical Kanon

def Bool.not_.r_true_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} (L : KanonBool.Syntax B) [Sem L] (O : Ops L), O.Sound →
  ∀ (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.not_.spec L (B.node (L.BoolK true) t__2))
  (L.bool_v_false)

def Bool.not_.r_false_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} (L : KanonBool.Syntax B) [Sem L] (O : Ops L), O.Sound →
  ∀ (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.not_.spec L (B.node (L.BoolK false) t__2))
  (L.bool_v_true)

def Bool.not_.r_not.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} (L : KanonBool.Syntax B) [Sem L] (O : Ops L), O.Sound →
  ∀ (sv : S.Term) (t__3 : S.Ty),
  S.Refines (KanonBool.Bool.not_.spec L (B.node (L.NotK sv) t__3))
  (sv)

def Bool.not_.r_or_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} (L : KanonBool.Syntax B) [Sem L] (O : Ops L), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term) (t__4 : S.Ty),
  S.Refines (KanonBool.Bool.not_.spec L (B.node (L.OrK v1 v2) t__4))
  ((O.bool_and_ (O.bool_not_ v1) (O.bool_not_ v2)))

def Bool.not_.r_and_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} (L : KanonBool.Syntax B) [Sem L] (O : Ops L), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term) (t__4 : S.Ty),
  S.Refines (KanonBool.Bool.not_.spec L (B.node (L.AndK v1 v2) t__4))
  ((O.bool_or_ (O.bool_not_ v1) (O.bool_not_ v2)))

def Bool.not_.r_ite.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} (L : KanonBool.Syntax B) [Sem L] (O : Ops L), O.Sound →
  ∀ (g : S.Term) (a : S.Term) (b : S.Term) (t__5 : S.Ty),
  S.Refines (KanonBool.Bool.not_.spec L (B.node (L.IteK g a b) t__5))
  ((O.bool_ite g (O.bool_not_ a) (O.bool_not_ b)))

def Bool.not_.r_distinct.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} (L : KanonBool.Syntax B) [Sem L] (O : Ops L), O.Sound →
  ∀ (l : S.Term) (r : S.Term) (t__7 : S.Ty),
  S.Refines (KanonBool.Bool.not_.spec L (B.node (L.DistinctK (l :: (r :: []))) t__7))
  ((O.bool_eq l r))

def Bool.not_.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} (L : KanonBool.Syntax B) [Sem L] (O : Ops L), O.Sound →
  ∀ (sv : S.Term),
  S.Refines (KanonBool.Bool.not_.spec L sv)
  ((B.node (L.NotK sv) L.TBool))

end KanonBool
