The ocaml-typed backend generates the typed interface of a language: its terms
`'a t` have a phantom parameter, a tag, that says what Kanon knows of the term.
The interface is organised like the language, with a module for each of its
files, and implemented by the rules.

  $ cat > lang.knl <<'KN'
  > [@@@ocaml_types "Lang_types"]
  > [@@@ocaml_prims "Lang_prims"]
  > [@@@ocaml_rules "Lang_rules"]
  > use "bitvec"
  > use "seq"
  > KN
  $ cat > bitvec.knl <<'KN'
  > type checked = { signed : bool; unsigned : bool }
  > 
  > sort TBool
  > (** Bit-vectors of a width. *)
  > sort TBitVec of nat
  > (** Bit-vectors that are not zero. *)
  > subsort TNonzero of nat : TBitVec n
  > subsort TZero of nat : TBitVec n
  > 
  > (** A bit-vector literal. *)
  > node BitVec of int * nat (v, n) : TBitVec n
  > (** The zero of a width. *)
  > node Zero of nat (n) : TZero n
  > (** Addition, which may overflow. *)
  > node Add of checked (c) : TBitVec n -> TBitVec n -> TBitVec n
  > (** Division: the divisor is known to be non-zero. *)
  > node Div : TBitVec n -> TNonzero n -> TBitVec n
  > node Ult : TBitVec n -> TBitVec n -> TBool
  > node Unspecified : TBitVec n -> TBitVec n -> TBitVec n
  > KN
  $ cat > bitvec.kn <<'KN'
  > (** Adds two bit-vectors. *)
  > rule add : Add (c, v1, v2)
  > rule div : Div (v1, v2)
  > rule ult : Ult (v1, v2)
  > KN
  $ cat > seq.knl <<'KN'
  > (** Sequences of terms of a sort. *)
  > sort TSeq of ty
  > node Seq : a list -> TSeq a
  > node Len : TSeq a -> TBitVec 32
  > KN
  $ cat > seq.kn <<'KN'
  > use "bitvec"
  > rule len : Len v
  > KN
  $ kanon ocaml-typed lang.knl
  (* Generated by kanon from lang.knl, bitvec.knl, seq.knl, bitvec.kn, seq.kn. Do not edit. *)
  
  open Lang_types
  
  (** The tags of the terms, one polymorphic variant type per sort and per subsort, with the sort in lowercase as its name. A sort that has subsorts has their variants too, which a term of the sort may be. The types may be joined, in a group of tags of the user: [type scalar = [ Tag.tbitvec | Tag.tfloat ]]. *)
  module Tag = struct
    type tbool = [ `TBool ]
    type tnonzero = [ `TNonzero ]
    type tzero = [ `TZero ]
    type tbitvec = [ `TBitVec | tnonzero | tzero ]
    type tseq = [ `TSeq ]
  end
  
  (** The typed interface of the language, organised like it: a module per Kanon module (per file). A term of type [_ t] has a phantom parameter, one of the tags of [Tag], that says what Kanon knows of the term, and the smart constructors check it at compile time. The tag is not data: a term is the same value as its untyped term, [raw]. *)
  module type S = sig
    (** The terms and sorts of the types of the language, without tag. *)
    type raw = t
    type raw_ty = ty
    
    (** A term, whose phantom parameter is its tag. *)
    type +'a t
    
    (** A sort of terms of the tag [ 'a ]. *)
    type +'a ty
    
    (** Forgets the tag of a term: the same value. *)
    val untyped : 'a t -> raw
    
    (** Trusts the tag of a term: unchecked. *)
    val type_ : raw -> 'a t
    
    (** Changes the tag of a term: unchecked. *)
    val cast : 'a t -> 'b t
    
    (** Forgets the tag of a sort. *)
    val untype_type : 'a ty -> raw_ty
    
    (** Trusts the tag of a sort: unchecked. *)
    val type_type : raw_ty -> 'a ty
    
    (** The Kanon module bitvec. *)
    module Bitvec : sig
      val t_bool : [> Tag.tbool ] ty
      
      (** Bit-vectors of a width. *)
      val t_bitvec : int -> [> Tag.tbitvec ] ty
      
      (** Adds two bit-vectors. *)
      val add : checked -> [< Tag.tbitvec ] t -> [< Tag.tbitvec ] t ->
        [> Tag.tbitvec ] t
      
      (** Division: the divisor is known to be non-zero. *)
      val div : [< Tag.tbitvec ] t -> [< Tag.tnonzero ] t -> [> Tag.tbitvec ] t
      
      val ult : [< Tag.tbitvec ] t -> [< Tag.tbitvec ] t -> [> Tag.tbool ] t
      val as_bitvec : _ t -> (Z.t * int) option
      val is_bitvec : _ t -> bool
      val as_zero : _ t -> int option
      val is_zero : _ t -> bool
      val as_add : _ t ->
        (checked * [> Tag.tbitvec ] t * [> Tag.tbitvec ] t) option
      val is_add : _ t -> bool
      val as_div : _ t -> ([> Tag.tbitvec ] t * [> Tag.tnonzero ] t) option
      val is_div : _ t -> bool
      val as_ult : _ t -> ([> Tag.tbitvec ] t * [> Tag.tbitvec ] t) option
      val is_ult : _ t -> bool
      val as_unspecified : _ t ->
        ([> Tag.tbitvec ] t * [> Tag.tbitvec ] t) option
      val is_unspecified : _ t -> bool
      val as_tbool : _ ty -> unit option
      val is_tbool : _ ty -> bool
      val as_tbitvec : _ ty -> int option
      val is_tbitvec : _ ty -> bool
    end
    
    (** The Kanon module seq. *)
    module Seq : sig
      (** Sequences of terms of a sort. *)
      val t_seq : _ ty -> [> Tag.tseq ] ty
      
      val len : [< Tag.tseq ] t -> [> Tag.tbitvec ] t
      val as_seq : _ t -> 'a t list option
      val is_seq : _ t -> bool
      val as_len : _ t -> [> Tag.tseq ] t option
      val is_len : _ t -> bool
      val as_tseq : _ ty -> raw_ty option
      val is_tseq : _ ty -> bool
    end
  end
  
  (** The implementation of [S]: the rules, with the types of [S] visible, [type 'a t = raw]. [S] hides it, since a visible equality would make every tag the same type. It has no constructor for the leaf nodes, which no rule builds: a program adds them around it, with [type_], in [module Typed = struct include (Derived : S) ... end]. *)
  module Derived = struct
    include Lang_rules
    
    type raw = t
    type raw_ty = ty
    type nonrec 'a t = raw
    type nonrec 'a ty = raw_ty
    
    let[@inline] untyped (x : 'a t) : raw = x
    let[@inline] type_ (x : raw) : 'a t = x
    let[@inline] cast (x : 'a t) : 'b t = x
    let[@inline] untype_type (x : 'a ty) : raw_ty = x
    let[@inline] type_type (x : raw_ty) : 'a ty = x
  end
  
  (** Checks that the rules satisfy [S], whatever their tags. *)
  module _ : S = Derived

A sort has a tag type, the lowercase name of its constructor, in `Tag`: the
variant of its name, and for a sort that has subsorts, their tag types. A term
of a subsort is accepted wherever its parent sort is, and not the reverse: an
operand `[< tbitvec ] t` accepts any bit-vector, `[< tnonzero ] t` (the divisor
of `div`) only those that are known to be non-zero. A result is `[> tag ] t`:
`add` builds a `tbitvec`, which has to be cast to be a divisor. The docs of
the rule or, failing that, of the node, are carried to the `val`. Parameters
are plain arguments. A node without a rule function (a leaf node, which no
rule builds, like `BitVec` and `Zero`) has no `val`, but it has its
destructors: a program builds leaf terms itself, from the types (`node (Zero
n) (TBitVec n)`), and gives them their tag with `type_`. A `val` is in the
module of the file of its declaration: the rule function, the sort, or the
rule; a module that has nothing to declare has no module.

`S` is the signature. `Derived` implements it with the rules, `let add =
Kanon_rules.bv_add`.

A sort variable is shared by the operands and the result (`b_ite`), and a
sort that the typing does not determine, or a node without a typing, has any
tag:

  $ cat > any.knl <<'KN'
  > [@@@ocaml_rules "R"]
  > type var [@ocaml "string"]
  > sort TInt
  > sort TOther
  > node Var of var
  > node Cast : TInt -> TOther
  > node Neg : TOther -> TInt
  > KN
  $ cat > any.kn <<'KN'
  > rule cast : Cast v
  > rule neg : Neg v
  > KN
  $ kanon ocaml-typed any.knl any.kn | sed -n '/^module type S/,/^end/p' | grep "^ *val " | grep -v "val \(as\|is\|type\|untype\)_\|untyped\|'b t\|b_\|sem_eq"
      val t_int : [> Tag.tint ] ty
      val t_other : [> Tag.tother ] ty
      val cast : [< Tag.tint ] t -> [> Tag.tother ] t
      val neg : [< Tag.tother ] t -> [> Tag.tint ] t

A rule function has the parameters that it declares, as the generated rules
have them: a `nat` or an `int` is a `Z.t` (`extract`). The arguments of the
constructors of the types are those of the types, and of the sorts and the
destructors, so a `nat` is an `int` there (`t_bitvec`, `as_lit`). The sorts that are
parameters of a node are raw (`raw_ty`): their tag is not known, and the terms
that are parameters (not operands) have any tag:

  $ cat > params.knl <<'KN'
  > [@@@ocaml_rules "R"]
  > type var = { id : int }
  > sort TBool
  > sort TBitVec of nat
  > node Extract of nat * nat (i, j) : TBitVec n -> TBitVec (j - i + 1)
  > node Lit of int * nat (v, n) : TBitVec n
  > node Exists of (var * ty) list * t : TBool
  > node Eqz : TBitVec n -> TBool
  > KN
  $ cat > params.kn <<'KN'
  > rule extract : Extract (i, j, v)
  > rule mk_exists : Exists (vars, body)
  > KN
  $ kanon ocaml-typed params.knl params.kn | sed -n '/^module type S/,/^end/p' | grep "^ *val " | grep -v "val \(as\|is\|type\|untype\)_\|untyped\|'b t\|b_\|sem_eq"
      val t_bool : [> Tag.tbool ] ty
      val t_bitvec : int -> [> Tag.tbitvec ] ty
      val extract : Z.t -> Z.t -> [< Tag.tbitvec ] t -> [> Tag.tbitvec ] t
      val mk_exists : ((var * raw_ty) list) -> _ t -> [> Tag.tbool ] t

A rule function whose spec is not a single node over its parameters is typed
by the outermost node of its spec: the result has the tag of that node, a
parameter that is an operand of it has the tag of the operand, and any other
parameter has any tag. The spec of `to_bool` is `Not (Eqz v)`, where `v` is not
an operand of `Not`; that of `lt_zero` is a node over a term that is not a
parameter; and that of `fmod` is not a node:

  $ cat > comp.knl <<'KN'
  > [@@@ocaml_rules "R"]
  > sort TBool
  > node Not : TBool -> TBool
  > sort TBitVec of nat [@get size]
  > sort TFloat
  > node Eqz : TBitVec n -> TBool
  > node Ult : TBitVec n -> TBitVec n -> TBool
  > node FRem : TFloat -> TFloat -> TFloat
  > node Zero of nat (n) : TBitVec n
  > KN
  $ cat > comp.kn <<'KN'
  > prim size : t -> int
  > rule to_bool (v : t) : Not (Eqz v)
  > rule ult_swapped (a b : t) : Ult (b, a)
  > rule lt_zero (v : t) : Ult (v, Zero (size v))
  > rule fmod (v1 v2 : t) : raw_fmod (FRem (v1, v2)) v1
  > fn raw_fmod (r v : t) : t = r
  > KN
  $ kanon ocaml-typed comp.knl comp.kn 2>&1 | sed -n '/^module type S/,/^end/p' | grep "^ *val " | grep -v "val \(as\|is\|type\|untype\)_\|untyped\|'b t\|b_\|sem_eq"
      val t_bool : [> Tag.tbool ] ty
      val t_bitvec : int -> [> Tag.tbitvec ] ty
      val t_float : [> Tag.tfloat ] ty
      val to_bool : _ t -> [> Tag.tbool ] t
      val ult_swapped : [< Tag.tbitvec ] t -> [< Tag.tbitvec ] t ->
      val lt_zero : [< Tag.tbitvec ] t -> [> Tag.tbool ] t
      val fmod : _ t -> _ t -> _ t

A sort and a subsort whose names differ by their case would have the same tag
type (two sorts would have the same destructors):

  $ cat > clash.knl <<'KN'
  > [@@@ocaml_rules "R"]
  > sort TInt
  > subsort TINT : TInt
  > KN
  $ echo > none.kn
  $ kanon ocaml-typed clash.knl none.kn
  kanon: TInt and TINT have the same tag type, tint
  [1]

The destructors share their names with the functions of their module, which
they may not take (the functions of another module are in another module of the
interface, and have another name in the rules):

  $ cat > any.kn <<'KN'
  > rule is_cast : Cast v
  > KN
  $ kanon ocaml-typed any.knl any.kn
  any.kn:1:0: Any.is_cast: the module has two items of this name (a function, a destructor or the function of a sort): rename one of them
  [1]

The implementation is made of the rules, whose OCaml module the language names,
and the modules of the interface are named after the files, which may not take
the names of the generated modules:

  $ echo 'sort TInt' > norules.knl
  $ kanon ocaml-typed norules.knl none.kn
  kanon: ocaml-typed: [@@@ocaml_rules "M"], in the declaration of the language, names the OCaml module of the rules (the output of kanon ocaml), which the implementation is made of
  [1]
  $ printf '[@@@ocaml_rules "R"]\nuse "tag"\n' > named.knl
  $ echo 'sort TInt' > tag.knl
  $ kanon ocaml-typed named.knl none.kn
  ./tag.knl:1:5: the module Tag has the name of a module that the generated code uses
  [1]
