-- Generated by kanon from l5.knl, bool.knl, pack.knl. Do not edit.
import L5.Val
import KanonBool.Lang
import PackMod.Lang
import L5.Lang

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace L5

open Classical Kanon

mutual

/-- The typing of the terms. -/
def Term.WT : Term → Prop
  | .bool n t => KanonBool.Node.wt Ty.bool Term.ty n t ∧ allBool n
  | .pack n t => PackMod.Node.wt Ty.bool Ty.pack Term.ty n t ∧ allPack n
  | .l5 n t => L5.Node.wt Ty.bool Ty.pack Term.ty n t ∧ allL5 n

def allBool : KanonBool.Node Term → Prop
  | (.Bool x1) => True
  | (.Not a1) => a1.WT
  | (.And a1 a2) => a1.WT ∧ a2.WT
  | (.Or a1 a2) => a1.WT ∧ a2.WT
  | (.Eq a1 a2) => a1.WT ∧ a2.WT
  | (.Ite a1 a2 a3) => a1.WT ∧ a2.WT ∧ a3.WT
  | (.Distinct l1) => allList l1

def allPack : (PackMod.Node Ty) Term → Prop
  | (.Pack l1) => allList l1
  | (.Some_ x1 a2) => a2.WT

def allL5 : L5.Node Term → Prop
  | (.Var x1) => True

def allList : List Term → Prop
  | [] => True
  | x :: xs => x.WT ∧ allList xs

end

mutual

/-- The evaluation of the terms. -/
def ev (ρ : Env) : Term → Option Val
  | .bool n t => KanonBool.Node.eval (D := dom) ρ t (evBool n)
  | .pack n t => PackMod.Node.eval (D := dom) ρ t (evPack n)
  | .l5 n t => L5.Node.eval (D := dom) ρ t (evL5 n)

def evBool : KanonBool.Node Term → KanonBool.Node (Env → Option Val)
  | (.Bool x1) => (.Bool x1)
  | (.Not a1) => (.Not (fun ρ => ev ρ a1))
  | (.And a1 a2) => (.And (fun ρ => ev ρ a1) (fun ρ => ev ρ a2))
  | (.Or a1 a2) => (.Or (fun ρ => ev ρ a1) (fun ρ => ev ρ a2))
  | (.Eq a1 a2) => (.Eq (fun ρ => ev ρ a1) (fun ρ => ev ρ a2))
  | (.Ite a1 a2 a3) => (.Ite (fun ρ => ev ρ a1) (fun ρ => ev ρ a2) (fun ρ => ev ρ a3))
  | (.Distinct l1) => (.Distinct (evList l1))

def evPack : (PackMod.Node Ty) Term → (PackMod.Node Ty) (Env → Option Val)
  | (.Pack l1) => (.Pack (evList l1))
  | (.Some_ x1 a2) => (.Some_ x1 (fun ρ => ev ρ a2))

def evL5 : L5.Node Term → L5.Node (Env → Option Val)
  | (.Var x1) => (.Var x1)

def evList : List Term → List (Env → Option Val)
  | [] => []
  | x :: xs => (fun ρ => ev ρ x) :: evList xs

end

theorem allList_iff : ∀ l, allList l ↔ ∀ x ∈ l, Term.WT x
  | [] => by simp [allList]
  | x :: xs => by simp [allList, allList_iff xs]

theorem evList_eq : ∀ l, evList l = l.map (fun c ρ => ev ρ c)
  | [] => rfl
  | x :: xs => by rw [evList, evList_eq xs]; rfl

theorem allBool_iff (n : KanonBool.Node Term) : allBool n ↔ n.All Term.WT := by
  cases n <;> simp [allBool, KanonBool.Node.All, allList_iff]

theorem evBool_eq (n : KanonBool.Node Term) : evBool n = n.map (fun c ρ => ev ρ c) := by
  cases n <;> simp only [evBool, KanonBool.Node.map, evList_eq]

theorem allPack_iff (n : (PackMod.Node Ty) Term) : allPack n ↔ n.All Term.WT := by
  cases n <;> simp [allPack, PackMod.Node.All, allList_iff]

theorem evPack_eq (n : (PackMod.Node Ty) Term) : evPack n = n.map (fun c ρ => ev ρ c) := by
  cases n <;> simp only [evPack, PackMod.Node.map, evList_eq]

theorem allL5_iff (n : L5.Node Term) : allL5 n ↔ n.All Term.WT := by
  cases n <;> simp [allL5, L5.Node.All, allList_iff]

theorem evL5_eq (n : L5.Node Term) : evL5 n = n.map (fun c ρ => ev ρ c) := by
  cases n <;> simp only [evL5, L5.Node.map, evList_eq]

/-- The typing of a node of `Bool`. -/
theorem WT_bool (n : KanonBool.Node Term) (t : Ty) :
  Term.WT (.bool n t) ↔ KanonBool.Node.wt Ty.bool Term.ty n t ∧ n.All Term.WT := by
  show (_ ∧ allBool n) ↔ _; rw [allBool_iff]

/-- The evaluation of a node of `Bool`. -/
theorem ev_bool (ρ : Env) (n : KanonBool.Node Term) (t : Ty) :
  ev ρ (.bool n t) = KanonBool.Node.eval (D := dom) ρ t (n.map (fun c ρ => ev ρ c)) :=
  congrArg (KanonBool.Node.eval (D := dom) ρ t) (evBool_eq n)

/-- The typing of a node of `Pack`. -/
theorem WT_pack (n : (PackMod.Node Ty) Term) (t : Ty) :
  Term.WT (.pack n t) ↔ PackMod.Node.wt Ty.bool Ty.pack Term.ty n t ∧ n.All Term.WT := by
  show (_ ∧ allPack n) ↔ _; rw [allPack_iff]

/-- The evaluation of a node of `Pack`. -/
theorem ev_pack (ρ : Env) (n : (PackMod.Node Ty) Term) (t : Ty) :
  ev ρ (.pack n t) = PackMod.Node.eval (D := dom) ρ t (n.map (fun c ρ => ev ρ c)) :=
  congrArg (PackMod.Node.eval (D := dom) ρ t) (evPack_eq n)

/-- The typing of a node of `L5`. -/
theorem WT_l5 (n : L5.Node Term) (t : Ty) :
  Term.WT (.l5 n t) ↔ L5.Node.wt Ty.bool Ty.pack Term.ty n t ∧ n.All Term.WT := by
  show (_ ∧ allL5 n) ↔ _; rw [allL5_iff]

/-- The evaluation of a node of `L5`. -/
theorem ev_l5 (ρ : Env) (n : L5.Node Term) (t : Ty) :
  ev ρ (.l5 n t) = L5.Node.eval (D := dom) ρ t (n.map (fun c ρ => ev ρ c)) :=
  congrArg (L5.Node.eval (D := dom) ρ t) (evL5_eq n)

/-- The semantics of the language. -/
@[reducible] def sem : Kanon.Sem where
  toDom := dom
  Term := Term
  ty := Term.ty
  WT := Term.WT
  ev := ev
  size := sizeOf

/-- The value of a term; `none` for poison. -/
abbrev eval : Env → Term → Option Val := sem.eval

/-- `r` refines `spec`: it has the same type, and the same value whenever `spec` is not poison. -/
abbrev Refines : Term → Term → Prop := sem.Refines

instance : Refinement Refines := Sem.refinement

instance instBoolLang : KanonBool.Lang sem where
  toValues := inferInstanceAs (KanonBool.Values dom)
  node := {
    inj := .bool
    proj := fun e => match e with | .bool n _ => some n | _ => none
    ty_inj := fun _ _ => rfl
    proj_inj := fun _ _ => rfl
    inj_proj := by intro e n h; cases e <;> cases h <;> rfl }
  WT_inj := WT_bool
  ev_inj := ev_bool
  size_proj := by kanon_size_proj
  srt := {
    inj := .bool
    proj := fun s => match s with | .bool s => some s | _ => none
    proj_inj := fun _ => rfl
    inj_proj := by intro b a h; cases b <;> cases h <;> rfl }

instance instPackLang : PackMod.Lang sem where
  toValues := inferInstanceAs (PackMod.Values dom)
  node := {
    inj := .pack
    proj := fun e => match e with | .pack n _ => some n | _ => none
    ty_inj := fun _ _ => rfl
    proj_inj := fun _ _ => rfl
    inj_proj := by intro e n h; cases e <;> cases h <;> rfl }
  WT_inj := WT_pack
  ev_inj := ev_pack
  size_proj := by kanon_size_proj
  srt := {
    inj := .pack
    proj := fun s => match s with | .pack s => some s | _ => none
    proj_inj := fun _ => rfl
    inj_proj := by intro b a h; cases b <;> cases h <;> rfl }
  proj_Bool_inj_Pack _ _ := rfl
  proj_Pack_inj_Bool _ _ := rfl
  sortProj_Bool_inj_Pack _ := rfl
  sortProj_Pack_inj_Bool _ := rfl

instance instL5Lang : L5.Lang sem where
  toValues := inferInstanceAs (L5.Values dom)
  node := {
    inj := .l5
    proj := fun e => match e with | .l5 n _ => some n | _ => none
    ty_inj := fun _ _ => rfl
    proj_inj := fun _ _ => rfl
    inj_proj := by intro e n h; cases e <;> cases h <;> rfl }
  WT_inj := WT_l5
  ev_inj := ev_l5
  size_proj := by kanon_size_proj
  proj_Bool_inj_L5 _ _ := rfl
  proj_Pack_inj_L5 _ _ := rfl
  proj_L5_inj_Bool _ _ := rfl
  proj_L5_inj_Pack _ _ := rfl

end L5
