-- Generated by kanon from cfg.knl, cfg.kn. Do not edit.
import CfgMod.Ops

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace CfgMod

open Classical Kanon

end CfgMod
