-- Generated by kanon from l1.knl, bool.knl, num.knl. Do not edit.
import L1.Semantics
import L1.Typing
import KanonBool.Soundness
import NumMod.Soundness
import L1.Soundness

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace L1

open Classical Kanon

/-- The oracles that the model is parameterised by. -/
structure Oracle where
  tag_le : Term → Term → Bool
  bool_sort_by_tag : (List Term) → (List Term)

/-- What the proofs assume of the oracles: what each module assumes of its own. -/
structure Oracle.Compat (orc : Oracle) : Prop where
  bool : KanonBool.Oracle.Compat (S := sem) orc.bool_sort_by_tag

def Bool.sure_neq (O : L1.Ops sem) (a : Term) (b : Term) : Bool :=
  (firstSome [KanonBool.Bool.sure_neq.c1 (S := sem) a b, KanonBool.Bool.sure_neq.c2 (S := sem) a b, NumMod.Bool.sure_neq.c1 (S := sem) a b]).getD (KanonBool.Bool.sure_neq.default (S := sem) a b)

theorem Bool.sure_neq.sound (O : L1.Ops sem) (hO : O.Sound) (a : Term) (b : Term) :
    KanonBool.Bool.sure_neq.post (S := sem) a b (Bool.sure_neq O a b) := by
  unfold Bool.sure_neq
  refine Kanon.getD_firstSome_cons (fun r h => KanonBool.Bool.sure_neq.c1.ok (S := sem) a b r h) ?_
  refine Kanon.getD_firstSome_cons (fun r h => KanonBool.Bool.sure_neq.c2.ok (S := sem) a b r h) ?_
  refine Kanon.getD_firstSome_cons (fun r h => NumMod.Bool.sure_neq.c1.ok (S := sem) a b r h) ?_
  exact Kanon.getD_firstSome_nil (KanonBool.Bool.sure_neq.default.ok (S := sem) a b)

def Bool.and_.step (O : L1.Ops sem) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [KanonBool.Bool.and_.r_same (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.and_.r_false_ (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.and_.r_true_ (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.and_.r_not (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.and_.r_and_ (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.and_.r_or_ (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.and_.r_eq_neq (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.and_.r_default (S := sem) O.toNumOps.toBoolOps v1 v2]).getD
    (KanonBool.Bool.and_.spec (S := sem) v1 v2)

theorem Bool.and_.step_sound (O : L1.Ops sem) (hO : O.Sound) (v1 : Term) (v2 : Term) :
    Refines (KanonBool.Bool.and_.spec (S := sem) v1 v2) (Bool.and_.step O v1 v2) := by
  unfold Bool.and_.step
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.and_.r_same.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.and_.r_false_.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.and_.r_true_.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.and_.r_not.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.and_.r_and_.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.and_.r_or_.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.and_.r_eq_neq.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.and_.r_default.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  exact Kanon.Refinement.firstSome_nil

def Bool.or_.step (O : L1.Ops sem) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [KanonBool.Bool.or_.r_same (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.or_.r_true_ (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.or_.r_false_ (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.or_.r_not (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.or_.r_or_ (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.or_.r_and_ (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.or_.r_default (S := sem) O.toNumOps.toBoolOps v1 v2]).getD
    (KanonBool.Bool.or_.spec (S := sem) v1 v2)

theorem Bool.or_.step_sound (O : L1.Ops sem) (hO : O.Sound) (v1 : Term) (v2 : Term) :
    Refines (KanonBool.Bool.or_.spec (S := sem) v1 v2) (Bool.or_.step O v1 v2) := by
  unfold Bool.or_.step
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.or_.r_same.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.or_.r_true_.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.or_.r_false_.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.or_.r_not.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.or_.r_or_.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.or_.r_and_.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.or_.r_default.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  exact Kanon.Refinement.firstSome_nil

def Bool.not_.step (O : L1.Ops sem) (sv : Term) : Term :=
  (firstSome [KanonBool.Bool.not_.r_true_ (S := sem) O.toNumOps.toBoolOps sv, KanonBool.Bool.not_.r_false_ (S := sem) O.toNumOps.toBoolOps sv, KanonBool.Bool.not_.r_not (S := sem) O.toNumOps.toBoolOps sv, KanonBool.Bool.not_.r_or_ (S := sem) O.toNumOps.toBoolOps sv, KanonBool.Bool.not_.r_and_ (S := sem) O.toNumOps.toBoolOps sv, KanonBool.Bool.not_.r_ite (S := sem) O.toNumOps.toBoolOps sv, KanonBool.Bool.not_.r_distinct (S := sem) O.toNumOps.toBoolOps sv, KanonBool.Bool.not_.r_default (S := sem) O.toNumOps.toBoolOps sv]).getD
    (KanonBool.Bool.not_.spec (S := sem) sv)

theorem Bool.not_.step_sound (O : L1.Ops sem) (hO : O.Sound) (sv : Term) :
    Refines (KanonBool.Bool.not_.spec (S := sem) sv) (Bool.not_.step O sv) := by
  unfold Bool.not_.step
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.not_.r_true_.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound sv res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.not_.r_false_.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound sv res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.not_.r_not.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound sv res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.not_.r_or_.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound sv res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.not_.r_and_.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound sv res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.not_.r_ite.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound sv res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.not_.r_distinct.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound sv res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.not_.r_default.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound sv res h) ?_
  exact Kanon.Refinement.firstSome_nil

def Bool.ite.step (O : L1.Ops sem) (guard : Term) (if_ : Term) (else_ : Term) : Term :=
  (firstSome [KanonBool.Bool.ite.r_true_ (S := sem) O.toNumOps.toBoolOps guard if_ else_, KanonBool.Bool.ite.r_false_ (S := sem) O.toNumOps.toBoolOps guard if_ else_, KanonBool.Bool.ite.r_bool (S := sem) O.toNumOps.toBoolOps guard if_ else_, KanonBool.Bool.ite.r_not_bool (S := sem) O.toNumOps.toBoolOps guard if_ else_, KanonBool.Bool.ite.r_false_then (S := sem) O.toNumOps.toBoolOps guard if_ else_, KanonBool.Bool.ite.r_true_then (S := sem) O.toNumOps.toBoolOps guard if_ else_, KanonBool.Bool.ite.r_false_else (S := sem) O.toNumOps.toBoolOps guard if_ else_, KanonBool.Bool.ite.r_true_else (S := sem) O.toNumOps.toBoolOps guard if_ else_, KanonBool.Bool.ite.r_not_guard (S := sem) O.toNumOps.toBoolOps guard if_ else_, KanonBool.Bool.ite.r_guard_then (S := sem) O.toNumOps.toBoolOps guard if_ else_, KanonBool.Bool.ite.r_guard_else (S := sem) O.toNumOps.toBoolOps guard if_ else_, KanonBool.Bool.ite.r_ite_then (S := sem) O.toNumOps.toBoolOps guard if_ else_, KanonBool.Bool.ite.r_ite_else (S := sem) O.toNumOps.toBoolOps guard if_ else_, KanonBool.Bool.ite.r_and_ite_then (S := sem) O.toNumOps.toBoolOps guard if_ else_, KanonBool.Bool.ite.r_or_ite_else (S := sem) O.toNumOps.toBoolOps guard if_ else_, KanonBool.Bool.ite.r_same (S := sem) O.toNumOps.toBoolOps guard if_ else_, KanonBool.Bool.ite.r_default (S := sem) O.toNumOps.toBoolOps guard if_ else_]).getD
    (KanonBool.Bool.ite.spec (S := sem) guard if_ else_)

theorem Bool.ite.step_sound (O : L1.Ops sem) (hO : O.Sound) (guard : Term) (if_ : Term) (else_ : Term) :
    Refines (KanonBool.Bool.ite.spec (S := sem) guard if_ else_) (Bool.ite.step O guard if_ else_) := by
  unfold Bool.ite.step
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_true_.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_false_.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_bool.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_not_bool.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_false_then.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_true_then.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_false_else.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_true_else.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_not_guard.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_guard_then.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_guard_else.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_ite_then.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_ite_else.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_and_ite_then.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_or_ite_else.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_same.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.ite.r_default.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound guard if_ else_ res h) ?_
  exact Kanon.Refinement.firstSome_nil

def Bool.eq.step (O : L1.Ops sem) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [NumMod.Bool.eq.r_nums (S := sem) O.toNumOps v1 v2, KanonBool.Bool.eq.r_same (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.eq.r_bools (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.eq.r_ite_ite (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.eq.r_false_ (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.eq.r_true_ (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.eq.r_nots (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.eq.r_default (S := sem) O.toNumOps.toBoolOps v1 v2]).getD
    (KanonBool.Bool.eq.spec (S := sem) v1 v2)

theorem Bool.eq.step_sound (O : L1.Ops sem) (hO : O.Sound) (v1 : Term) (v2 : Term) :
    Refines (KanonBool.Bool.eq.spec (S := sem) v1 v2) (Bool.eq.step O v1 v2) := by
  unfold Bool.eq.step
  refine Kanon.Refinement.firstSome_cons (fun res h => NumMod.Bool.eq.r_nums.sound (S := sem) O.toNumOps hO.toNumSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.eq.r_same.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.eq.r_bools.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.eq.r_ite_ite.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.eq.r_false_.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.eq.r_true_.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.eq.r_nots.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.eq.r_default.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  exact Kanon.Refinement.firstSome_nil

def Bool.eq_untyped.step (O : L1.Ops sem) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [KanonBool.Bool.eq_untyped.r_ill_typed (S := sem) O.toNumOps.toBoolOps v1 v2, KanonBool.Bool.eq_untyped.r_typed (S := sem) O.toNumOps.toBoolOps v1 v2]).getD
    (KanonBool.Bool.eq_untyped.spec (S := sem) v1 v2)

theorem Bool.eq_untyped.step_sound (O : L1.Ops sem) (hO : O.Sound) (v1 : Term) (v2 : Term) :
    Refines (KanonBool.Bool.eq_untyped.spec (S := sem) v1 v2) (Bool.eq_untyped.step O v1 v2) := by
  unfold Bool.eq_untyped.step
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.eq_untyped.r_ill_typed.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.eq_untyped.r_typed.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound v1 v2 res h) ?_
  exact Kanon.Refinement.firstSome_nil

def Bool.distinct.step (O : L1.Ops sem) (l : (List Term)) : Term :=
  (firstSome [KanonBool.Bool.distinct.r_small (S := sem) O.toNumOps.toBoolOps l, KanonBool.Bool.distinct.r_distinct (S := sem) O.toNumOps.toBoolOps l, KanonBool.Bool.distinct.r_not_distinct (S := sem) O.toNumOps.toBoolOps l, KanonBool.Bool.distinct.r_default (S := sem) O.toNumOps.toBoolOps l]).getD
    (KanonBool.Bool.distinct.spec (S := sem) l)

theorem Bool.distinct.step_sound (O : L1.Ops sem) (hO : O.Sound) (l : (List Term)) :
    Refines (KanonBool.Bool.distinct.spec (S := sem) l) (Bool.distinct.step O l) := by
  unfold Bool.distinct.step
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.distinct.r_small.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound l res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.distinct.r_distinct.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound l res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.distinct.r_not_distinct.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound l res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => KanonBool.Bool.distinct.r_default.sound (S := sem) O.toNumOps.toBoolOps hO.toNumSound.toBoolSound l res h) ?_
  exact Kanon.Refinement.firstSome_nil

def Num.add.step (O : L1.Ops sem) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [NumMod.Num.add.r_unit_zero (S := sem) O.toNumOps v1 v2, NumMod.Num.add.r_lits (S := sem) O.toNumOps v1 v2, NumMod.Num.add.r_default (S := sem) O.toNumOps v1 v2]).getD
    (NumMod.Num.add.spec (S := sem) v1 v2)

theorem Num.add.step_sound (O : L1.Ops sem) (hO : O.Sound) (v1 : Term) (v2 : Term) :
    Refines (NumMod.Num.add.spec (S := sem) v1 v2) (Num.add.step O v1 v2) := by
  unfold Num.add.step
  refine Kanon.Refinement.firstSome_cons (fun res h => NumMod.Num.add.r_unit_zero.sound (S := sem) O.toNumOps hO.toNumSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => NumMod.Num.add.r_lits.sound (S := sem) O.toNumOps hO.toNumSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => NumMod.Num.add.r_default.sound (S := sem) O.toNumOps hO.toNumSound v1 v2 res h) ?_
  exact Kanon.Refinement.firstSome_nil

def Num.less.step (O : L1.Ops sem) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [NumMod.Num.less.r_lits (S := sem) O.toNumOps v1 v2, NumMod.Num.less.r_pos (S := sem) O.toNumOps v1 v2, NumMod.Num.less.r_same (S := sem) O.toNumOps v1 v2, NumMod.Num.less.r_default (S := sem) O.toNumOps v1 v2]).getD
    (NumMod.Num.less.spec (S := sem) v1 v2)

theorem Num.less.step_sound (O : L1.Ops sem) (hO : O.Sound) (v1 : Term) (v2 : Term) :
    Refines (NumMod.Num.less.spec (S := sem) v1 v2) (Num.less.step O v1 v2) := by
  unfold Num.less.step
  refine Kanon.Refinement.firstSome_cons (fun res h => NumMod.Num.less.r_lits.sound (S := sem) O.toNumOps hO.toNumSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => NumMod.Num.less.r_pos.sound (S := sem) O.toNumOps hO.toNumSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => NumMod.Num.less.r_same.sound (S := sem) O.toNumOps hO.toNumSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => NumMod.Num.less.r_default.sound (S := sem) O.toNumOps hO.toNumSound v1 v2 res h) ?_
  exact Kanon.Refinement.firstSome_nil

def Num.max.step (O : L1.Ops sem) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [NumMod.Num.max.r_same (S := sem) O.toNumOps v1 v2, NumMod.Num.max.r_default (S := sem) O.toNumOps v1 v2]).getD
    (NumMod.Num.max.spec (S := sem) v1 v2)

theorem Num.max.step_sound (O : L1.Ops sem) (hO : O.Sound) (v1 : Term) (v2 : Term) :
    Refines (NumMod.Num.max.spec (S := sem) v1 v2) (Num.max.step O v1 v2) := by
  unfold Num.max.step
  refine Kanon.Refinement.firstSome_cons (fun res h => NumMod.Num.max.r_same.sound (S := sem) O.toNumOps hO.toNumSound v1 v2 res h) ?_
  refine Kanon.Refinement.firstSome_cons (fun res h => NumMod.Num.max.r_default.sound (S := sem) O.toNumOps hO.toNumSound v1 v2 res h) ?_
  exact Kanon.Refinement.firstSome_nil

/-- The rule functions as their specs, without simplification. -/
def opsRaw (orc : Oracle) : L1.Ops sem :=
  { tag_le := orc.tag_le,
    bool_sort_by_tag := orc.bool_sort_by_tag,
    bool_sure_neq := fun a b => KanonBool.Bool.sure_neq.default (S := sem) a b,
    bool_and_ := fun v1 v2 => KanonBool.Bool.and_.spec (S := sem) v1 v2,
    bool_or_ := fun v1 v2 => KanonBool.Bool.or_.spec (S := sem) v1 v2,
    bool_not_ := fun sv => KanonBool.Bool.not_.spec (S := sem) sv,
    bool_ite := fun guard if_ else_ => KanonBool.Bool.ite.spec (S := sem) guard if_ else_,
    bool_eq := fun v1 v2 => KanonBool.Bool.eq.spec (S := sem) v1 v2,
    bool_eq_untyped := fun v1 v2 => KanonBool.Bool.eq_untyped.spec (S := sem) v1 v2,
    bool_distinct := fun l => KanonBool.Bool.distinct.spec (S := sem) l,
    num_add := fun v1 v2 => NumMod.Num.add.spec (S := sem) v1 v2,
    num_less := fun v1 v2 => NumMod.Num.less.spec (S := sem) v1 v2,
    num_max := fun v1 v2 => NumMod.Num.max.spec (S := sem) v1 v2 }

/-- One step of the rule functions, over those of `O`. -/
def opsStep (O : L1.Ops sem) : L1.Ops sem :=
  { O with
    bool_sure_neq := Bool.sure_neq O,
    bool_and_ := Bool.and_.step O,
    bool_or_ := Bool.or_.step O,
    bool_not_ := Bool.not_.step O,
    bool_ite := Bool.ite.step O,
    bool_eq := Bool.eq.step O,
    bool_eq_untyped := Bool.eq_untyped.step O,
    bool_distinct := Bool.distinct.step O,
    num_add := Num.add.step O,
    num_less := Num.less.step O,
    num_max := Num.max.step O }

/-- The rule functions, with `n` steps of fuel. -/
def opsN (orc : Oracle) : Nat → L1.Ops sem
  | 0 => opsRaw orc
  | n + 1 => opsStep (opsN orc n)

/-- Every rule function refines its spec, for any amount of fuel. -/
theorem opsN_sound (orc : Oracle) (h : orc.Compat) : ∀ n, (opsN orc n).Sound
  | 0 =>
    { bool_and_ := fun v1 v2 => Kanon.Sem.Refines.refl,
      bool_or_ := fun v1 v2 => Kanon.Sem.Refines.refl,
      bool_not_ := fun sv => Kanon.Sem.Refines.refl,
      bool_ite := fun guard if_ else_ => Kanon.Sem.Refines.refl,
      bool_eq := fun v1 v2 => Kanon.Sem.Refines.refl,
      bool_eq_untyped := fun v1 v2 => Kanon.Sem.Refines.refl,
      bool_distinct := fun l => Kanon.Sem.Refines.refl,
      num_add := fun v1 v2 => Kanon.Sem.Refines.refl,
      num_less := fun v1 v2 => Kanon.Sem.Refines.refl,
      num_max := fun v1 v2 => Kanon.Sem.Refines.refl,
      bool_orc := h.bool,
      bool_sure_neq := fun a b => KanonBool.Bool.sure_neq.default.ok (S := sem) a b }
  | n + 1 =>
    have hO := opsN_sound orc h n
    { bool_and_ := Bool.and_.step_sound _ hO,
      bool_or_ := Bool.or_.step_sound _ hO,
      bool_not_ := Bool.not_.step_sound _ hO,
      bool_ite := Bool.ite.step_sound _ hO,
      bool_eq := Bool.eq.step_sound _ hO,
      bool_eq_untyped := Bool.eq_untyped.step_sound _ hO,
      bool_distinct := Bool.distinct.step_sound _ hO,
      num_add := Num.add.step_sound _ hO,
      num_less := Num.less.step_sound _ hO,
      num_max := Num.max.step_sound _ hO,
      bool_orc := hO.bool_orc,
      bool_sure_neq := Bool.sure_neq.sound _ hO }

end L1
