-- Generated by kanon from int.knl, int.kn. Do not edit.
import IntMod.Lift

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace IntMod

open Classical Kanon

def Int.int_lt.r_lits.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [IntMod.Lang S] [KanonBool.Typed S] [IntMod.Typed S] (O : Ops S), O.Sound →
  ∀ (x : Int) (t__2 : S.Ty) (y : Int) (t__4 : S.Ty),
  S.Refines (IntMod.Int.int_lt.spec (IntMod.mk (.Int x) t__2) (IntMod.mk (.Int y) t__4))
  ((KanonBool.Bool.of_bool (decide (x < y))))

def Int.int_lt.r_same.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [IntMod.Lang S] [KanonBool.Typed S] [IntMod.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term),
  (decide (v1 = v2)) = true →
  S.Refines (IntMod.Int.int_lt.spec v1 v2)
  (KanonBool.v_false)

def Int.int_lt.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [IntMod.Lang S] [KanonBool.Typed S] [IntMod.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term),
  S.Refines (IntMod.Int.int_lt.spec v1 v2)
  ((IntMod.mk (.Lt v1 v2) (KanonBool.sort .TBool)))

end IntMod
