-- Generated by kanon from int.knl, int.kn. Do not edit.
import IntMod.Statements

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace IntMod

open Classical Kanon

def Int.int_lt.r_lits.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} (L : IntMod.Syntax B LBool) [KanonBool.Sem LBool] [Sem L] (O : Ops L), O.Sound →
  ∀ (x : Int) (t__2 : S.Ty) (y : Int) (t__4 : S.Ty),
  S.Refines (IntMod.Int.int_lt.spec L (B.node (L.IntK x) t__2) (B.node (L.IntK y) t__4))
  ((LBool.bool_of_bool (decide (x < y))))

def Int.int_lt.r_same.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} (L : IntMod.Syntax B LBool) [KanonBool.Sem LBool] [Sem L] (O : Ops L), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term),
  (decide (v1 = v2)) = true →
  S.Refines (IntMod.Int.int_lt.spec L v1 v2)
  (LBool.bool_v_false)

def Int.int_lt.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} (L : IntMod.Syntax B LBool) [KanonBool.Sem LBool] [Sem L] (O : Ops L), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term),
  S.Refines (IntMod.Int.int_lt.spec L v1 v2)
  ((B.node (L.LtK v1 v2) LBool.TBool))

end IntMod
