-- Generated by kanon from pack.knl, pack.kn. Do not edit.
import KanonCore.Embed

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace PackMod

open Classical Kanon

/-- The sorts of the module. -/
inductive Srt (Ty : Type) where
  /-- Lists of terms of a sort. -/
  | TPack (x1 : Ty)
  deriving DecidableEq, Repr, Inhabited

/-- The nodes of the module, over the terms `T` of a language. -/
inductive Node (Ty : Type) (T : Type) where
  /-- A list of terms, of the sort of its elements. -/
  | Pack (l1 : (List T))
  /-- Whether some values of the names, of their sorts, make the body true. -/
  | Some_ (x1 : (List (String × Ty))) (a2 : T)

namespace Node

variable {Ty T U : Type}

/-- The node with its children mapped by `f`. -/
def map (f : T → U) : (Node Ty) T → (Node Ty) U
  | (.Pack l1) => (.Pack (l1.map f))
  | (.Some_ x1 a2) => (.Some_ x1 (f a2))

/-- Every child of the node satisfies `P`. -/
def All (P : T → Prop) : (Node Ty) T → Prop
  | (.Pack l1) => (∀ y ∈ l1, P y)
  | (.Some_ x1 a2) => P a2

/-- The nodes have the same arguments, and their children are related by `R`. -/
def Rel (R : T → U → Prop) : (Node Ty) T → (Node Ty) U → Prop
  | (.Pack l1), (.Pack l1') => Kanon.Forall₂ R l1 l1'
  | (.Some_ x1 a2), (.Some_ x1' a2') => x1 = x1' ∧ R a2 a2'
  | _, _ => False

end Node

end PackMod
