-- Generated by kanon from pack.knl, pack.kn. Do not edit.
import PackMod.Lift
import PackMod.Soundness.Bool.sure_neq
import PackMod.Soundness.Pack.some_

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace PackMod

open Classical Kanon

end PackMod
