-- Generated by kanon from bool.kn, num.kn, neg.kn, even.kn, mix.kn. Do not edit.
import L3.Statements
import L3.Model.Bool.and_

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L3

open Classical Kanon

def Bool.and_.r_same.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.and_.r_same O v1 v2 = some res →
  Refines (Bool.and_.spec v1 v2) res

def Bool.and_.r_false_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.and_.r_false_ O v1 v2 = some res →
  Refines (Bool.and_.spec v1 v2) res

def Bool.and_.r_true_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.and_.r_true_ O v1 v2 = some res →
  Refines (Bool.and_.spec v1 v2) res

def Bool.and_.r_not.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.and_.r_not O v1 v2 = some res →
  Refines (Bool.and_.spec v1 v2) res

def Bool.and_.r_and_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.and_.r_and_ O v1 v2 = some res →
  Refines (Bool.and_.spec v1 v2) res

def Bool.and_.r_or_.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.and_.r_or_ O v1 v2 = some res →
  Refines (Bool.and_.spec v1 v2) res

def Bool.and_.r_eq_neq.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.and_.r_eq_neq O v1 v2 = some res →
  Refines (Bool.and_.spec v1 v2) res

def Bool.and_.r_default.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bool.and_.r_default O v1 v2 = some res →
  Refines (Bool.and_.spec v1 v2) res

def Bool.and_.r_same.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term),
  (decide (v1 = v2)) = true →
  Refines (Bool.and_.spec v1 v2)
  (v1)

def Bool.and_.r_false_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (t__2 : Ty),
  Refines (Bool.and_.spec (Term.mk (Kind.Bool false) t__2) v2)
  (v_false)

def Bool.and_.r_false_.swap.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (t__2 : Ty),
  Refines (Bool.and_.spec v1 (Term.mk (Kind.Bool false) t__2))
  (v_false)

def Bool.and_.r_true_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (t__2 : Ty),
  Refines (Bool.and_.spec (Term.mk (Kind.Bool true) t__2) v2)
  (v2)

def Bool.and_.r_true_.swap.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (t__2 : Ty),
  Refines (Bool.and_.spec v1 (Term.mk (Kind.Bool true) t__2))
  (v1)

def Bool.and_.r_not.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (kanon__3 : Term) (t__4 : Ty),
  (decide (v1 = kanon__3)) = true →
  Refines (Bool.and_.spec v1 (Term.mk (Kind.Op1 Op1.Not kanon__3) t__4))
  (v_false)

def Bool.and_.r_not.swap.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (kanon__3 : Term) (t__4 : Ty),
  (decide (v2 = kanon__3)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op1 Op1.Not kanon__3) t__4) v2)
  (v_false)

def Bool.and_.r_and_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (a : Term) (w__3 : Term) (t__4 : Ty),
  (decide (a = v2)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op2 Op2.And a w__3) t__4) v2)
  ((Term.mk (Kind.Op2 Op2.And a w__3) t__4))

def Bool.and_.r_and_.swap1.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (w__3 : Term) (a : Term) (t__4 : Ty),
  (decide (a = v2)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op2 Op2.And w__3 a) t__4) v2)
  ((Term.mk (Kind.Op2 Op2.And w__3 a) t__4))

def Bool.and_.r_and_.swap2.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (a : Term) (w__3 : Term) (t__4 : Ty),
  (decide (a = v1)) = true →
  Refines (Bool.and_.spec v1 (Term.mk (Kind.Op2 Op2.And a w__3) t__4))
  ((Term.mk (Kind.Op2 Op2.And a w__3) t__4))

def Bool.and_.r_and_.swap1_swap2.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (w__3 : Term) (a : Term) (t__4 : Ty),
  (decide (a = v1)) = true →
  Refines (Bool.and_.spec v1 (Term.mk (Kind.Op2 Op2.And w__3 a) t__4))
  ((Term.mk (Kind.Op2 Op2.And w__3 a) t__4))

def Bool.and_.r_or_.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (a : Term) (w__3 : Term) (t__4 : Ty),
  (decide (a = v2)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op2 Op2.Or a w__3) t__4) v2)
  (a)

def Bool.and_.r_or_.swap1.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v2 : Term) (w__3 : Term) (a : Term) (t__4 : Ty),
  (decide (a = v2)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op2 Op2.Or w__3 a) t__4) v2)
  (a)

def Bool.and_.r_or_.swap2.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (a : Term) (w__3 : Term) (t__4 : Ty),
  (decide (a = v1)) = true →
  Refines (Bool.and_.spec v1 (Term.mk (Kind.Op2 Op2.Or a w__3) t__4))
  (a)

def Bool.and_.r_or_.swap1_swap2.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (w__3 : Term) (a : Term) (t__4 : Ty),
  (decide (a = v1)) = true →
  Refines (Bool.and_.spec v1 (Term.mk (Kind.Op2 Op2.Or w__3 a) t__4))
  (a)

def Bool.and_.r_eq_neq.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (a : Term) (x : Term) (t__4 : Ty) (kanon__7 : Term) (y : Term) (t__9 : Ty),
  ((decide (a = kanon__7)) && (Bool.sure_neq x y)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op2 Op2.Eq a x) t__4) (Term.mk (Kind.Op2 Op2.Eq kanon__7 y) t__9))
  (v_false)

def Bool.and_.r_eq_neq.swap2.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (a : Term) (x : Term) (t__4 : Ty) (y : Term) (kanon__7 : Term) (t__9 : Ty),
  ((decide (a = kanon__7)) && (Bool.sure_neq x y)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op2 Op2.Eq a x) t__4) (Term.mk (Kind.Op2 Op2.Eq y kanon__7) t__9))
  (v_false)

def Bool.and_.r_eq_neq.swap1.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (x : Term) (a : Term) (t__4 : Ty) (kanon__7 : Term) (y : Term) (t__9 : Ty),
  ((decide (a = kanon__7)) && (Bool.sure_neq x y)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op2 Op2.Eq x a) t__4) (Term.mk (Kind.Op2 Op2.Eq kanon__7 y) t__9))
  (v_false)

def Bool.and_.r_eq_neq.swap1_swap2.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (x : Term) (a : Term) (t__4 : Ty) (y : Term) (kanon__7 : Term) (t__9 : Ty),
  ((decide (a = kanon__7)) && (Bool.sure_neq x y)) = true →
  Refines (Bool.and_.spec (Term.mk (Kind.Op2 Op2.Eq x a) t__4) (Term.mk (Kind.Op2 Op2.Eq y kanon__7) t__9))
  (v_false)

def Bool.and_.r_default.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (v1 : Term) (v2 : Term),
  Refines (Bool.and_.spec v1 v2)
  ((Term.mk (mk_commut_binop O Op2.And v1 v2) Ty.TBool))

end L3
