-- Generated by kanon from word.knl, word.kn. Do not edit.
import KanonCore.Attr
import WordMod.Sem
import KanonBool.Ops
import CfgMod.Ops

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace WordMod

open Classical Kanon

def Word.add.spec {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCfg : CfgMod.Syntax B} (L : WordMod.Syntax B LBool LCfg) (f : CfgMod.Flags) (n : Int) (v1 : S.Term) (v2 : S.Term) : S.Term :=
  (B.node (L.WAddK f n v1 v2) (L.TWord n))

def Word.round.spec {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCfg : CfgMod.Syntax B} (L : WordMod.Syntax B LBool LCfg) (m : CfgMod.Rounding) (n : Int) (v : S.Term) : S.Term :=
  (B.node (L.WRoundK m n v) (L.TWord n))

def Word.double.spec {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCfg : CfgMod.Syntax B} (L : WordMod.Syntax B LBool LCfg) (n : Int) (v : S.Term) : S.Term :=
  (L.word_twice n v)

def Word.double_closed.spec {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCfg : CfgMod.Syntax B} (L : WordMod.Syntax B LBool LCfg) (n : Int) (v : S.Term) : S.Term :=
  (L.word_twice n v)

attribute [kanon_spec]
  Word.add.spec
  Word.round.spec
  Word.double.spec
  Word.double_closed.spec

/-- The rule functions, oracles and helpers of the module `Word` in the model of a
language. -/
structure Ops {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCfg : CfgMod.Syntax B} (L : WordMod.Syntax B LBool LCfg) extends
    toBoolOps : KanonBool.Ops LBool, toCfgOps : CfgMod.Ops LCfg where
  word_add : CfgMod.Flags → Int → S.Term → S.Term → S.Term
  word_round : CfgMod.Rounding → Int → S.Term → S.Term
  word_double : Int → S.Term → S.Term
  word_double_closed : Int → S.Term → S.Term

/-- What the proofs assume of the model: its rule functions refine their specs, and the
equations of its helpers. -/
structure Ops.Sound {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCfg : CfgMod.Syntax B} {L : WordMod.Syntax B LBool LCfg} (O : Ops L) : Prop extends
    toBoolSound : KanonBool.Ops.Sound O.toBoolOps, toCfgSound : CfgMod.Ops.Sound O.toCfgOps where
  word_add : ∀ (f : CfgMod.Flags) (n : Int) (v1 : S.Term) (v2 : S.Term), S.Refines (WordMod.Word.add.spec L f n v1 v2) (O.word_add f n v1 v2)
  word_round : ∀ (m : CfgMod.Rounding) (n : Int) (v : S.Term), S.Refines (WordMod.Word.round.spec L m n v) (O.word_round m n v)
  word_double : ∀ (n : Int) (v : S.Term), S.Refines (WordMod.Word.double.spec L n v) (O.word_double n v)
  word_double_closed : ∀ (n : Int) (v : S.Term), S.Refines (WordMod.Word.double_closed.spec L n v) (O.word_double_closed n v)

end WordMod
