-- Generated by kanon from word.knl, word.kn. Do not edit.
import WordMod.Model
import KanonCore.Proof
import KanonBool.Statements

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace WordMod

open Classical Kanon

namespace Lib

variable {S : Kanon.Sem} [KanonBool.Lang S] [WordMod.Lang S] [KanonBool.Typed S] [WordMod.Typed S] {O : Ops S}

theorem lift_bool_and_ (hO : O.Sound) {v1 v1' : S.Term} {v2 v2' : S.Term}
  (h_v1 : S.Refines v1 v1')
  (h_v2 : S.Refines v2 v2') :
  S.Refines (KanonBool.Bool.and_.spec v1 v2) (O.bool_and_ v1' v2') :=
  KanonBool.Lib.lift_bool_and_ (O := O.toBoolOps) hO.toBoolSound h_v1 h_v2

theorem lift_bool_or_ (hO : O.Sound) {v1 v1' : S.Term} {v2 v2' : S.Term}
  (h_v1 : S.Refines v1 v1')
  (h_v2 : S.Refines v2 v2') :
  S.Refines (KanonBool.Bool.or_.spec v1 v2) (O.bool_or_ v1' v2') :=
  KanonBool.Lib.lift_bool_or_ (O := O.toBoolOps) hO.toBoolSound h_v1 h_v2

theorem lift_bool_not_ (hO : O.Sound) {sv sv' : S.Term}
  (h_sv : S.Refines sv sv') :
  S.Refines (KanonBool.Bool.not_.spec sv) (O.bool_not_ sv') :=
  KanonBool.Lib.lift_bool_not_ (O := O.toBoolOps) hO.toBoolSound h_sv

theorem lift_bool_ite (hO : O.Sound) {guard guard' : S.Term} {if_ if_' : S.Term} {else_ else_' : S.Term}
  (h_guard : S.Refines guard guard')
  (h_if_ : S.Refines if_ if_')
  (h_else_ : S.Refines else_ else_') :
  S.Refines (KanonBool.Bool.ite.spec guard if_ else_) (O.bool_ite guard' if_' else_') :=
  KanonBool.Lib.lift_bool_ite (O := O.toBoolOps) hO.toBoolSound h_guard h_if_ h_else_

theorem lift_bool_eq (hO : O.Sound) {v1 v1' : S.Term} {v2 v2' : S.Term}
  (h_v1 : S.Refines v1 v1')
  (h_v2 : S.Refines v2 v2') :
  S.Refines (KanonBool.Bool.eq.spec v1 v2) (O.bool_eq v1' v2') :=
  KanonBool.Lib.lift_bool_eq (O := O.toBoolOps) hO.toBoolSound h_v1 h_v2

theorem lift_bool_eq_untyped (hO : O.Sound) {v1 v1' : S.Term} {v2 v2' : S.Term}
  (h_v1 : S.Refines v1 v1')
  (h_v2 : S.Refines v2 v2') :
  S.Refines (KanonBool.Bool.eq_untyped.spec v1 v2) (O.bool_eq_untyped v1' v2') :=
  KanonBool.Lib.lift_bool_eq_untyped (O := O.toBoolOps) hO.toBoolSound h_v1 h_v2

theorem lift_bool_distinct (hO : O.Sound) {l : (List S.Term)} :
  S.Refines (KanonBool.Bool.distinct.spec l) (O.bool_distinct l) :=
  KanonBool.Lib.lift_bool_distinct (O := O.toBoolOps) hO.toBoolSound

theorem lift_word_add (hO : O.Sound) {f : CfgMod.Flags} {n : Int} {v1 v1' : S.Term} {v2 v2' : S.Term}
  (h_v1 : S.Refines v1 v1')
  (h_v2 : S.Refines v2 v2') :
  S.Refines (WordMod.Word.add.spec f n v1 v2) (O.word_add f n v1' v2') :=
  Kanon.Sem.Refines.trans (by simp only [kanon_spec]; kanon_congr) (hO.word_add f n v1' v2')

theorem lift_word_round (hO : O.Sound) {m : CfgMod.Rounding} {n : Int} {v v' : S.Term}
  (h_v : S.Refines v v') :
  S.Refines (WordMod.Word.round.spec m n v) (O.word_round m n v') :=
  Kanon.Sem.Refines.trans (by simp only [kanon_spec]; kanon_congr) (hO.word_round m n v')

theorem lift_word_choose (hO : O.Sound) {g g' : S.Term} {a a' : S.Term} {b b' : S.Term}
  (h_g : S.Refines g g')
  (h_a : S.Refines a a')
  (h_b : S.Refines b b') :
  S.Refines (WordMod.Word.choose.spec g a b) (O.word_choose g' a' b') :=
  Kanon.Sem.Refines.trans (by simp only [kanon_spec]; kanon_congr) (hO.word_choose g' a' b')

theorem lift_word_double (hO : O.Sound) {n : Int} {v v' : S.Term}
  (h_v : S.Refines v v') :
  S.Refines (WordMod.Word.double.spec n v) (O.word_double n v') :=
  Kanon.Sem.Refines.trans (by simp only [kanon_spec, WordMod.Word.twice]; kanon_congr) (hO.word_double n v')

end Lib

def Word.add.r_lits.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [WordMod.Lang S] [KanonBool.Typed S] [WordMod.Typed S] (O : Ops S), O.Sound →
  ∀ (f : CfgMod.Flags) (n : Int) (x : Int) (w__2 : Int) (t__3 : S.Ty) (y : Int) (w__5 : Int) (t__6 : S.Ty),
  S.Refines (WordMod.Word.add.spec f n (WordMod.mk (.Wd x w__2) t__3) (WordMod.mk (.Wd y w__5) t__6))
  ((WordMod.mk (.Wd (O.word_wsum x y) n) (WordMod.sort (.TWord n))))

def Word.add.r_plain.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [WordMod.Lang S] [KanonBool.Typed S] [WordMod.Typed S] (O : Ops S), O.Sound →
  ∀ (f : CfgMod.Flags) (n : Int) (v1 : S.Term) (v2 : S.Term),
  ((decide ((WordMod.Word.left_lit v1) = (0 : Int))) && (! f.strict)) = true →
  S.Refines (WordMod.Word.add.spec f n v1 v2)
  ((WordMod.mk (.WAdd WordMod.Word.plain n v1 v2) (WordMod.sort (.TWord n))))

def Word.add.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [WordMod.Lang S] [KanonBool.Typed S] [WordMod.Typed S] (O : Ops S), O.Sound →
  ∀ (f : CfgMod.Flags) (n : Int) (v1 : S.Term) (v2 : S.Term),
  S.Refines (WordMod.Word.add.spec f n v1 v2)
  ((WordMod.mk (.WAdd f n v1 v2) (WordMod.sort (.TWord n))))

def Word.round.r_check.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [WordMod.Lang S] [KanonBool.Typed S] [WordMod.Typed S] (O : Ops S), O.Sound →
  ∀ (m : CfgMod.Rounding) (n : Int) (z : Int) (w__2 : Int) (t__3 : S.Ty),
  S.Refines (WordMod.Word.round.spec m n (WordMod.mk (.Wd z w__2) t__3))
  (((firstSome [(match (O.word_wcheck z) with
                  | (some _) =>
                  some ((WordMod.mk (.WRound m n (WordMod.mk (.Wd z w__2) t__3)) (WordMod.sort (.TWord n))))
                  | _ => none),
     (match (O.word_wcheck z) with
       | none =>
       some ((WordMod.mk (.WRound m n (WordMod.mk (.Wd z w__2) t__3)) (WordMod.sort (.TWord n))))
       | _ => none)]).getD
     Inhabited.default))

def Word.round.r_keep.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [WordMod.Lang S] [KanonBool.Typed S] [WordMod.Typed S] (O : Ops S), O.Sound →
  ∀ (m : CfgMod.Rounding) (n : Int) (v : S.Term),
  (((WordMod.Word.is_down m) || (decide (m = CfgMod.Rounding.Up))) && (WordMod.Word.is_word (S.ty v))) = true →
  S.Refines (WordMod.Word.round.spec m n v)
  (v)

def Word.round.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [WordMod.Lang S] [KanonBool.Typed S] [WordMod.Typed S] (O : Ops S), O.Sound →
  ∀ (m : CfgMod.Rounding) (n : Int) (v : S.Term),
  S.Refines (WordMod.Word.round.spec m n v)
  ((WordMod.mk (.WRound m n v) (WordMod.sort (.TWord n))))

def Word.choose.r_main.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [WordMod.Lang S] [KanonBool.Typed S] [WordMod.Typed S] (O : Ops S), O.Sound →
  ∀ (g : S.Term) (a : S.Term) (b : S.Term),
  S.Refines (WordMod.Word.choose.spec g a b)
  ((O.bool_ite g a b))

def Word.double.r_main.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [WordMod.Lang S] [KanonBool.Typed S] [WordMod.Typed S] (O : Ops S), O.Sound →
  ∀ (n : Int) (v : S.Term),
  S.Refines (WordMod.Word.double.spec n v)
  ((WordMod.mk (.WAdd WordMod.Word.plain n v v) (WordMod.sort (.TWord n))))

end WordMod
