-- Generated by kanon from neg.knl, neg.kn. Do not edit.
import NegMod.Statements
import KanonBool.Soundness
import NumMod.Soundness

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace NegMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Num.add.r_negself.main.ok : Num.add.r_negself.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Num.add.r_negself.main)

set_option maxHeartbeats 400000 in
theorem Num.add.r_negself.swap.ok : Num.add.r_negself.swap.Stmt := by
  intro S _ _ _ _ _ O hO v2 b t__4 hg
  refine Kanon.Sem.Refines.trans ?_
    (Num.add.r_negself.main.ok O hO v2 b t__4 hg)
  simp only [NumMod.Num.add.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (NumMod.Add.comm.ok ..) ?_
  kanon_congr

theorem Num.add.r_negself.sound {S : Kanon.Sem} [KanonBool.Lang S] [NumMod.Lang S] [NegMod.Lang S] [KanonBool.Typed S] [NumMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Num.add.r_negself O v1 v2 = some res) : S.Refines (NumMod.Num.add.spec v1 v2) res := by
  unfold Num.add.r_negself at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Num.add.r_negself.main.ok O hO)
  · kanon_arm h (Num.add.r_negself.swap.ok O hO)

set_option maxHeartbeats 400000 in
theorem Neg.neg.r_lit.main.ok : Neg.neg.r_lit.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Neg.neg.r_lit.main)

set_option maxHeartbeats 400000 in
theorem Neg.neg.r_neg.main.ok : Neg.neg.r_neg.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Neg.neg.r_neg.main)

set_option maxHeartbeats 400000 in
theorem Neg.neg.r_default.main.ok : Neg.neg.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Neg.neg.r_default.main)

theorem Neg.neg.r_lit.sound {S : Kanon.Sem} [KanonBool.Lang S] [NumMod.Lang S] [NegMod.Lang S] [KanonBool.Typed S] [NumMod.Typed S] (O : Ops S) (hO : O.Sound) (v : S.Term) (res : S.Term)
    (h : Neg.neg.r_lit O v = some res) : S.Refines (NegMod.Neg.neg.spec v) res := by
  unfold Neg.neg.r_lit at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Neg.neg.r_lit.main.ok O hO)

theorem Neg.neg.r_neg.sound {S : Kanon.Sem} [KanonBool.Lang S] [NumMod.Lang S] [NegMod.Lang S] [KanonBool.Typed S] [NumMod.Typed S] (O : Ops S) (hO : O.Sound) (v : S.Term) (res : S.Term)
    (h : Neg.neg.r_neg O v = some res) : S.Refines (NegMod.Neg.neg.spec v) res := by
  unfold Neg.neg.r_neg at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Neg.neg.r_neg.main.ok O hO)

theorem Neg.neg.r_default.sound {S : Kanon.Sem} [KanonBool.Lang S] [NumMod.Lang S] [NegMod.Lang S] [KanonBool.Typed S] [NumMod.Typed S] (O : Ops S) (hO : O.Sound) (v : S.Term) (res : S.Term)
    (h : Neg.neg.r_default O v = some res) : S.Refines (NegMod.Neg.neg.spec v) res := by
  unfold Neg.neg.r_default at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Neg.neg.r_default.main.ok O hO)

end NegMod
