-- Generated by kanon from neg.knl, neg.kn. Do not edit.
import NegMod.Model
import KanonCore.Proof
import NumMod.Statements

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace NegMod

open Classical Kanon

namespace Lib

variable {S : Kanon.Sem} [KanonBool.Lang S] [NumMod.Lang S] [NegMod.Lang S] [KanonBool.Typed S] [NumMod.Typed S] {O : Ops S}

theorem lift_bool_and_ (hO : O.Sound) {v1 v1' : S.Term} {v2 v2' : S.Term}
  (h_v1 : S.Refines v1 v1')
  (h_v2 : S.Refines v2 v2') :
  S.Refines (KanonBool.Bool.and_.spec v1 v2) (O.bool_and_ v1' v2') :=
  KanonBool.Lib.lift_bool_and_ (O := O.toNumOps.toBoolOps) hO.toNumSound.toBoolSound h_v1 h_v2

theorem lift_bool_or_ (hO : O.Sound) {v1 v1' : S.Term} {v2 v2' : S.Term}
  (h_v1 : S.Refines v1 v1')
  (h_v2 : S.Refines v2 v2') :
  S.Refines (KanonBool.Bool.or_.spec v1 v2) (O.bool_or_ v1' v2') :=
  KanonBool.Lib.lift_bool_or_ (O := O.toNumOps.toBoolOps) hO.toNumSound.toBoolSound h_v1 h_v2

theorem lift_bool_not_ (hO : O.Sound) {sv sv' : S.Term}
  (h_sv : S.Refines sv sv') :
  S.Refines (KanonBool.Bool.not_.spec sv) (O.bool_not_ sv') :=
  KanonBool.Lib.lift_bool_not_ (O := O.toNumOps.toBoolOps) hO.toNumSound.toBoolSound h_sv

theorem lift_bool_ite (hO : O.Sound) {guard guard' : S.Term} {if_ if_' : S.Term} {else_ else_' : S.Term}
  (h_guard : S.Refines guard guard')
  (h_if_ : S.Refines if_ if_')
  (h_else_ : S.Refines else_ else_') :
  S.Refines (KanonBool.Bool.ite.spec guard if_ else_) (O.bool_ite guard' if_' else_') :=
  KanonBool.Lib.lift_bool_ite (O := O.toNumOps.toBoolOps) hO.toNumSound.toBoolSound h_guard h_if_ h_else_

theorem lift_bool_eq (hO : O.Sound) {v1 v1' : S.Term} {v2 v2' : S.Term}
  (h_v1 : S.Refines v1 v1')
  (h_v2 : S.Refines v2 v2') :
  S.Refines (KanonBool.Bool.eq.spec v1 v2) (O.bool_eq v1' v2') :=
  KanonBool.Lib.lift_bool_eq (O := O.toNumOps.toBoolOps) hO.toNumSound.toBoolSound h_v1 h_v2

theorem lift_bool_eq_untyped (hO : O.Sound) {v1 v1' : S.Term} {v2 v2' : S.Term}
  (h_v1 : S.Refines v1 v1')
  (h_v2 : S.Refines v2 v2') :
  S.Refines (KanonBool.Bool.eq_untyped.spec v1 v2) (O.bool_eq_untyped v1' v2') :=
  KanonBool.Lib.lift_bool_eq_untyped (O := O.toNumOps.toBoolOps) hO.toNumSound.toBoolSound h_v1 h_v2

theorem lift_bool_distinct (hO : O.Sound) {l : (List S.Term)} :
  S.Refines (KanonBool.Bool.distinct.spec l) (O.bool_distinct l) :=
  KanonBool.Lib.lift_bool_distinct (O := O.toNumOps.toBoolOps) hO.toNumSound.toBoolSound

theorem lift_num_add (hO : O.Sound) {v1 v1' : S.Term} {v2 v2' : S.Term}
  (h_v1 : S.Refines v1 v1')
  (h_v2 : S.Refines v2 v2') :
  S.Refines (NumMod.Num.add.spec v1 v2) (O.num_add v1' v2') :=
  NumMod.Lib.lift_num_add (O := O.toNumOps) hO.toNumSound h_v1 h_v2

theorem lift_num_less (hO : O.Sound) {v1 v1' : S.Term} {v2 v2' : S.Term}
  (h_v1 : S.Refines v1 v1')
  (h_v2 : S.Refines v2 v2') :
  S.Refines (NumMod.Num.less.spec v1 v2) (O.num_less v1' v2') :=
  NumMod.Lib.lift_num_less (O := O.toNumOps) hO.toNumSound h_v1 h_v2

theorem lift_num_max (hO : O.Sound) {v1 v1' : S.Term} {v2 v2' : S.Term}
  (h_v1 : S.Refines v1 v1')
  (h_v2 : S.Refines v2 v2') :
  S.Refines (NumMod.Num.max.spec v1 v2) (O.num_max v1' v2') :=
  NumMod.Lib.lift_num_max (O := O.toNumOps) hO.toNumSound h_v1 h_v2

theorem lift_neg_neg (hO : O.Sound) {v v' : S.Term}
  (h_v : S.Refines v v') :
  S.Refines (NegMod.Neg.neg.spec v) (O.neg_neg v') :=
  Kanon.Sem.Refines.trans (by simp only [kanon_spec]; kanon_congr) (hO.neg_neg v')

end Lib

def Num.add.r_negself.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [NumMod.Lang S] [NegMod.Lang S] [KanonBool.Typed S] [NumMod.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (b : S.Term) (t__4 : S.Ty),
  (decide (v1 = b)) = true →
  S.Refines (NumMod.Num.add.spec v1 (NegMod.mk (.Neg b) t__4))
  ((NumMod.mk (.Num (0 : Int)) (NumMod.sort .TNum)))

def Num.add.r_negself.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [NumMod.Lang S] [NegMod.Lang S] [KanonBool.Typed S] [NumMod.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (b : S.Term) (t__4 : S.Ty),
  (decide (v2 = b)) = true →
  S.Refines (NumMod.Num.add.spec (NegMod.mk (.Neg b) t__4) v2)
  ((NumMod.mk (.Num (0 : Int)) (NumMod.sort .TNum)))

def Neg.neg.r_lit.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [NumMod.Lang S] [NegMod.Lang S] [KanonBool.Typed S] [NumMod.Typed S] (O : Ops S), O.Sound →
  ∀ (x : Int) (t__2 : S.Ty),
  S.Refines (NegMod.Neg.neg.spec (NumMod.mk (.Num x) t__2))
  ((NumMod.mk (.Num ((0 : Int) - x)) (NumMod.sort .TNum)))

def Neg.neg.r_neg.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [NumMod.Lang S] [NegMod.Lang S] [KanonBool.Typed S] [NumMod.Typed S] (O : Ops S), O.Sound →
  ∀ (a : S.Term) (t__3 : S.Ty),
  S.Refines (NegMod.Neg.neg.spec (NegMod.mk (.Neg a) t__3))
  (a)

def Neg.neg.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [NumMod.Lang S] [NegMod.Lang S] [KanonBool.Typed S] [NumMod.Typed S] (O : Ops S), O.Sound →
  ∀ (v : S.Term),
  S.Refines (NegMod.Neg.neg.spec v)
  ((NegMod.mk (.Neg v) (NumMod.sort .TNum)))

end NegMod
