kanon ocaml-all DIR writes the OCaml of a language in DIR/Generated/: what
the backends ocaml-types, ocaml, ocaml-typed and ocaml-tests print. Their files
are named after the OCaml modules that the language declares, with
[@@@ocaml_types "M"] and [@@@ocaml_rules "M"]; typed.ml is only written for a
language that has [@@@ocaml_rules], and tests.ml opens the module of the rules.

  $ kanon ocaml-all out lang.knl
  $ ls out out/Generated
  out:
  Generated
  
  out/Generated:
  mini_rules.ml
  mini_types.ml
  tests.ml
  typed.ml
  $ kanon ocaml-types lang.knl | diff - out/Generated/mini_types.ml
  $ kanon ocaml lang.knl | diff - out/Generated/mini_rules.ml
  $ kanon ocaml-typed lang.knl | diff - out/Generated/typed.ml
  $ kanon ocaml-tests lang.knl | diff - out/Generated/tests.ml
  3a4,5
  > open Mini_rules
  > 
  [1]
  $ head -n 8 out/Generated/tests.ml
  (* Generated by kanon from int.kn. Do not edit. *)
  
  [@@@warning "-a+11"]
  
  open Mini_types
  
  open Mini_rules
  
  $ head -n 1 out/Generated/*.ml | grep -c 'Generated by kanon .* Do not edit'
  4

Without those declarations, the files are types.ml and rules.ml, and there is no
typed.ml (ocaml-typed needs the module of the rules).

  $ kanon ocaml-all plain-out plain.knl
  $ ls plain-out/Generated
  rules.ml
  tests.ml
  types.ml
  $ grep -c '^open Rules' plain-out/Generated/tests.ml
  1

Everything in Generated is generated, and nothing else is written. A file that
is beside Generated, or in the Generated directory of the Lean files of another
directory, is kept.

  $ echo '-- mine' > out/mine.ml
  $ mkdir -p out/Ex/Generated && echo '-- lean' > out/Ex/Generated/Node.lean
  $ kanon ocaml-all out lang.knl
  $ cat out/mine.ml out/Ex/Generated/Node.lean
  -- mine
  -- lean

With --check, kanon ocaml-all checks that Generated has exactly the files that it
would write.

  $ kanon ocaml-all --check out lang.knl

A missing file, a file that was edited, and any other file, are reported.

  $ rm out/Generated/typed.ml
  $ echo '(* edited *)' >> out/Generated/tests.ml
  $ echo '(* Generated by kanon from int.kn. Do not edit. *)' > out/Generated/old.ml
  $ mkdir out/Generated/sub && echo x > out/Generated/sub/notes.txt
  $ kanon ocaml-all --check out lang.knl
  kanon: out/Generated/tests.ml is not up to date (run kanon ocaml-all)
  kanon: out/Generated/typed.ml is missing (run kanon ocaml-all)
  kanon: out/Generated/old.ml is no longer generated (run kanon ocaml-all)
  kanon: out/Generated/sub/notes.txt is no longer generated (run kanon ocaml-all)
  [1]

kanon ocaml-all clears Generated, and writes it again.

  $ kanon ocaml-all out lang.knl
  $ kanon ocaml-all --check out lang.knl
  $ ls out out/Generated
  out:
  Ex
  Generated
  mine.ml
  
  out/Generated:
  mini_rules.ml
  mini_types.ml
  tests.ml
  typed.ml

It does not delete through a symbolic link, nor a file, and it needs DIR to be a
directory.

  $ mkdir elsewhere && echo precious > elsewhere/file
  $ rm -r out/Generated && ln -s ../elsewhere out/Generated
  $ kanon ocaml-all out lang.knl
  kanon: out/Generated is a symbolic link: kanon does not follow it
  [1]
  $ cat elsewhere/file
  precious
  $ rm out/Generated && echo x > out/Generated
  $ kanon ocaml-all out lang.knl
  kanon: out/Generated is not a directory
  [1]
  $ echo x > afile
  $ kanon ocaml-all afile lang.knl
  kanon: afile is not a directory
  [1]

The files have different names:

  $ sed 's/Mini_rules/Tests/' lang.knl > lang2.knl
  $ kanon ocaml-all out2 lang2.knl
  kanon: two OCaml modules write the same file (mini_types.ml, tests.ml, typed.ml, tests.ml)
  [1]
  $ test -e out2 || echo nothing written
  nothing written
  $ sed 's/Mini_rules/A.b/' lang.knl > lang3.knl
  $ kanon ocaml-all out2 lang3.knl
  kanon: the OCaml module "A.b" has no file: it is not a module name
  [1]
