-- Generated by kanon from bool.kn, num.kn, neg.kn. Do not edit.
import L2.Statements
import L2.Lang
import NumMod.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L2

open Classical Kanon

@[kanon_comm_lemma] theorem Op2.Add.comm.ok : Op2.Add.comm.Stmt :=
  fun a b t => NumMod.Add.comm.ok (S := sem) numSyntax a b t

end L2
