-- Generated by kanon from int.kn. Do not edit.
import DivisionExample.Statements.Int.div
import DivisionExample.Soundness.Laws
import DivisionExample.Proofs.Int.div

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace DivisionExample

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Int.div.r_self.main.ok : Int.div.r_self.main.Stmt := kanon_proof% Int.div.r_self.main

theorem Int.div.r_self.proof : Int.div.r_self.Stmt := by
  intro O hO v1 v2 res hs_v2 h
  simp only [Int.div.r_self] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Int.div.r_self.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Int.div.r_default.main.ok : Int.div.r_default.main.Stmt := kanon_proof% Int.div.r_default.main

theorem Int.div.r_default.proof : Int.div.r_default.Stmt := by
  intro O hO v1 v2 res hs_v2 h
  simp only [Int.div.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Int.div.r_default.main.ok O hO)

theorem Int.div.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) (hs_v2 : Nonzero v2) :
  Refines (Int.div.spec v1 v2) (Int.div.step O v1 v2) := by
  unfold Int.div.step
  refine Refinement.firstSome_cons (fun res h => Int.div.r_self.proof O hO v1 v2 res hs_v2 h) ?_
  refine Refinement.firstSome_cons (fun res h => Int.div.r_default.proof O hO v1 v2 res hs_v2 h) ?_
  exact Refinement.firstSome_nil

end DivisionExample
