-- Generated by kanon from int.knl, int.kn. Do not edit.
import IntMod.Statements
import KanonBool.Soundness

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace IntMod

open Classical Kanon

set_option maxHeartbeats 400000 in
@[kanon_comm_lemma] theorem Plus.comm.ok : Plus.comm.Stmt :=
  no_implicit_lambda% (kanon_proof% Plus.comm)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_ints.main.ok : Bool.eq.r_ints.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_ints.main)

theorem Bool.eq.r_ints.sound {S : Kanon.Sem} [KanonBool.Lang S] [IntMod.Lang S] [KanonBool.Typed S] [IntMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_ints O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  simp only [Bool.eq.r_ints] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_ints.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Int.plus.r_lits.main.ok : Int.plus.r_lits.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Int.plus.r_lits.main)

set_option maxHeartbeats 400000 in
theorem Int.plus.r_unit_zero.main.ok : Int.plus.r_unit_zero.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Int.plus.r_unit_zero.main)

set_option maxHeartbeats 400000 in
theorem Int.plus.r_unit_zero.swap.ok : Int.plus.r_unit_zero.swap.Stmt := by
  intro S _ _ _ _ O hO v2 kanon__2 t__3 hg
  refine Kanon.Sem.Refines.trans ?_
    (Int.plus.r_unit_zero.main.ok O hO v2 kanon__2 t__3 hg)
  simp only [IntMod.Int.plus.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (IntMod.Plus.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Int.plus.r_default.main.ok : Int.plus.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Int.plus.r_default.main)

theorem Int.plus.r_lits.sound {S : Kanon.Sem} [KanonBool.Lang S] [IntMod.Lang S] [KanonBool.Typed S] [IntMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Int.plus.r_lits O v1 v2 = some res) : S.Refines (IntMod.Int.plus.spec v1 v2) res := by
  simp only [Int.plus.r_lits] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Int.plus.r_lits.main.ok O hO)

theorem Int.plus.r_unit_zero.sound {S : Kanon.Sem} [KanonBool.Lang S] [IntMod.Lang S] [KanonBool.Typed S] [IntMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Int.plus.r_unit_zero O v1 v2 = some res) : S.Refines (IntMod.Int.plus.spec v1 v2) res := by
  simp only [Int.plus.r_unit_zero] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Int.plus.r_unit_zero.main.ok O hO)
  · kanon_arm h (Int.plus.r_unit_zero.swap.ok O hO)

theorem Int.plus.r_default.sound {S : Kanon.Sem} [KanonBool.Lang S] [IntMod.Lang S] [KanonBool.Typed S] [IntMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Int.plus.r_default O v1 v2 = some res) : S.Refines (IntMod.Int.plus.spec v1 v2) res := by
  simp only [Int.plus.r_default] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Int.plus.r_default.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Int.int_lt.r_lits.main.ok : Int.int_lt.r_lits.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Int.int_lt.r_lits.main)

set_option maxHeartbeats 400000 in
theorem Int.int_lt.r_same.main.ok : Int.int_lt.r_same.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Int.int_lt.r_same.main)

set_option maxHeartbeats 400000 in
theorem Int.int_lt.r_default.main.ok : Int.int_lt.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Int.int_lt.r_default.main)

theorem Int.int_lt.r_lits.sound {S : Kanon.Sem} [KanonBool.Lang S] [IntMod.Lang S] [KanonBool.Typed S] [IntMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Int.int_lt.r_lits O v1 v2 = some res) : S.Refines (IntMod.Int.int_lt.spec v1 v2) res := by
  simp only [Int.int_lt.r_lits] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Int.int_lt.r_lits.main.ok O hO)

theorem Int.int_lt.r_same.sound {S : Kanon.Sem} [KanonBool.Lang S] [IntMod.Lang S] [KanonBool.Typed S] [IntMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Int.int_lt.r_same O v1 v2 = some res) : S.Refines (IntMod.Int.int_lt.spec v1 v2) res := by
  simp only [Int.int_lt.r_same] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Int.int_lt.r_same.main.ok O hO)

theorem Int.int_lt.r_default.sound {S : Kanon.Sem} [KanonBool.Lang S] [IntMod.Lang S] [KanonBool.Typed S] [IntMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Int.int_lt.r_default O v1 v2 = some res) : S.Refines (IntMod.Int.int_lt.spec v1 v2) res := by
  simp only [Int.int_lt.r_default] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Int.int_lt.r_default.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Bool.sure_neq.c1.ok : Bool.sure_neq.c1.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.sure_neq.c1)

end IntMod
