-- Generated by kanon from l4.knl, bool.knl, word.knl, cfg.knl. Do not edit.

import CfgMod.Types

namespace L4

inductive Op1 where
  | Not
  /-- A word, rounded. -/
  | WRound : CfgMod.Rounding → Int → Op1
  /-- A word, widened by `k` bits. -/
  | WExt : Int → Op1
  deriving DecidableEq, Repr, Inhabited

inductive Op2 where
  | And
  | Or
  | Eq
  /-- The sum of two words of width `n`. -/
  | WAdd : CfgMod.Flags → Int → Op2
  deriving DecidableEq, Repr, Inhabited

/-- The operators whose operands commute (`[@comm]`). -/
def Op2.Comm : Op2 → Prop
  | .And | .Or | .Eq => True
  | _ => False

inductive Op3 where
  | Ite
  deriving DecidableEq, Repr, Inhabited

inductive OpN where
  | Distinct
  deriving DecidableEq, Repr, Inhabited

inductive Ty where
  | TBool
  /-- Integers of a width. -/
  | TWord : Int → Ty
  deriving DecidableEq, Repr, Inhabited

end L4
