-- Generated by kanon from bool.kn, num.kn, neg.kn, even.kn, mix.kn. Do not edit.
import L3.Model.Bool.and_
import L3.Model.Bool.or_
import L3.Model.Bool.not_
import L3.Model.Bool.ite
import L3.Model.Bool.eq
import L3.Model.Bool.eq_untyped
import L3.Model.Bool.distinct
import L3.Model.Num.add
import L3.Model.Num.less
import L3.Model.Num.max
import L3.Model.Neg.neg
import L3.Model.Even.rem2

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L3

open Classical Kanon

def opsStep (O : Ops) : Ops :=
  { orc := O.orc,
    bool_and_ := Bool.and_.step O,
    bool_or_ := Bool.or_.step O,
    bool_not_ := Bool.not_.step O,
    bool_ite := Bool.ite.step O,
    bool_eq := Bool.eq.step O,
    bool_eq_untyped := Bool.eq_untyped.step O,
    bool_distinct := Bool.distinct.step O,
    num_add := Num.add.step O,
    num_less := Num.less.step O,
    num_max := Num.max.step O,
    neg_neg := Neg.neg.step O,
    even_rem2 := Even.rem2.step O }

def opsN (orc : Oracle) : Nat → Ops
  | 0 => opsRaw orc
  | n + 1 => opsStep (opsN orc n)

end L3
