-- Generated by kanon from bool.kn, num.kn, neg.kn, even.kn, mix.kn. Do not edit.
import L3.Signatures

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L3

open Classical Kanon

/-- The primitives that the model is parameterised by. -/
structure Oracle where
  tag_le : Term → Term → Bool
  sort_by_tag : (List Term) → (List Term)

/-- The rule functions, as used by the rules. -/
structure Ops where
  orc : Oracle
  bool_and_ : Term → Term → Term
  bool_or_ : Term → Term → Term
  bool_not_ : Term → Term
  bool_ite : Term → Term → Term → Term
  bool_eq : Term → Term → Term
  bool_eq_untyped : Term → Term → Term
  bool_distinct : (List Term) → Term
  num_add : Term → Term → Term
  num_less : Term → Term → Term
  num_max : Term → Term → Term
  neg_neg : Term → Term
  even_rem2 : Term → Term

def Bool.and_.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.And v1 v2) Ty.TBool)

def Bool.or_.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.Or v1 v2) Ty.TBool)

def Bool.not_.spec (sv : Term) : Term :=
  (Term.mk (Kind.Op1 Op1.Not sv) Ty.TBool)

def Bool.ite.spec (guard : Term) (if_ : Term) (else_ : Term) : Term :=
  (Term.mk (Kind.Op3 Op3.Ite guard if_ else_) (ty if_))

def Bool.eq.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.Eq v1 v2) Ty.TBool)

def Bool.eq_untyped.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.Eq v1 v2) Ty.TBool)

def Bool.distinct.spec (l : (List Term)) : Term :=
  (Term.mk (Kind.OpN OpN.Distinct l) Ty.TBool)

def Num.add.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.Add v1 v2) Ty.TNum)

def Num.less.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.Lt v1 v2) Ty.TBool)

def Num.max.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.Max v1 v2) Ty.TNum)

def Neg.neg.spec (v : Term) : Term :=
  (Term.mk (Kind.Op1 Op1.Neg v) Ty.TNum)

def Even.rem2.spec (v : Term) : Term :=
  (Term.mk (Kind.Op1 Op1.Rem2 v) Ty.TNum)

def opsRaw (orc : Oracle) : Ops :=
  { orc := orc,
    bool_and_ := fun v1 v2 => Bool.and_.spec v1 v2,
    bool_or_ := fun v1 v2 => Bool.or_.spec v1 v2,
    bool_not_ := fun sv => Bool.not_.spec sv,
    bool_ite := fun guard if_ else_ => Bool.ite.spec guard if_ else_,
    bool_eq := fun v1 v2 => Bool.eq.spec v1 v2,
    bool_eq_untyped := fun v1 v2 => Bool.eq_untyped.spec v1 v2,
    bool_distinct := fun l => Bool.distinct.spec l,
    num_add := fun v1 v2 => Num.add.spec v1 v2,
    num_less := fun v1 v2 => Num.less.spec v1 v2,
    num_max := fun v1 v2 => Num.max.spec v1 v2,
    neg_neg := fun v => Neg.neg.spec v,
    even_rem2 := fun v => Even.rem2.spec v }

end L3
