-- Generated by kanon from bool.kn, num.kn, neg.kn, even.kn, mix.kn. Do not edit.
import L3.Model
import L3.Soundness.Laws
import L3.Soundness.Bool.and_
import L3.Soundness.Bool.or_
import L3.Soundness.Bool.not_
import L3.Soundness.Bool.ite
import L3.Soundness.Bool.eq
import L3.Soundness.Bool.eq_untyped
import L3.Soundness.Bool.distinct
import L3.Soundness.Num.add
import L3.Soundness.Num.less
import L3.Soundness.Num.max
import L3.Soundness.Neg.neg
import L3.Soundness.Even.rem2

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L3

open Classical Kanon

/-- Every rule function refines its spec, for any amount of fuel. -/
theorem opsN_sound (orc : Oracle) (h : orc.Compat) :
  ∀ n, (opsN orc n).Sound
  | 0 =>
    { orc := h,
      bool_and_ := fun v1 v2 => Refinement.refl,
      bool_or_ := fun v1 v2 => Refinement.refl,
      bool_not_ := fun sv => Refinement.refl,
      bool_ite := fun guard if_ else_ => Refinement.refl,
      bool_eq := fun v1 v2 => Refinement.refl,
      bool_eq_untyped := fun v1 v2 => Refinement.refl,
      bool_distinct := fun l => Refinement.refl,
      num_add := fun v1 v2 => Refinement.refl,
      num_less := fun v1 v2 => Refinement.refl,
      num_max := fun v1 v2 => Refinement.refl,
      neg_neg := fun v => Refinement.refl,
      even_rem2 := fun v => Refinement.refl }
  | n + 1 =>
    have hO := opsN_sound orc h n
    { orc := hO.orc,
      bool_and_ := Bool.and_.step_sound _ hO,
      bool_or_ := Bool.or_.step_sound _ hO,
      bool_not_ := Bool.not_.step_sound _ hO,
      bool_ite := Bool.ite.step_sound _ hO,
      bool_eq := Bool.eq.step_sound _ hO,
      bool_eq_untyped := Bool.eq_untyped.step_sound _ hO,
      bool_distinct := Bool.distinct.step_sound _ hO,
      num_add := Num.add.step_sound _ hO,
      num_less := Num.less.step_sound _ hO,
      num_max := Num.max.step_sound _ hO,
      neg_neg := Neg.neg.step_sound _ hO,
      even_rem2 := Even.rem2.step_sound _ hO }

end L3
