-- Generated by kanon from bool.kn, num.kn, neg.kn, even.kn, mix.kn. Do not edit.
import KanonCore.Attr
import L3.Semantics

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L3

open Classical Kanon

attribute [kanon_spec]
  Bool.and_.spec
  Bool.or_.spec
  Bool.not_.spec
  Bool.ite.spec
  Bool.eq.spec
  Bool.eq_untyped.spec
  Bool.distinct.spec
  Num.add.spec
  Num.less.spec
  Num.max.spec
  Neg.neg.spec
  Even.rem2.spec

/-- Every rule function refines its spec. -/
structure Ops.Sound (O : Ops) : Prop where
  orc : O.orc.Compat
  bool_and_ : ∀ (v1 : Term) (v2 : Term), Refines (Bool.and_.spec v1 v2) (O.bool_and_ v1 v2)
  bool_or_ : ∀ (v1 : Term) (v2 : Term), Refines (Bool.or_.spec v1 v2) (O.bool_or_ v1 v2)
  bool_not_ : ∀ (sv : Term), Refines (Bool.not_.spec sv) (O.bool_not_ sv)
  bool_ite : ∀ (guard : Term) (if_ : Term) (else_ : Term), Refines (Bool.ite.spec guard if_ else_) (O.bool_ite guard if_ else_)
  bool_eq : ∀ (v1 : Term) (v2 : Term), Refines (Bool.eq.spec v1 v2) (O.bool_eq v1 v2)
  bool_eq_untyped : ∀ (v1 : Term) (v2 : Term), Refines (Bool.eq_untyped.spec v1 v2) (O.bool_eq_untyped v1 v2)
  bool_distinct : ∀ (l : (List Term)), Refines (Bool.distinct.spec l) (O.bool_distinct l)
  num_add : ∀ (v1 : Term) (v2 : Term), Refines (Num.add.spec v1 v2) (O.num_add v1 v2)
  num_less : ∀ (v1 : Term) (v2 : Term), Refines (Num.less.spec v1 v2) (O.num_less v1 v2)
  num_max : ∀ (v1 : Term) (v2 : Term), Refines (Num.max.spec v1 v2) (O.num_max v1 v2)
  neg_neg : ∀ (v : Term), Refines (Neg.neg.spec v) (O.neg_neg v)
  even_rem2 : ∀ (v : Term), Refines (Even.rem2.spec v) (O.even_rem2 v)

/-- The operands of `Op2.And` commute. -/
def Op2.And.comm.Stmt : Prop :=
  ∀ (a b : Term) (t : Ty),
  Refines (Term.mk (Kind.Op2 Op2.And a b) t)
  (Term.mk (Kind.Op2 Op2.And b a) t)

/-- The operands of `Op2.Or` commute. -/
def Op2.Or.comm.Stmt : Prop :=
  ∀ (a b : Term) (t : Ty),
  Refines (Term.mk (Kind.Op2 Op2.Or a b) t)
  (Term.mk (Kind.Op2 Op2.Or b a) t)

/-- The operands of `Op2.Eq` commute. -/
def Op2.Eq.comm.Stmt : Prop :=
  ∀ (a b : Term) (t : Ty),
  Refines (Term.mk (Kind.Op2 Op2.Eq a b) t)
  (Term.mk (Kind.Op2 Op2.Eq b a) t)

/-- The operands of `Op2.Add` commute. -/
def Op2.Add.comm.Stmt : Prop :=
  ∀ (a b : Term) (t : Ty),
  Refines (Term.mk (Kind.Op2 Op2.Add a b) t)
  (Term.mk (Kind.Op2 Op2.Add b a) t)

end L3
