-- Generated by kanon from l3.knl, bool.knl, num.knl, neg.knl, even.knl, mix.knl. Do not edit.

namespace L3

inductive Op1 where
  | Not
  | Neg
  /-- The remainder of an even integer by 2. -/
  | Rem2
  deriving DecidableEq, Repr, Inhabited

inductive Op2 where
  | And
  | Or
  | Eq
  | Add
  | Lt
  /-- The maximum of two integers. -/
  | Max
  deriving DecidableEq, Repr, Inhabited

/-- The operators whose operands commute (`[@comm]`). -/
def Op2.Comm : Op2 → Prop
  | .And | .Or | .Eq | .Add => True
  | _ => False

inductive Op3 where
  | Ite
  deriving DecidableEq, Repr, Inhabited

inductive OpN where
  | Distinct
  deriving DecidableEq, Repr, Inhabited

inductive Ty where
  | TBool
  | TNum
  /-- Even integers. -/
  | TEven
  deriving DecidableEq, Repr, Inhabited

end L3
