-- Generated by kanon from bool.kn, word.kn. Do not edit.
import L4.Interface
import CfgMod.Syntax

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L4

open Classical Kanon

/-- The interface of the module `Cfg`: every law holds by definition. -/
def cfgSyntax : CfgMod.Syntax (S := sem) modBase := {}

attribute [kanon_law] cfgSyntax

end L4
