-- Generated by kanon from bool.kn, word.kn. Do not edit.
import L4.Interface
import L4.Interface.Bool
import L4.Interface.Cfg
import L4.Model.Word.is_word
import L4.Model.Word.left_lit
import L4.Model.Word.plain
import L4.Model.Word.is_down
import L4.Model.Word.twice
import WordMod.Syntax

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L4

open Classical Kanon

/-- The interface of the module `Word`: every law holds by definition. -/
def wordSyntax : WordMod.Syntax (S := sem) modBase boolSyntax cfgSyntax where
  TWord := Ty.TWord
  TWord_ne_TBool := by intros; exact nofun
  TWord_inj := by intros; rename_i h; cases h; simp
  asTWord := fun s => match s with | (Ty.TWord x1) => some x1 | _ => none
  asTWord_sort := by intros; rfl
  asTWord_sound := by intro s x1 h; cases s <;> cases h <;> rfl
  WdK := fun x1 n => (Kind.Wd x1 n)
  WT_Wd := by intros; first | exact Iff.rfl | kanon_law
  asWd := fun v => match v with | Term.mk (Kind.Wd x1 n) _ => some (x1, n) | _ => none
  asWd_node := by intros; rfl
  asWd_sound := by intro v x1 n h; dsimp only at h; split at h <;> cases h <;> rfl
  WBlobK := fun x1 x2 => (Kind.WBlob x1 x2)
  WT_WBlob := by intros; first | exact Iff.rfl | kanon_law
  asWBlob := fun v => match v with | Term.mk (Kind.WBlob x1 x2) _ => some (x1, x2) | _ => none
  asWBlob_node := by intros; rfl
  asWBlob_sound := by intro v x1 x2 h; dsimp only at h; split at h <;> cases h <;> rfl
  WAddK := fun x1 n a1 a2 => (Kind.Op2 (Op2.WAdd x1 n) a1 a2)
  WT_WAdd := by intros; first | exact Iff.rfl | kanon_law
  asWAdd := fun v => match v with | Term.mk (Kind.Op2 (Op2.WAdd x1 n) a1 a2) _ => some (x1, n, a1, a2) | _ => none
  asWAdd_node := by intros; rfl
  asWAdd_sound := by intro v x1 n a1 a2 h; dsimp only at h; split at h <;> cases h <;> rfl
  WRoundK := fun x1 n a1 => (Kind.Op1 (Op1.WRound x1 n) a1)
  WT_WRound := by intros; first | exact Iff.rfl | kanon_law
  asWRound := fun v => match v with | Term.mk (Kind.Op1 (Op1.WRound x1 n) a1) _ => some (x1, n, a1) | _ => none
  asWRound_node := by intros; rfl
  asWRound_sound := by intro v x1 n a1 h; dsimp only at h; split at h <;> cases h <;> rfl
  word_is_word := Word.is_word
  word_is_word_eq := by kanon_bridge Word.is_word
  word_left_lit := Word.left_lit
  word_left_lit_eq := by kanon_bridge Word.left_lit
  word_plain := Word.plain
  word_plain_eq := by kanon_bridge Word.plain
  word_is_down := Word.is_down
  word_is_down_eq := by kanon_bridge Word.is_down
  word_twice := Word.twice
  word_twice_eq := by kanon_bridge Word.twice

attribute [kanon_law] wordSyntax

end L4
