-- Generated by kanon from bool.kn, num.kn, neg.kn, even.kn, mix.kn. Do not edit.
import L3.Ops

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L3

open Classical Kanon

def Even.rem2.r_lit (O : Ops) (v : Term) : Option Term :=
  (match v with
    | (Term.mk (Kind.Ev z) _) =>
    (whenSome true ((Term.mk (Kind.Num (0 : Int)) Ty.TNum)))
    | _ => none)

def Even.rem2.r_default (O : Ops) (v : Term) : Option Term :=
  (match v with
    | _ =>
    (whenSome true ((Term.mk (Kind.Op1 Op1.Rem2 v) Ty.TNum))))

def Even.rem2.step (O : Ops) (v : Term) : Term :=
  (firstSome [Even.rem2.r_lit O v, Even.rem2.r_default O v]).getD (Even.rem2.spec v)

end L3
