-- Generated by kanon from bool.kn. Do not edit.
import KanonCore.Generic
import BoolExample.Semantics

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BoolExample

open Classical Kanon

/-- The name of the node of a kind. -/
def kindName : Kind → String
  | (Kind.Var _) => "Var"
  | (Kind.Bool _) => "Bool"
  | (Kind.Op1 Op1.Not _) => "Not"
  | (Kind.Op2 Op2.And _ _) => "And"
  | (Kind.Op2 Op2.Or _ _) => "Or"
  | (Kind.Op2 Op2.Eq _ _) => "Eq"
  | (Kind.Op3 Op3.Ite _ _ _) => "Ite"
  | (Kind.OpN OpN.Distinct _) => "Distinct"

/-- The terms of the language, for the interfaces of its modules. -/
def modBase : Kanon.Base sem where
  Kind := Kind
  node := Term.mk
  ty_node _ _ := rfl
  kindName := kindName

attribute [kanon_law] modBase

end BoolExample
