-- Generated by kanon from bool.kn. Do not edit.
import BoolExample.Model.Bool.and_
import BoolExample.Model.Bool.or_
import BoolExample.Model.Bool.not_
import BoolExample.Model.Bool.ite
import BoolExample.Model.Bool.eq
import BoolExample.Model.Bool.eq_untyped
import BoolExample.Model.Bool.distinct

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BoolExample

open Classical Kanon

def opsStep (O : Ops) : Ops :=
  { orc := O.orc,
    bool_and_ := Bool.and_.step O,
    bool_or_ := Bool.or_.step O,
    bool_not_ := Bool.not_.step O,
    bool_ite := Bool.ite.step O,
    bool_eq := Bool.eq.step O,
    bool_eq_untyped := Bool.eq_untyped.step O,
    bool_distinct := Bool.distinct.step O }

def opsN (orc : Oracle) : Nat → Ops
  | 0 => opsRaw orc
  | n + 1 => opsStep (opsN orc n)

end BoolExample
