-- Generated by kanon from bool.kn. Do not edit.
import BoolExample.Signatures

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BoolExample

open Classical Kanon

/-- The primitives that the model is parameterised by. -/
  structure Oracle where
  tag_le : Term → Term → Bool
  sort_by_tag : (List Term) → (List Term)

def of_bool (b : Bool) : Term :=
  (if b then v_true else v_false)

def sure_neq (a : Term) (b : Term) : Bool :=
  ((! (decide ((ty a) = (ty b)))) || ((firstSome [(match a, b with
                                                    | (Term.mk (Kind.Bool a) _), (Term.mk (Kind.Bool b) _) =>
                                                    some ((! (decide (a = b))))
                                                    | _, _ => none)]).getD
                                       (match a, b with | _, _ => false)))

def at_most_one (l : (List Term)) : Bool :=
  ((firstSome [(match l with | [] => some (true) | _ => none),
    (match l with | (_ :: []) => some (true) | _ => none)]).getD
    (match l with | _ => false))

mutual

def distinct_check_one (a : Term) (rest : (List Term)) : (Option Bool) :=
  ((firstSome [(match rest with | [] => some ((some true)) | _ => none),
    (match rest with
      | (b :: rest) =>
      some ((if (equal a b)
            then (some false)
            else (if (sure_neq a b)
                 then (distinct_check_one a rest)
                 else none)))
      | _ => none)]).getD
    Inhabited.default)
termination_by sizeOf rest
decreasing_by all_goals (simp_wf; omega)

end

mutual

def distinct_check (l : (List Term)) : (Option Bool) :=
  ((firstSome [(match l with | [] => some ((some true)) | _ => none),
    (match l with
      | (a :: rest) =>
      some (((firstSome [(match (distinct_check_one a rest) with
                           | (some true) =>
                           some ((distinct_check rest))
                           | _ => none)]).getD
              (match (distinct_check_one a rest) with | r => r)))
      | _ => none)]).getD
    Inhabited.default)
termination_by sizeOf l
decreasing_by all_goals (simp_wf; omega)

end

/-- The rule functions, as used by the rules. -/
  structure Ops where
  orc : Oracle
  b_and : Term → Term → Term
  b_or : Term → Term → Term
  b_not : Term → Term
  b_ite : Term → Term → Term → Term
  sem_eq : Term → Term → Term
  sem_eq_untyped : Term → Term → Term
  b_distinct : (List Term) → Term

def mk_commut_binop (O : Ops) (op : Binop) (l : Term) (r : Term) : Kind :=
  (if (O.orc.tag_le l r) then (Kind.Binop op l r) else (Kind.Binop op r l))

@[kanon_spec] def b_and.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Binop Binop.And v1 v2) Ty.TBool)

@[kanon_spec] def b_or.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Binop Binop.Or v1 v2) Ty.TBool)

@[kanon_spec] def b_not.spec (sv : Term) : Term :=
  (Term.mk (Kind.Unop Unop.Not sv) Ty.TBool)

@[kanon_spec] def b_ite.spec (guard : Term) (if_ : Term) (else_ : Term) : Term :=
  (Term.mk (Kind.Triop Triop.Ite guard if_ else_) (ty if_))

@[kanon_spec] def sem_eq.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Binop Binop.Eq v1 v2) Ty.TBool)

@[kanon_spec] def sem_eq_untyped.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Binop Binop.Eq v1 v2) Ty.TBool)

@[kanon_spec] def b_distinct.spec (l : (List Term)) : Term :=
  (Term.mk (Kind.Nop Nop.Distinct l) Ty.TBool)

def b_and.r_same (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with | v, kanon__2 => (whenSome (equal v kanon__2) (v)))

def b_and.r_false_ (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Bool false) _), _ =>
    (whenSome true (v_false))
    | _, _ => none)
  <|> (match v1, v2 with
        | _, (Term.mk (Kind.Bool false) _) =>
        (whenSome true (v_false))
        | _, _ => none)

def b_and.r_true_ (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Bool true) _), x =>
    (whenSome true (x))
    | _, _ => none)
  <|> (match v1, v2 with
        | x, (Term.mk (Kind.Bool true) _) =>
        (whenSome true (x))
        | _, _ => none)

def b_and.r_not (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | p, (Term.mk (Kind.Unop Unop.Not kanon__3) _) =>
    (whenSome (equal p kanon__3) (v_false))
    | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Unop Unop.Not kanon__3) _), p =>
        (whenSome (equal p kanon__3) (v_false))
        | _, _ => none)

def b_and.r_and_ (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | x@(Term.mk (Kind.Binop Binop.And a _) _), kanon__7 =>
    (whenSome (equal a kanon__7) (x))
    | _, _ => none)
  <|> (match v1, v2 with
        | x@(Term.mk (Kind.Binop Binop.And _ a) _), kanon__7 =>
        (whenSome (equal a kanon__7) (x))
        | _, _ => none)
  <|> (match v1, v2 with
        | kanon__7, x@(Term.mk (Kind.Binop Binop.And a _) _) =>
        (whenSome (equal a kanon__7) (x))
        | _, _ => none)
  <|> (match v1, v2 with
        | kanon__7, x@(Term.mk (Kind.Binop Binop.And _ a) _) =>
        (whenSome (equal a kanon__7) (x))
        | _, _ => none)

def b_and.r_or_ (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Binop Binop.Or a _) _), kanon__6 =>
    (whenSome (equal a kanon__6) (a))
    | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Binop Binop.Or _ a) _), kanon__6 =>
        (whenSome (equal a kanon__6) (a))
        | _, _ => none)
  <|> (match v1, v2 with
        | kanon__6, (Term.mk (Kind.Binop Binop.Or a _) _) =>
        (whenSome (equal a kanon__6) (a))
        | _, _ => none)
  <|> (match v1, v2 with
        | kanon__6, (Term.mk (Kind.Binop Binop.Or _ a) _) =>
        (whenSome (equal a kanon__6) (a))
        | _, _ => none)

def b_and.r_eq_neq (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Binop Binop.Eq a x) _), (Term.mk (Kind.Binop Binop.Eq kanon__7 y) _) =>
    (whenSome ((equal a kanon__7) && (sure_neq x y)) (v_false))
    | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Binop Binop.Eq a x) _), (Term.mk (Kind.Binop Binop.Eq y kanon__7) _) =>
        (whenSome ((equal a kanon__7) && (sure_neq x y)) (v_false))
        | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Binop Binop.Eq x a) _), (Term.mk (Kind.Binop Binop.Eq kanon__7 y) _) =>
        (whenSome ((equal a kanon__7) && (sure_neq x y)) (v_false))
        | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Binop Binop.Eq x a) _), (Term.mk (Kind.Binop Binop.Eq y kanon__7) _) =>
        (whenSome ((equal a kanon__7) && (sure_neq x y)) (v_false))
        | _, _ => none)

def b_and.r_default (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | _, _ =>
    (whenSome true ((Term.mk (mk_commut_binop O Binop.And v1 v2) Ty.TBool))))

def b_and.step (O : Ops) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [b_and.r_same O v1 v2, b_and.r_false_ O v1 v2, b_and.r_true_ O v1 v2, b_and.r_not O v1 v2, b_and.r_and_ O v1 v2, b_and.r_or_ O v1 v2, b_and.r_eq_neq O v1 v2, b_and.r_default O v1 v2]).getD (b_and.spec v1 v2)

def b_or.r_same (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with | v, kanon__2 => (whenSome (equal v kanon__2) (v)))

def b_or.r_true_ (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Bool true) _), _ =>
    (whenSome true (v_true))
    | _, _ => none)
  <|> (match v1, v2 with
        | _, (Term.mk (Kind.Bool true) _) =>
        (whenSome true (v_true))
        | _, _ => none)

def b_or.r_false_ (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Bool false) _), x =>
    (whenSome true (x))
    | _, _ => none)
  <|> (match v1, v2 with
        | x, (Term.mk (Kind.Bool false) _) =>
        (whenSome true (x))
        | _, _ => none)

def b_or.r_not (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | p, (Term.mk (Kind.Unop Unop.Not kanon__3) _) =>
    (whenSome (equal p kanon__3) (v_true))
    | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Unop Unop.Not kanon__3) _), p =>
        (whenSome (equal p kanon__3) (v_true))
        | _, _ => none)

def b_or.r_or_ (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | x@(Term.mk (Kind.Binop Binop.Or a _) _), kanon__7 =>
    (whenSome (equal a kanon__7) (x))
    | _, _ => none)
  <|> (match v1, v2 with
        | x@(Term.mk (Kind.Binop Binop.Or _ a) _), kanon__7 =>
        (whenSome (equal a kanon__7) (x))
        | _, _ => none)
  <|> (match v1, v2 with
        | kanon__7, x@(Term.mk (Kind.Binop Binop.Or a _) _) =>
        (whenSome (equal a kanon__7) (x))
        | _, _ => none)
  <|> (match v1, v2 with
        | kanon__7, x@(Term.mk (Kind.Binop Binop.Or _ a) _) =>
        (whenSome (equal a kanon__7) (x))
        | _, _ => none)

def b_or.r_and_ (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Binop Binop.And a _) _), kanon__6 =>
    (whenSome (equal a kanon__6) (a))
    | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Binop Binop.And _ a) _), kanon__6 =>
        (whenSome (equal a kanon__6) (a))
        | _, _ => none)
  <|> (match v1, v2 with
        | kanon__6, (Term.mk (Kind.Binop Binop.And a _) _) =>
        (whenSome (equal a kanon__6) (a))
        | _, _ => none)
  <|> (match v1, v2 with
        | kanon__6, (Term.mk (Kind.Binop Binop.And _ a) _) =>
        (whenSome (equal a kanon__6) (a))
        | _, _ => none)

def b_or.r_default (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | _, _ =>
    (whenSome true ((Term.mk (mk_commut_binop O Binop.Or v1 v2) Ty.TBool))))

def b_or.step (O : Ops) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [b_or.r_same O v1 v2, b_or.r_true_ O v1 v2, b_or.r_false_ O v1 v2, b_or.r_not O v1 v2, b_or.r_or_ O v1 v2, b_or.r_and_ O v1 v2, b_or.r_default O v1 v2]).getD (b_or.spec v1 v2)

def b_not.r_true_ (O : Ops) (sv : Term) : Option Term :=
  (match sv with
    | (Term.mk (Kind.Bool true) _) =>
    (whenSome true (v_false))
    | _ => none)

def b_not.r_false_ (O : Ops) (sv : Term) : Option Term :=
  (match sv with
    | (Term.mk (Kind.Bool false) _) =>
    (whenSome true (v_true))
    | _ => none)

def b_not.r_not (O : Ops) (sv : Term) : Option Term :=
  (match sv with
    | (Term.mk (Kind.Unop Unop.Not sv) _) =>
    (whenSome true (sv))
    | _ => none)

def b_not.r_or_ (O : Ops) (sv : Term) : Option Term :=
  (match sv with
    | (Term.mk (Kind.Binop Binop.Or v1 v2) _) =>
    (whenSome true ((O.b_and (O.b_not v1) (O.b_not v2))))
    | _ => none)

def b_not.r_and_ (O : Ops) (sv : Term) : Option Term :=
  (match sv with
    | (Term.mk (Kind.Binop Binop.And v1 v2) _) =>
    (whenSome true ((O.b_or (O.b_not v1) (O.b_not v2))))
    | _ => none)

def b_not.r_ite (O : Ops) (sv : Term) : Option Term :=
  (match sv with
    | (Term.mk (Kind.Triop Triop.Ite g a b) _) =>
    (whenSome true ((O.b_ite g (O.b_not a) (O.b_not b))))
    | _ => none)

def b_not.r_distinct (O : Ops) (sv : Term) : Option Term :=
  (match sv with
    | (Term.mk (Kind.Nop Nop.Distinct (l :: (r :: []))) _) =>
    (whenSome true ((O.sem_eq l r)))
    | _ => none)

def b_not.r_default (O : Ops) (sv : Term) : Option Term :=
  (match sv with
    | _ =>
    (whenSome true ((Term.mk (Kind.Unop Unop.Not sv) Ty.TBool))))

def b_not.step (O : Ops) (sv : Term) : Term :=
  (firstSome [b_not.r_true_ O sv, b_not.r_false_ O sv, b_not.r_not O sv, b_not.r_or_ O sv, b_not.r_and_ O sv, b_not.r_ite O sv, b_not.r_distinct O sv, b_not.r_default O sv]).getD (b_not.spec sv)

def b_ite.r_true_ (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | (Term.mk (Kind.Bool true) _), _, _ =>
    (whenSome true (if_))
    | _, _, _ => none)

def b_ite.r_false_ (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | (Term.mk (Kind.Bool false) _), _, _ =>
    (whenSome true (else_))
    | _, _, _ => none)

def b_ite.r_bool (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, (Term.mk (Kind.Bool true) _), (Term.mk (Kind.Bool false) _) =>
    (whenSome true (guard))
    | _, _, _ => none)

def b_ite.r_not_bool (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, (Term.mk (Kind.Bool false) _), (Term.mk (Kind.Bool true) _) =>
    (whenSome true ((O.b_not guard)))
    | _, _, _ => none)

def b_ite.r_false_then (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, (Term.mk (Kind.Bool false) _), _ =>
    (whenSome true ((O.b_and (O.b_not guard) else_)))
    | _, _, _ => none)

def b_ite.r_true_then (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, (Term.mk (Kind.Bool true) _), _ =>
    (whenSome true ((O.b_or guard else_)))
    | _, _, _ => none)

def b_ite.r_false_else (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, _, (Term.mk (Kind.Bool false) _) =>
    (whenSome true ((O.b_and guard if_)))
    | _, _, _ => none)

def b_ite.r_true_else (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, _, (Term.mk (Kind.Bool true) _) =>
    (whenSome true ((O.b_or (O.b_not guard) if_)))
    | _, _, _ => none)

def b_ite.r_not_guard (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | (Term.mk (Kind.Unop Unop.Not g) _), _, _ =>
    (whenSome true ((O.b_ite g else_ if_)))
    | _, _, _ => none)

def b_ite.r_guard_then (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | g, kanon__2, _ =>
    (whenSome (equal g kanon__2) ((O.b_or guard else_))))

def b_ite.r_guard_else (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | g, _, kanon__3 =>
    (whenSome (equal g kanon__3) ((O.b_and guard if_))))

def b_ite.r_ite_then (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | g, (Term.mk (Kind.Triop Triop.Ite kanon__3 x _) _), _ =>
    (whenSome (equal g kanon__3) ((O.b_ite guard x else_)))
    | _, _, _ => none)

def b_ite.r_ite_else (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | g, _, (Term.mk (Kind.Triop Triop.Ite kanon__4 _ y) _) =>
    (whenSome (equal g kanon__4) ((O.b_ite guard if_ y)))
    | _, _, _ => none)

def b_ite.r_and_ite_then (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | (Term.mk (Kind.Binop Binop.And g _) _), (Term.mk (Kind.Triop Triop.Ite kanon__7 x _) _), _ =>
    (whenSome (equal g kanon__7) ((O.b_ite guard x else_)))
    | _, _, _ => none)
  <|> (match guard, if_, else_ with
        | (Term.mk (Kind.Binop Binop.And _ g) _), (Term.mk (Kind.Triop Triop.Ite kanon__7 x _) _), _ =>
        (whenSome (equal g kanon__7) ((O.b_ite guard x else_)))
        | _, _, _ => none)

def b_ite.r_or_ite_else (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | (Term.mk (Kind.Binop Binop.Or g _) _), _, (Term.mk (Kind.Triop Triop.Ite kanon__8 _ y) _) =>
    (whenSome (equal g kanon__8) ((O.b_ite guard if_ y)))
    | _, _, _ => none)
  <|> (match guard, if_, else_ with
        | (Term.mk (Kind.Binop Binop.Or _ g) _), _, (Term.mk (Kind.Triop Triop.Ite kanon__8 _ y) _) =>
        (whenSome (equal g kanon__8) ((O.b_ite guard if_ y)))
        | _, _, _ => none)

def b_ite.r_same (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, x, kanon__3 =>
    (whenSome (equal x kanon__3) (if_)))

def b_ite.r_default (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, _, _ =>
    (whenSome true
    ((Term.mk (Kind.Triop Triop.Ite guard if_ else_) (ty if_)))))

def b_ite.step (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Term :=
  (firstSome [b_ite.r_true_ O guard if_ else_, b_ite.r_false_ O guard if_ else_, b_ite.r_bool O guard if_ else_, b_ite.r_not_bool O guard if_ else_, b_ite.r_false_then O guard if_ else_, b_ite.r_true_then O guard if_ else_, b_ite.r_false_else O guard if_ else_, b_ite.r_true_else O guard if_ else_, b_ite.r_not_guard O guard if_ else_, b_ite.r_guard_then O guard if_ else_, b_ite.r_guard_else O guard if_ else_, b_ite.r_ite_then O guard if_ else_, b_ite.r_ite_else O guard if_ else_, b_ite.r_and_ite_then O guard if_ else_, b_ite.r_or_ite_else O guard if_ else_, b_ite.r_same O guard if_ else_, b_ite.r_default O guard if_ else_]).getD (b_ite.spec guard if_ else_)

def sem_eq.r_same (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with | v, kanon__2 => (whenSome (equal v kanon__2) (v_true)))

def sem_eq.r_bools (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Bool b1) _), (Term.mk (Kind.Bool b2) _) =>
    (whenSome true ((of_bool (decide (b1 = b2)))))
    | _, _ => none)

def sem_eq.r_ite_ite (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Triop Triop.Ite b l r) _), (Term.mk (Kind.Triop Triop.Ite kanon__7 l' r') _) =>
    (whenSome (equal b kanon__7)
    ((O.b_ite b (O.sem_eq l l') (O.sem_eq r r'))))
    | _, _ => none)

def sem_eq.r_false_ (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Bool false) _), x =>
    (whenSome true ((O.b_not x)))
    | _, _ => none)
  <|> (match v1, v2 with
        | x, (Term.mk (Kind.Bool false) _) =>
        (whenSome true ((O.b_not x)))
        | _, _ => none)

def sem_eq.r_true_ (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Bool true) _), x =>
    (whenSome true (x))
    | _, _ => none)
  <|> (match v1, v2 with
        | x, (Term.mk (Kind.Bool true) _) =>
        (whenSome true (x))
        | _, _ => none)

def sem_eq.r_nots (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Unop Unop.Not b) _), (Term.mk (Kind.Unop Unop.Not c) _) =>
    (whenSome true ((O.sem_eq b c)))
    | _, _ => none)

def sem_eq.r_default (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | _, _ =>
    (whenSome true ((Term.mk (mk_commut_binop O Binop.Eq v1 v2) Ty.TBool))))

def sem_eq.step (O : Ops) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [sem_eq.r_same O v1 v2, sem_eq.r_bools O v1 v2, sem_eq.r_ite_ite O v1 v2, sem_eq.r_false_ O v1 v2, sem_eq.r_true_ O v1 v2, sem_eq.r_nots O v1 v2, sem_eq.r_default O v1 v2]).getD (sem_eq.spec v1 v2)

def sem_eq_untyped.r_ill_typed (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | _, _ =>
    (whenSome (! (decide ((ty v1) = (ty v2)))) (v_false)))

def sem_eq_untyped.r_typed (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with | _, _ => (whenSome true ((O.sem_eq v1 v2))))

def sem_eq_untyped.step (O : Ops) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [sem_eq_untyped.r_ill_typed O v1 v2, sem_eq_untyped.r_typed O v1 v2]).getD (sem_eq_untyped.spec v1 v2)

def b_distinct.r_small (O : Ops) (l : (List Term)) : Option Term :=
  (match l with | _ => (whenSome (at_most_one l) (v_true)))

def b_distinct.r_distinct (O : Ops) (l : (List Term)) : Option Term :=
  (match l with
    | _ =>
    (whenSome (decide ((distinct_check l) = (some true))) (v_true)))

def b_distinct.r_not_distinct (O : Ops) (l : (List Term)) : Option Term :=
  (match l with
    | _ =>
    (whenSome (decide ((distinct_check l) = (some false))) (v_false)))

def b_distinct.r_default (O : Ops) (l : (List Term)) : Option Term :=
  (match l with
    | _ =>
    (whenSome true
    ((Term.mk (Kind.Nop Nop.Distinct (O.orc.sort_by_tag l)) Ty.TBool))))

def b_distinct.step (O : Ops) (l : (List Term)) : Term :=
  (firstSome [b_distinct.r_small O l, b_distinct.r_distinct O l, b_distinct.r_not_distinct O l, b_distinct.r_default O l]).getD (b_distinct.spec l)

def opsRaw (orc : Oracle) : Ops :=
  { orc := orc,
    b_and := fun v1 v2 => b_and.spec v1 v2,
    b_or := fun v1 v2 => b_or.spec v1 v2,
    b_not := fun sv => b_not.spec sv,
    b_ite := fun guard if_ else_ => b_ite.spec guard if_ else_,
    sem_eq := fun v1 v2 => sem_eq.spec v1 v2,
    sem_eq_untyped := fun v1 v2 => sem_eq_untyped.spec v1 v2,
    b_distinct := fun l => b_distinct.spec l }

def opsStep (O : Ops) : Ops :=
  { orc := O.orc,
    b_and := b_and.step O,
    b_or := b_or.step O,
    b_not := b_not.step O,
    b_ite := b_ite.step O,
    sem_eq := sem_eq.step O,
    sem_eq_untyped := sem_eq_untyped.step O,
    b_distinct := b_distinct.step O }

def opsN (orc : Oracle) : Nat → Ops
  | 0 => opsRaw orc
  | n + 1 => opsStep (opsN orc n)

end BoolExample
