-- Generated by kanon from bool.kn. Do not edit.

import BoolExample.Prims

namespace BoolExample

/-! The primitives of the rules, with the types they are declared with. -/

noncomputable section

example : Term → Term → Bool := equal
example : Term → Kind := kind
example : Term := v_true
example : Term := v_false

end

end BoolExample
