-- Generated by kanon from bool.kn. Do not edit.
import BoolExample.Statements
import BoolExample.Lib.Rule
import BoolExample.Proofs

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BoolExample

open Classical Kanon

/-- The rule functions, oracles and helpers of the bool module in the model, for the proofs
of its arms by Kanon's library (`Kanon.BoolMod`). -/
def Ops.bool (O : Ops) : BoolMod.Ops boolLang where
  b_and := O.bool_and_
  b_or := O.bool_or_
  b_not := O.bool_not_
  b_ite := O.bool_ite
  sem_eq := O.bool_eq
  tag_le := O.orc.tag_le
  sort_by_tag := O.orc.sort_by_tag
  at_most_one := Bool.at_most_one
  distinct_check_one := Bool.distinct_check_one
  distinct_check := Bool.distinct_check

theorem Ops.Sound.bool {O : Ops} (hO : O.Sound) : O.bool.Sound where
  b_and := hO.bool_and_
  b_or := hO.bool_or_
  b_not := hO.bool_not_
  b_ite := hO.bool_ite
  sem_eq := hO.bool_eq
  sort_by_tag := hO.orc.sort_by_tag
  at_most_one _ _ _ := rfl
  distinct_check_one_nil _ := by
    dsimp only [Ops.bool]; rw [Bool.distinct_check_one]; rfl
  distinct_check_one_cons _ _ _ := by
    dsimp only [Ops.bool]; rw [Bool.distinct_check_one]; rfl
  distinct_check_nil := by
    dsimp only [Ops.bool]; rw [Bool.distinct_check]; rfl
  distinct_check_cons _ _ := by
    dsimp only [Ops.bool]; rw [Bool.distinct_check]; split <;> simp_all [firstSome]

@[kanon_comm_lemma] theorem Op2.And.comm.ok : Op2.And.comm.Stmt :=
  fun _ _ _ => BoolMod.Lang.refines_and_comm (L := boolLang)

@[kanon_comm_lemma] theorem Op2.Or.comm.ok : Op2.Or.comm.Stmt :=
  fun _ _ _ => BoolMod.Lang.refines_or_comm (L := boolLang)

@[kanon_comm_lemma] theorem Op2.Eq.comm.ok : Op2.Eq.comm.Stmt :=
  fun _ _ _ => BoolMod.Lang.refines_eq_comm (L := boolLang)

theorem Bool.and_.r_same.main.ok : Bool.and_.r_same.main.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_same.main boolLang O.bool hO.bool

theorem Bool.and_.r_same.proof : Bool.and_.r_same.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.and_.r_same] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_same.main.ok O hO)

theorem Bool.and_.r_false_.main.ok : Bool.and_.r_false_.main.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_false_.main boolLang O.bool hO.bool

theorem Bool.and_.r_false_.swap.ok : Bool.and_.r_false_.swap.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_false_.swap boolLang O.bool hO.bool

theorem Bool.and_.r_false_.proof : Bool.and_.r_false_.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.and_.r_false_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_false_.main.ok O hO)
  · kanon_arm h (Bool.and_.r_false_.swap.ok O hO)

theorem Bool.and_.r_true_.main.ok : Bool.and_.r_true_.main.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_true_.main boolLang O.bool hO.bool

theorem Bool.and_.r_true_.swap.ok : Bool.and_.r_true_.swap.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_true_.swap boolLang O.bool hO.bool

theorem Bool.and_.r_true_.proof : Bool.and_.r_true_.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.and_.r_true_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_true_.main.ok O hO)
  · kanon_arm h (Bool.and_.r_true_.swap.ok O hO)

theorem Bool.and_.r_not.main.ok : Bool.and_.r_not.main.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_not.main boolLang O.bool hO.bool

theorem Bool.and_.r_not.swap.ok : Bool.and_.r_not.swap.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_not.swap boolLang O.bool hO.bool

theorem Bool.and_.r_not.proof : Bool.and_.r_not.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.and_.r_not] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_not.main.ok O hO)
  · kanon_arm h (Bool.and_.r_not.swap.ok O hO)

theorem Bool.and_.r_and_.main.ok : Bool.and_.r_and_.main.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_and_.main boolLang O.bool hO.bool

theorem Bool.and_.r_and_.swap1.ok : Bool.and_.r_and_.swap1.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_and_.swap1 boolLang O.bool hO.bool

theorem Bool.and_.r_and_.swap2.ok : Bool.and_.r_and_.swap2.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_and_.swap2 boolLang O.bool hO.bool

theorem Bool.and_.r_and_.swap1_swap2.ok : Bool.and_.r_and_.swap1_swap2.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_and_.swap1_swap2 boolLang O.bool hO.bool

theorem Bool.and_.r_and_.proof : Bool.and_.r_and_.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.and_.r_and_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_and_.main.ok O hO)
  · kanon_arm h (Bool.and_.r_and_.swap1.ok O hO)
  · kanon_arm h (Bool.and_.r_and_.swap2.ok O hO)
  · kanon_arm h (Bool.and_.r_and_.swap1_swap2.ok O hO)

theorem Bool.and_.r_or_.main.ok : Bool.and_.r_or_.main.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_or_.main boolLang O.bool hO.bool

theorem Bool.and_.r_or_.swap1.ok : Bool.and_.r_or_.swap1.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_or_.swap1 boolLang O.bool hO.bool

theorem Bool.and_.r_or_.swap2.ok : Bool.and_.r_or_.swap2.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_or_.swap2 boolLang O.bool hO.bool

theorem Bool.and_.r_or_.swap1_swap2.ok : Bool.and_.r_or_.swap1_swap2.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_or_.swap1_swap2 boolLang O.bool hO.bool

theorem Bool.and_.r_or_.proof : Bool.and_.r_or_.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.and_.r_or_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_or_.main.ok O hO)
  · kanon_arm h (Bool.and_.r_or_.swap1.ok O hO)
  · kanon_arm h (Bool.and_.r_or_.swap2.ok O hO)
  · kanon_arm h (Bool.and_.r_or_.swap1_swap2.ok O hO)

theorem Bool.and_.r_eq_neq.main.ok : Bool.and_.r_eq_neq.main.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_eq_neq.main boolLang O.bool hO.bool

theorem Bool.and_.r_eq_neq.swap2.ok : Bool.and_.r_eq_neq.swap2.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_eq_neq.swap2 boolLang O.bool hO.bool

theorem Bool.and_.r_eq_neq.swap1.ok : Bool.and_.r_eq_neq.swap1.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_eq_neq.swap1 boolLang O.bool hO.bool

theorem Bool.and_.r_eq_neq.swap1_swap2.ok : Bool.and_.r_eq_neq.swap1_swap2.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_eq_neq.swap1_swap2 boolLang O.bool hO.bool

theorem Bool.and_.r_eq_neq.proof : Bool.and_.r_eq_neq.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.and_.r_eq_neq] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_eq_neq.main.ok O hO)
  · kanon_arm h (Bool.and_.r_eq_neq.swap2.ok O hO)
  · kanon_arm h (Bool.and_.r_eq_neq.swap1.ok O hO)
  · kanon_arm h (Bool.and_.r_eq_neq.swap1_swap2.ok O hO)

theorem Bool.and_.r_default.main.ok : Bool.and_.r_default.main.Stmt :=
  fun O hO => BoolMod.Bool.and_.r_default.main boolLang O.bool hO.bool

theorem Bool.and_.r_default.proof : Bool.and_.r_default.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.and_.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_default.main.ok O hO)

theorem Bool.or_.r_same.main.ok : Bool.or_.r_same.main.Stmt :=
  fun O hO => BoolMod.Bool.or_.r_same.main boolLang O.bool hO.bool

theorem Bool.or_.r_same.proof : Bool.or_.r_same.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.or_.r_same] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.or_.r_same.main.ok O hO)

theorem Bool.or_.r_true_.main.ok : Bool.or_.r_true_.main.Stmt :=
  fun O hO => BoolMod.Bool.or_.r_true_.main boolLang O.bool hO.bool

theorem Bool.or_.r_true_.swap.ok : Bool.or_.r_true_.swap.Stmt :=
  fun O hO => BoolMod.Bool.or_.r_true_.swap boolLang O.bool hO.bool

theorem Bool.or_.r_true_.proof : Bool.or_.r_true_.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.or_.r_true_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.or_.r_true_.main.ok O hO)
  · kanon_arm h (Bool.or_.r_true_.swap.ok O hO)

theorem Bool.or_.r_false_.main.ok : Bool.or_.r_false_.main.Stmt :=
  fun O hO => BoolMod.Bool.or_.r_false_.main boolLang O.bool hO.bool

theorem Bool.or_.r_false_.swap.ok : Bool.or_.r_false_.swap.Stmt :=
  fun O hO => BoolMod.Bool.or_.r_false_.swap boolLang O.bool hO.bool

theorem Bool.or_.r_false_.proof : Bool.or_.r_false_.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.or_.r_false_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.or_.r_false_.main.ok O hO)
  · kanon_arm h (Bool.or_.r_false_.swap.ok O hO)

theorem Bool.or_.r_not.main.ok : Bool.or_.r_not.main.Stmt :=
  fun O hO => BoolMod.Bool.or_.r_not.main boolLang O.bool hO.bool

theorem Bool.or_.r_not.swap.ok : Bool.or_.r_not.swap.Stmt :=
  fun O hO => BoolMod.Bool.or_.r_not.swap boolLang O.bool hO.bool

theorem Bool.or_.r_not.proof : Bool.or_.r_not.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.or_.r_not] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.or_.r_not.main.ok O hO)
  · kanon_arm h (Bool.or_.r_not.swap.ok O hO)

theorem Bool.or_.r_or_.main.ok : Bool.or_.r_or_.main.Stmt :=
  fun O hO => BoolMod.Bool.or_.r_or_.main boolLang O.bool hO.bool

theorem Bool.or_.r_or_.swap1.ok : Bool.or_.r_or_.swap1.Stmt :=
  fun O hO => BoolMod.Bool.or_.r_or_.swap1 boolLang O.bool hO.bool

theorem Bool.or_.r_or_.swap2.ok : Bool.or_.r_or_.swap2.Stmt :=
  fun O hO => BoolMod.Bool.or_.r_or_.swap2 boolLang O.bool hO.bool

theorem Bool.or_.r_or_.swap1_swap2.ok : Bool.or_.r_or_.swap1_swap2.Stmt :=
  fun O hO => BoolMod.Bool.or_.r_or_.swap1_swap2 boolLang O.bool hO.bool

theorem Bool.or_.r_or_.proof : Bool.or_.r_or_.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.or_.r_or_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.or_.r_or_.main.ok O hO)
  · kanon_arm h (Bool.or_.r_or_.swap1.ok O hO)
  · kanon_arm h (Bool.or_.r_or_.swap2.ok O hO)
  · kanon_arm h (Bool.or_.r_or_.swap1_swap2.ok O hO)

theorem Bool.or_.r_and_.main.ok : Bool.or_.r_and_.main.Stmt :=
  fun O hO => BoolMod.Bool.or_.r_and_.main boolLang O.bool hO.bool

theorem Bool.or_.r_and_.swap1.ok : Bool.or_.r_and_.swap1.Stmt :=
  fun O hO => BoolMod.Bool.or_.r_and_.swap1 boolLang O.bool hO.bool

theorem Bool.or_.r_and_.swap2.ok : Bool.or_.r_and_.swap2.Stmt :=
  fun O hO => BoolMod.Bool.or_.r_and_.swap2 boolLang O.bool hO.bool

theorem Bool.or_.r_and_.swap1_swap2.ok : Bool.or_.r_and_.swap1_swap2.Stmt :=
  fun O hO => BoolMod.Bool.or_.r_and_.swap1_swap2 boolLang O.bool hO.bool

theorem Bool.or_.r_and_.proof : Bool.or_.r_and_.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.or_.r_and_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.or_.r_and_.main.ok O hO)
  · kanon_arm h (Bool.or_.r_and_.swap1.ok O hO)
  · kanon_arm h (Bool.or_.r_and_.swap2.ok O hO)
  · kanon_arm h (Bool.or_.r_and_.swap1_swap2.ok O hO)

theorem Bool.or_.r_default.main.ok : Bool.or_.r_default.main.Stmt :=
  fun O hO => BoolMod.Bool.or_.r_default.main boolLang O.bool hO.bool

theorem Bool.or_.r_default.proof : Bool.or_.r_default.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.or_.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.or_.r_default.main.ok O hO)

theorem Bool.not_.r_true_.main.ok : Bool.not_.r_true_.main.Stmt :=
  fun O hO => BoolMod.Bool.not_.r_true_.main boolLang O.bool hO.bool

theorem Bool.not_.r_true_.proof : Bool.not_.r_true_.Stmt := by
  intro O hO sv res h
  simp only [Bool.not_.r_true_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.not_.r_true_.main.ok O hO)

theorem Bool.not_.r_false_.main.ok : Bool.not_.r_false_.main.Stmt :=
  fun O hO => BoolMod.Bool.not_.r_false_.main boolLang O.bool hO.bool

theorem Bool.not_.r_false_.proof : Bool.not_.r_false_.Stmt := by
  intro O hO sv res h
  simp only [Bool.not_.r_false_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.not_.r_false_.main.ok O hO)

theorem Bool.not_.r_not.main.ok : Bool.not_.r_not.main.Stmt :=
  fun O hO => BoolMod.Bool.not_.r_not.main boolLang O.bool hO.bool

theorem Bool.not_.r_not.proof : Bool.not_.r_not.Stmt := by
  intro O hO sv res h
  simp only [Bool.not_.r_not] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.not_.r_not.main.ok O hO)

theorem Bool.not_.r_or_.main.ok : Bool.not_.r_or_.main.Stmt :=
  fun O hO => BoolMod.Bool.not_.r_or_.main boolLang O.bool hO.bool

theorem Bool.not_.r_or_.proof : Bool.not_.r_or_.Stmt := by
  intro O hO sv res h
  simp only [Bool.not_.r_or_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.not_.r_or_.main.ok O hO)

theorem Bool.not_.r_and_.main.ok : Bool.not_.r_and_.main.Stmt :=
  fun O hO => BoolMod.Bool.not_.r_and_.main boolLang O.bool hO.bool

theorem Bool.not_.r_and_.proof : Bool.not_.r_and_.Stmt := by
  intro O hO sv res h
  simp only [Bool.not_.r_and_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.not_.r_and_.main.ok O hO)

theorem Bool.not_.r_ite.main.ok : Bool.not_.r_ite.main.Stmt :=
  fun O hO => BoolMod.Bool.not_.r_ite.main boolLang O.bool hO.bool

theorem Bool.not_.r_ite.proof : Bool.not_.r_ite.Stmt := by
  intro O hO sv res h
  simp only [Bool.not_.r_ite] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.not_.r_ite.main.ok O hO)

theorem Bool.not_.r_distinct.main.ok : Bool.not_.r_distinct.main.Stmt :=
  fun O hO => BoolMod.Bool.not_.r_distinct.main boolLang O.bool hO.bool

theorem Bool.not_.r_distinct.proof : Bool.not_.r_distinct.Stmt := by
  intro O hO sv res h
  simp only [Bool.not_.r_distinct] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.not_.r_distinct.main.ok O hO)

theorem Bool.not_.r_default.main.ok : Bool.not_.r_default.main.Stmt :=
  fun O hO => BoolMod.Bool.not_.r_default.main boolLang O.bool hO.bool

theorem Bool.not_.r_default.proof : Bool.not_.r_default.Stmt := by
  intro O hO sv res h
  simp only [Bool.not_.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.not_.r_default.main.ok O hO)

theorem Bool.ite.r_true_.main.ok : Bool.ite.r_true_.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_true_.main boolLang O.bool hO.bool

theorem Bool.ite.r_true_.proof : Bool.ite.r_true_.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_true_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_true_.main.ok O hO)

theorem Bool.ite.r_false_.main.ok : Bool.ite.r_false_.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_false_.main boolLang O.bool hO.bool

theorem Bool.ite.r_false_.proof : Bool.ite.r_false_.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_false_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_false_.main.ok O hO)

theorem Bool.ite.r_bool.main.ok : Bool.ite.r_bool.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_bool.main boolLang O.bool hO.bool

theorem Bool.ite.r_bool.proof : Bool.ite.r_bool.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_bool] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_bool.main.ok O hO)

theorem Bool.ite.r_not_bool.main.ok : Bool.ite.r_not_bool.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_not_bool.main boolLang O.bool hO.bool

theorem Bool.ite.r_not_bool.proof : Bool.ite.r_not_bool.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_not_bool] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_not_bool.main.ok O hO)

theorem Bool.ite.r_false_then.main.ok : Bool.ite.r_false_then.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_false_then.main boolLang O.bool hO.bool

theorem Bool.ite.r_false_then.proof : Bool.ite.r_false_then.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_false_then] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_false_then.main.ok O hO)

theorem Bool.ite.r_true_then.main.ok : Bool.ite.r_true_then.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_true_then.main boolLang O.bool hO.bool

theorem Bool.ite.r_true_then.proof : Bool.ite.r_true_then.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_true_then] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_true_then.main.ok O hO)

theorem Bool.ite.r_false_else.main.ok : Bool.ite.r_false_else.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_false_else.main boolLang O.bool hO.bool

theorem Bool.ite.r_false_else.proof : Bool.ite.r_false_else.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_false_else] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_false_else.main.ok O hO)

theorem Bool.ite.r_true_else.main.ok : Bool.ite.r_true_else.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_true_else.main boolLang O.bool hO.bool

theorem Bool.ite.r_true_else.proof : Bool.ite.r_true_else.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_true_else] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_true_else.main.ok O hO)

theorem Bool.ite.r_not_guard.main.ok : Bool.ite.r_not_guard.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_not_guard.main boolLang O.bool hO.bool

theorem Bool.ite.r_not_guard.proof : Bool.ite.r_not_guard.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_not_guard] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_not_guard.main.ok O hO)

theorem Bool.ite.r_guard_then.main.ok : Bool.ite.r_guard_then.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_guard_then.main boolLang O.bool hO.bool

theorem Bool.ite.r_guard_then.proof : Bool.ite.r_guard_then.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_guard_then] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_guard_then.main.ok O hO)

theorem Bool.ite.r_guard_else.main.ok : Bool.ite.r_guard_else.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_guard_else.main boolLang O.bool hO.bool

theorem Bool.ite.r_guard_else.proof : Bool.ite.r_guard_else.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_guard_else] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_guard_else.main.ok O hO)

theorem Bool.ite.r_ite_then.main.ok : Bool.ite.r_ite_then.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_ite_then.main boolLang O.bool hO.bool

theorem Bool.ite.r_ite_then.proof : Bool.ite.r_ite_then.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_ite_then] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_ite_then.main.ok O hO)

theorem Bool.ite.r_ite_else.main.ok : Bool.ite.r_ite_else.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_ite_else.main boolLang O.bool hO.bool

theorem Bool.ite.r_ite_else.proof : Bool.ite.r_ite_else.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_ite_else] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_ite_else.main.ok O hO)

theorem Bool.ite.r_and_ite_then.main.ok : Bool.ite.r_and_ite_then.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_and_ite_then.main boolLang O.bool hO.bool

theorem Bool.ite.r_and_ite_then.swap.ok : Bool.ite.r_and_ite_then.swap.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_and_ite_then.swap boolLang O.bool hO.bool

theorem Bool.ite.r_and_ite_then.proof : Bool.ite.r_and_ite_then.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_and_ite_then] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_and_ite_then.main.ok O hO)
  · kanon_arm h (Bool.ite.r_and_ite_then.swap.ok O hO)

theorem Bool.ite.r_or_ite_else.main.ok : Bool.ite.r_or_ite_else.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_or_ite_else.main boolLang O.bool hO.bool

theorem Bool.ite.r_or_ite_else.swap.ok : Bool.ite.r_or_ite_else.swap.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_or_ite_else.swap boolLang O.bool hO.bool

theorem Bool.ite.r_or_ite_else.proof : Bool.ite.r_or_ite_else.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_or_ite_else] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_or_ite_else.main.ok O hO)
  · kanon_arm h (Bool.ite.r_or_ite_else.swap.ok O hO)

theorem Bool.ite.r_same.main.ok : Bool.ite.r_same.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_same.main boolLang O.bool hO.bool

theorem Bool.ite.r_same.proof : Bool.ite.r_same.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_same] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_same.main.ok O hO)

theorem Bool.ite.r_default.main.ok : Bool.ite.r_default.main.Stmt :=
  fun O hO => BoolMod.Bool.ite.r_default.main boolLang O.bool hO.bool

theorem Bool.ite.r_default.proof : Bool.ite.r_default.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [Bool.ite.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.ite.r_default.main.ok O hO)

theorem Bool.eq.r_same.main.ok : Bool.eq.r_same.main.Stmt :=
  fun O hO => BoolMod.Bool.eq.r_same.main boolLang O.bool hO.bool

theorem Bool.eq.r_same.proof : Bool.eq.r_same.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.eq.r_same] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.eq.r_same.main.ok O hO)

theorem Bool.eq.r_bools.main.ok : Bool.eq.r_bools.main.Stmt :=
  fun O hO => BoolMod.Bool.eq.r_bools.main boolLang O.bool hO.bool

theorem Bool.eq.r_bools.proof : Bool.eq.r_bools.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.eq.r_bools] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.eq.r_bools.main.ok O hO)

theorem Bool.eq.r_ite_ite.main.ok : Bool.eq.r_ite_ite.main.Stmt :=
  fun O hO => BoolMod.Bool.eq.r_ite_ite.main boolLang O.bool hO.bool

theorem Bool.eq.r_ite_ite.proof : Bool.eq.r_ite_ite.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.eq.r_ite_ite] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.eq.r_ite_ite.main.ok O hO)

theorem Bool.eq.r_false_.main.ok : Bool.eq.r_false_.main.Stmt :=
  fun O hO => BoolMod.Bool.eq.r_false_.main boolLang O.bool hO.bool

theorem Bool.eq.r_false_.swap.ok : Bool.eq.r_false_.swap.Stmt :=
  fun O hO => BoolMod.Bool.eq.r_false_.swap boolLang O.bool hO.bool

theorem Bool.eq.r_false_.proof : Bool.eq.r_false_.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.eq.r_false_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.eq.r_false_.main.ok O hO)
  · kanon_arm h (Bool.eq.r_false_.swap.ok O hO)

theorem Bool.eq.r_true_.main.ok : Bool.eq.r_true_.main.Stmt :=
  fun O hO => BoolMod.Bool.eq.r_true_.main boolLang O.bool hO.bool

theorem Bool.eq.r_true_.swap.ok : Bool.eq.r_true_.swap.Stmt :=
  fun O hO => BoolMod.Bool.eq.r_true_.swap boolLang O.bool hO.bool

theorem Bool.eq.r_true_.proof : Bool.eq.r_true_.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.eq.r_true_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.eq.r_true_.main.ok O hO)
  · kanon_arm h (Bool.eq.r_true_.swap.ok O hO)

theorem Bool.eq.r_nots.main.ok : Bool.eq.r_nots.main.Stmt :=
  fun O hO => BoolMod.Bool.eq.r_nots.main boolLang O.bool hO.bool

theorem Bool.eq.r_nots.proof : Bool.eq.r_nots.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.eq.r_nots] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.eq.r_nots.main.ok O hO)

theorem Bool.eq.r_default.main.ok : Bool.eq.r_default.main.Stmt :=
  fun O hO => BoolMod.Bool.eq.r_default.main boolLang O.bool hO.bool

theorem Bool.eq.r_default.proof : Bool.eq.r_default.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.eq.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.eq.r_default.main.ok O hO)

theorem Bool.eq_untyped.r_ill_typed.main.ok : Bool.eq_untyped.r_ill_typed.main.Stmt :=
  fun O hO => BoolMod.Bool.eq_untyped.r_ill_typed.main boolLang O.bool hO.bool

theorem Bool.eq_untyped.r_ill_typed.proof : Bool.eq_untyped.r_ill_typed.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.eq_untyped.r_ill_typed] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.eq_untyped.r_ill_typed.main.ok O hO)

theorem Bool.eq_untyped.r_typed.main.ok : Bool.eq_untyped.r_typed.main.Stmt :=
  fun O hO => BoolMod.Bool.eq_untyped.r_typed.main boolLang O.bool hO.bool

theorem Bool.eq_untyped.r_typed.proof : Bool.eq_untyped.r_typed.Stmt := by
  intro O hO v1 v2 res h
  simp only [Bool.eq_untyped.r_typed] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.eq_untyped.r_typed.main.ok O hO)

theorem Bool.distinct.r_small.main.ok : Bool.distinct.r_small.main.Stmt :=
  fun O hO => BoolMod.Bool.distinct.r_small.main boolLang O.bool hO.bool

theorem Bool.distinct.r_small.proof : Bool.distinct.r_small.Stmt := by
  intro O hO l res h
  simp only [Bool.distinct.r_small] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.distinct.r_small.main.ok O hO)

theorem Bool.distinct.r_distinct.main.ok : Bool.distinct.r_distinct.main.Stmt :=
  fun O hO => BoolMod.Bool.distinct.r_distinct.main boolLang O.bool hO.bool

theorem Bool.distinct.r_distinct.proof : Bool.distinct.r_distinct.Stmt := by
  intro O hO l res h
  simp only [Bool.distinct.r_distinct] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.distinct.r_distinct.main.ok O hO)

theorem Bool.distinct.r_not_distinct.main.ok : Bool.distinct.r_not_distinct.main.Stmt :=
  fun O hO => BoolMod.Bool.distinct.r_not_distinct.main boolLang O.bool hO.bool

theorem Bool.distinct.r_not_distinct.proof : Bool.distinct.r_not_distinct.Stmt := by
  intro O hO l res h
  simp only [Bool.distinct.r_not_distinct] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.distinct.r_not_distinct.main.ok O hO)

theorem Bool.distinct.r_default.main.ok : Bool.distinct.r_default.main.Stmt :=
  fun O hO => BoolMod.Bool.distinct.r_default.main boolLang O.bool hO.bool

theorem Bool.distinct.r_default.proof : Bool.distinct.r_default.Stmt := by
  intro O hO l res h
  simp only [Bool.distinct.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.distinct.r_default.main.ok O hO)

theorem Bool.and_.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (Bool.and_.spec v1 v2) (Bool.and_.step O v1 v2) := by
  unfold Bool.and_.step
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_same.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_false_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_true_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_not.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_and_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_or_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_eq_neq.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_default.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

theorem Bool.or_.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (Bool.or_.spec v1 v2) (Bool.or_.step O v1 v2) := by
  unfold Bool.or_.step
  refine Refinement.firstSome_cons (fun res h => Bool.or_.r_same.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.or_.r_true_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.or_.r_false_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.or_.r_not.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.or_.r_or_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.or_.r_and_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.or_.r_default.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

theorem Bool.not_.step_sound (O : Ops) (hO : O.Sound) (sv : Term) :
  Refines (Bool.not_.spec sv) (Bool.not_.step O sv) := by
  unfold Bool.not_.step
  refine Refinement.firstSome_cons (fun res h => Bool.not_.r_true_.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.not_.r_false_.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.not_.r_not.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.not_.r_or_.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.not_.r_and_.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.not_.r_ite.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.not_.r_distinct.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.not_.r_default.proof O hO sv res h) ?_
  exact Refinement.firstSome_nil

theorem Bool.ite.step_sound (O : Ops) (hO : O.Sound) (guard : Term) (if_ : Term) (else_ : Term) :
  Refines (Bool.ite.spec guard if_ else_) (Bool.ite.step O guard if_ else_) := by
  unfold Bool.ite.step
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_true_.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_false_.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_bool.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_not_bool.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_false_then.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_true_then.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_false_else.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_true_else.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_not_guard.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_guard_then.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_guard_else.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_ite_then.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_ite_else.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_and_ite_then.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_or_ite_else.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_same.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.ite.r_default.proof O hO guard if_ else_ res h) ?_
  exact Refinement.firstSome_nil

theorem Bool.eq.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (Bool.eq.spec v1 v2) (Bool.eq.step O v1 v2) := by
  unfold Bool.eq.step
  refine Refinement.firstSome_cons (fun res h => Bool.eq.r_same.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.eq.r_bools.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.eq.r_ite_ite.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.eq.r_false_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.eq.r_true_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.eq.r_nots.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.eq.r_default.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

theorem Bool.eq_untyped.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (Bool.eq_untyped.spec v1 v2) (Bool.eq_untyped.step O v1 v2) := by
  unfold Bool.eq_untyped.step
  refine Refinement.firstSome_cons (fun res h => Bool.eq_untyped.r_ill_typed.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.eq_untyped.r_typed.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

theorem Bool.distinct.step_sound (O : Ops) (hO : O.Sound) (l : (List Term)) :
  Refines (Bool.distinct.spec l) (Bool.distinct.step O l) := by
  unfold Bool.distinct.step
  refine Refinement.firstSome_cons (fun res h => Bool.distinct.r_small.proof O hO l res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.distinct.r_distinct.proof O hO l res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.distinct.r_not_distinct.proof O hO l res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.distinct.r_default.proof O hO l res h) ?_
  exact Refinement.firstSome_nil

/-- Every rule function refines its spec, for any amount of fuel. -/
theorem opsN_sound (orc : Oracle) (h : orc.Compat) :
  ∀ n, (opsN orc n).Sound
  | 0 =>
    { orc := h,
      bool_and_ := fun v1 v2 => Refinement.refl,
      bool_or_ := fun v1 v2 => Refinement.refl,
      bool_not_ := fun sv => Refinement.refl,
      bool_ite := fun guard if_ else_ => Refinement.refl,
      bool_eq := fun v1 v2 => Refinement.refl,
      bool_eq_untyped := fun v1 v2 => Refinement.refl,
      bool_distinct := fun l => Refinement.refl }
  | n + 1 =>
    have hO := opsN_sound orc h n
    { orc := hO.orc,
      bool_and_ := Bool.and_.step_sound _ hO,
      bool_or_ := Bool.or_.step_sound _ hO,
      bool_not_ := Bool.not_.step_sound _ hO,
      bool_ite := Bool.ite.step_sound _ hO,
      bool_eq := Bool.eq.step_sound _ hO,
      bool_eq_untyped := Bool.eq_untyped.step_sound _ hO,
      bool_distinct := Bool.distinct.step_sound _ hO }

end BoolExample
