-- Generated by kanon from bool.kn, int.kn. Do not edit.
import IntsExample.Signatures

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace IntsExample

open Classical Kanon

def Bool.of_bool (b : Bool) : Term :=
  (if b then v_true else v_false)

end IntsExample
