The built-in modules: `use +name` uses the module of modules/ built into
kanon. The example language of examples/bool is made of the bool module alone
(`use +bool`); the generated files name its files bool.knl and bool.kn.

  $ kanon ocaml-types ../../examples/bool/lang.knl | head -n 14
  (* Generated by kanon from lang.knl, bool.knl. Do not edit. *)
  
  [@@@warning "-a"]
  
  type var = string
  
  and kind =
    | Var of var
    | Bool of bool
    | Op1 of op1 * t
    | Op2 of op2 * t * t
    | Op3 of op3 * t * t * t
    | OpN of opn * (t list)
  
  $ kanon ocaml ../../examples/bool/lang.knl | head -n 9
  (* Generated by kanon from bool.kn. Do not edit. *)
  
  [@@@warning "-a+11"]
  
  module _ : sig
    val sort_by_tag : (t list) -> (t list)
    val v_true : t
    val v_false : t
  end = Prims

An unknown built-in module:

  $ echo 'use +int' > int.kn
  $ kanon ocaml ../../examples/bool/lang.knl int.kn
  kanon: use "+int": no +int.knl or +int.kn
  [1]
