-- Generated by kanon from bool.kn, num.kn, neg.kn, even.kn, mix.kn. Do not edit.
import L3.Statements
import L3.Lifts
import L3.Nodes
import L3.Lib.Rule
import L3.Instance
import KanonBool.Soundness.Laws
import NumMod.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L3

open Classical Kanon

@[kanon_comm_lemma] theorem Op2.And.comm.ok : Op2.And.comm.Stmt :=
  fun a b t => KanonBool.And.comm.ok (S := sem) boolSyntax a b t

@[kanon_comm_lemma] theorem Op2.Or.comm.ok : Op2.Or.comm.Stmt :=
  fun a b t => KanonBool.Or.comm.ok (S := sem) boolSyntax a b t

@[kanon_comm_lemma] theorem Op2.Eq.comm.ok : Op2.Eq.comm.Stmt :=
  fun a b t => KanonBool.Eq.comm.ok (S := sem) boolSyntax a b t

@[kanon_comm_lemma] theorem Op2.Add.comm.ok : Op2.Add.comm.Stmt :=
  fun a b t => NumMod.Add.comm.ok (S := sem) numSyntax a b t

end L3
