-- Generated by kanon from bool.kn, num.kn, neg.kn, even.kn, mix.kn. Do not edit.
import L3.Interface.Mix
import L3.Statements
import MixMod.Ops

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L3

open Classical Kanon

/-- The model of the language, for the module `Mix`. -/
def Ops.toMix (O : Ops) : MixMod.Ops (S := sem) mixSyntax where
  tag_le := O.orc.tag_le
  bool_and_ := O.bool_and_
  bool_or_ := O.bool_or_
  bool_not_ := O.bool_not_
  bool_ite := O.bool_ite
  bool_eq := O.bool_eq
  bool_eq_untyped := O.bool_eq_untyped
  bool_distinct := O.bool_distinct
  bool_sort_by_tag := O.orc.sort_by_tag
  even_rem2 := O.even_rem2
  neg_neg := O.neg_neg
  num_add := O.num_add
  num_less := O.num_less
  num_max := O.num_max

theorem Ops.Sound.toMix {O : Ops} (hO : O.Sound) : (Ops.toMix O).Sound where
  bool_and_ := hO.bool_and_
  bool_or_ := hO.bool_or_
  bool_not_ := hO.bool_not_
  bool_ite := hO.bool_ite
  bool_eq := hO.bool_eq
  bool_eq_untyped := hO.bool_eq_untyped
  bool_distinct := hO.bool_distinct
  bool_orc := hO.orc.bool
  even_rem2 := hO.even_rem2
  neg_neg := hO.neg_neg
  num_add := hO.num_add
  num_less := hO.num_less
  num_max := hO.num_max

end L3
