Documentation comments: a comment (** ... *) right before a declaration is
stored with it and printed along the generated OCaml and Lean. A plain comment
(* ... *) is ignored.

  $ cat > lang.knl <<'KN'
  > [@@@ocaml_prims "Prims"]
  > 
  > (** A plain integer type. *)
  > type big [@ocaml "Z.t"] [@lean "Int"]
  > 
  > (* plain comments are ignored *)
  > (** The sort of integers. *)
  > sort TInt
  > 
  > (** The sort of booleans. *)
  > sort TBool
  > 
  > (** An integer literal.
  >     It spans several lines. *)
  > node Int of int : TInt
  > 
  > (** Addition. Mentions a nested (* plain comment *) and (* another (* nested *) one *). *)
  > node Add : TInt -> TInt -> TInt [@comm] [@fold Rules.add_z] [@unit 0]
  > 
  > (** Comparison: contains a close-comment lookalike ( * ) and a Lean one -/ here. *)
  > node Le : TInt -> TInt -> TBool [@fold Rules.le_z Rules.of_bool]
  > 
  > node Bool of bool : TBool
  > notation Int
  > notation Bool
  > infix "+" = Add, Rules.add
  > KN
  $ cat > rules.kn <<'KN'
  > (** A primitive. *)
  > prim of_bool : bool -> t
  > 
  > (** An oracle. *)
  > oracle sort_ints : t list -> t list
  > 
  > (** A helper function. *)
  > fn add_z (x y : int) : int = x + y
  > 
  > (** Another one,
  >     on two lines. *)
  > fn le_z (x y : int) : bool = x <= y
  > 
  > (** The rule of addition. *)
  > rule add : Add (v1, v2) =
  >   | zero: 0 + x -> x
  > 
  > (** The rule of comparison. *)
  > rule le : Le (v1, v2)
  > KN

  $ kanon ocaml-types lang.knl
  (* Generated by kanon from lang.knl. Do not edit. *)
  
  [@@@warning "-a"]
  
  (** A plain integer type. *)
  type big = Z.t
  
  and kind =
    | Int of Z.t (** An integer literal.
                     It spans several lines. *)
    | Bool of bool
    | Op2 of op2 * t * t
  
  and op2 =
    | Add (** Addition. Mentions a nested ( * plain comment * ) and ( * another ( * nested * ) one * ). *)
    | Le (** Comparison: contains a close-comment lookalike ( * ) and a Lean one -/ here. *)
  
  and ty =
    | TInt (** The sort of integers. *)
    | TBool (** The sort of booleans. *)
  
  and t = {
    kind : kind;
    ty : ty;
    tag : int;
  }
  
  let hash_combine x y = (x * 65599) + y
  
  let rec equal_t (a : t) (b : t) = Int.equal a.tag b.tag
  
  and hash_t (a : t) = a.tag
  
  and equal_big (a : big) (b : big) = Stdlib.( = ) a b
  
  and hash_big (a : big) = Hashtbl.hash a
  
  and equal_kind (a : kind) (b : kind) =
    match (a, b) with
    | Int a1, Int b1 -> Z.equal a1 b1
    | Bool a1, Bool b1 -> Stdlib.Bool.equal a1 b1
    | Op2 (a1, a2, a3), Op2 (b1, b2, b3) ->
        equal_op2 a1 b1 && equal_t a2 b2 && equal_t a3 b3
    | _ -> false
  
  and hash_kind (a : kind) =
    match a with
    | Int a1 -> hash_combine (0) (Z.hash a1)
    | Bool a1 -> hash_combine (1) (Stdlib.Bool.to_int a1)
    | Op2 (a1, a2, a3) ->
        hash_combine
          (hash_combine (hash_combine (2) (hash_op2 a1)) (hash_t a2))
          (hash_t a3)
  
  and equal_op2 (a : op2) (b : op2) =
    match (a, b) with
    | Add, Add -> true
    | Le, Le -> true
    | _ -> false
  
  and hash_op2 (a : op2) =
    match a with
    | Add -> 0
    | Le -> 1
  
  and equal_ty (a : ty) (b : ty) =
    match (a, b) with
    | TInt, TInt -> true
    | TBool, TBool -> true
    | _ -> false
  
  and hash_ty (a : ty) =
    match a with
    | TInt -> 0
    | TBool -> 1
  
  (* Not safe across domains (TODO). *)
  let node : kind -> ty -> t =
    let module H = Ephemeron.K1.Make (struct
      type nonrec t = t
      let equal a b = equal_kind a.kind b.kind && equal_ty a.ty b.ty
      let hash a = hash_combine (hash_kind a.kind) (hash_ty a.ty)
    end) in
    let table = H.create 1024 and tags = ref 0 in
    fun kind ty ->
      let v = { kind; ty; tag = -1 } in
      match H.find table v with
      | t -> t
      | exception Not_found ->
        let t = { v with tag = !tags } in
        incr tags;
        H.add table t t;
        t
  $ kanon ocaml lang.knl rules.kn
  (* Generated by kanon from rules.kn. Do not edit. *)
  
  [@@@warning "-a+11"]
  
  module _ : sig
    
    (** A primitive. *)
    val of_bool : bool -> t
    
    (** An oracle. *)
    val sort_ints : (t list) -> (t list)
  end = Prims
  
  (** The functions of the language, in one recursive group, by their flat name: the module in lowercase, an underscore, and the name. The modules below are their names. Not meant to be used. *)
  module Kanon_flat = struct
    let[@inline] mk_commut_binop (op : op2) (l : t) (r : t) : kind =
        (if (Stdlib.Int.compare l.tag r.tag <= 0)
        then (Op2 (op, l, r))
        else (Op2 (op, r, l)))
    
    let[@inline] rules_add_z (x : Z.t) (y : Z.t) : Z.t = (Z.add x y)
    
    let[@inline] rules_le_z (x : Z.t) (y : Z.t) : bool = (Z.leq x y)
    
    let rules_add (v1 : t) (v2 : t) : t =
        (assert ((match v1.ty, v2.ty with
                 | ((TInt), (TInt)) -> true
                 | _ -> false
                 ) [@warning "-11"]);
        (match v1, v2 with
        | ({ kind = Int (i1); _ }, { kind = Int (i2); _ }) ->
          (node (Int ((rules_add_z i1 i2))) TInt)
        | (x, { kind = Int (kanon__2); _ })
          when (((Z.equal kanon__2 Z.zero))) ->
          x
        | ({ kind = Int (kanon__2); _ }, x)
          when (((Z.equal kanon__2 Z.zero))) ->
          x
        | ({ kind = Int (kanon__1); _ }, x)
          when (((Z.equal kanon__1 Z.zero))) ->
          x
        | (x, { kind = Int (kanon__1); _ })
          when (((Z.equal kanon__1 Z.zero))) ->
          x
        | _ -> (node (mk_commut_binop Add v1 v2) TInt)
        ))
    
    let rules_le (v1 : t) (v2 : t) : t =
        (assert ((match v1.ty, v2.ty with
                 | ((TInt), (TInt)) -> true
                 | _ -> false
                 ) [@warning "-11"]);
        (match v1, v2 with
        | ({ kind = Int (i1); _ }, { kind = Int (i2); _ }) ->
          (Prims.of_bool (rules_le_z i1 i2))
        | _ -> (node (Op2 (Le, v1, v2)) TBool)
        ))
  end
  
  (** The Kanon module lang. *)
  module Lang = struct
    (** The sort of integers. *)
    let t_int : ty = TInt
    
    (** The sort of booleans. *)
    let t_bool : ty = TBool
    
    let as_int (t : t) =
      match[@warning "-11"] t with { kind = Int (p1); _ } -> Some p1 | _ -> None
    
    let is_int (t : t) =
      match[@warning "-11"] t with { kind = Int (_); _ } -> true | _ -> false
    
    let as_bool (t : t) =
      match[@warning "-11"] t with { kind = Bool (p1); _ } -> Some p1 | _ -> None
    
    let is_bool (t : t) =
      match[@warning "-11"] t with { kind = Bool (_); _ } -> true | _ -> false
    
    let as_add (t : t) =
      match[@warning "-11"] t with { kind = Op2 (Add, x1, x2); _ } -> Some (x1, x2) | _ -> None
    
    let is_add (t : t) =
      match[@warning "-11"] t with { kind = Op2 (Add, _, _); _ } -> true | _ -> false
    
    let as_le (t : t) =
      match[@warning "-11"] t with { kind = Op2 (Le, x1, x2); _ } -> Some (x1, x2) | _ -> None
    
    let is_le (t : t) =
      match[@warning "-11"] t with { kind = Op2 (Le, _, _); _ } -> true | _ -> false
    
    let as_tint (t : ty) =
      match[@warning "-11"] t with TInt -> Some () | _ -> None
    
    let is_tint (t : ty) =
      match[@warning "-11"] t with TInt -> true | _ -> false
    
    let as_tbool (t : ty) =
      match[@warning "-11"] t with TBool -> Some () | _ -> None
    
    let is_tbool (t : ty) =
      match[@warning "-11"] t with TBool -> true | _ -> false
  end
  
  (** The Kanon module rules. *)
  module Rules = struct
    (** A helper function. *)
    let add_z = Kanon_flat.rules_add_z
    
    (** Another one,
        on two lines. *)
    let le_z = Kanon_flat.rules_le_z
    
    (** The rule of addition. *)
    let add = Kanon_flat.rules_add
    
    (** The rule of comparison. *)
    let le = Kanon_flat.rules_le
  end
  
  
  $ kanon lean-node lang.knl rules.kn
  -- Generated by kanon from lang.knl. Do not edit.
  import KanonCore.Embed
  
  set_option linter.unusedVariables false
  set_option linter.unusedSimpArgs false
  set_option linter.unusedSectionVars false
  set_option maxHeartbeats 1000000
  
  noncomputable section
  
  namespace Kanon
  
  open Classical Kanon
  
  /-- The sorts of the module. -/
  inductive Srt where
    /-- The sort of integers. -/
    | TInt
    /-- The sort of booleans. -/
    | TBool
    deriving DecidableEq, Repr, Inhabited
  
  /-- The nodes of the module, over the terms `T` of a language. -/
  inductive Node (T : Type) where
    /-- An integer literal.
        It spans several lines. -/
    | Int (x1 : Int)
    | Bool (x1 : Bool)
    /-- Addition. Mentions a nested (* plain comment *) and (* another (* nested *) one *). -/
    | Add (a1 : T) (a2 : T)
    /-- Comparison: contains a close-comment lookalike ( * ) and a Lean one - / here. -/
    | Le (a1 : T) (a2 : T)
  
  namespace Node
  
  variable {T U : Type}
  
  /-- The node with its children mapped by `f`. -/
  def map (f : T → U) : Node T → Node U
    | (.Int x1) => (.Int x1)
    | (.Bool x1) => (.Bool x1)
    | (.Add a1 a2) => (.Add (f a1) (f a2))
    | (.Le a1 a2) => (.Le (f a1) (f a2))
  
  /-- Every child of the node satisfies `P`. -/
  def All (P : T → Prop) : Node T → Prop
    | (.Int x1) => True
    | (.Bool x1) => True
    | (.Add a1 a2) => P a1 ∧ P a2
    | (.Le a1 a2) => P a1 ∧ P a2
  
  /-- The nodes have the same arguments, and their children are related by `R`. -/
  def Rel (R : T → U → Prop) : Node T → Node U → Prop
    | (.Int x1), (.Int x1') => x1 = x1'
    | (.Bool x1), (.Bool x1') => x1 = x1'
    | (.Add a1 a2), (.Add a1' a2') => R a1 a1' ∧ R a2 a2'
    | (.Le a1 a2), (.Le a1' a2') => R a1 a1' ∧ R a2 a2'
    | _, _ => False
  
  end Node
  
  end Kanon
  $ kanon lean-syntax lang.knl rules.kn
  -- Generated by kanon from lang.knl. Do not edit.
  import Kanon.Node
  
  set_option linter.unusedVariables false
  set_option linter.unusedSimpArgs false
  set_option linter.unusedSectionVars false
  set_option maxHeartbeats 1000000
  
  noncomputable section
  
  namespace Kanon
  
  open Classical Kanon
  
  /-- The sorts of the language: those of its modules. -/
  inductive Ty where
    | lang (s : Kanon.Srt)
    deriving DecidableEq, Repr
  
  /-- The terms of the language: the nodes of its modules, at a sort. -/
  inductive Term where
    | lang (n : Kanon.Node Term) (t : Ty)
  
  /-- The sort of a term. -/
  def Term.ty : Term → Ty
    | .lang _ t => t
  
  instance : Inhabited Ty := ⟨.lang default⟩
  instance : Inhabited Term := ⟨.lang (.Int default) default⟩
  
  end Kanon
  $ kanon lean-model lang.knl rules.kn
  -- Kanon/Model.lean
  
  -- Generated by kanon from lang.knl. Do not edit.
  import Kanon.Lang
  import KanonCore.Model
  import KanonCore.Attr
  import KanonCore.Embed
  
  set_option linter.unusedVariables false
  set_option linter.unusedSimpArgs false
  set_option linter.unusedSectionVars false
  set_option maxHeartbeats 1000000
  
  noncomputable section
  
  namespace Kanon
  
  open Classical Kanon
  
  /-- The rule functions, oracles and extensible helpers of the module, in the model of a
  language. -/
  structure Ops (S : Kanon.Sem) extends Kanon.OpsBase S
  
  variable {S : Kanon.Sem} [Kanon.Lang S]
  
  /-- What the proofs assume of the model: its rule functions refine their specs, its oracles
  and extensible helpers do what they are assumed to do. -/
  structure Ops.Sound (O : Ops S) : Prop
  
  end Kanon
  
  -- Kanon/Rules/Model.lean
  
  -- Generated by kanon from rules.kn. Do not edit.
  import Kanon.Model
  import KanonCore.Model
  import KanonCore.Attr
  import KanonCore.Embed
  
  set_option linter.unusedVariables false
  set_option linter.unusedSimpArgs false
  set_option linter.unusedSectionVars false
  set_option maxHeartbeats 1000000
  
  noncomputable section
  
  namespace Kanon.Rules
  
  open Classical Kanon
  
  /-- The rule functions, oracles and extensible helpers of the module, in the model of a
  language. -/
  structure Ops (S : Kanon.Sem) extends toLangOps : Kanon.Ops S where
    /-- The rule of addition. -/
    rules_add : S.Term → S.Term → S.Term
    /-- The rule of comparison. -/
    rules_le : S.Term → S.Term → S.Term
    /-- An oracle. -/
    rules_sort_ints : (List S.Term) → (List S.Term)
  
  variable {S : Kanon.Sem} [Kanon.Lang S]
  
  /-- A helper function. -/
  def Rules.add_z (x : Int) (y : Int) : Int :=
    (x + y)
  
  /-- Another one,
      on two lines. -/
  def Rules.le_z (x : Int) (y : Int) : Bool :=
    (decide (x ≤ y))
  
  attribute [kanon_body] Rules.add_z Rules.le_z
  
  /-- The rule of addition. -/
  def Rules.add.spec (v1 : S.Term) (v2 : S.Term) : S.Term :=
    (Kanon.mk (.Add v1 v2) (Kanon.sort .TInt))
  
  /-- The rule of comparison. -/
  def Rules.le.spec (v1 : S.Term) (v2 : S.Term) : S.Term :=
    (Kanon.mk (.Le v1 v2) (Kanon.sort .TBool))
  
  attribute [kanon_spec]
    Rules.add.spec
    Rules.le.spec
  
  def Rules.add.r_lits (O : Ops S) (v1 : S.Term) (v2 : S.Term) : Option S.Term :=
    (match (Kanon.proj v1), (Kanon.proj v2) with
      | some (.Int i1), some (.Int i2) =>
      (whenSome true
      ((Kanon.mk (.Int (Kanon.Rules.Rules.add_z i1 i2)) (Kanon.sort .TInt))))
      | _, _ => none)
  
  def Rules.add.r_unit_zero (O : Ops S) (v1 : S.Term) (v2 : S.Term) : Option S.Term :=
    (match v1, (Kanon.proj v2) with
      | x, some (.Int kanon__2) =>
      (whenSome (decide (kanon__2 = (0 : Int))) (x))
      | _, _ => none)
    <|> (match (Kanon.proj v1), v2 with
          | some (.Int kanon__2), x =>
          (whenSome (decide (kanon__2 = (0 : Int))) (x))
          | _, _ => none)
  
  def Rules.add.r_zero (O : Ops S) (v1 : S.Term) (v2 : S.Term) : Option S.Term :=
    (match (Kanon.proj v1), v2 with
      | some (.Int kanon__1), x =>
      (whenSome (decide (kanon__1 = (0 : Int))) (x))
      | _, _ => none)
    <|> (match v1, (Kanon.proj v2) with
          | x, some (.Int kanon__1) =>
          (whenSome (decide (kanon__1 = (0 : Int))) (x))
          | _, _ => none)
  
  def Rules.add.r_default (O : Ops S) (v1 : S.Term) (v2 : S.Term) : Option S.Term :=
    (match v1, v2 with
      | _, _ =>
      (whenSome true
      ((if O.tag_le v1 v2
       then (Kanon.mk (.Add v1 v2) (Kanon.sort .TInt))
       else (Kanon.mk (.Add v2 v1) (Kanon.sort .TInt))))))
  
  def Rules.le.r_lits (O : Ops S) (v1 : S.Term) (v2 : S.Term) : Option S.Term :=
    (match (Kanon.proj v1), (Kanon.proj v2) with
      | some (.Int i1), some (.Int i2) =>
      (whenSome true ((Kanon.Rules.of_bool (Kanon.Rules.Rules.le_z i1 i2))))
      | _, _ => none)
  
  def Rules.le.r_default (O : Ops S) (v1 : S.Term) (v2 : S.Term) : Option S.Term :=
    (match v1, v2 with
      | _, _ =>
      (whenSome true ((Kanon.mk (.Le v1 v2) (Kanon.sort .TBool)))))
  
  /-- What the proofs assume of the model: its rule functions refine their specs, its oracles
  and extensible helpers do what they are assumed to do. -/
  structure Ops.Sound (O : Ops S) : Prop extends toLangSound : Kanon.Ops.Sound O.toLangOps where
    rules_add : ∀ (v1 : S.Term) (v2 : S.Term), S.Refines (Rules.add.spec v1 v2) (O.rules_add v1 v2)
    rules_le : ∀ (v1 : S.Term) (v2 : S.Term), S.Refines (Rules.le.spec v1 v2) (O.rules_le v1 v2)
    rules_orc : Oracle.Compat (S := S) O.rules_sort_ints
  
  end Kanon.Rules

A doc comment that follows nothing, or is in a position without a declaration,
is an error.

  $ printf '(** dangling *)\n' > dangling.knl
  $ kanon ocaml-types dangling.knl
  dangling.knl:1:0: this doc comment is not followed by an item to document
  [1]
  $ printf 'sort TInt\n(** inside *) [@@@ocaml_prims "P"]\n' > floating.knl
  $ kanon ocaml-types floating.knl
  floating.knl:2:0: a doc comment cannot document this item: only fn, rule, node, sort, subsort, type, prim, oracle, infix, prefix and constant can have one
  [1]
  $ printf '(** a *)\n(** b *)\nsort TInt\n' > two.knl
  $ kanon ocaml-types two.knl
  two.knl:2:0: misplaced doc comment: it must come right before a fn, rule, node, sort, subsort, type, prim, oracle, infix, prefix or constant
  [1]
  $ printf 'sort TInt\nnode Int of int : TInt\nnotation Int\n(** doc *)\nnotation Int\n' > notation.knl
  $ kanon ocaml-types notation.knl
  notation.knl:4:0: a doc comment cannot document this item: only fn, rule, node, sort, subsort, type, prim, oracle, infix, prefix and constant can have one
  [1]
  $ printf 'node Not : TBool -> TBool\nsort TBool\n' > case.knl
  $ printf 'rule not_ : Not v =\n  (** case *)\n  | a: Not (Not x) -> x\n' > case.kn
  $ kanon ocaml-types case.knl case.kn
  case.kn:2:2: misplaced doc comment: it must come right before a fn, rule, node, sort, subsort, type, prim, oracle, infix, prefix or constant
  [1]
