-- Generated by kanon from bool.knl, bool.kn. Do not edit.
import KanonBool.Lift

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace KanonBool

open Classical Kanon

/-- The operands of `And` commute. -/
def And.comm.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (a b : S.Term) (t : S.Ty),
  S.Refines (KanonBool.mk (.And a b) t)
  (KanonBool.mk (.And b a) t)

/-- The operands of `Or` commute. -/
def Or.comm.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (a b : S.Term) (t : S.Ty),
  S.Refines (KanonBool.mk (.Or a b) t)
  (KanonBool.mk (.Or b a) t)

/-- The operands of `Eq` commute. -/
def Eq.comm.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (a b : S.Term) (t : S.Ty),
  S.Refines (KanonBool.mk (.Eq a b) t)
  (KanonBool.mk (.Eq b a) t)

end KanonBool
