let read f = In_channel.with_open_bin f In_channel.input_all

let fail fmt =
  Printf.ksprintf
    (fun s ->
      prerr_endline s;
      exit 1)
    fmt

(** What [Parts.run] prints for [args], with its exit code. *)
let parts args =
  let out = Buffer.create 4096 in
  let fout = Format.formatter_of_buffer out in
  let code =
    Parts.run args fout (Format.formatter_of_buffer (Buffer.create 256))
  in
  Format.pp_print_flush fout ();
  (code, Buffer.contents out)

let contains s sub =
  let n = String.length sub in
  let rec go i =
    i + n <= String.length s && (String.sub s i n = sub || go (i + 1))
  in
  go 0

let () =
  let lang = Sys.argv.(1) in
  let dir = Filename.temp_dir "kanon-parts" "" in
  Check.reset ();
  if
    Cli.run [ "ocaml"; dir; lang ] Format.std_formatter Format.err_formatter
    <> 0
  then fail "kanon ocaml failed";
  List.iter
    (fun (backend, file) ->
      Check.reset ();
      let code, out = parts [ backend; lang ] in
      let expected = read (Filename.concat dir ("Generated/" ^ file)) in
      if code <> 0 || out <> expected then fail "%s is not %s" backend file)
    [
      ("ocaml-types", "tiny_types.ml");
      ("ocaml", "tiny_rules.ml");
      ("ocaml-typed", "typed.ml");
      ("ocaml-tests", "tests.ml");
    ];
  List.iter
    (fun backend ->
      if String.length backend > 5 && String.sub backend 0 5 = "lean-" then (
        Check.reset ();
        let code, out = parts [ backend; lang ] in
        if code <> 0 || not (contains out "Generated by kanon") then
          fail "%s prints no file" backend))
    Parts.backends;
  Check.reset ();
  if fst (parts [ "nothing"; lang ]) <> 2 then fail "an unknown backend"
