-- Generated by kanon from bool.kn, num.kn, neg.kn, even.kn, mix.kn. Do not edit.
import L3.Signatures
import L3.Model.Bool.distinct_check_one

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L3

open Classical Kanon

mutual

def Bool.distinct_check (l : (List Term)) : (Option Bool) :=
  ((firstSome [(match l with | [] => some ((some true)) | _ => none),
    (match l with
      | (a :: rest) =>
      some (((firstSome [(match (Bool.distinct_check_one a rest) with
                           | (some true) =>
                           some ((Bool.distinct_check rest))
                           | _ => none)]).getD
              (match (Bool.distinct_check_one a rest) with | r => r)))
      | _ => none)]).getD
    Inhabited.default)
termination_by sizeOf l
decreasing_by all_goals (simp_wf; omega)

end

end L3
