-- Generated by kanon from even.knl, even.kn. Do not edit.
import KanonCore.Embed

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace EvenMod

open Classical Kanon

/-- The sorts of the module. -/
inductive Srt where
  /-- Even integers. -/
  | TEven
  deriving DecidableEq, Repr, Inhabited

/-- The nodes of the module, over the terms `T` of a language. -/
inductive Node (T : Type) where
  | Ev (x1 : Int)
  /-- The remainder of an even integer by 2. -/
  | Rem2 (a1 : T)

namespace Node

variable {T U : Type}

/-- The node with its children mapped by `f`. -/
def map (f : T → U) : Node T → Node U
  | (.Ev x1) => (.Ev x1)
  | (.Rem2 a1) => (.Rem2 (f a1))

/-- Every child of the node satisfies `P`. -/
def All (P : T → Prop) : Node T → Prop
  | (.Ev x1) => True
  | (.Rem2 a1) => P a1

/-- The nodes have the same arguments, and their children are related by `R`. -/
def Rel (R : T → U → Prop) : Node T → Node U → Prop
  | (.Ev x1), (.Ev x1') => x1 = x1'
  | (.Rem2 a1), (.Rem2 a1') => R a1 a1'
  | _, _ => False

/-- The children of the node, in order. -/
def children : Node T → List T
  | (.Ev x1) => []
  | (.Rem2 a1) => [a1]

/-- Every child of the node satisfies `P` when all its children do. -/
theorem all_iff (P : T → Prop) (n : Node T) : n.All P ↔ ∀ c ∈ n.children, P c := by
  cases n <;> simp [All, children, or_imp, forall_and]

end Node

end EvenMod
