-- Generated by kanon from bool.kn, num.kn. Do not edit.
import L1.Statements.Bool.not_
import L1.Soundness.Laws
import L1.Instance
import KanonBool.Soundness.Bool.not_

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L1

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bool.not_.r_true_.main.ok : Bool.not_.r_true_.main.Stmt :=
  fun O hO => KanonBool.Bool.not_.r_true_.main.ok (S := sem) boolSyntax
  (Ops.toBool O) (Ops.Sound.toBool hO)

theorem Bool.not_.r_true_.proof : Bool.not_.r_true_.Stmt := by
  intro O hO sv res h
  simp only [Bool.not_.r_true_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.not_.r_true_.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Bool.not_.r_false_.main.ok : Bool.not_.r_false_.main.Stmt :=
  fun O hO => KanonBool.Bool.not_.r_false_.main.ok (S := sem) boolSyntax
  (Ops.toBool O) (Ops.Sound.toBool hO)

theorem Bool.not_.r_false_.proof : Bool.not_.r_false_.Stmt := by
  intro O hO sv res h
  simp only [Bool.not_.r_false_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.not_.r_false_.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Bool.not_.r_not.main.ok : Bool.not_.r_not.main.Stmt :=
  fun O hO => KanonBool.Bool.not_.r_not.main.ok (S := sem) boolSyntax
  (Ops.toBool O) (Ops.Sound.toBool hO)

theorem Bool.not_.r_not.proof : Bool.not_.r_not.Stmt := by
  intro O hO sv res h
  simp only [Bool.not_.r_not] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.not_.r_not.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Bool.not_.r_or_.main.ok : Bool.not_.r_or_.main.Stmt :=
  fun O hO => KanonBool.Bool.not_.r_or_.main.ok (S := sem) boolSyntax
  (Ops.toBool O) (Ops.Sound.toBool hO)

theorem Bool.not_.r_or_.proof : Bool.not_.r_or_.Stmt := by
  intro O hO sv res h
  simp only [Bool.not_.r_or_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.not_.r_or_.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Bool.not_.r_and_.main.ok : Bool.not_.r_and_.main.Stmt :=
  fun O hO => KanonBool.Bool.not_.r_and_.main.ok (S := sem) boolSyntax
  (Ops.toBool O) (Ops.Sound.toBool hO)

theorem Bool.not_.r_and_.proof : Bool.not_.r_and_.Stmt := by
  intro O hO sv res h
  simp only [Bool.not_.r_and_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.not_.r_and_.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Bool.not_.r_ite.main.ok : Bool.not_.r_ite.main.Stmt :=
  fun O hO => KanonBool.Bool.not_.r_ite.main.ok (S := sem) boolSyntax
  (Ops.toBool O) (Ops.Sound.toBool hO)

theorem Bool.not_.r_ite.proof : Bool.not_.r_ite.Stmt := by
  intro O hO sv res h
  simp only [Bool.not_.r_ite] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.not_.r_ite.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Bool.not_.r_distinct.main.ok : Bool.not_.r_distinct.main.Stmt :=
  fun O hO => KanonBool.Bool.not_.r_distinct.main.ok (S := sem) boolSyntax
  (Ops.toBool O) (Ops.Sound.toBool hO)

theorem Bool.not_.r_distinct.proof : Bool.not_.r_distinct.Stmt := by
  intro O hO sv res h
  simp only [Bool.not_.r_distinct] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.not_.r_distinct.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Bool.not_.r_default.main.ok : Bool.not_.r_default.main.Stmt :=
  fun O hO => KanonBool.Bool.not_.r_default.main.ok (S := sem) boolSyntax
  (Ops.toBool O) (Ops.Sound.toBool hO)

theorem Bool.not_.r_default.proof : Bool.not_.r_default.Stmt := by
  intro O hO sv res h
  simp only [Bool.not_.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.not_.r_default.main.ok O hO)

theorem Bool.not_.step_sound (O : Ops) (hO : O.Sound) (sv : Term) :
  Refines (Bool.not_.spec sv) (Bool.not_.step O sv) := by
  unfold Bool.not_.step
  refine Refinement.firstSome_cons (fun res h => Bool.not_.r_true_.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.not_.r_false_.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.not_.r_not.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.not_.r_or_.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.not_.r_and_.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.not_.r_ite.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.not_.r_distinct.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.not_.r_default.proof O hO sv res h) ?_
  exact Refinement.firstSome_nil

end L1
