-- Generated by kanon from bool.kn, word.kn. Do not edit.
import L4.Statements
import L4.Model.Word.add

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L4

open Classical Kanon

def Word.add.r_plain.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (f : CfgMod.Flags) (n : Int) (v1 : Term) (v2 : Term) (res : Term), Word.add.r_plain O f n v1 v2 = some res →
  Refines (Word.add.spec f n v1 v2) res

def Word.add.r_default.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (f : CfgMod.Flags) (n : Int) (v1 : Term) (v2 : Term) (res : Term), Word.add.r_default O f n v1 v2 = some res →
  Refines (Word.add.spec f n v1 v2) res

def Word.add.r_plain.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (f : CfgMod.Flags) (n : Int) (v1 : Term) (v2 : Term),
  ((decide ((Word.left_lit v1) = (0 : Int))) && (! f.strict)) = true →
  Refines (Word.add.spec f n v1 v2)
  ((Term.mk (Kind.Op2 (Op2.WAdd Word.plain n) v1 v2) (Ty.TWord n)))

def Word.add.r_default.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (f : CfgMod.Flags) (n : Int) (v1 : Term) (v2 : Term),
  Refines (Word.add.spec f n v1 v2)
  ((Term.mk (Kind.Op2 (Op2.WAdd f n) v1 v2) (Ty.TWord n)))

end L4
