-- Generated by kanon from bool.kn, word.kn. Do not edit.
import L4.Statements
import L4.Model.Word.choose

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L4

open Classical Kanon

def Word.choose.r_main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (g : Term) (a : Term) (b : Term) (res : Term), Word.choose.r_main O g a b = some res →
  Refines (Word.choose.spec g a b) res

def Word.choose.r_main.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (g : Term) (a : Term) (b : Term),
  Refines (Word.choose.spec g a b)
  ((O.bool_ite g a b))

end L4
