-- Generated by kanon from bool.kn, word.kn. Do not edit.
import L4.Statements
import L4.Model.Word.double_closed

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace L4

open Classical Kanon

def Word.double_closed.r_main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (n : Int) (v : Term) (res : Term), Word.double_closed.r_main O n v = some res →
  Refines (Word.double_closed.spec n v) res

def Word.double_closed.r_main.main.Stmt : Prop :=
  ∀ (O : Ops), O.Sound →
  ∀ (n : Int) (v : Term),
  Refines (Word.double_closed.spec n v)
  ((Term.mk (Kind.Op2 (Op2.WAdd Word.plain n) v v) (Ty.TWord n)))

end L4
