-- Generated by kanon from mix.knl, mix.kn. Do not edit.
import MixMod.Statements

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace MixMod

open Classical Kanon

def Neg.neg.r_rem.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LNum : NumMod.Syntax B LBool} {LEven : EvenMod.Syntax B LBool LNum} {LNeg : NegMod.Syntax B LBool LNum} (L : MixMod.Syntax B LBool LNum LEven LNeg) [KanonBool.Sem LBool] [NumMod.Sem LNum] [EvenMod.Sem LEven] [NegMod.Sem LNeg] [Sem L] (O : Ops L), O.Sound →
  ∀ (a : S.Term) (t__3 : S.Ty),
  (LEven.even_is_ev a) = true →
  S.Refines (NegMod.Neg.neg.spec LNeg (B.node (LEven.Rem2K a) t__3))
  ((B.node (LNum.NumK (0 : Int)) LNum.TNum))

end MixMod
