-- Generated by kanon from bool.knl, bool.kn. Do not edit.
import KanonCore.Attr
import KanonBool.Sem

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace KanonBool

open Classical Kanon

def Bool.and_.spec {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} (L : KanonBool.Syntax B) (v1 : S.Term) (v2 : S.Term) : S.Term :=
  (B.node (L.AndK v1 v2) L.TBool)

def Bool.or_.spec {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} (L : KanonBool.Syntax B) (v1 : S.Term) (v2 : S.Term) : S.Term :=
  (B.node (L.OrK v1 v2) L.TBool)

def Bool.not_.spec {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} (L : KanonBool.Syntax B) (sv : S.Term) : S.Term :=
  (B.node (L.NotK sv) L.TBool)

def Bool.ite.spec {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} (L : KanonBool.Syntax B) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) : S.Term :=
  (B.node (L.IteK guard if_ else_) (S.ty if_))

def Bool.eq.spec {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} (L : KanonBool.Syntax B) (v1 : S.Term) (v2 : S.Term) : S.Term :=
  (B.node (L.EqK v1 v2) L.TBool)

def Bool.eq_untyped.spec {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} (L : KanonBool.Syntax B) (v1 : S.Term) (v2 : S.Term) : S.Term :=
  (B.node (L.EqK v1 v2) L.TBool)

def Bool.distinct.spec {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} (L : KanonBool.Syntax B) (l : (List S.Term)) : S.Term :=
  (B.node (L.DistinctK l) L.TBool)

attribute [kanon_spec]
  Bool.and_.spec
  Bool.or_.spec
  Bool.not_.spec
  Bool.ite.spec
  Bool.eq.spec
  Bool.eq_untyped.spec
  Bool.distinct.spec

/-- The rule functions, oracles and helpers of the module `Bool` in the model of a
language. -/
structure Ops {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} (L : KanonBool.Syntax B) extends
    toBase : Kanon.OpsBase S where
  bool_and_ : S.Term → S.Term → S.Term
  bool_or_ : S.Term → S.Term → S.Term
  bool_not_ : S.Term → S.Term
  bool_ite : S.Term → S.Term → S.Term → S.Term
  bool_eq : S.Term → S.Term → S.Term
  bool_eq_untyped : S.Term → S.Term → S.Term
  bool_distinct : (List S.Term) → S.Term
  bool_sort_by_tag : (List S.Term) → (List S.Term)

/-- What the proofs assume of the model: its rule functions refine their specs, and the
equations of its helpers. -/
structure Ops.Sound {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {L : KanonBool.Syntax B} [Sem L] (O : Ops L) : Prop where
  bool_and_ : ∀ (v1 : S.Term) (v2 : S.Term), S.Refines (KanonBool.Bool.and_.spec L v1 v2) (O.bool_and_ v1 v2)
  bool_or_ : ∀ (v1 : S.Term) (v2 : S.Term), S.Refines (KanonBool.Bool.or_.spec L v1 v2) (O.bool_or_ v1 v2)
  bool_not_ : ∀ (sv : S.Term), S.Refines (KanonBool.Bool.not_.spec L sv) (O.bool_not_ sv)
  bool_ite : ∀ (guard : S.Term) (if_ : S.Term) (else_ : S.Term), S.Refines (KanonBool.Bool.ite.spec L guard if_ else_) (O.bool_ite guard if_ else_)
  bool_eq : ∀ (v1 : S.Term) (v2 : S.Term), S.Refines (KanonBool.Bool.eq.spec L v1 v2) (O.bool_eq v1 v2)
  bool_eq_untyped : ∀ (v1 : S.Term) (v2 : S.Term), S.Refines (KanonBool.Bool.eq_untyped.spec L v1 v2) (O.bool_eq_untyped v1 v2)
  bool_distinct : ∀ (l : (List S.Term)), S.Refines (KanonBool.Bool.distinct.spec L l) (O.bool_distinct l)
  bool_orc : Oracle.Compat L O.bool_sort_by_tag

end KanonBool
