-- Generated by kanon from bool.knl, bool.kn. Do not edit.
import KanonBool.Statements
import KanonBool.Proofs

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace KanonBool

open Classical Kanon

set_option maxHeartbeats 400000 in
@[kanon_comm_lemma] theorem And.comm.ok : And.comm.Stmt :=
  no_implicit_lambda% (kanon_proof% And.comm)

set_option maxHeartbeats 400000 in
@[kanon_comm_lemma] theorem Or.comm.ok : Or.comm.Stmt :=
  no_implicit_lambda% (kanon_proof% Or.comm)

set_option maxHeartbeats 400000 in
@[kanon_comm_lemma] theorem Eq.comm.ok : Eq.comm.Stmt :=
  no_implicit_lambda% (kanon_proof% Eq.comm)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_same.main.ok : Bool.and_.r_same.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.and_.r_same.main)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_false_.main.ok : Bool.and_.r_false_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.and_.r_false_.main)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_false_.swap.ok : Bool.and_.r_false_.swap.Stmt := by
  intro S _ _ O hO v1 t__2
  refine Kanon.Sem.Refines.trans ?_ (Bool.and_.r_false_.main.ok O hO v1 t__2)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.And.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_true_.main.ok : Bool.and_.r_true_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.and_.r_true_.main)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_true_.swap.ok : Bool.and_.r_true_.swap.Stmt := by
  intro S _ _ O hO v1 t__2
  refine Kanon.Sem.Refines.trans ?_ (Bool.and_.r_true_.main.ok O hO v1 t__2)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.And.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_not.main.ok : Bool.and_.r_not.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.and_.r_not.main)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_not.swap.ok : Bool.and_.r_not.swap.Stmt := by
  intro S _ _ O hO v2 kanon__3 t__4 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bool.and_.r_not.main.ok O hO v2 kanon__3 t__4 hg)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.And.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_and_.main.ok : Bool.and_.r_and_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.and_.r_and_.main)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_and_.swap1.ok : Bool.and_.r_and_.swap1.Stmt := by
  intro S _ _ O hO v2 w__3 a t__4 hg
  have : S.Refines (KanonBool.mk (.And w__3 a) t__4)
    (KanonBool.mk (.And a w__3) t__4) :=
    KanonBool.And.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Kanon.Sem.Refines.trans (Bool.and_.r_and_.main.ok O hO v2 a w__3 t__4 hg)
    (by (try dsimp only); (repeat' apply Kanon.Refinement.ite_congr) <;> first | exact Kanon.Sem.Refines.refl | kanon_comm))
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_and_.swap2.ok : Bool.and_.r_and_.swap2.Stmt := by
  intro S _ _ O hO v1 a w__3 t__4 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bool.and_.r_and_.main.ok O hO v1 a w__3 t__4 hg)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.And.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_and_.swap1_swap2.ok : Bool.and_.r_and_.swap1_swap2.Stmt := by
  intro S _ _ O hO v1 w__3 a t__4 hg
  have : S.Refines (KanonBool.mk (.And w__3 a) t__4)
    (KanonBool.mk (.And a w__3) t__4) :=
    KanonBool.And.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Kanon.Sem.Refines.trans (Bool.and_.r_and_.main.ok O hO v1 a w__3 t__4 hg)
    (by (try dsimp only); (repeat' apply Kanon.Refinement.ite_congr) <;> first | exact Kanon.Sem.Refines.refl | kanon_comm))
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.And.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_or_.main.ok : Bool.and_.r_or_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.and_.r_or_.main)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_or_.swap1.ok : Bool.and_.r_or_.swap1.Stmt := by
  intro S _ _ O hO v2 w__3 a t__4 hg
  have : S.Refines (KanonBool.mk (.Or w__3 a) t__4)
    (KanonBool.mk (.Or a w__3) t__4) :=
    KanonBool.Or.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.and_.r_or_.main.ok O hO v2 a w__3 t__4 hg)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_or_.swap2.ok : Bool.and_.r_or_.swap2.Stmt := by
  intro S _ _ O hO v1 a w__3 t__4 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bool.and_.r_or_.main.ok O hO v1 a w__3 t__4 hg)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.And.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_or_.swap1_swap2.ok : Bool.and_.r_or_.swap1_swap2.Stmt := by
  intro S _ _ O hO v1 w__3 a t__4 hg
  have : S.Refines (KanonBool.mk (.Or w__3 a) t__4)
    (KanonBool.mk (.Or a w__3) t__4) :=
    KanonBool.Or.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.and_.r_or_.main.ok O hO v1 a w__3 t__4 hg)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.And.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_eq_neq.main.ok : Bool.and_.r_eq_neq.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.and_.r_eq_neq.main)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_eq_neq.swap2.ok : Bool.and_.r_eq_neq.swap2.Stmt := by
  intro S _ _ O hO a x t__4 y kanon__7 t__9 hg
  have : S.Refines (KanonBool.mk (.Eq y kanon__7) t__9)
    (KanonBool.mk (.Eq kanon__7 y) t__9) :=
    KanonBool.Eq.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.and_.r_eq_neq.main.ok O hO a x t__4 kanon__7 y t__9 hg)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_eq_neq.swap1.ok : Bool.and_.r_eq_neq.swap1.Stmt := by
  intro S _ _ O hO x a t__4 kanon__7 y t__9 hg
  have : S.Refines (KanonBool.mk (.Eq x a) t__4)
    (KanonBool.mk (.Eq a x) t__4) :=
    KanonBool.Eq.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.and_.r_eq_neq.main.ok O hO a x t__4 kanon__7 y t__9 hg)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_eq_neq.swap1_swap2.ok : Bool.and_.r_eq_neq.swap1_swap2.Stmt := by
  intro S _ _ O hO x a t__4 y kanon__7 t__9 hg
  have : S.Refines (KanonBool.mk (.Eq x a) t__4)
    (KanonBool.mk (.Eq a x) t__4) :=
    KanonBool.Eq.comm.ok ..
  have : S.Refines (KanonBool.mk (.Eq y kanon__7) t__9)
    (KanonBool.mk (.Eq kanon__7 y) t__9) :=
    KanonBool.Eq.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.and_.r_eq_neq.main.ok O hO a x t__4 kanon__7 y t__9 hg)
  simp only [KanonBool.Bool.and_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_default.main.ok : Bool.and_.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.and_.r_default.main)

theorem Bool.and_.r_same.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.and_.r_same O v1 v2 = some res) : S.Refines (KanonBool.Bool.and_.spec v1 v2) res := by
  simp only [Bool.and_.r_same] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.and_.r_same.main.ok O hO)

theorem Bool.and_.r_false_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.and_.r_false_ O v1 v2 = some res) : S.Refines (KanonBool.Bool.and_.spec v1 v2) res := by
  simp only [Bool.and_.r_false_] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.and_.r_false_.main.ok O hO)
  · kanon_arm h (Bool.and_.r_false_.swap.ok O hO)

theorem Bool.and_.r_true_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.and_.r_true_ O v1 v2 = some res) : S.Refines (KanonBool.Bool.and_.spec v1 v2) res := by
  simp only [Bool.and_.r_true_] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.and_.r_true_.main.ok O hO)
  · kanon_arm h (Bool.and_.r_true_.swap.ok O hO)

theorem Bool.and_.r_not.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.and_.r_not O v1 v2 = some res) : S.Refines (KanonBool.Bool.and_.spec v1 v2) res := by
  simp only [Bool.and_.r_not] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.and_.r_not.main.ok O hO)
  · kanon_arm h (Bool.and_.r_not.swap.ok O hO)

theorem Bool.and_.r_and_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.and_.r_and_ O v1 v2 = some res) : S.Refines (KanonBool.Bool.and_.spec v1 v2) res := by
  simp only [Bool.and_.r_and_] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.and_.r_and_.main.ok O hO)
  · kanon_arm h (Bool.and_.r_and_.swap1.ok O hO)
  · kanon_arm h (Bool.and_.r_and_.swap2.ok O hO)
  · kanon_arm h (Bool.and_.r_and_.swap1_swap2.ok O hO)

theorem Bool.and_.r_or_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.and_.r_or_ O v1 v2 = some res) : S.Refines (KanonBool.Bool.and_.spec v1 v2) res := by
  simp only [Bool.and_.r_or_] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.and_.r_or_.main.ok O hO)
  · kanon_arm h (Bool.and_.r_or_.swap1.ok O hO)
  · kanon_arm h (Bool.and_.r_or_.swap2.ok O hO)
  · kanon_arm h (Bool.and_.r_or_.swap1_swap2.ok O hO)

theorem Bool.and_.r_eq_neq.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.and_.r_eq_neq O v1 v2 = some res) : S.Refines (KanonBool.Bool.and_.spec v1 v2) res := by
  simp only [Bool.and_.r_eq_neq] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.and_.r_eq_neq.main.ok O hO)
  · kanon_arm h (Bool.and_.r_eq_neq.swap2.ok O hO)
  · kanon_arm h (Bool.and_.r_eq_neq.swap1.ok O hO)
  · kanon_arm h (Bool.and_.r_eq_neq.swap1_swap2.ok O hO)

theorem Bool.and_.r_default.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.and_.r_default O v1 v2 = some res) : S.Refines (KanonBool.Bool.and_.spec v1 v2) res := by
  simp only [Bool.and_.r_default] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.and_.r_default.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Bool.or_.r_same.main.ok : Bool.or_.r_same.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.or_.r_same.main)

set_option maxHeartbeats 400000 in
theorem Bool.or_.r_true_.main.ok : Bool.or_.r_true_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.or_.r_true_.main)

set_option maxHeartbeats 400000 in
theorem Bool.or_.r_true_.swap.ok : Bool.or_.r_true_.swap.Stmt := by
  intro S _ _ O hO v1 t__2
  refine Kanon.Sem.Refines.trans ?_ (Bool.or_.r_true_.main.ok O hO v1 t__2)
  simp only [KanonBool.Bool.or_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Or.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.or_.r_false_.main.ok : Bool.or_.r_false_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.or_.r_false_.main)

set_option maxHeartbeats 400000 in
theorem Bool.or_.r_false_.swap.ok : Bool.or_.r_false_.swap.Stmt := by
  intro S _ _ O hO v1 t__2
  refine Kanon.Sem.Refines.trans ?_ (Bool.or_.r_false_.main.ok O hO v1 t__2)
  simp only [KanonBool.Bool.or_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Or.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.or_.r_not.main.ok : Bool.or_.r_not.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.or_.r_not.main)

set_option maxHeartbeats 400000 in
theorem Bool.or_.r_not.swap.ok : Bool.or_.r_not.swap.Stmt := by
  intro S _ _ O hO v2 kanon__3 t__4 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bool.or_.r_not.main.ok O hO v2 kanon__3 t__4 hg)
  simp only [KanonBool.Bool.or_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Or.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.or_.r_or_.main.ok : Bool.or_.r_or_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.or_.r_or_.main)

set_option maxHeartbeats 400000 in
theorem Bool.or_.r_or_.swap1.ok : Bool.or_.r_or_.swap1.Stmt := by
  intro S _ _ O hO v2 w__3 a t__4 hg
  have : S.Refines (KanonBool.mk (.Or w__3 a) t__4)
    (KanonBool.mk (.Or a w__3) t__4) :=
    KanonBool.Or.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Kanon.Sem.Refines.trans (Bool.or_.r_or_.main.ok O hO v2 a w__3 t__4 hg)
    (by (try dsimp only); (repeat' apply Kanon.Refinement.ite_congr) <;> first | exact Kanon.Sem.Refines.refl | kanon_comm))
  simp only [KanonBool.Bool.or_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.or_.r_or_.swap2.ok : Bool.or_.r_or_.swap2.Stmt := by
  intro S _ _ O hO v1 a w__3 t__4 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bool.or_.r_or_.main.ok O hO v1 a w__3 t__4 hg)
  simp only [KanonBool.Bool.or_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Or.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.or_.r_or_.swap1_swap2.ok : Bool.or_.r_or_.swap1_swap2.Stmt := by
  intro S _ _ O hO v1 w__3 a t__4 hg
  have : S.Refines (KanonBool.mk (.Or w__3 a) t__4)
    (KanonBool.mk (.Or a w__3) t__4) :=
    KanonBool.Or.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Kanon.Sem.Refines.trans (Bool.or_.r_or_.main.ok O hO v1 a w__3 t__4 hg)
    (by (try dsimp only); (repeat' apply Kanon.Refinement.ite_congr) <;> first | exact Kanon.Sem.Refines.refl | kanon_comm))
  simp only [KanonBool.Bool.or_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Or.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.or_.r_and_.main.ok : Bool.or_.r_and_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.or_.r_and_.main)

set_option maxHeartbeats 400000 in
theorem Bool.or_.r_and_.swap1.ok : Bool.or_.r_and_.swap1.Stmt := by
  intro S _ _ O hO v2 w__3 a t__4 hg
  have : S.Refines (KanonBool.mk (.And w__3 a) t__4)
    (KanonBool.mk (.And a w__3) t__4) :=
    KanonBool.And.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.or_.r_and_.main.ok O hO v2 a w__3 t__4 hg)
  simp only [KanonBool.Bool.or_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.or_.r_and_.swap2.ok : Bool.or_.r_and_.swap2.Stmt := by
  intro S _ _ O hO v1 a w__3 t__4 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bool.or_.r_and_.main.ok O hO v1 a w__3 t__4 hg)
  simp only [KanonBool.Bool.or_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Or.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.or_.r_and_.swap1_swap2.ok : Bool.or_.r_and_.swap1_swap2.Stmt := by
  intro S _ _ O hO v1 w__3 a t__4 hg
  have : S.Refines (KanonBool.mk (.And w__3 a) t__4)
    (KanonBool.mk (.And a w__3) t__4) :=
    KanonBool.And.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.or_.r_and_.main.ok O hO v1 a w__3 t__4 hg)
  simp only [KanonBool.Bool.or_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Or.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.or_.r_default.main.ok : Bool.or_.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.or_.r_default.main)

theorem Bool.or_.r_same.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.or_.r_same O v1 v2 = some res) : S.Refines (KanonBool.Bool.or_.spec v1 v2) res := by
  simp only [Bool.or_.r_same] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.or_.r_same.main.ok O hO)

theorem Bool.or_.r_true_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.or_.r_true_ O v1 v2 = some res) : S.Refines (KanonBool.Bool.or_.spec v1 v2) res := by
  simp only [Bool.or_.r_true_] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.or_.r_true_.main.ok O hO)
  · kanon_arm h (Bool.or_.r_true_.swap.ok O hO)

theorem Bool.or_.r_false_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.or_.r_false_ O v1 v2 = some res) : S.Refines (KanonBool.Bool.or_.spec v1 v2) res := by
  simp only [Bool.or_.r_false_] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.or_.r_false_.main.ok O hO)
  · kanon_arm h (Bool.or_.r_false_.swap.ok O hO)

theorem Bool.or_.r_not.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.or_.r_not O v1 v2 = some res) : S.Refines (KanonBool.Bool.or_.spec v1 v2) res := by
  simp only [Bool.or_.r_not] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.or_.r_not.main.ok O hO)
  · kanon_arm h (Bool.or_.r_not.swap.ok O hO)

theorem Bool.or_.r_or_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.or_.r_or_ O v1 v2 = some res) : S.Refines (KanonBool.Bool.or_.spec v1 v2) res := by
  simp only [Bool.or_.r_or_] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.or_.r_or_.main.ok O hO)
  · kanon_arm h (Bool.or_.r_or_.swap1.ok O hO)
  · kanon_arm h (Bool.or_.r_or_.swap2.ok O hO)
  · kanon_arm h (Bool.or_.r_or_.swap1_swap2.ok O hO)

theorem Bool.or_.r_and_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.or_.r_and_ O v1 v2 = some res) : S.Refines (KanonBool.Bool.or_.spec v1 v2) res := by
  simp only [Bool.or_.r_and_] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.or_.r_and_.main.ok O hO)
  · kanon_arm h (Bool.or_.r_and_.swap1.ok O hO)
  · kanon_arm h (Bool.or_.r_and_.swap2.ok O hO)
  · kanon_arm h (Bool.or_.r_and_.swap1_swap2.ok O hO)

theorem Bool.or_.r_default.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.or_.r_default O v1 v2 = some res) : S.Refines (KanonBool.Bool.or_.spec v1 v2) res := by
  simp only [Bool.or_.r_default] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.or_.r_default.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Bool.not_.r_true_.main.ok : Bool.not_.r_true_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.not_.r_true_.main)

set_option maxHeartbeats 400000 in
theorem Bool.not_.r_false_.main.ok : Bool.not_.r_false_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.not_.r_false_.main)

set_option maxHeartbeats 400000 in
theorem Bool.not_.r_not.main.ok : Bool.not_.r_not.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.not_.r_not.main)

set_option maxHeartbeats 400000 in
theorem Bool.not_.r_or_.main.ok : Bool.not_.r_or_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.not_.r_or_.main)

set_option maxHeartbeats 400000 in
theorem Bool.not_.r_and_.main.ok : Bool.not_.r_and_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.not_.r_and_.main)

set_option maxHeartbeats 400000 in
theorem Bool.not_.r_ite.main.ok : Bool.not_.r_ite.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.not_.r_ite.main)

set_option maxHeartbeats 400000 in
theorem Bool.not_.r_distinct.main.ok : Bool.not_.r_distinct.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.not_.r_distinct.main)

set_option maxHeartbeats 400000 in
theorem Bool.not_.r_default.main.ok : Bool.not_.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.not_.r_default.main)

theorem Bool.not_.r_true_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (sv : S.Term) (res : S.Term)
    (h : Bool.not_.r_true_ O sv = some res) : S.Refines (KanonBool.Bool.not_.spec sv) res := by
  simp only [Bool.not_.r_true_] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.not_.r_true_.main.ok O hO)

theorem Bool.not_.r_false_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (sv : S.Term) (res : S.Term)
    (h : Bool.not_.r_false_ O sv = some res) : S.Refines (KanonBool.Bool.not_.spec sv) res := by
  simp only [Bool.not_.r_false_] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.not_.r_false_.main.ok O hO)

theorem Bool.not_.r_not.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (sv : S.Term) (res : S.Term)
    (h : Bool.not_.r_not O sv = some res) : S.Refines (KanonBool.Bool.not_.spec sv) res := by
  simp only [Bool.not_.r_not] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.not_.r_not.main.ok O hO)

theorem Bool.not_.r_or_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (sv : S.Term) (res : S.Term)
    (h : Bool.not_.r_or_ O sv = some res) : S.Refines (KanonBool.Bool.not_.spec sv) res := by
  simp only [Bool.not_.r_or_] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.not_.r_or_.main.ok O hO)

theorem Bool.not_.r_and_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (sv : S.Term) (res : S.Term)
    (h : Bool.not_.r_and_ O sv = some res) : S.Refines (KanonBool.Bool.not_.spec sv) res := by
  simp only [Bool.not_.r_and_] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.not_.r_and_.main.ok O hO)

theorem Bool.not_.r_ite.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (sv : S.Term) (res : S.Term)
    (h : Bool.not_.r_ite O sv = some res) : S.Refines (KanonBool.Bool.not_.spec sv) res := by
  simp only [Bool.not_.r_ite] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.not_.r_ite.main.ok O hO)

theorem Bool.not_.r_distinct.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (sv : S.Term) (res : S.Term)
    (h : Bool.not_.r_distinct O sv = some res) : S.Refines (KanonBool.Bool.not_.spec sv) res := by
  simp only [Bool.not_.r_distinct] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.not_.r_distinct.main.ok O hO)

theorem Bool.not_.r_default.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (sv : S.Term) (res : S.Term)
    (h : Bool.not_.r_default O sv = some res) : S.Refines (KanonBool.Bool.not_.spec sv) res := by
  simp only [Bool.not_.r_default] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.not_.r_default.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_true_.main.ok : Bool.ite.r_true_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_true_.main)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_false_.main.ok : Bool.ite.r_false_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_false_.main)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_bool.main.ok : Bool.ite.r_bool.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_bool.main)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_not_bool.main.ok : Bool.ite.r_not_bool.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_not_bool.main)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_false_then.main.ok : Bool.ite.r_false_then.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_false_then.main)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_true_then.main.ok : Bool.ite.r_true_then.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_true_then.main)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_false_else.main.ok : Bool.ite.r_false_else.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_false_else.main)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_true_else.main.ok : Bool.ite.r_true_else.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_true_else.main)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_not_guard.main.ok : Bool.ite.r_not_guard.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_not_guard.main)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_guard_then.main.ok : Bool.ite.r_guard_then.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_guard_then.main)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_guard_else.main.ok : Bool.ite.r_guard_else.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_guard_else.main)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_ite_then.main.ok : Bool.ite.r_ite_then.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_ite_then.main)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_ite_else.main.ok : Bool.ite.r_ite_else.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_ite_else.main)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_and_ite_then.main.ok : Bool.ite.r_and_ite_then.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_and_ite_then.main)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_and_ite_then.swap.ok : Bool.ite.r_and_ite_then.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_and_ite_then.swap)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_or_ite_else.main.ok : Bool.ite.r_or_ite_else.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_or_ite_else.main)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_or_ite_else.swap.ok : Bool.ite.r_or_ite_else.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_or_ite_else.swap)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_same.main.ok : Bool.ite.r_same.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_same.main)

set_option maxHeartbeats 400000 in
theorem Bool.ite.r_default.main.ok : Bool.ite.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.ite.r_default.main)

theorem Bool.ite.r_true_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_true_ O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_true_] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_true_.main.ok O hO)

theorem Bool.ite.r_false_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_false_ O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_false_] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_false_.main.ok O hO)

theorem Bool.ite.r_bool.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_bool O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_bool] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_bool.main.ok O hO)

theorem Bool.ite.r_not_bool.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_not_bool O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_not_bool] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_not_bool.main.ok O hO)

theorem Bool.ite.r_false_then.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_false_then O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_false_then] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_false_then.main.ok O hO)

theorem Bool.ite.r_true_then.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_true_then O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_true_then] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_true_then.main.ok O hO)

theorem Bool.ite.r_false_else.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_false_else O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_false_else] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_false_else.main.ok O hO)

theorem Bool.ite.r_true_else.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_true_else O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_true_else] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_true_else.main.ok O hO)

theorem Bool.ite.r_not_guard.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_not_guard O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_not_guard] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_not_guard.main.ok O hO)

theorem Bool.ite.r_guard_then.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_guard_then O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_guard_then] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_guard_then.main.ok O hO)

theorem Bool.ite.r_guard_else.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_guard_else O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_guard_else] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_guard_else.main.ok O hO)

theorem Bool.ite.r_ite_then.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_ite_then O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_ite_then] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_ite_then.main.ok O hO)

theorem Bool.ite.r_ite_else.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_ite_else O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_ite_else] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_ite_else.main.ok O hO)

theorem Bool.ite.r_and_ite_then.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_and_ite_then O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_and_ite_then] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_and_ite_then.main.ok O hO)
  · kanon_arm h (Bool.ite.r_and_ite_then.swap.ok O hO)

theorem Bool.ite.r_or_ite_else.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_or_ite_else O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_or_ite_else] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_or_ite_else.main.ok O hO)
  · kanon_arm h (Bool.ite.r_or_ite_else.swap.ok O hO)

theorem Bool.ite.r_same.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_same O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_same] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_same.main.ok O hO)

theorem Bool.ite.r_default.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (guard : S.Term) (if_ : S.Term) (else_ : S.Term) (res : S.Term)
    (h : Bool.ite.r_default O guard if_ else_ = some res) : S.Refines (KanonBool.Bool.ite.spec guard if_ else_) res := by
  simp only [Bool.ite.r_default] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.ite.r_default.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_same.main.ok : Bool.eq.r_same.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_same.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_bools.main.ok : Bool.eq.r_bools.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_bools.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_ite_ite.main.ok : Bool.eq.r_ite_ite.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_ite_ite.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_false_.main.ok : Bool.eq.r_false_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_false_.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_false_.swap.ok : Bool.eq.r_false_.swap.Stmt := by
  intro S _ _ O hO v1 t__2
  refine Kanon.Sem.Refines.trans ?_ (Bool.eq.r_false_.main.ok O hO v1 t__2)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_true_.main.ok : Bool.eq.r_true_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_true_.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_true_.swap.ok : Bool.eq.r_true_.swap.Stmt := by
  intro S _ _ O hO v1 t__2
  refine Kanon.Sem.Refines.trans ?_ (Bool.eq.r_true_.main.ok O hO v1 t__2)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_nots.main.ok : Bool.eq.r_nots.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_nots.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_default.main.ok : Bool.eq.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_default.main)

theorem Bool.eq.r_same.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_same O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  simp only [Bool.eq.r_same] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_same.main.ok O hO)

theorem Bool.eq.r_bools.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_bools O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  simp only [Bool.eq.r_bools] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_bools.main.ok O hO)

theorem Bool.eq.r_ite_ite.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_ite_ite O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  simp only [Bool.eq.r_ite_ite] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_ite_ite.main.ok O hO)

theorem Bool.eq.r_false_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_false_ O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  simp only [Bool.eq.r_false_] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_false_.main.ok O hO)
  · kanon_arm h (Bool.eq.r_false_.swap.ok O hO)

theorem Bool.eq.r_true_.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_true_ O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  simp only [Bool.eq.r_true_] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_true_.main.ok O hO)
  · kanon_arm h (Bool.eq.r_true_.swap.ok O hO)

theorem Bool.eq.r_nots.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_nots O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  simp only [Bool.eq.r_nots] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_nots.main.ok O hO)

theorem Bool.eq.r_default.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_default O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  simp only [Bool.eq.r_default] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_default.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Bool.eq_untyped.r_ill_typed.main.ok : Bool.eq_untyped.r_ill_typed.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq_untyped.r_ill_typed.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq_untyped.r_typed.main.ok : Bool.eq_untyped.r_typed.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq_untyped.r_typed.main)

theorem Bool.eq_untyped.r_ill_typed.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq_untyped.r_ill_typed O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq_untyped.spec v1 v2) res := by
  simp only [Bool.eq_untyped.r_ill_typed] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq_untyped.r_ill_typed.main.ok O hO)

theorem Bool.eq_untyped.r_typed.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq_untyped.r_typed O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq_untyped.spec v1 v2) res := by
  simp only [Bool.eq_untyped.r_typed] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq_untyped.r_typed.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Bool.distinct.r_small.main.ok : Bool.distinct.r_small.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.distinct.r_small.main)

set_option maxHeartbeats 400000 in
theorem Bool.distinct.r_distinct.main.ok : Bool.distinct.r_distinct.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.distinct.r_distinct.main)

set_option maxHeartbeats 400000 in
theorem Bool.distinct.r_not_distinct.main.ok : Bool.distinct.r_not_distinct.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.distinct.r_not_distinct.main)

set_option maxHeartbeats 400000 in
theorem Bool.distinct.r_default.main.ok : Bool.distinct.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.distinct.r_default.main)

theorem Bool.distinct.r_small.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (l : (List S.Term)) (res : S.Term)
    (h : Bool.distinct.r_small O l = some res) : S.Refines (KanonBool.Bool.distinct.spec l) res := by
  simp only [Bool.distinct.r_small] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.distinct.r_small.main.ok O hO)

theorem Bool.distinct.r_distinct.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (l : (List S.Term)) (res : S.Term)
    (h : Bool.distinct.r_distinct O l = some res) : S.Refines (KanonBool.Bool.distinct.spec l) res := by
  simp only [Bool.distinct.r_distinct] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.distinct.r_distinct.main.ok O hO)

theorem Bool.distinct.r_not_distinct.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (l : (List S.Term)) (res : S.Term)
    (h : Bool.distinct.r_not_distinct O l = some res) : S.Refines (KanonBool.Bool.distinct.spec l) res := by
  simp only [Bool.distinct.r_not_distinct] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.distinct.r_not_distinct.main.ok O hO)

theorem Bool.distinct.r_default.sound {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S) (hO : O.Sound) (l : (List S.Term)) (res : S.Term)
    (h : Bool.distinct.r_default O l = some res) : S.Refines (KanonBool.Bool.distinct.spec l) res := by
  simp only [Bool.distinct.r_default] at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.distinct.r_default.main.ok O hO)

set_option maxHeartbeats 400000 in
theorem Bool.sure_neq.c1.ok : Bool.sure_neq.c1.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.sure_neq.c1)

set_option maxHeartbeats 400000 in
theorem Bool.sure_neq.c2.ok : Bool.sure_neq.c2.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.sure_neq.c2)

set_option maxHeartbeats 400000 in
theorem Bool.sure_neq.default.ok : Bool.sure_neq.default.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.sure_neq.default)

end KanonBool
