-- Generated by kanon from bool.knl, bool.kn. Do not edit.
import KanonBool.Model
import KanonCore.Proof

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace KanonBool

open Classical Kanon

namespace Lib

variable {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] {O : Ops S}

theorem lift_bool_and_ (hO : O.Sound) {v1 v1' : S.Term} {v2 v2' : S.Term}
  (h_v1 : S.Refines v1 v1')
  (h_v2 : S.Refines v2 v2') :
  S.Refines (KanonBool.Bool.and_.spec v1 v2) (O.bool_and_ v1' v2') :=
  Kanon.Sem.Refines.trans (by simp only [kanon_spec]; kanon_congr) (hO.bool_and_ v1' v2')

theorem lift_bool_or_ (hO : O.Sound) {v1 v1' : S.Term} {v2 v2' : S.Term}
  (h_v1 : S.Refines v1 v1')
  (h_v2 : S.Refines v2 v2') :
  S.Refines (KanonBool.Bool.or_.spec v1 v2) (O.bool_or_ v1' v2') :=
  Kanon.Sem.Refines.trans (by simp only [kanon_spec]; kanon_congr) (hO.bool_or_ v1' v2')

theorem lift_bool_not_ (hO : O.Sound) {sv sv' : S.Term}
  (h_sv : S.Refines sv sv') :
  S.Refines (KanonBool.Bool.not_.spec sv) (O.bool_not_ sv') :=
  Kanon.Sem.Refines.trans (by simp only [kanon_spec]; kanon_congr) (hO.bool_not_ sv')

theorem lift_bool_ite (hO : O.Sound) {guard guard' : S.Term} {if_ if_' : S.Term} {else_ else_' : S.Term}
  (h_guard : S.Refines guard guard')
  (h_if_ : S.Refines if_ if_')
  (h_else_ : S.Refines else_ else_') :
  S.Refines (KanonBool.Bool.ite.spec guard if_ else_) (O.bool_ite guard' if_' else_') :=
  Kanon.Sem.Refines.trans (by simp only [kanon_spec]; kanon_congr) (hO.bool_ite guard' if_' else_')

theorem lift_bool_eq (hO : O.Sound) {v1 v1' : S.Term} {v2 v2' : S.Term}
  (h_v1 : S.Refines v1 v1')
  (h_v2 : S.Refines v2 v2') :
  S.Refines (KanonBool.Bool.eq.spec v1 v2) (O.bool_eq v1' v2') :=
  Kanon.Sem.Refines.trans (by simp only [kanon_spec]; kanon_congr) (hO.bool_eq v1' v2')

theorem lift_bool_eq_untyped (hO : O.Sound) {v1 v1' : S.Term} {v2 v2' : S.Term}
  (h_v1 : S.Refines v1 v1')
  (h_v2 : S.Refines v2 v2') :
  S.Refines (KanonBool.Bool.eq_untyped.spec v1 v2) (O.bool_eq_untyped v1' v2') :=
  Kanon.Sem.Refines.trans (by simp only [kanon_spec]; kanon_congr) (hO.bool_eq_untyped v1' v2')

theorem lift_bool_distinct (hO : O.Sound) {l : (List S.Term)} :
  S.Refines (KanonBool.Bool.distinct.spec l) (O.bool_distinct l) :=
  hO.bool_distinct l

end Lib

/-- The operands of `And` commute. -/
def And.comm.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (a b : S.Term) (t : S.Ty),
  S.Refines (KanonBool.mk (.And a b) t)
  (KanonBool.mk (.And b a) t)

/-- The operands of `Or` commute. -/
def Or.comm.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (a b : S.Term) (t : S.Ty),
  S.Refines (KanonBool.mk (.Or a b) t)
  (KanonBool.mk (.Or b a) t)

/-- The operands of `Eq` commute. -/
def Eq.comm.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (a b : S.Term) (t : S.Ty),
  S.Refines (KanonBool.mk (.Eq a b) t)
  (KanonBool.mk (.Eq b a) t)

def Bool.and_.r_same.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term),
  (decide (v1 = v2)) = true →
  S.Refines (KanonBool.Bool.and_.spec v1 v2)
  (v1)

def Bool.and_.r_false_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.and_.spec (KanonBool.mk (.Bool false) t__2) v2)
  (KanonBool.v_false)

def Bool.and_.r_false_.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.and_.spec v1 (KanonBool.mk (.Bool false) t__2))
  (KanonBool.v_false)

def Bool.and_.r_true_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.and_.spec (KanonBool.mk (.Bool true) t__2) v2)
  (v2)

def Bool.and_.r_true_.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.and_.spec v1 (KanonBool.mk (.Bool true) t__2))
  (v1)

def Bool.and_.r_not.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (kanon__3 : S.Term) (t__4 : S.Ty),
  (decide (v1 = kanon__3)) = true →
  S.Refines (KanonBool.Bool.and_.spec v1 (KanonBool.mk (.Not kanon__3) t__4))
  (KanonBool.v_false)

def Bool.and_.r_not.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (kanon__3 : S.Term) (t__4 : S.Ty),
  (decide (v2 = kanon__3)) = true →
  S.Refines (KanonBool.Bool.and_.spec (KanonBool.mk (.Not kanon__3) t__4) v2)
  (KanonBool.v_false)

def Bool.and_.r_and_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (a : S.Term) (w__3 : S.Term) (t__4 : S.Ty),
  (decide (a = v2)) = true →
  S.Refines (KanonBool.Bool.and_.spec (KanonBool.mk (.And a w__3) t__4) v2)
  ((KanonBool.mk (.And a w__3) t__4))

def Bool.and_.r_and_.swap1.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (w__3 : S.Term) (a : S.Term) (t__4 : S.Ty),
  (decide (a = v2)) = true →
  S.Refines (KanonBool.Bool.and_.spec (KanonBool.mk (.And w__3 a) t__4) v2)
  ((KanonBool.mk (.And w__3 a) t__4))

def Bool.and_.r_and_.swap2.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (a : S.Term) (w__3 : S.Term) (t__4 : S.Ty),
  (decide (a = v1)) = true →
  S.Refines (KanonBool.Bool.and_.spec v1 (KanonBool.mk (.And a w__3) t__4))
  ((KanonBool.mk (.And a w__3) t__4))

def Bool.and_.r_and_.swap1_swap2.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (w__3 : S.Term) (a : S.Term) (t__4 : S.Ty),
  (decide (a = v1)) = true →
  S.Refines (KanonBool.Bool.and_.spec v1 (KanonBool.mk (.And w__3 a) t__4))
  ((KanonBool.mk (.And w__3 a) t__4))

def Bool.and_.r_or_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (a : S.Term) (w__3 : S.Term) (t__4 : S.Ty),
  (decide (a = v2)) = true →
  S.Refines (KanonBool.Bool.and_.spec (KanonBool.mk (.Or a w__3) t__4) v2)
  (a)

def Bool.and_.r_or_.swap1.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (w__3 : S.Term) (a : S.Term) (t__4 : S.Ty),
  (decide (a = v2)) = true →
  S.Refines (KanonBool.Bool.and_.spec (KanonBool.mk (.Or w__3 a) t__4) v2)
  (a)

def Bool.and_.r_or_.swap2.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (a : S.Term) (w__3 : S.Term) (t__4 : S.Ty),
  (decide (a = v1)) = true →
  S.Refines (KanonBool.Bool.and_.spec v1 (KanonBool.mk (.Or a w__3) t__4))
  (a)

def Bool.and_.r_or_.swap1_swap2.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (w__3 : S.Term) (a : S.Term) (t__4 : S.Ty),
  (decide (a = v1)) = true →
  S.Refines (KanonBool.Bool.and_.spec v1 (KanonBool.mk (.Or w__3 a) t__4))
  (a)

def Bool.and_.r_eq_neq.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (a : S.Term) (x : S.Term) (t__4 : S.Ty) (kanon__7 : S.Term) (y : S.Term) (t__9 : S.Ty),
  ((decide (a = kanon__7)) && (O.bool_sure_neq x y)) = true →
  S.Refines (KanonBool.Bool.and_.spec (KanonBool.mk (.Eq a x) t__4) (KanonBool.mk (.Eq kanon__7 y) t__9))
  (KanonBool.v_false)

def Bool.and_.r_eq_neq.swap2.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (a : S.Term) (x : S.Term) (t__4 : S.Ty) (y : S.Term) (kanon__7 : S.Term) (t__9 : S.Ty),
  ((decide (a = kanon__7)) && (O.bool_sure_neq x y)) = true →
  S.Refines (KanonBool.Bool.and_.spec (KanonBool.mk (.Eq a x) t__4) (KanonBool.mk (.Eq y kanon__7) t__9))
  (KanonBool.v_false)

def Bool.and_.r_eq_neq.swap1.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (x : S.Term) (a : S.Term) (t__4 : S.Ty) (kanon__7 : S.Term) (y : S.Term) (t__9 : S.Ty),
  ((decide (a = kanon__7)) && (O.bool_sure_neq x y)) = true →
  S.Refines (KanonBool.Bool.and_.spec (KanonBool.mk (.Eq x a) t__4) (KanonBool.mk (.Eq kanon__7 y) t__9))
  (KanonBool.v_false)

def Bool.and_.r_eq_neq.swap1_swap2.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (x : S.Term) (a : S.Term) (t__4 : S.Ty) (y : S.Term) (kanon__7 : S.Term) (t__9 : S.Ty),
  ((decide (a = kanon__7)) && (O.bool_sure_neq x y)) = true →
  S.Refines (KanonBool.Bool.and_.spec (KanonBool.mk (.Eq x a) t__4) (KanonBool.mk (.Eq y kanon__7) t__9))
  (KanonBool.v_false)

def Bool.and_.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term),
  S.Refines (KanonBool.Bool.and_.spec v1 v2)
  ((if O.tag_le v1 v2
   then (KanonBool.mk (.And v1 v2) (KanonBool.sort .TBool))
   else (KanonBool.mk (.And v2 v1) (KanonBool.sort .TBool))))

def Bool.or_.r_same.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term),
  (decide (v1 = v2)) = true →
  S.Refines (KanonBool.Bool.or_.spec v1 v2)
  (v1)

def Bool.or_.r_true_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.or_.spec (KanonBool.mk (.Bool true) t__2) v2)
  (KanonBool.v_true)

def Bool.or_.r_true_.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.or_.spec v1 (KanonBool.mk (.Bool true) t__2))
  (KanonBool.v_true)

def Bool.or_.r_false_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.or_.spec (KanonBool.mk (.Bool false) t__2) v2)
  (v2)

def Bool.or_.r_false_.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.or_.spec v1 (KanonBool.mk (.Bool false) t__2))
  (v1)

def Bool.or_.r_not.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (kanon__3 : S.Term) (t__4 : S.Ty),
  (decide (v1 = kanon__3)) = true →
  S.Refines (KanonBool.Bool.or_.spec v1 (KanonBool.mk (.Not kanon__3) t__4))
  (KanonBool.v_true)

def Bool.or_.r_not.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (kanon__3 : S.Term) (t__4 : S.Ty),
  (decide (v2 = kanon__3)) = true →
  S.Refines (KanonBool.Bool.or_.spec (KanonBool.mk (.Not kanon__3) t__4) v2)
  (KanonBool.v_true)

def Bool.or_.r_or_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (a : S.Term) (w__3 : S.Term) (t__4 : S.Ty),
  (decide (a = v2)) = true →
  S.Refines (KanonBool.Bool.or_.spec (KanonBool.mk (.Or a w__3) t__4) v2)
  ((KanonBool.mk (.Or a w__3) t__4))

def Bool.or_.r_or_.swap1.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (w__3 : S.Term) (a : S.Term) (t__4 : S.Ty),
  (decide (a = v2)) = true →
  S.Refines (KanonBool.Bool.or_.spec (KanonBool.mk (.Or w__3 a) t__4) v2)
  ((KanonBool.mk (.Or w__3 a) t__4))

def Bool.or_.r_or_.swap2.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (a : S.Term) (w__3 : S.Term) (t__4 : S.Ty),
  (decide (a = v1)) = true →
  S.Refines (KanonBool.Bool.or_.spec v1 (KanonBool.mk (.Or a w__3) t__4))
  ((KanonBool.mk (.Or a w__3) t__4))

def Bool.or_.r_or_.swap1_swap2.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (w__3 : S.Term) (a : S.Term) (t__4 : S.Ty),
  (decide (a = v1)) = true →
  S.Refines (KanonBool.Bool.or_.spec v1 (KanonBool.mk (.Or w__3 a) t__4))
  ((KanonBool.mk (.Or w__3 a) t__4))

def Bool.or_.r_and_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (a : S.Term) (w__3 : S.Term) (t__4 : S.Ty),
  (decide (a = v2)) = true →
  S.Refines (KanonBool.Bool.or_.spec (KanonBool.mk (.And a w__3) t__4) v2)
  (a)

def Bool.or_.r_and_.swap1.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (w__3 : S.Term) (a : S.Term) (t__4 : S.Ty),
  (decide (a = v2)) = true →
  S.Refines (KanonBool.Bool.or_.spec (KanonBool.mk (.And w__3 a) t__4) v2)
  (a)

def Bool.or_.r_and_.swap2.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (a : S.Term) (w__3 : S.Term) (t__4 : S.Ty),
  (decide (a = v1)) = true →
  S.Refines (KanonBool.Bool.or_.spec v1 (KanonBool.mk (.And a w__3) t__4))
  (a)

def Bool.or_.r_and_.swap1_swap2.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (w__3 : S.Term) (a : S.Term) (t__4 : S.Ty),
  (decide (a = v1)) = true →
  S.Refines (KanonBool.Bool.or_.spec v1 (KanonBool.mk (.And w__3 a) t__4))
  (a)

def Bool.or_.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term),
  S.Refines (KanonBool.Bool.or_.spec v1 v2)
  ((if O.tag_le v1 v2
   then (KanonBool.mk (.Or v1 v2) (KanonBool.sort .TBool))
   else (KanonBool.mk (.Or v2 v1) (KanonBool.sort .TBool))))

def Bool.not_.r_true_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.not_.spec (KanonBool.mk (.Bool true) t__2))
  (KanonBool.v_false)

def Bool.not_.r_false_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.not_.spec (KanonBool.mk (.Bool false) t__2))
  (KanonBool.v_true)

def Bool.not_.r_not.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (sv : S.Term) (t__3 : S.Ty),
  S.Refines (KanonBool.Bool.not_.spec (KanonBool.mk (.Not sv) t__3))
  (sv)

def Bool.not_.r_or_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term) (t__4 : S.Ty),
  S.Refines (KanonBool.Bool.not_.spec (KanonBool.mk (.Or v1 v2) t__4))
  ((O.bool_and_ (O.bool_not_ v1) (O.bool_not_ v2)))

def Bool.not_.r_and_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term) (t__4 : S.Ty),
  S.Refines (KanonBool.Bool.not_.spec (KanonBool.mk (.And v1 v2) t__4))
  ((O.bool_or_ (O.bool_not_ v1) (O.bool_not_ v2)))

def Bool.not_.r_ite.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (g : S.Term) (a : S.Term) (b : S.Term) (t__5 : S.Ty),
  S.Refines (KanonBool.Bool.not_.spec (KanonBool.mk (.Ite g a b) t__5))
  ((O.bool_ite g (O.bool_not_ a) (O.bool_not_ b)))

def Bool.not_.r_distinct.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (l : S.Term) (r : S.Term) (t__7 : S.Ty),
  S.Refines (KanonBool.Bool.not_.spec (KanonBool.mk (.Distinct (l :: (r :: []))) t__7))
  ((O.bool_eq l r))

def Bool.not_.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (sv : S.Term),
  S.Refines (KanonBool.Bool.not_.spec sv)
  ((KanonBool.mk (.Not sv) (KanonBool.sort .TBool)))

def Bool.ite.r_true_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (if_ : S.Term) (else_ : S.Term) (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.ite.spec (KanonBool.mk (.Bool true) t__2) if_ else_)
  (if_)

def Bool.ite.r_false_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (if_ : S.Term) (else_ : S.Term) (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.ite.spec (KanonBool.mk (.Bool false) t__2) if_ else_)
  (else_)

def Bool.ite.r_bool.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (guard : S.Term) (t__3 : S.Ty) (t__5 : S.Ty),
  S.Refines (KanonBool.Bool.ite.spec guard (KanonBool.mk (.Bool true) t__3) (KanonBool.mk (.Bool false) t__5))
  (guard)

def Bool.ite.r_not_bool.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (guard : S.Term) (t__3 : S.Ty) (t__5 : S.Ty),
  S.Refines (KanonBool.Bool.ite.spec guard (KanonBool.mk (.Bool false) t__3) (KanonBool.mk (.Bool true) t__5))
  ((O.bool_not_ guard))

def Bool.ite.r_false_then.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (guard : S.Term) (else_ : S.Term) (t__3 : S.Ty),
  S.Refines (KanonBool.Bool.ite.spec guard (KanonBool.mk (.Bool false) t__3) else_)
  ((O.bool_and_ (O.bool_not_ guard) else_))

def Bool.ite.r_true_then.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (guard : S.Term) (else_ : S.Term) (t__3 : S.Ty),
  S.Refines (KanonBool.Bool.ite.spec guard (KanonBool.mk (.Bool true) t__3) else_)
  ((O.bool_or_ guard else_))

def Bool.ite.r_false_else.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (guard : S.Term) (if_ : S.Term) (t__4 : S.Ty),
  S.Refines (KanonBool.Bool.ite.spec guard if_ (KanonBool.mk (.Bool false) t__4))
  ((O.bool_and_ guard if_))

def Bool.ite.r_true_else.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (guard : S.Term) (if_ : S.Term) (t__4 : S.Ty),
  S.Refines (KanonBool.Bool.ite.spec guard if_ (KanonBool.mk (.Bool true) t__4))
  ((O.bool_or_ (O.bool_not_ guard) if_))

def Bool.ite.r_not_guard.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (if_ : S.Term) (else_ : S.Term) (g : S.Term) (t__3 : S.Ty),
  S.Refines (KanonBool.Bool.ite.spec (KanonBool.mk (.Not g) t__3) if_ else_)
  ((O.bool_ite g else_ if_))

def Bool.ite.r_guard_then.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (guard : S.Term) (if_ : S.Term) (else_ : S.Term),
  (decide (guard = if_)) = true →
  S.Refines (KanonBool.Bool.ite.spec guard if_ else_)
  ((O.bool_or_ guard else_))

def Bool.ite.r_guard_else.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (guard : S.Term) (if_ : S.Term) (else_ : S.Term),
  (decide (guard = else_)) = true →
  S.Refines (KanonBool.Bool.ite.spec guard if_ else_)
  ((O.bool_and_ guard if_))

def Bool.ite.r_ite_then.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (guard : S.Term) (else_ : S.Term) (kanon__3 : S.Term) (x : S.Term) (w__5 : S.Term) (t__6 : S.Ty),
  (decide (guard = kanon__3)) = true →
  S.Refines (KanonBool.Bool.ite.spec guard (KanonBool.mk (.Ite kanon__3 x w__5) t__6) else_)
  ((O.bool_ite guard x else_))

def Bool.ite.r_ite_else.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (guard : S.Term) (if_ : S.Term) (kanon__4 : S.Term) (w__5 : S.Term) (y : S.Term) (t__7 : S.Ty),
  (decide (guard = kanon__4)) = true →
  S.Refines (KanonBool.Bool.ite.spec guard if_ (KanonBool.mk (.Ite kanon__4 w__5 y) t__7))
  ((O.bool_ite guard if_ y))

def Bool.ite.r_and_ite_then.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (else_ : S.Term) (g : S.Term) (w__3 : S.Term) (t__4 : S.Ty) (kanon__7 : S.Term) (x : S.Term) (w__9 : S.Term) (t__10 : S.Ty),
  (decide (g = kanon__7)) = true →
  S.Refines (KanonBool.Bool.ite.spec (KanonBool.mk (.And g w__3) t__4) (KanonBool.mk (.Ite kanon__7 x w__9) t__10) else_)
  ((O.bool_ite (KanonBool.mk (.And g w__3) t__4) x else_))

def Bool.ite.r_and_ite_then.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (else_ : S.Term) (w__3 : S.Term) (g : S.Term) (t__4 : S.Ty) (kanon__7 : S.Term) (x : S.Term) (w__9 : S.Term) (t__10 : S.Ty),
  (decide (g = kanon__7)) = true →
  S.Refines (KanonBool.Bool.ite.spec (KanonBool.mk (.And w__3 g) t__4) (KanonBool.mk (.Ite kanon__7 x w__9) t__10) else_)
  ((O.bool_ite (KanonBool.mk (.And w__3 g) t__4) x else_))

def Bool.ite.r_or_ite_else.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (if_ : S.Term) (g : S.Term) (w__3 : S.Term) (t__4 : S.Ty) (kanon__8 : S.Term) (w__9 : S.Term) (y : S.Term) (t__11 : S.Ty),
  (decide (g = kanon__8)) = true →
  S.Refines (KanonBool.Bool.ite.spec (KanonBool.mk (.Or g w__3) t__4) if_ (KanonBool.mk (.Ite kanon__8 w__9 y) t__11))
  ((O.bool_ite (KanonBool.mk (.Or g w__3) t__4) if_ y))

def Bool.ite.r_or_ite_else.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (if_ : S.Term) (w__3 : S.Term) (g : S.Term) (t__4 : S.Ty) (kanon__8 : S.Term) (w__9 : S.Term) (y : S.Term) (t__11 : S.Ty),
  (decide (g = kanon__8)) = true →
  S.Refines (KanonBool.Bool.ite.spec (KanonBool.mk (.Or w__3 g) t__4) if_ (KanonBool.mk (.Ite kanon__8 w__9 y) t__11))
  ((O.bool_ite (KanonBool.mk (.Or w__3 g) t__4) if_ y))

def Bool.ite.r_same.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (guard : S.Term) (if_ : S.Term) (else_ : S.Term),
  (decide (if_ = else_)) = true →
  S.Refines (KanonBool.Bool.ite.spec guard if_ else_)
  (if_)

def Bool.ite.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (guard : S.Term) (if_ : S.Term) (else_ : S.Term),
  S.Refines (KanonBool.Bool.ite.spec guard if_ else_)
  ((KanonBool.mk (.Ite guard if_ else_) (S.ty if_)))

def Bool.eq.r_same.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term),
  (decide (v1 = v2)) = true →
  S.Refines (KanonBool.Bool.eq.spec v1 v2)
  (KanonBool.v_true)

def Bool.eq.r_bools.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (b1 : Bool) (t__2 : S.Ty) (b2 : Bool) (t__4 : S.Ty),
  S.Refines (KanonBool.Bool.eq.spec (KanonBool.mk (.Bool b1) t__2) (KanonBool.mk (.Bool b2) t__4))
  ((KanonBool.Bool.of_bool (decide (b1 = b2))))

def Bool.eq.r_ite_ite.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (b : S.Term) (l : S.Term) (r : S.Term) (t__5 : S.Ty) (kanon__7 : S.Term) (l' : S.Term) (r' : S.Term) (t__10 : S.Ty),
  (decide (b = kanon__7)) = true →
  S.Refines (KanonBool.Bool.eq.spec (KanonBool.mk (.Ite b l r) t__5) (KanonBool.mk (.Ite kanon__7 l' r') t__10))
  ((O.bool_ite b (O.bool_eq l l') (O.bool_eq r r')))

def Bool.eq.r_false_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.eq.spec (KanonBool.mk (.Bool false) t__2) v2)
  ((O.bool_not_ v2))

def Bool.eq.r_false_.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.eq.spec v1 (KanonBool.mk (.Bool false) t__2))
  ((O.bool_not_ v1))

def Bool.eq.r_true_.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v2 : S.Term) (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.eq.spec (KanonBool.mk (.Bool true) t__2) v2)
  (v2)

def Bool.eq.r_true_.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (t__2 : S.Ty),
  S.Refines (KanonBool.Bool.eq.spec v1 (KanonBool.mk (.Bool true) t__2))
  (v1)

def Bool.eq.r_nots.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (b : S.Term) (t__3 : S.Ty) (c : S.Term) (t__6 : S.Ty),
  S.Refines (KanonBool.Bool.eq.spec (KanonBool.mk (.Not b) t__3) (KanonBool.mk (.Not c) t__6))
  ((O.bool_eq b c))

def Bool.eq.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term),
  S.Refines (KanonBool.Bool.eq.spec v1 v2)
  ((if O.tag_le v1 v2
   then (KanonBool.mk (.Eq v1 v2) (KanonBool.sort .TBool))
   else (KanonBool.mk (.Eq v2 v1) (KanonBool.sort .TBool))))

def Bool.eq_untyped.r_ill_typed.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term),
  (! (decide ((S.ty v1) = (S.ty v2)))) = true →
  S.Refines (KanonBool.Bool.eq_untyped.spec v1 v2)
  (KanonBool.v_false)

def Bool.eq_untyped.r_typed.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term),
  S.Refines (KanonBool.Bool.eq_untyped.spec v1 v2)
  ((O.bool_eq v1 v2))

def Bool.distinct.r_small.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (l : (List S.Term)),
  (KanonBool.Bool.at_most_one l) = true →
  S.Refines (KanonBool.Bool.distinct.spec l)
  (KanonBool.v_true)

def Bool.distinct.r_distinct.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (l : (List S.Term)),
  (decide ((KanonBool.Bool.distinct_check O l) = (some true))) = true →
  S.Refines (KanonBool.Bool.distinct.spec l)
  (KanonBool.v_true)

def Bool.distinct.r_not_distinct.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (l : (List S.Term)),
  (decide ((KanonBool.Bool.distinct_check O l) = (some false))) = true →
  S.Refines (KanonBool.Bool.distinct.spec l)
  (KanonBool.v_false)

def Bool.distinct.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S] (O : Ops S), O.Sound →
  ∀ (l : (List S.Term)),
  S.Refines (KanonBool.Bool.distinct.spec l)
  ((KanonBool.mk (.Distinct (O.bool_sort_by_tag l)) (KanonBool.sort .TBool)))

def Bool.sure_neq.c1.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S], ∀ (a : S.Term) (b : S.Term) (r : Bool), Bool.sure_neq.c1 a b = some r →
  KanonBool.Bool.sure_neq.post a b r

def Bool.sure_neq.c2.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S], ∀ (a : S.Term) (b : S.Term) (r : Bool), Bool.sure_neq.c2 a b = some r →
  KanonBool.Bool.sure_neq.post a b r

def Bool.sure_neq.default.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [KanonBool.Typed S], ∀ (a : S.Term) (b : S.Term), Bool.sure_neq.post a b (Bool.sure_neq.default a b)

end KanonBool
