-- Generated by kanon from bool.knl, bool.kn. Do not edit.
import KanonCore.Generic

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace KanonBool

open Classical Kanon

/-- What the module `Bool` needs of the terms `B` of a language of semantics `S`, whose
modules that it uses have the interfaces of the parameters: Kanon generates it, and each
language that uses the module gives it, by definition. -/
structure Syntax {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] (B : Kanon.Base S) where
  TBool : S.Ty
  BoolK : Bool → B.Kind
  NotK : S.Term → B.Kind
  AndK : S.Term → S.Term → B.Kind
  OrK : S.Term → S.Term → B.Kind
  EqK : S.Term → S.Term → B.Kind
  IteK : S.Term → S.Term → S.Term → B.Kind
  DistinctK : (List S.Term) → B.Kind
  WT_Bool : ∀ (x1 : Bool) (t : S.Ty), S.WT (B.node (BoolK x1) t) ↔ t = TBool
  WT_Not : ∀ (a1 : S.Term) (t : S.Ty), S.WT (B.node (NotK a1) t) ↔ ((S.ty a1) = TBool ∧ t = TBool) ∧ S.WT a1
  WT_And : ∀ (a1 : S.Term) (a2 : S.Term) (t : S.Ty), S.WT (B.node (AndK a1 a2) t) ↔ ((S.ty a1) = TBool ∧ (S.ty a2) = TBool ∧ t = TBool) ∧ S.WT a1 ∧ S.WT a2
  WT_Or : ∀ (a1 : S.Term) (a2 : S.Term) (t : S.Ty), S.WT (B.node (OrK a1 a2) t) ↔ ((S.ty a1) = TBool ∧ (S.ty a2) = TBool ∧ t = TBool) ∧ S.WT a1 ∧ S.WT a2
  WT_Eq : ∀ (a1 : S.Term) (a2 : S.Term) (t : S.Ty), S.WT (B.node (EqK a1 a2) t) ↔ ((S.ty a2) = (S.ty a1) ∧ t = TBool) ∧ S.WT a1 ∧ S.WT a2
  WT_Ite : ∀ (a1 : S.Term) (a2 : S.Term) (a3 : S.Term) (t : S.Ty), S.WT (B.node (IteK a1 a2 a3) t) ↔ ((S.ty a1) = TBool ∧ (S.ty a3) = (S.ty a2) ∧ t = (S.ty a2)) ∧ S.WT a1 ∧ S.WT a2 ∧ S.WT a3
  WT_Distinct : ∀ (l1 : (List S.Term)) (t : S.Ty), S.WT (B.node (DistinctK l1) t) ↔ ∃ e, (t = TBool) ∧ ∀ x ∈ l1, S.ty x = e ∧ S.WT x
  /-- The arguments of a `Bool` node. -/
  asBool : S.Term → Option Bool
  asBool_node : ∀ (x1 : Bool) (t : S.Ty), asBool (B.node (BoolK x1) t) = some x1
  asBool_sound : ∀ (v : S.Term) (x1 : Bool), asBool v = some x1 → v = (B.node (BoolK x1) (S.ty v))
  /-- The arguments of a `Not` node. -/
  asNot : S.Term → Option S.Term
  asNot_node : ∀ (a1 : S.Term) (t : S.Ty), asNot (B.node (NotK a1) t) = some a1
  asNot_sound : ∀ (v : S.Term) (a1 : S.Term), asNot v = some a1 → v = (B.node (NotK a1) (S.ty v))
  /-- The arguments of a `And` node. -/
  asAnd : S.Term → Option (S.Term × S.Term)
  asAnd_node : ∀ (a1 : S.Term) (a2 : S.Term) (t : S.Ty), asAnd (B.node (AndK a1 a2) t) = some (a1, a2)
  asAnd_sound : ∀ (v : S.Term) (a1 : S.Term) (a2 : S.Term), asAnd v = some (a1, a2) → v = (B.node (AndK a1 a2) (S.ty v))
  /-- The arguments of a `Or` node. -/
  asOr : S.Term → Option (S.Term × S.Term)
  asOr_node : ∀ (a1 : S.Term) (a2 : S.Term) (t : S.Ty), asOr (B.node (OrK a1 a2) t) = some (a1, a2)
  asOr_sound : ∀ (v : S.Term) (a1 : S.Term) (a2 : S.Term), asOr v = some (a1, a2) → v = (B.node (OrK a1 a2) (S.ty v))
  /-- The arguments of a `Eq` node. -/
  asEq : S.Term → Option (S.Term × S.Term)
  asEq_node : ∀ (a1 : S.Term) (a2 : S.Term) (t : S.Ty), asEq (B.node (EqK a1 a2) t) = some (a1, a2)
  asEq_sound : ∀ (v : S.Term) (a1 : S.Term) (a2 : S.Term), asEq v = some (a1, a2) → v = (B.node (EqK a1 a2) (S.ty v))
  /-- The arguments of a `Ite` node. -/
  asIte : S.Term → Option (S.Term × S.Term × S.Term)
  asIte_node : ∀ (a1 : S.Term) (a2 : S.Term) (a3 : S.Term) (t : S.Ty), asIte (B.node (IteK a1 a2 a3) t) = some (a1, a2, a3)
  asIte_sound : ∀ (v : S.Term) (a1 : S.Term) (a2 : S.Term) (a3 : S.Term), asIte v = some (a1, a2, a3) → v = (B.node (IteK a1 a2 a3) (S.ty v))
  /-- The arguments of a `Distinct` node. -/
  asDistinct : S.Term → Option (List S.Term)
  asDistinct_node : ∀ (l1 : (List S.Term)) (t : S.Ty), asDistinct (B.node (DistinctK l1) t) = some l1
  asDistinct_sound : ∀ (v : S.Term) (l1 : (List S.Term)), asDistinct v = some l1 → v = (B.node (DistinctK l1) (S.ty v))
  bool_v_true : S.Term
  bool_v_false : S.Term
  bool_of_bool : Bool → S.Term
  bool_sure_neq : S.Term → S.Term → Bool
  bool_at_most_one : (List S.Term) → Bool
  bool_distinct_check_one : S.Term → (List S.Term) → (Option Bool)
  bool_distinct_check : (List S.Term) → (Option Bool)
  bool_of_bool_eq : ∀ (b : Bool), (bool_of_bool b) =
      (if b then bool_v_true else bool_v_false)
  bool_at_most_one_eq : ∀ (l : (List S.Term)), (bool_at_most_one l) =
      ((firstSome [(match l with | [] => some (true) | _ => none),
        (match l with | (_ :: []) => some (true) | _ => none)]).getD
        (match l with | _ => false))
  bool_distinct_check_one_eq : ∀ (a : S.Term) (rest : (List S.Term)), (bool_distinct_check_one a rest) =
      ((firstSome [(match rest with | [] => some ((some true)) | _ => none),
        (match rest with
          | (b :: rest) =>
          some ((if (decide (a = b))
                then (some false)
                else (if (bool_sure_neq a b)
                     then (bool_distinct_check_one a rest)
                     else none)))
          | _ => none)]).getD
        Inhabited.default)
  bool_distinct_check_eq : ∀ (l : (List S.Term)), (bool_distinct_check l) =
      ((firstSome [(match l with | [] => some ((some true)) | _ => none),
        (match l with
          | (a :: rest) =>
          some (((firstSome [(match (bool_distinct_check_one a rest) with
                               | (some true) =>
                               some ((bool_distinct_check rest))
                               | _ => none)]).getD
                  (match (bool_distinct_check_one a rest) with | r => r)))
          | _ => none)]).getD
        Inhabited.default)

end KanonBool
