(** The command line of kanon, [kanon BACKEND FILE...] (see {!Main}), as a
    function, for kanon and for its web runtime. *)

(** The parts of the generated Lean files (see {!Gen_lean.parts}), whose
    backends are [lean-PART]. *)
let lean_parts ~module_only ~lang ~has_proof prog =
  Gen_lean.parts ~module_only ~lang ~has_proof prog

(** The backends that write on standard output, in the order of the usage. *)
let backends =
  [ "ocaml-types"; "ocaml"; "ocaml-typed"; "ocaml-tests" ]
  @ List.map
      (fun (part, _) -> "lean-" ^ part)
      (lean_parts ~module_only:false ~lang:[]
         ~has_proof:(fun _ _ -> false)
         (lazy (assert false)))

(** The end of the command, with its exit code. *)
exception Exit_code of int

let usage err =
  Format.fprintf err "%s@."
    ("usage: kanon ("
    ^ String.concat " | " backends
    ^ ") FILE...\n\
      \       kanon lean-all [--check] DIR FILE...\n\
      \       kanon lsp\n\
      \       kanon --version\n\
       Files use modules with use \"path\", or use builtin \"name\" for those \
       built into kanon: "
    ^ String.concat ", "
        (List.sort_uniq compare
           (List.map
              (fun (n, _) -> Printf.sprintf "%S" (Filename.remove_extension n))
              Builtin.files)));
  raise (Exit_code 2)

(** The contents of a generated file. *)
let contents (f : Gen_lean.file) =
  let b = Buffer.create 4096 in
  let ft = Format.formatter_of_buffer b in
  f.contents ft;
  Format.pp_print_flush ft ();
  Buffer.contents b

let read_file name = In_channel.with_open_bin name In_channel.input_all

(** Whether the file [name] was generated by kanon, from its first line. *)
let generated name =
  let prefix = "-- Generated by kanon" in
  match In_channel.with_open_bin name In_channel.input_line with
  | Some l ->
      String.length l >= String.length prefix
      && String.sub l 0 (String.length prefix) = prefix
  | None -> false
  | exception Sys_error _ -> false

(** The [.lean] files under the directory [d], recursively. *)
let rec lean_files d =
  if Sys.file_exists d && Sys.is_directory d then
    List.concat_map
      (fun n ->
        let p = Filename.concat d n in
        if Sys.is_directory p then lean_files p
        else if Filename.check_suffix n ".lean" then [ p ]
        else [])
      (List.sort compare (Array.to_list (Sys.readdir d)))
  else []

let rec mkdir_p d =
  if not (Sys.file_exists d) then (
    mkdir_p (Filename.dirname d);
    Sys.mkdir d 0o755)

(** [kanon lean-all [--check] DIR]: writes the generated Lean files [files]
    under [dir] (the directory of the root module), and removes the files that
    kanon generated there before and no longer does; with [check], only checks
    that the files are up to date, and is whether they are. *)
let lean_all ~check ~err dir (files : Gen_lean.file list) =
  let ok = ref true in
  let report fmt =
    ok := false;
    Format.fprintf err ("kanon: " ^^ fmt ^^ "@.")
  in
  let names =
    List.map
      (fun (f : Gen_lean.file) ->
        let name = Filename.concat dir (Gen_lean.file_name f) in
        let text = contents f in
        let current =
          if Sys.file_exists name then Some (read_file name) else None
        in
        if current <> Some text then
          if check then
            report "%s is %s (run kanon lean-all)" name
              (if current = None then "missing" else "not up to date")
          else (
            mkdir_p (Filename.dirname name);
            Out_channel.with_open_bin name (fun oc ->
                Out_channel.output_string oc text));
        name)
      files
  in
  let roots =
    List.sort_uniq compare (List.map (fun (f : Gen_lean.file) -> f.froot) files)
  in
  List.iter
    (fun name ->
      if (not (List.mem name names)) && generated name then
        if check then
          report "%s is no longer generated (run kanon lean-all)" name
        else Sys.remove name)
    (List.sort_uniq compare
       (List.concat_map
          (fun root ->
            lean_files
              (Filename.concat dir
                 (String.concat "/" (String.split_on_char '.' root))))
          roots));
  !ok

(** [run args out err] runs [kanon args] (without [lsp]), writing on [out] and
    [err] for standard output and error, and is its exit code. Exceptions other
    than the errors of the files are raised. *)
let run args out err =
  try
    match args with
    | [ "--version" ] ->
        Format.fprintf out "%s@." Version.version;
        0
    | backend :: args -> (
        let target, files =
          match (backend, args) with
          | "lean-all", "--check" :: dir :: files -> (Some (true, dir), files)
          | "lean-all", dir :: files -> (Some (false, dir), files)
          | "lean-all", [] -> usage err
          | _ -> (None, args)
        in
        try
          if files = [] then usage err;
          Gen_lean.module_uses := [];
          Gen_lean.builtin_modules := [];
          Gen_lean.root_module := None;
          Gen_lean.module_files := [];
          let on_parse f str =
            match Check.module_of_file ~loc:Location.none f with
            | Some m ->
                if !Gen_lean.root_module = None then
                  Gen_lean.root_module := Some m;
                if Option.is_some (Loader.builtin f) then
                  Gen_lean.builtin_modules := m :: !Gen_lean.builtin_modules;
                let uses =
                  List.filter_map
                    (fun (u, _) -> Check.module_of_file ~loc:Location.none u)
                    (fst (Loader.uses str))
                in
                let old =
                  Option.value ~default:[]
                    (List.assoc_opt m !Gen_lean.module_uses)
                in
                Gen_lean.module_uses :=
                  (m, old @ uses) :: List.remove_assoc m !Gen_lean.module_uses;
                let fs =
                  Option.value ~default:[]
                    (List.assoc_opt m !Gen_lean.module_files)
                in
                Gen_lean.module_files :=
                  (m, fs @ [ Loader.source_name f ])
                  :: List.remove_assoc m !Gen_lean.module_files
            | None -> ()
          in
          let langs, files =
            try Loader.load ~on_parse files with
            | Loader.No_builtin f ->
                Format.fprintf err "kanon: %s: no such built-in module file@." f;
                usage err
            | Loader.Missing (_, msg) ->
                Format.fprintf err "kanon: %s@." msg;
                raise (Exit_code 1)
          in
          if langs = [] then usage err;
          Check.language (List.concat_map snd langs);
          let prog =
            lazy
              (if files = [] then usage err;
               Check.program (List.concat_map snd files))
          in
          let lang = List.map (fun (f, _) -> Loader.source_name f) langs in
          let sources = List.map (fun (f, _) -> Loader.source_name f) files in
          (* a module built into kanon, given alone: only its own files *)
          let module_only =
            match langs with
            | (f, _) :: _ -> Option.is_some (Loader.builtin f)
            | [] -> false
          in
          ignore sources;
          let lean has_proof =
            lean_parts ~module_only ~lang ~has_proof
              (lazy (Check.program (List.concat_map snd files)))
          in
          match (target, backend) with
          | Some (check, dir), _ ->
              let has_proof r path =
                Sys.file_exists
                  (Filename.concat dir (Gen_lean.file_name_at r path))
              in
              let files =
                List.concat_map (fun (_, gen) -> gen ()) (lean has_proof)
              in
              if lean_all ~check ~err dir files then 0 else 1
          | None, "ocaml-types" ->
              Gen_ocaml.types ~sources:lang out;
              0
          | None, "ocaml" ->
              Gen_ocaml.program ~sources out (Lazy.force prog);
              0
          | None, "ocaml-typed" ->
              Gen_typed.program ~sources:(lang @ sources) out (Lazy.force prog);
              0
          | None, "ocaml-tests" ->
              Gen_tests.program ~sources out (Lazy.force prog);
              0
          | None, _ -> (
              match
                List.assoc_opt backend
                  (List.map
                     (fun (part, gen) -> ("lean-" ^ part, gen))
                     (lean (fun _ _ -> false)))
              with
              | Some gen ->
                  (* the files of a part of several, each after its name *)
                  let files = gen () in
                  List.iteri
                    (fun i (f : Gen_lean.file) ->
                      if List.length files > 1 then
                        Format.fprintf out "%s-- %s@.@."
                          (if i > 0 then "\n" else "")
                          (Gen_lean.file_name f);
                      Format.fprintf out "%s@?" (contents f))
                    files;
                  0
              | None -> usage err)
        with Check.Error (loc, msg) ->
          if loc = Location.none then Format.fprintf err "kanon: %s@." msg
          else Format.fprintf err "%a: %s@." Check.pp_loc loc msg;
          1)
    | [] -> usage err
  with Exit_code code -> code
