-- Generated by kanon from int.knl, int.kn. Do not edit.
import DivMod.Lift
import DivMod.Soundness.Comm
import DivMod.Soundness.Int.plus
import DivMod.Soundness.Int.div
import DivMod.Soundness.Int.sq1

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace DivMod

open Classical Kanon

end DivMod
