-- Generated by kanon from word.knl, word.kn. Do not edit.
import WordMod.Statements.Word.choose
import WordMod.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace WordMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Word.choose.r_main.main.ok : Word.choose.r_main.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Word.choose.r_main.main)

end WordMod
