-- Generated by kanon from word.knl, word.kn. Do not edit.
import WordMod.Statements.Word.double
import WordMod.Proofs
import KanonBool.Soundness.Comm

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace WordMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Word.double.r_main.main.ok : Word.double.r_main.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Word.double.r_main.main)

theorem Word.double.r_main.sound {S : Kanon.Sem} [KanonBool.Lang S] [WordMod.Lang S] [KanonBool.Typed S] [WordMod.Typed S] (O : Ops S) (hO : O.Sound) (n : Int) (v : S.Term) (res : S.Term)
    (h : Word.double.r_main O n v = some res) : S.Refines (WordMod.Word.double.spec n v) res := by
  unfold Word.double.r_main at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Word.double.r_main.main.ok O hO)

end WordMod
